{"matches":[{"vulnerability":{"id":"GHSA-q34m-jh98-gwm2","dataSource":"https://github.com/advisories/GHSA-q34m-jh98-gwm2","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Werkzeug possible resource exhaustion when parsing file data in forms","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-49767","epss":0.00974,"percentile":0.75666,"date":"2025-06-02"}],"fix":{"versions":["0.20.0"],"state":"fixed"},"advisories":[],"risk":0.60875},"relatedVulnerabilities":[{"id":"CVE-2024-49767","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-49767","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pallets/quart/commit/5e78c4169b8eb66b91ead3e62d44721b9e1644ee","https://github.com/pallets/quart/commit/abb04a512496206de279225340ed022852fbf51f","https://github.com/pallets/werkzeug/commit/50cfeebcb0727e18cc52ffbeb125f4a66551179b","https://github.com/pallets/werkzeug/releases/tag/3.0.6","https://github.com/pallets/werkzeug/security/advisories/GHSA-q34m-jh98-gwm2","https://security.netapp.com/advisory/ntap-20250103-0007/"],"description":"Werkzeug is a Web Server Gateway Interface web application library. Applications using `werkzeug.formparser.MultiPartParser` corresponding to a version of Werkzeug prior to 3.0.6 to parse `multipart/form-data` requests (e.g. all flask applications) are vulnerable to a relatively simple but effective resource exhaustion (denial of service) attack. A specifically crafted form submission request can cause the parser to allocate and block 3 to 8 times the upload size in main memory. There is no upper limit; a single upload at 1 Gbit/s can exhaust 32 GB of RAM in less than 60 seconds. Werkzeug version 3.0.6 fixes this issue.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:L/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":6.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-49767","epss":0.00974,"percentile":0.75666,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"quart","version":"0.18.3"}},"found":{"versionConstraint":"<0.20.0 (python)","vulnerabilityID":"GHSA-q34m-jh98-gwm2"},"fix":{"suggestedVersion":"0.20.0"}}],"artifact":{"id":"015b6fcf9831ebde","name":"quart","version":"0.18.3","type":"python","locations":[{"path":"/lib/python3.8/site-packages/quart-0.18.3.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/quart-0.18.3.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/quart-0.18.3.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/quart-0.18.3.dist-info/RECORD","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:philip_graham_jones_project:python-quart:0.18.3:*:*:*:*:*:*:*","cpe:2.3:a:philip_graham_jones_project:python_quart:0.18.3:*:*:*:*:*:*:*","cpe:2.3:a:philip_graham_jonesproject:python-quart:0.18.3:*:*:*:*:*:*:*","cpe:2.3:a:philip_graham_jonesproject:python_quart:0.18.3:*:*:*:*:*:*:*","cpe:2.3:a:philip_graham_jones_project:quart:0.18.3:*:*:*:*:*:*:*","cpe:2.3:a:philip-graham-jones:python-quart:0.18.3:*:*:*:*:*:*:*","cpe:2.3:a:philip-graham-jones:python_quart:0.18.3:*:*:*:*:*:*:*","cpe:2.3:a:philip_graham_jones:python-quart:0.18.3:*:*:*:*:*:*:*","cpe:2.3:a:philip_graham_jones:python_quart:0.18.3:*:*:*:*:*:*:*","cpe:2.3:a:philip_graham_jonesproject:quart:0.18.3:*:*:*:*:*:*:*","cpe:2.3:a:pgjones_project:python-quart:0.18.3:*:*:*:*:*:*:*","cpe:2.3:a:pgjones_project:python_quart:0.18.3:*:*:*:*:*:*:*","cpe:2.3:a:pgjonesproject:python-quart:0.18.3:*:*:*:*:*:*:*","cpe:2.3:a:pgjonesproject:python_quart:0.18.3:*:*:*:*:*:*:*","cpe:2.3:a:philip-graham-jones:quart:0.18.3:*:*:*:*:*:*:*","cpe:2.3:a:philip_graham_jones:quart:0.18.3:*:*:*:*:*:*:*","cpe:2.3:a:python-quart:python-quart:0.18.3:*:*:*:*:*:*:*","cpe:2.3:a:python-quart:python_quart:0.18.3:*:*:*:*:*:*:*","cpe:2.3:a:python_quart:python-quart:0.18.3:*:*:*:*:*:*:*","cpe:2.3:a:python_quart:python_quart:0.18.3:*:*:*:*:*:*:*","cpe:2.3:a:pgjones_project:quart:0.18.3:*:*:*:*:*:*:*","cpe:2.3:a:pgjones:python-quart:0.18.3:*:*:*:*:*:*:*","cpe:2.3:a:pgjones:python_quart:0.18.3:*:*:*:*:*:*:*","cpe:2.3:a:pgjonesproject:quart:0.18.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python-quart:0.18.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python_quart:0.18.3:*:*:*:*:*:*:*","cpe:2.3:a:python-quart:quart:0.18.3:*:*:*:*:*:*:*","cpe:2.3:a:python_quart:quart:0.18.3:*:*:*:*:*:*:*","cpe:2.3:a:quart:python-quart:0.18.3:*:*:*:*:*:*:*","cpe:2.3:a:quart:python_quart:0.18.3:*:*:*:*:*:*:*","cpe:2.3:a:pgjones:quart:0.18.3:*:*:*:*:*:*:*","cpe:2.3:a:python:quart:0.18.3:*:*:*:*:*:*:*","cpe:2.3:a:quart:quart:0.18.3:*:*:*:*:*:*:*"],"purl":"pkg:pypi/quart@0.18.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-q34m-jh98-gwm2","dataSource":"https://github.com/advisories/GHSA-q34m-jh98-gwm2","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Werkzeug possible resource exhaustion when parsing file data in forms","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-49767","epss":0.00974,"percentile":0.75666,"date":"2025-06-02"}],"fix":{"versions":["3.0.6"],"state":"fixed"},"advisories":[],"risk":0.60875},"relatedVulnerabilities":[{"id":"CVE-2024-49767","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-49767","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pallets/quart/commit/5e78c4169b8eb66b91ead3e62d44721b9e1644ee","https://github.com/pallets/quart/commit/abb04a512496206de279225340ed022852fbf51f","https://github.com/pallets/werkzeug/commit/50cfeebcb0727e18cc52ffbeb125f4a66551179b","https://github.com/pallets/werkzeug/releases/tag/3.0.6","https://github.com/pallets/werkzeug/security/advisories/GHSA-q34m-jh98-gwm2","https://security.netapp.com/advisory/ntap-20250103-0007/"],"description":"Werkzeug is a Web Server Gateway Interface web application library. Applications using `werkzeug.formparser.MultiPartParser` corresponding to a version of Werkzeug prior to 3.0.6 to parse `multipart/form-data` requests (e.g. all flask applications) are vulnerable to a relatively simple but effective resource exhaustion (denial of service) attack. A specifically crafted form submission request can cause the parser to allocate and block 3 to 8 times the upload size in main memory. There is no upper limit; a single upload at 1 Gbit/s can exhaust 32 GB of RAM in less than 60 seconds. Werkzeug version 3.0.6 fixes this issue.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:L/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":6.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-49767","epss":0.00974,"percentile":0.75666,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"werkzeug","version":"2.3.8"}},"found":{"versionConstraint":"<=3.0.5 (python)","vulnerabilityID":"GHSA-q34m-jh98-gwm2"},"fix":{"suggestedVersion":"3.0.6"}}],"artifact":{"id":"18dfa85150beca55","name":"werkzeug","version":"2.3.8","type":"python","locations":[{"path":"/lib/python3.8/site-packages/werkzeug-2.3.8.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/werkzeug-2.3.8.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/werkzeug-2.3.8.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/werkzeug-2.3.8.dist-info/RECORD","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:python-werkzeug:python-werkzeug:2.3.8:*:*:*:*:*:*:*","cpe:2.3:a:python-werkzeug:python_werkzeug:2.3.8:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:python-werkzeug:2.3.8:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:python_werkzeug:2.3.8:*:*:*:*:*:*:*","cpe:2.3:a:python-werkzeug:werkzeug:2.3.8:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:werkzeug:2.3.8:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:python-werkzeug:2.3.8:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:python_werkzeug:2.3.8:*:*:*:*:*:*:*","cpe:2.3:a:python:python-werkzeug:2.3.8:*:*:*:*:*:*:*","cpe:2.3:a:python:python_werkzeug:2.3.8:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:werkzeug:2.3.8:*:*:*:*:*:*:*","cpe:2.3:a:python:werkzeug:2.3.8:*:*:*:*:*:*:*"],"purl":"pkg:pypi/werkzeug@2.3.8","upstreams":[]}},{"vulnerability":{"id":"GHSA-248v-346w-9cwc","dataSource":"https://github.com/advisories/GHSA-248v-346w-9cwc","namespace":"github:language:python","severity":"Low","urls":[],"description":"Certifi removes GLOBALTRUST root certificate","cvss":[],"epss":[{"cve":"CVE-2024-39689","epss":0.01928,"percentile":0.82506,"date":"2025-06-02"}],"fix":{"versions":["2024.7.4"],"state":"fixed"},"advisories":[],"risk":0.5783999999999999},"relatedVulnerabilities":[{"id":"CVE-2024-39689","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-39689","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/certifi/python-certifi/commit/bd8153872e9c6fc98f4023df9c2deaffea2fa463","https://github.com/certifi/python-certifi/security/advisories/GHSA-248v-346w-9cwc","https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI","https://github.com/certifi/python-certifi/commit/bd8153872e9c6fc98f4023df9c2deaffea2fa463","https://github.com/certifi/python-certifi/security/advisories/GHSA-248v-346w-9cwc","https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI","https://security.netapp.com/advisory/ntap-20241206-0001/"],"description":"Certifi is a curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts. Certifi starting in 2021.5.30 and prior to 2024.7.4 recognized root certificates from `GLOBALTRUST`. Certifi 2024.7.04 removes root certificates from `GLOBALTRUST` from the root store. These are in the process of being removed from Mozilla's trust store. `GLOBALTRUST`'s root certificates are being removed pursuant to an investigation which identified \"long-running and unresolved compliance issues.\"","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-39689","epss":0.01928,"percentile":0.82506,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"certifi","version":"2023.7.22"}},"found":{"versionConstraint":">=2021.5.30,<2024.7.4 (python)","vulnerabilityID":"GHSA-248v-346w-9cwc"},"fix":{"suggestedVersion":"2024.7.4"}}],"artifact":{"id":"2c8f16c321d51985","name":"certifi","version":"2023.7.22","type":"python","locations":[{"path":"/lib/python3.8/site-packages/certifi-2023.7.22.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/certifi-2023.7.22.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/certifi-2023.7.22.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/certifi-2023.7.22.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/certifi-2023.7.22.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/certifi-2023.7.22.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MPL-2.0"],"cpes":["cpe:2.3:a:certifi:certifi:2023.7.22:*:*:*:*:python:*:*"],"purl":"pkg:pypi/certifi@2023.7.22","upstreams":[]}},{"vulnerability":{"id":"GHSA-3f63-hfp8-52jq","dataSource":"https://github.com/advisories/GHSA-3f63-hfp8-52jq","namespace":"github:language:python","severity":"Critical","urls":[],"description":"Arbitrary Code Execution in Pillow","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.1,"exploitabilityScore":2.3,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-50447","epss":0.00408,"percentile":0.6039,"date":"2025-06-02"}],"fix":{"versions":["10.2.0"],"state":"fixed"},"advisories":[],"risk":0.34884},"relatedVulnerabilities":[{"id":"CVE-2023-50447","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-50447","namespace":"nvd:cpe","severity":"High","urls":["http://www.openwall.com/lists/oss-security/2024/01/20/1","https://devhub.checkmarx.com/cve-details/CVE-2023-50447/","https://duartecsantos.github.io/2024-01-02-CVE-2023-50447/","https://github.com/python-pillow/Pillow/releases","https://lists.debian.org/debian-lts-announce/2024/01/msg00019.html","http://www.openwall.com/lists/oss-security/2024/01/20/1","https://devhub.checkmarx.com/cve-details/CVE-2023-50447/","https://duartecsantos.github.io/2024-01-02-CVE-2023-50447/","https://github.com/python-pillow/Pillow/releases","https://lists.debian.org/debian-lts-announce/2024/01/msg00019.html"],"description":"Pillow through 10.1.0 allows PIL.ImageMath.eval Arbitrary Code Execution via the environment parameter, a different vulnerability than CVE-2022-22817 (which was about the expression parameter).","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.1,"exploitabilityScore":2.3,"impactScore":5.9},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.1,"exploitabilityScore":2.3,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-50447","epss":0.00408,"percentile":0.6039,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"pillow","version":"10.0.1"}},"found":{"versionConstraint":"<10.2.0 (python)","vulnerabilityID":"GHSA-3f63-hfp8-52jq"},"fix":{"suggestedVersion":"10.2.0"}}],"artifact":{"id":"75bf0879584d9bf7","name":"pillow","version":"10.0.1","type":"python","locations":[{"path":"/lib/python3.8/site-packages/Pillow-10.0.1.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/Pillow-10.0.1.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/Pillow-10.0.1.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/Pillow-10.0.1.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/Pillow-10.0.1.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/Pillow-10.0.1.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["HPND"],"cpes":["cpe:2.3:a:jeffrey_a__clark_(alex)_project:python-pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex)_project:python_pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex)project:python-pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex)project:python_pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex)_project:pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex):python-pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex):python_pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex)project:pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex):pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:aclark_project:python-pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:aclark_project:python_pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:aclarkproject:python-pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:aclarkproject:python_pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python-pillow:python-pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python-pillow:python_pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python_pillow:python-pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python_pillow:python_pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:aclark_project:pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:aclark:python-pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:aclark:python_pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:aclarkproject:pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:pillow:python-pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:pillow:python_pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python-pillow:pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python:python-pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python:python_pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python_pillow:pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:aclark:pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:pillow:pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python:pillow:10.0.1:*:*:*:*:*:*:*"],"purl":"pkg:pypi/pillow@10.0.1","upstreams":[]}},{"vulnerability":{"id":"GHSA-5rjg-fvgr-3xxf","dataSource":"https://github.com/advisories/GHSA-5rjg-fvgr-3xxf","namespace":"github:language:python","severity":"High","urls":[],"description":"setuptools has a path traversal vulnerability in PackageIndex.download that leads to Arbitrary File Write","cvss":[],"epss":[{"cve":"CVE-2025-47273","epss":0.00435,"percentile":0.6206,"date":"2025-06-02"}],"fix":{"versions":["78.1.1"],"state":"fixed"},"advisories":[],"risk":0.32625},"relatedVulnerabilities":[{"id":"CVE-2025-47273","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-47273","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pypa/setuptools/blob/6ead555c5fb29bc57fe6105b1bffc163f56fd558/setuptools/package_index.py#L810C1-L825C88","https://github.com/pypa/setuptools/commit/250a6d17978f9f6ac3ac887091f2d32886fbbb0b","https://github.com/pypa/setuptools/issues/4946","https://github.com/pypa/setuptools/security/advisories/GHSA-5rjg-fvgr-3xxf","https://lists.debian.org/debian-lts-announce/2025/05/msg00035.html","https://github.com/pypa/setuptools/issues/4946"],"description":"setuptools is a package that allows users to download, build, install, upgrade, and uninstall Python packages. A path traversal vulnerability in `PackageIndex` is present in setuptools prior to version 78.1.1. An attacker would be allowed to write files to arbitrary locations on the filesystem with the permissions of the process running the Python code, which could escalate to remote code execution depending on the context. Version 78.1.1 fixes the issue.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:H/VA:N/SC:N/SI:N/SA:N/E:P/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":7.7},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-47273","epss":0.00435,"percentile":0.6206,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"setuptools","version":"75.3.0"}},"found":{"versionConstraint":"<78.1.1 (python)","vulnerabilityID":"GHSA-5rjg-fvgr-3xxf"},"fix":{"suggestedVersion":"78.1.1"}}],"artifact":{"id":"c84db8db3c953103","name":"setuptools","version":"75.3.0","type":"python","locations":[{"path":"/lib/python3.8/site-packages/setuptools-75.3.0.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/setuptools-75.3.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/setuptools-75.3.0.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/setuptools-75.3.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/setuptools-75.3.0.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/setuptools-75.3.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:setuptools:75.3.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/setuptools@75.3.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-jjg7-2v4v-x38h","dataSource":"https://github.com/advisories/GHSA-jjg7-2v4v-x38h","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Internationalized Domain Names in Applications (IDNA) vulnerable to denial of service from specially crafted inputs to idna.encode","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":6.2,"exploitabilityScore":2.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-3651","epss":0.00436,"percentile":0.62112,"date":"2025-06-02"}],"fix":{"versions":["3.7"],"state":"fixed"},"advisories":[],"risk":0.24416000000000004},"relatedVulnerabilities":[{"id":"CVE-2024-3651","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-3651","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/kjd/idna/commit/1d365e17e10d72d0b7876316fc7b9ca0eebdd38d","https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb","https://github.com/kjd/idna/commit/1d365e17e10d72d0b7876316fc7b9ca0eebdd38d","https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb"],"description":"A vulnerability was identified in the kjd/idna library, specifically within the `idna.encode()` function, affecting version 3.6. The issue arises from the function's handling of crafted input strings, which can lead to quadratic complexity and consequently, a denial of service condition. This vulnerability is triggered by a crafted input that causes the `idna.encode()` function to process the input with considerable computational load, significantly increasing the processing time in a quadratic manner relative to the input size.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security@huntr.dev","type":"Secondary","version":"3.0","vector":"CVSS:3.0/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":6.2,"exploitabilityScore":2.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-3651","epss":0.00436,"percentile":0.62112,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"idna","version":"3.4"}},"found":{"versionConstraint":"<3.7 (python)","vulnerabilityID":"GHSA-jjg7-2v4v-x38h"},"fix":{"suggestedVersion":"3.7"}}],"artifact":{"id":"351063774e5ca50f","name":"idna","version":"3.4","type":"python","locations":[{"path":"/lib/python3.8/site-packages/idna-3.4.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/idna-3.4.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/idna-3.4.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/idna-3.4.dist-info/RECORD","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:kim_davies_<kim_project:python-idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kim_project:python_idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kimproject:python-idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kimproject:python_idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kim_project:idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:kim-davies-<kim:python-idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:kim-davies-<kim:python_idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kim:python-idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kim:python_idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kimproject:idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:python-idna:python-idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:python-idna:python_idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:python_idna:python-idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:python_idna:python_idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:kim-davies-<kim:idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kim:idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python-idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python_idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:idna:python-idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:idna:python_idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:python-idna:idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:python_idna:idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:python:idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:idna:idna:3.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/idna@3.4","upstreams":[]}},{"vulnerability":{"id":"GHSA-w596-4wvx-j9j6","dataSource":"https://github.com/advisories/GHSA-w596-4wvx-j9j6","namespace":"github:language:python","severity":"High","urls":[],"description":"ReDoS in py library when used with subversion","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-42969","epss":0.00117,"percentile":0.31764,"date":"2025-06-02"}],"fix":{"versions":[],"state":"not-fixed"},"advisories":[],"risk":0.08775000000000001},"relatedVulnerabilities":[{"id":"CVE-2022-42969","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2022-42969","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pytest-dev/py/blob/cb87a83960523a2367d0f19226a73aed4ce4291d/py/_path/svnurl.py#L316","https://github.com/pytest-dev/py/issues/287","https://news.ycombinator.com/item?id=34163710","https://pypi.org/project/py","https://github.com/pytest-dev/py/blob/cb87a83960523a2367d0f19226a73aed4ce4291d/py/_path/svnurl.py#L316","https://github.com/pytest-dev/py/issues/287","https://news.ycombinator.com/item?id=34163710","https://pypi.org/project/py"],"description":"The py library through 1.11.0 for Python allows remote attackers to conduct a ReDoS (Regular expression Denial of Service) attack via a Subversion repository with crafted info data, because the InfoSvnCommand argument is mishandled. Note: This has been disputed by multiple third parties as not being reproduceable and they argue this is not a valid vulnerability.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"cve@mitre.org","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L","metrics":{"baseScore":5.3,"exploitabilityScore":3.9,"impactScore":1.5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-42969","epss":0.00117,"percentile":0.31764,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"py","version":"1.11.0"}},"found":{"versionConstraint":"<=1.11.0 (python)","vulnerabilityID":"GHSA-w596-4wvx-j9j6"}}],"artifact":{"id":"85106d991f6dfa3d","name":"py","version":"1.11.0","type":"python","locations":[{"path":"/lib/python3.8/site-packages/py-1.11.0.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/py-1.11.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/py-1.11.0.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/py-1.11.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/py-1.11.0.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/py-1.11.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT license"],"cpes":["cpe:2.3:a:holger_krekel,_ronny_pfannschmidt,_benjamin_peterson_and_others_project:python-py:1.11.0:*:*:*:*:*:*:*","cpe:2.3:a:holger_krekel,_ronny_pfannschmidt,_benjamin_peterson_and_others_project:python_py:1.11.0:*:*:*:*:*:*:*","cpe:2.3:a:holger_krekel,_ronny_pfannschmidt,_benjamin_peterson_and_othersproject:python-py:1.11.0:*:*:*:*:*:*:*","cpe:2.3:a:holger_krekel,_ronny_pfannschmidt,_benjamin_peterson_and_othersproject:python_py:1.11.0:*:*:*:*:*:*:*","cpe:2.3:a:holger_krekel,_ronny_pfannschmidt,_benjamin_peterson_and_others_project:py:1.11.0:*:*:*:*:*:*:*","cpe:2.3:a:holger_krekel,_ronny_pfannschmidt,_benjamin_peterson_and_others:python-py:1.11.0:*:*:*:*:*:*:*","cpe:2.3:a:holger_krekel,_ronny_pfannschmidt,_benjamin_peterson_and_others:python_py:1.11.0:*:*:*:*:*:*:*","cpe:2.3:a:holger_krekel,_ronny_pfannschmidt,_benjamin_peterson_and_othersproject:py:1.11.0:*:*:*:*:*:*:*","cpe:2.3:a:holger_krekel,_ronny_pfannschmidt,_benjamin_peterson_and_others:py:1.11.0:*:*:*:*:*:*:*","cpe:2.3:a:pytest_dev_project:python-py:1.11.0:*:*:*:*:*:*:*","cpe:2.3:a:pytest_dev_project:python_py:1.11.0:*:*:*:*:*:*:*","cpe:2.3:a:pytest_devproject:python-py:1.11.0:*:*:*:*:*:*:*","cpe:2.3:a:pytest_devproject:python_py:1.11.0:*:*:*:*:*:*:*","cpe:2.3:a:pytest_dev_project:py:1.11.0:*:*:*:*:*:*:*","cpe:2.3:a:pytest-dev:python-py:1.11.0:*:*:*:*:*:*:*","cpe:2.3:a:pytest-dev:python_py:1.11.0:*:*:*:*:*:*:*","cpe:2.3:a:pytest_dev:python-py:1.11.0:*:*:*:*:*:*:*","cpe:2.3:a:pytest_dev:python_py:1.11.0:*:*:*:*:*:*:*","cpe:2.3:a:pytest_devproject:py:1.11.0:*:*:*:*:*:*:*","cpe:2.3:a:python-py:python-py:1.11.0:*:*:*:*:*:*:*","cpe:2.3:a:python-py:python_py:1.11.0:*:*:*:*:*:*:*","cpe:2.3:a:python_py:python-py:1.11.0:*:*:*:*:*:*:*","cpe:2.3:a:python_py:python_py:1.11.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python-py:1.11.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python_py:1.11.0:*:*:*:*:*:*:*","cpe:2.3:a:pytest-dev:py:1.11.0:*:*:*:*:*:*:*","cpe:2.3:a:pytest_dev:py:1.11.0:*:*:*:*:*:*:*","cpe:2.3:a:py:python-py:1.11.0:*:*:*:*:*:*:*","cpe:2.3:a:py:python_py:1.11.0:*:*:*:*:*:*:*","cpe:2.3:a:python-py:py:1.11.0:*:*:*:*:*:*:*","cpe:2.3:a:python_py:py:1.11.0:*:*:*:*:*:*:*","cpe:2.3:a:python:py:1.11.0:*:*:*:*:*:*:*","cpe:2.3:a:py:py:1.11.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/py@1.11.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-44wm-f244-xhp3","dataSource":"https://github.com/advisories/GHSA-44wm-f244-xhp3","namespace":"github:language:python","severity":"High","urls":[],"description":"Pillow buffer overflow vulnerability","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:H/PR:L/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":6.7,"exploitabilityScore":0.8,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-28219","epss":0.00095,"percentile":0.27871,"date":"2025-06-02"}],"fix":{"versions":["10.3.0"],"state":"fixed"},"advisories":[],"risk":0.06745},"relatedVulnerabilities":[{"id":"CVE-2024-28219","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-28219","namespace":"nvd:cpe","severity":"Medium","urls":["https://lists.debian.org/debian-lts-announce/2024/04/msg00008.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4XLPUT3VK4GQ6EVY525TT2QNUIXNRU5M/","https://pillow.readthedocs.io/en/stable/releasenotes/10.3.0.html#security","https://lists.debian.org/debian-lts-announce/2024/04/msg00008.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4XLPUT3VK4GQ6EVY525TT2QNUIXNRU5M/","https://pillow.readthedocs.io/en/stable/releasenotes/10.3.0.html#security"],"description":"In _imagingcms.c in Pillow before 10.3.0, a buffer overflow exists because strcpy is used instead of strncpy.","cvss":[{"source":"cve@mitre.org","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:H/PR:L/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":6.7,"exploitabilityScore":0.8,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-28219","epss":0.00095,"percentile":0.27871,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"pillow","version":"10.0.1"}},"found":{"versionConstraint":"<10.3.0 (python)","vulnerabilityID":"GHSA-44wm-f244-xhp3"},"fix":{"suggestedVersion":"10.3.0"}}],"artifact":{"id":"75bf0879584d9bf7","name":"pillow","version":"10.0.1","type":"python","locations":[{"path":"/lib/python3.8/site-packages/Pillow-10.0.1.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/Pillow-10.0.1.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/Pillow-10.0.1.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/Pillow-10.0.1.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/Pillow-10.0.1.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/Pillow-10.0.1.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["HPND"],"cpes":["cpe:2.3:a:jeffrey_a__clark_(alex)_project:python-pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex)_project:python_pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex)project:python-pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex)project:python_pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex)_project:pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex):python-pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex):python_pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex)project:pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex):pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:aclark_project:python-pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:aclark_project:python_pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:aclarkproject:python-pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:aclarkproject:python_pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python-pillow:python-pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python-pillow:python_pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python_pillow:python-pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python_pillow:python_pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:aclark_project:pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:aclark:python-pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:aclark:python_pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:aclarkproject:pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:pillow:python-pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:pillow:python_pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python-pillow:pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python:python-pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python:python_pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python_pillow:pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:aclark:pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:pillow:pillow:10.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python:pillow:10.0.1:*:*:*:*:*:*:*"],"purl":"pkg:pypi/pillow@10.0.1","upstreams":[]}},{"vulnerability":{"id":"GHSA-q2x7-8rv6-6q7h","dataSource":"https://github.com/advisories/GHSA-q2x7-8rv6-6q7h","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Jinja has a sandbox breakout through indirect reference to format method","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":7.8,"exploitabilityScore":1.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-56326","epss":0.00103,"percentile":0.29451,"date":"2025-06-02"}],"fix":{"versions":["3.1.5"],"state":"fixed"},"advisories":[],"risk":0.06592},"relatedVulnerabilities":[{"id":"CVE-2024-56326","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-56326","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pallets/jinja/commit/48b0687e05a5466a91cd5812d604fa37ad0943b4","https://github.com/pallets/jinja/releases/tag/3.1.5","https://github.com/pallets/jinja/security/advisories/GHSA-q2x7-8rv6-6q7h"],"description":"Jinja is an extensible templating engine. Prior to 3.1.5, An oversight in how the Jinja sandboxed environment detects calls to str.format allows an attacker that controls the content of a template to execute arbitrary Python code. To exploit the vulnerability, an attacker needs to control the content of a template. Whether that is the case depends on the type of application using Jinja. This vulnerability impacts users of applications which execute untrusted templates. Jinja's sandbox does catch calls to str.format and ensures they don't escape the sandbox. However, it's possible to store a reference to a malicious string's format method, then pass that to a filter that calls it. No such filters are built-in to Jinja, but could be present through custom filters in an application. After the fix, such indirect calls are also handled by the sandbox. This vulnerability is fixed in 3.1.5.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:L/AC:L/AT:P/PR:L/UI:P/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":5.4},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":7.8,"exploitabilityScore":1.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-56326","epss":0.00103,"percentile":0.29451,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"jinja2","version":"3.0.3"}},"found":{"versionConstraint":"<=3.1.4 (python)","vulnerabilityID":"GHSA-q2x7-8rv6-6q7h"},"fix":{"suggestedVersion":"3.1.5"}}],"artifact":{"id":"11052aada3872803","name":"jinja2","version":"3.0.3","type":"python","locations":[{"path":"/lib/python3.8/site-packages/Jinja2-3.0.3.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/Jinja2-3.0.3.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/Jinja2-3.0.3.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/Jinja2-3.0.3.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/Jinja2-3.0.3.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/Jinja2-3.0.3.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:armin_ronacher_project:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher_project:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher_project:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python:jinja2:3.0.3:*:*:*:*:*:*:*"],"purl":"pkg:pypi/jinja2@3.0.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-h5c8-rqwp-cp95","dataSource":"https://github.com/advisories/GHSA-h5c8-rqwp-cp95","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Jinja vulnerable to HTML attribute injection when passing user input as keys to xmlattr filter","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N","metrics":{"baseScore":5.4,"exploitabilityScore":2.9,"impactScore":2.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-22195","epss":0.00102,"percentile":0.29274,"date":"2025-06-02"}],"fix":{"versions":["3.1.3"],"state":"fixed"},"advisories":[],"risk":0.05304000000000001},"relatedVulnerabilities":[{"id":"CVE-2024-22195","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-22195","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pallets/jinja/releases/tag/3.1.3","https://github.com/pallets/jinja/security/advisories/GHSA-h5c8-rqwp-cp95","https://lists.debian.org/debian-lts-announce/2024/01/msg00010.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5XCWZD464AJJJUBOO7CMPXQ4ROBC6JX2/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DELCVUUYX75I5K4Q5WMJG4MUZJA6VAIP/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/O7YWRBX6JQCWC2XXCTZ55C7DPMGICCN3/","https://github.com/pallets/jinja/releases/tag/3.1.3","https://github.com/pallets/jinja/security/advisories/GHSA-h5c8-rqwp-cp95","https://lists.debian.org/debian-lts-announce/2024/01/msg00010.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5XCWZD464AJJJUBOO7CMPXQ4ROBC6JX2/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DELCVUUYX75I5K4Q5WMJG4MUZJA6VAIP/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/O7YWRBX6JQCWC2XXCTZ55C7DPMGICCN3/"],"description":"Jinja is an extensible templating engine. Special placeholders in the template allow writing code similar to Python syntax. It is possible to inject arbitrary HTML attributes into the rendered HTML template, potentially leading to Cross-Site Scripting (XSS). The Jinja `xmlattr` filter can be abused to inject arbitrary HTML attribute keys and values, bypassing the auto escaping mechanism and potentially leading to XSS. It may also be possible to bypass attribute validation checks if they are blacklist-based.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N","metrics":{"baseScore":6.1,"exploitabilityScore":2.9,"impactScore":2.8},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N","metrics":{"baseScore":5.4,"exploitabilityScore":2.9,"impactScore":2.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-22195","epss":0.00102,"percentile":0.29274,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"jinja2","version":"3.0.3"}},"found":{"versionConstraint":"<3.1.3 (python)","vulnerabilityID":"GHSA-h5c8-rqwp-cp95"},"fix":{"suggestedVersion":"3.1.3"}}],"artifact":{"id":"11052aada3872803","name":"jinja2","version":"3.0.3","type":"python","locations":[{"path":"/lib/python3.8/site-packages/Jinja2-3.0.3.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/Jinja2-3.0.3.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/Jinja2-3.0.3.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/Jinja2-3.0.3.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/Jinja2-3.0.3.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/Jinja2-3.0.3.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:armin_ronacher_project:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher_project:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher_project:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python:jinja2:3.0.3:*:*:*:*:*:*:*"],"purl":"pkg:pypi/jinja2@3.0.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-h75v-3vvj-5mfj","dataSource":"https://github.com/advisories/GHSA-h75v-3vvj-5mfj","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Jinja vulnerable to HTML attribute injection when passing user input as keys to xmlattr filter","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N","metrics":{"baseScore":5.4,"exploitabilityScore":2.9,"impactScore":2.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-34064","epss":0.00085,"percentile":0.25888,"date":"2025-06-02"}],"fix":{"versions":["3.1.4"],"state":"fixed"},"advisories":[],"risk":0.0442},"relatedVulnerabilities":[{"id":"CVE-2024-34064","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-34064","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pallets/jinja/commit/0668239dc6b44ef38e7a6c9f91f312fd4ca581cb","https://github.com/pallets/jinja/security/advisories/GHSA-h75v-3vvj-5mfj","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/567XIGSZMABG6TSMYWD7MIYNJSUQQRUC/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/GCLF44KY43BSVMTE6S53B4V5WP3FRRSE/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SSCBHIL6BYKR5NRCBXP4XMP2CEEKGFVS/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZALNWE3TXPPHVPSI3AZ5CTMSTAVN5UMS/","https://github.com/pallets/jinja/commit/0668239dc6b44ef38e7a6c9f91f312fd4ca581cb","https://github.com/pallets/jinja/security/advisories/GHSA-h75v-3vvj-5mfj","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/567XIGSZMABG6TSMYWD7MIYNJSUQQRUC/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/GCLF44KY43BSVMTE6S53B4V5WP3FRRSE/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SSCBHIL6BYKR5NRCBXP4XMP2CEEKGFVS/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZALNWE3TXPPHVPSI3AZ5CTMSTAVN5UMS/"],"description":"Jinja is an extensible templating engine. The `xmlattr` filter in affected versions of Jinja accepts keys containing non-attribute characters. XML/HTML attributes cannot contain spaces, `/`, `>`, or `=`, as each would then be interpreted as starting a separate attribute. If an application accepts keys (as opposed to only values) as user input, and renders these in pages that other users see as well, an attacker could use this to inject other attributes and perform XSS. The fix for CVE-2024-22195 only addressed spaces but not other characters. Accepting keys as user input is now explicitly considered an unintended use case of the `xmlattr` filter, and code that does so without otherwise validating the input should be flagged as insecure, regardless of Jinja version. Accepting _values_ as user input continues to be safe. This vulnerability is fixed in 3.1.4.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N","metrics":{"baseScore":5.4,"exploitabilityScore":2.9,"impactScore":2.6},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N","metrics":{"baseScore":5.4,"exploitabilityScore":2.9,"impactScore":2.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-34064","epss":0.00085,"percentile":0.25888,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"jinja2","version":"3.0.3"}},"found":{"versionConstraint":"<3.1.4 (python)","vulnerabilityID":"GHSA-h75v-3vvj-5mfj"},"fix":{"suggestedVersion":"3.1.4"}}],"artifact":{"id":"11052aada3872803","name":"jinja2","version":"3.0.3","type":"python","locations":[{"path":"/lib/python3.8/site-packages/Jinja2-3.0.3.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/Jinja2-3.0.3.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/Jinja2-3.0.3.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/Jinja2-3.0.3.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/Jinja2-3.0.3.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/Jinja2-3.0.3.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:armin_ronacher_project:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher_project:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher_project:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python:jinja2:3.0.3:*:*:*:*:*:*:*"],"purl":"pkg:pypi/jinja2@3.0.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-gmj6-6f8f-6699","dataSource":"https://github.com/advisories/GHSA-gmj6-6f8f-6699","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Jinja has a sandbox breakout through malicious filenames","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.8,"exploitabilityScore":2.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-56201","epss":0.00064,"percentile":0.20401,"date":"2025-06-02"}],"fix":{"versions":["3.1.5"],"state":"fixed"},"advisories":[],"risk":0.044160000000000005},"relatedVulnerabilities":[{"id":"CVE-2024-56201","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-56201","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pallets/jinja/commit/767b23617628419ae3709ccfb02f9602ae9fe51f","https://github.com/pallets/jinja/issues/1792","https://github.com/pallets/jinja/releases/tag/3.1.5","https://github.com/pallets/jinja/security/advisories/GHSA-gmj6-6f8f-6699"],"description":"Jinja is an extensible templating engine. In versions on the 3.x branch prior to 3.1.5, a bug in the Jinja compiler allows an attacker that controls both the content and filename of a template to execute arbitrary Python code, regardless of if Jinja's sandbox is used. To exploit the vulnerability, an attacker needs to control both the filename and the contents of a template. Whether that is the case depends on the type of application using Jinja. This vulnerability impacts users of applications which execute untrusted templates where the template author can also choose the template filename. This vulnerability is fixed in 3.1.5.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:L/AC:L/AT:P/PR:L/UI:P/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":5.4},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-56201","epss":0.00064,"percentile":0.20401,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"jinja2","version":"3.0.3"}},"found":{"versionConstraint":">=3.0.0,<=3.1.4 (python)","vulnerabilityID":"GHSA-gmj6-6f8f-6699"},"fix":{"suggestedVersion":"3.1.5"}}],"artifact":{"id":"11052aada3872803","name":"jinja2","version":"3.0.3","type":"python","locations":[{"path":"/lib/python3.8/site-packages/Jinja2-3.0.3.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/Jinja2-3.0.3.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/Jinja2-3.0.3.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/Jinja2-3.0.3.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/Jinja2-3.0.3.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/Jinja2-3.0.3.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:armin_ronacher_project:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher_project:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher_project:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python:jinja2:3.0.3:*:*:*:*:*:*:*"],"purl":"pkg:pypi/jinja2@3.0.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-vqfr-h8mv-ghfj","dataSource":"https://github.com/advisories/GHSA-vqfr-h8mv-ghfj","namespace":"github:language:python","severity":"Critical","urls":[],"description":"h11 accepts some malformed Chunked-Encoding bodies","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N","metrics":{"baseScore":9.1,"exploitabilityScore":3.9,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-43859","epss":0.00044,"percentile":0.13131,"date":"2025-06-02"}],"fix":{"versions":["0.16.0"],"state":"fixed"},"advisories":[],"risk":0.03982},"relatedVulnerabilities":[{"id":"CVE-2025-43859","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-43859","namespace":"nvd:cpe","severity":"Critical","urls":["https://github.com/python-hyper/h11/commit/114803a29ce50116dc47951c690ad4892b1a36ed","https://github.com/python-hyper/h11/security/advisories/GHSA-vqfr-h8mv-ghfj"],"description":"h11 is a Python implementation of HTTP/1.1. Prior to version 0.16.0, a leniency in h11's parsing of line terminators in chunked-coding message bodies can lead to request smuggling vulnerabilities under certain conditions. This issue has been patched in version 0.16.0. Since exploitation requires the combination of buggy h11 with a buggy (reverse) proxy, fixing either component is sufficient to mitigate this issue.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N","metrics":{"baseScore":9.1,"exploitabilityScore":3.9,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-43859","epss":0.00044,"percentile":0.13131,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"h11","version":"0.13.0"}},"found":{"versionConstraint":"<0.16.0 (python)","vulnerabilityID":"GHSA-vqfr-h8mv-ghfj"},"fix":{"suggestedVersion":"0.16.0"}}],"artifact":{"id":"890661fad1101ba2","name":"h11","version":"0.13.0","type":"python","locations":[{"path":"/lib/python3.8/site-packages/h11-0.13.0.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/h11-0.13.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/h11-0.13.0.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/h11-0.13.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/h11-0.13.0.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/h11-0.13.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:nathaniel_j__smith_project:python-h11:0.13.0:*:*:*:*:*:*:*","cpe:2.3:a:nathaniel_j__smith_project:python_h11:0.13.0:*:*:*:*:*:*:*","cpe:2.3:a:nathaniel_j__smithproject:python-h11:0.13.0:*:*:*:*:*:*:*","cpe:2.3:a:nathaniel_j__smithproject:python_h11:0.13.0:*:*:*:*:*:*:*","cpe:2.3:a:nathaniel_j__smith_project:h11:0.13.0:*:*:*:*:*:*:*","cpe:2.3:a:nathaniel_j__smith:python-h11:0.13.0:*:*:*:*:*:*:*","cpe:2.3:a:nathaniel_j__smith:python_h11:0.13.0:*:*:*:*:*:*:*","cpe:2.3:a:nathaniel_j__smithproject:h11:0.13.0:*:*:*:*:*:*:*","cpe:2.3:a:nathaniel_j__smith:h11:0.13.0:*:*:*:*:*:*:*","cpe:2.3:a:njs_project:python-h11:0.13.0:*:*:*:*:*:*:*","cpe:2.3:a:njs_project:python_h11:0.13.0:*:*:*:*:*:*:*","cpe:2.3:a:njsproject:python-h11:0.13.0:*:*:*:*:*:*:*","cpe:2.3:a:njsproject:python_h11:0.13.0:*:*:*:*:*:*:*","cpe:2.3:a:python-h11:python-h11:0.13.0:*:*:*:*:*:*:*","cpe:2.3:a:python-h11:python_h11:0.13.0:*:*:*:*:*:*:*","cpe:2.3:a:python_h11:python-h11:0.13.0:*:*:*:*:*:*:*","cpe:2.3:a:python_h11:python_h11:0.13.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python-h11:0.13.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python_h11:0.13.0:*:*:*:*:*:*:*","cpe:2.3:a:njs_project:h11:0.13.0:*:*:*:*:*:*:*","cpe:2.3:a:h11:python-h11:0.13.0:*:*:*:*:*:*:*","cpe:2.3:a:h11:python_h11:0.13.0:*:*:*:*:*:*:*","cpe:2.3:a:njs:python-h11:0.13.0:*:*:*:*:*:*:*","cpe:2.3:a:njs:python_h11:0.13.0:*:*:*:*:*:*:*","cpe:2.3:a:njsproject:h11:0.13.0:*:*:*:*:*:*:*","cpe:2.3:a:python-h11:h11:0.13.0:*:*:*:*:*:*:*","cpe:2.3:a:python_h11:h11:0.13.0:*:*:*:*:*:*:*","cpe:2.3:a:python:h11:0.13.0:*:*:*:*:*:*:*","cpe:2.3:a:h11:h11:0.13.0:*:*:*:*:*:*:*","cpe:2.3:a:njs:h11:0.13.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/h11@0.13.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-2g68-c3qc-8985","dataSource":"https://github.com/advisories/GHSA-2g68-c3qc-8985","namespace":"github:language:python","severity":"High","urls":[],"description":"Werkzeug debugger vulnerable to remote execution when interacting with attacker controlled domain","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":1.7,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-34069","epss":0.0005,"percentile":0.15341,"date":"2025-06-02"}],"fix":{"versions":["3.0.3"],"state":"fixed"},"advisories":[],"risk":0.0375},"relatedVulnerabilities":[{"id":"CVE-2024-34069","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-34069","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pallets/werkzeug/commit/3386395b24c7371db11a5b8eaac0c91da5362692","https://github.com/pallets/werkzeug/security/advisories/GHSA-2g68-c3qc-8985","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/H4SH32AM3CTPMAAEOIDAN7VU565LO4IR/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HFERFN7PINV4MOGMGA3DPIXJPDCYOEJZ/","https://security.netapp.com/advisory/ntap-20240614-0004/","https://github.com/pallets/werkzeug/commit/3386395b24c7371db11a5b8eaac0c91da5362692","https://github.com/pallets/werkzeug/security/advisories/GHSA-2g68-c3qc-8985","https://lists.debian.org/debian-lts-announce/2025/02/msg00026.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/H4SH32AM3CTPMAAEOIDAN7VU565LO4IR/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HFERFN7PINV4MOGMGA3DPIXJPDCYOEJZ/","https://security.netapp.com/advisory/ntap-20240614-0004/"],"description":"Werkzeug is a comprehensive WSGI web application library. The debugger in affected versions of Werkzeug can allow an attacker to execute code on a developer's machine under some circumstances. This requires the attacker to get the developer to interact with a domain and subdomain they control, and enter the debugger PIN, but if they are successful it allows access to the debugger even if it is only running on localhost. This also requires the attacker to guess a URL in the developer's application that will trigger the debugger. This vulnerability is fixed in 3.0.3.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":1.7,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-34069","epss":0.0005,"percentile":0.15341,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"werkzeug","version":"2.3.8"}},"found":{"versionConstraint":"<3.0.3 (python)","vulnerabilityID":"GHSA-2g68-c3qc-8985"},"fix":{"suggestedVersion":"3.0.3"}}],"artifact":{"id":"18dfa85150beca55","name":"werkzeug","version":"2.3.8","type":"python","locations":[{"path":"/lib/python3.8/site-packages/werkzeug-2.3.8.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/werkzeug-2.3.8.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/werkzeug-2.3.8.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/werkzeug-2.3.8.dist-info/RECORD","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:python-werkzeug:python-werkzeug:2.3.8:*:*:*:*:*:*:*","cpe:2.3:a:python-werkzeug:python_werkzeug:2.3.8:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:python-werkzeug:2.3.8:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:python_werkzeug:2.3.8:*:*:*:*:*:*:*","cpe:2.3:a:python-werkzeug:werkzeug:2.3.8:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:werkzeug:2.3.8:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:python-werkzeug:2.3.8:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:python_werkzeug:2.3.8:*:*:*:*:*:*:*","cpe:2.3:a:python:python-werkzeug:2.3.8:*:*:*:*:*:*:*","cpe:2.3:a:python:python_werkzeug:2.3.8:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:werkzeug:2.3.8:*:*:*:*:*:*:*","cpe:2.3:a:python:werkzeug:2.3.8:*:*:*:*:*:*:*"],"purl":"pkg:pypi/werkzeug@2.3.8","upstreams":[]}},{"vulnerability":{"id":"GHSA-f9vj-2wh5-fj8j","dataSource":"https://github.com/advisories/GHSA-f9vj-2wh5-fj8j","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Werkzeug safe_join not safe on Windows","cvss":[],"epss":[{"cve":"CVE-2024-49766","epss":0.00036,"percentile":0.09088,"date":"2025-06-02"}],"fix":{"versions":["3.0.6"],"state":"fixed"},"advisories":[],"risk":0.018000000000000002},"relatedVulnerabilities":[{"id":"CVE-2024-49766","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-49766","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pallets/werkzeug/commit/2767bcb10a7dd1c297d812cc5e6d11a474c1f092","https://github.com/pallets/werkzeug/releases/tag/3.0.6","https://github.com/pallets/werkzeug/security/advisories/GHSA-f9vj-2wh5-fj8j","https://security.netapp.com/advisory/ntap-20250131-0005/"],"description":"Werkzeug is a Web Server Gateway Interface web application library. On Python < 3.11 on Windows, os.path.isabs() does not catch UNC paths like //server/share. Werkzeug's safe_join() relies on this check, and so can produce a path that is not safe, potentially allowing unintended access to data. Applications using Python >= 3.11, or not using Windows, are not vulnerable. Werkzeug version 3.0.6 contains a patch.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:H/AT:N/PR:N/UI:N/VC:L/VI:N/VA:N/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":6.3},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-49766","epss":0.00036,"percentile":0.09088,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"werkzeug","version":"2.3.8"}},"found":{"versionConstraint":"<=3.0.5 (python)","vulnerabilityID":"GHSA-f9vj-2wh5-fj8j"},"fix":{"suggestedVersion":"3.0.6"}}],"artifact":{"id":"18dfa85150beca55","name":"werkzeug","version":"2.3.8","type":"python","locations":[{"path":"/lib/python3.8/site-packages/werkzeug-2.3.8.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/werkzeug-2.3.8.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/werkzeug-2.3.8.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/werkzeug-2.3.8.dist-info/RECORD","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:python-werkzeug:python-werkzeug:2.3.8:*:*:*:*:*:*:*","cpe:2.3:a:python-werkzeug:python_werkzeug:2.3.8:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:python-werkzeug:2.3.8:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:python_werkzeug:2.3.8:*:*:*:*:*:*:*","cpe:2.3:a:python-werkzeug:werkzeug:2.3.8:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:werkzeug:2.3.8:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:python-werkzeug:2.3.8:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:python_werkzeug:2.3.8:*:*:*:*:*:*:*","cpe:2.3:a:python:python-werkzeug:2.3.8:*:*:*:*:*:*:*","cpe:2.3:a:python:python_werkzeug:2.3.8:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:werkzeug:2.3.8:*:*:*:*:*:*:*","cpe:2.3:a:python:werkzeug:2.3.8:*:*:*:*:*:*:*"],"purl":"pkg:pypi/werkzeug@2.3.8","upstreams":[]}},{"vulnerability":{"id":"GHSA-cpwx-vrp4-4pq7","dataSource":"https://github.com/advisories/GHSA-cpwx-vrp4-4pq7","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Jinja2 vulnerable to sandbox breakout through attr filter selecting format method","cvss":[],"epss":[{"cve":"CVE-2025-27516","epss":0.00034,"percentile":0.08503,"date":"2025-06-02"}],"fix":{"versions":["3.1.6"],"state":"fixed"},"advisories":[],"risk":0.017},"relatedVulnerabilities":[{"id":"CVE-2025-27516","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-27516","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pallets/jinja/commit/90457bbf33b8662926ae65cdde4c4c32e756e403","https://github.com/pallets/jinja/security/advisories/GHSA-cpwx-vrp4-4pq7","https://lists.debian.org/debian-lts-announce/2025/04/msg00045.html"],"description":"Jinja is an extensible templating engine. Prior to 3.1.6, an oversight in how the Jinja sandboxed environment interacts with the |attr filter allows an attacker that controls the content of a template to execute arbitrary Python code. To exploit the vulnerability, an attacker needs to control the content of a template. Whether that is the case depends on the type of application using Jinja. This vulnerability impacts users of applications which execute untrusted templates. Jinja's sandbox does catch calls to str.format and ensures they don't escape the sandbox. However, it's possible to use the |attr filter to get a reference to a string's plain format method, bypassing the sandbox. After the fix, the |attr filter no longer bypasses the environment's attribute lookup. This vulnerability is fixed in 3.1.6.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:L/AC:L/AT:P/PR:L/UI:P/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":5.4},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-27516","epss":0.00034,"percentile":0.08503,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"jinja2","version":"3.0.3"}},"found":{"versionConstraint":"<=3.1.5 (python)","vulnerabilityID":"GHSA-cpwx-vrp4-4pq7"},"fix":{"suggestedVersion":"3.1.6"}}],"artifact":{"id":"11052aada3872803","name":"jinja2","version":"3.0.3","type":"python","locations":[{"path":"/lib/python3.8/site-packages/Jinja2-3.0.3.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/Jinja2-3.0.3.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/Jinja2-3.0.3.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/Jinja2-3.0.3.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/Jinja2-3.0.3.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/Jinja2-3.0.3.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:armin_ronacher_project:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher_project:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher_project:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python-jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python_jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:jinja2:3.0.3:*:*:*:*:*:*:*","cpe:2.3:a:python:jinja2:3.0.3:*:*:*:*:*:*:*"],"purl":"pkg:pypi/jinja2@3.0.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-34jh-p97f-mpxf","dataSource":"https://github.com/advisories/GHSA-34jh-p97f-mpxf","namespace":"github:language:python","severity":"Medium","urls":[],"description":"urllib3's Proxy-Authorization request header isn't stripped during cross-origin redirects","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.4,"exploitabilityScore":0.8,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-37891","epss":0.00033,"percentile":0.08074,"date":"2025-06-02"}],"fix":{"versions":["2.2.2"],"state":"fixed"},"advisories":[],"risk":0.01551},"relatedVulnerabilities":[{"id":"CVE-2024-37891","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-37891","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/urllib3/urllib3/commit/accff72ecc2f6cf5a76d9570198a93ac7c90270e","https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf","https://github.com/urllib3/urllib3/commit/accff72ecc2f6cf5a76d9570198a93ac7c90270e","https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf","https://security.netapp.com/advisory/ntap-20240822-0003/","https://www.vicarius.io/vsociety/posts/proxy-authorization-header-handling-vulnerability-in-urllib3-cve-2024-37891"],"description":"urllib3 is a user-friendly HTTP client library for Python. When using urllib3's proxy support with `ProxyManager`, the `Proxy-Authorization` header is only sent to the configured proxy, as expected. However, when sending HTTP requests *without* using urllib3's proxy support, it's possible to accidentally configure the `Proxy-Authorization` header even though it won't have any effect as the request is not using a forwarding proxy or a tunneling proxy. In those cases, urllib3 doesn't treat the `Proxy-Authorization` HTTP header as one carrying authentication material and thus doesn't strip the header on cross-origin redirects. Because this is a highly unlikely scenario, we believe the severity of this vulnerability is low for almost all users. Out of an abundance of caution urllib3 will automatically strip the `Proxy-Authorization` header during cross-origin redirects to avoid the small chance that users are doing this on accident. Users should use urllib3's proxy support or disable automatic redirects to achieve safe processing of the `Proxy-Authorization` header, but we still decided to strip the header by default in order to further protect users who aren't using the correct approach. We believe the number of usages affected by this advisory is low. It requires all of the following to be true to be exploited: 1. Setting the `Proxy-Authorization` header without using urllib3's built-in proxy support. 2. Not disabling HTTP redirects. 3. Either not using an HTTPS origin server or for the proxy or target origin to redirect to a malicious origin. Users are advised to update to either version 1.26.19 or version 2.2.2. Users unable to upgrade may use the `Proxy-Authorization` header with urllib3's `ProxyManager`, disable HTTP redirects using `redirects=False` when sending requests, or not user the `Proxy-Authorization` header as mitigations.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.4,"exploitabilityScore":0.8,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-37891","epss":0.00033,"percentile":0.08074,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"urllib3","version":"2.1.0"}},"found":{"versionConstraint":">=2.0.0,<2.2.2 (python)","vulnerabilityID":"GHSA-34jh-p97f-mpxf"},"fix":{"suggestedVersion":"2.2.2"}}],"artifact":{"id":"8c3e2795a1eb3d89","name":"urllib3","version":"2.1.0","type":"python","locations":[{"path":"/lib/python3.8/site-packages/urllib3-2.1.0.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/urllib3-2.1.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/urllib3-2.1.0.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/urllib3-2.1.0.dist-info/RECORD","annotations":{"evidence":"supporting"}}],"language":"python","licenses":[],"cpes":["cpe:2.3:a:python:urllib3:2.1.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/urllib3@2.1.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-9wx4-h78v-vm56","dataSource":"https://github.com/advisories/GHSA-9wx4-h78v-vm56","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Requests `Session` object does not verify requests after making first request with verify=False","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N","metrics":{"baseScore":5.6,"exploitabilityScore":0.4,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-35195","epss":0.00009,"percentile":0.0055,"date":"2025-06-02"}],"fix":{"versions":["2.32.0"],"state":"fixed"},"advisories":[],"risk":0.004770000000000001},"relatedVulnerabilities":[{"id":"CVE-2024-35195","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-35195","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac","https://github.com/psf/requests/pull/6655","https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ/","https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac","https://github.com/psf/requests/pull/6655","https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ/"],"description":"Requests is a HTTP library. Prior to 2.32.0, when making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same host will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool. This vulnerability is fixed in 2.32.0.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N","metrics":{"baseScore":5.6,"exploitabilityScore":0.4,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-35195","epss":0.00009,"percentile":0.0055,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"requests","version":"2.31.0"}},"found":{"versionConstraint":"<2.32.0 (python)","vulnerabilityID":"GHSA-9wx4-h78v-vm56"},"fix":{"suggestedVersion":"2.32.0"}}],"artifact":{"id":"5afaa862a437a2e6","name":"requests","version":"2.31.0","type":"python","locations":[{"path":"/lib/python3.8/site-packages/requests-2.31.0.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/requests-2.31.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/requests-2.31.0.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/requests-2.31.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/requests-2.31.0.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/requests-2.31.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache 2.0"],"cpes":["cpe:2.3:a:python:requests:2.31.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/requests@2.31.0","upstreams":[]}}],"source":{"type":"sbom-file","target":"easyvizar-edge-syft.json"},"distro":{"name":"","version":"","idLike":null},"descriptor":{"name":"grype","version":"0.92.2","configuration":{"output":["json=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-05-21/easyvizar-edge-grype.json","template=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-05-21/easyvizar-edge-grype.html"],"file":"","pretty":false,"distro":"","add-cpes-if-none":false,"output-template-file":"../html.tmpl","check-for-app-update":true,"only-fixed":false,"only-notfixed":false,"ignore-wontfix":"","platform":"","search":{"scope":"squashed","unindexed-archives":false,"indexed-archives":true},"ignore":[{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"kernel-headers","version":"","language":"","type":"rpm","location":"","upstream-name":"kernel"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux(-.*)?-headers-.*","version":"","language":"","type":"deb","location":"","upstream-name":"linux.*"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux-libc-dev","version":"","language":"","type":"deb","location":"","upstream-name":"linux"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"}],"exclude":[],"externalSources":{"enable":false,"maven":{"searchUpstreamBySha1":true,"baseUrl":"https://search.maven.org/solrsearch/select","rateLimit":300000000}},"match":{"java":{"using-cpes":false},"jvm":{"using-cpes":true},"dotnet":{"using-cpes":false},"golang":{"using-cpes":false,"always-use-cpe-for-stdlib":true,"allow-main-module-pseudo-version-comparison":false},"javascript":{"using-cpes":false},"python":{"using-cpes":false},"ruby":{"using-cpes":false},"rust":{"using-cpes":false},"stock":{"using-cpes":true}},"fail-on-severity":"","registry":{"insecure-skip-tls-verify":false,"insecure-use-http":false,"auth":null,"ca-cert":""},"show-suppressed":false,"by-cve":false,"SortBy":{"sort-by":"risk"},"name":"","default-image-pull-source":"","vex-documents":[],"vex-add":[],"match-upstream-kernel-headers":false,"db":{"cache-dir":"/Users/alan/Library/Caches/grype/db","update-url":"https://grype.anchore.io/databases","ca-cert":"","auto-update":true,"validate-by-hash-on-start":true,"validate-age":true,"max-allowed-built-age":432000000000000,"require-update-check":false,"update-available-timeout":30000000000,"update-download-timeout":300000000000,"max-update-check-frequency":7200000000000},"exp":{},"dev":{"db":{"debug":false}}},"db":{"status":{"schemaVersion":"v6.0.2","from":"https://grype.anchore.io/databases/v6/vulnerability-db_v6.0.2_2025-06-03T01:32:03Z_1748923962.tar.zst?checksum=sha256%3A02a6127217518a93e0ef8739cb9f2d659109fff0d9cc25f0c13d5ca8b307a118","built":"2025-06-03T04:12:42Z","path":"/Users/alan/Library/Caches/grype/db/6/vulnerability.db","valid":true},"providers":{"alpine":{"captured":"2025-06-03T01:32:27Z","input":"xxh64:a6a065ece392f6d1"},"amazon":{"captured":"2025-06-03T01:32:10Z","input":"xxh64:b65d458d6858d72a"},"chainguard":{"captured":"2025-06-03T01:32:15Z","input":"xxh64:bad092583f78d4dd"},"debian":{"captured":"2025-06-03T01:32:22Z","input":"xxh64:b4717cad509f50d8"},"epss":{"captured":"2025-06-03T01:32:43Z","input":"xxh64:2f9660be834e0ce6"},"github":{"captured":"2025-06-03T01:32:21Z","input":"xxh64:cdd94f1952fcf607"},"kev":{"captured":"2025-06-03T01:32:03Z","input":"xxh64:575844c3434cc70b"},"mariner":{"captured":"2025-06-03T01:32:11Z","input":"xxh64:7628f1adb0b9b12b"},"nvd":{"captured":"2025-06-03T01:32:30Z","input":"xxh64:463c4e9a1d401101"},"oracle":{"captured":"2025-06-03T01:32:27Z","input":"xxh64:257df3059d28d823"},"rhel":{"captured":"2025-06-03T01:33:04Z","input":"xxh64:59e7d70bf674afdc"},"sles":{"captured":"2025-06-03T01:32:46Z","input":"xxh64:3cf7f372ea0c981a"},"ubuntu":{"captured":"2025-06-03T01:33:20Z","input":"xxh64:075be8afc080f2be"},"wolfi":{"captured":"2025-06-03T01:32:31Z","input":"xxh64:1aa0b26b004bdd38"}}},"timestamp":"2025-06-03T13:03:36.797788+01:00"}}
