{"matches":[{"vulnerability":{"id":"GHSA-q34m-jh98-gwm2","dataSource":"https://github.com/advisories/GHSA-q34m-jh98-gwm2","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Werkzeug possible resource exhaustion when parsing file data in forms","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-49767","epss":0.00974,"percentile":0.75666,"date":"2025-06-02"}],"fix":{"versions":["3.0.6"],"state":"fixed"},"advisories":[],"risk":0.60875},"relatedVulnerabilities":[{"id":"CVE-2024-49767","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-49767","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pallets/quart/commit/5e78c4169b8eb66b91ead3e62d44721b9e1644ee","https://github.com/pallets/quart/commit/abb04a512496206de279225340ed022852fbf51f","https://github.com/pallets/werkzeug/commit/50cfeebcb0727e18cc52ffbeb125f4a66551179b","https://github.com/pallets/werkzeug/releases/tag/3.0.6","https://github.com/pallets/werkzeug/security/advisories/GHSA-q34m-jh98-gwm2","https://security.netapp.com/advisory/ntap-20250103-0007/"],"description":"Werkzeug is a Web Server Gateway Interface web application library. Applications using `werkzeug.formparser.MultiPartParser` corresponding to a version of Werkzeug prior to 3.0.6 to parse `multipart/form-data` requests (e.g. all flask applications) are vulnerable to a relatively simple but effective resource exhaustion (denial of service) attack. A specifically crafted form submission request can cause the parser to allocate and block 3 to 8 times the upload size in main memory. There is no upper limit; a single upload at 1 Gbit/s can exhaust 32 GB of RAM in less than 60 seconds. Werkzeug version 3.0.6 fixes this issue.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:L/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":6.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-49767","epss":0.00974,"percentile":0.75666,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"werkzeug","version":"3.0.1"}},"found":{"versionConstraint":"<=3.0.5 (python)","vulnerabilityID":"GHSA-q34m-jh98-gwm2"},"fix":{"suggestedVersion":"3.0.6"}}],"artifact":{"id":"32446d0ea1bb1b4f","name":"werkzeug","version":"3.0.1","type":"python","locations":[{"path":"/lib/python3.8/site-packages/werkzeug-3.0.1.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/werkzeug-3.0.1.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/werkzeug-3.0.1.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/werkzeug-3.0.1.dist-info/RECORD","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:python-werkzeug:python-werkzeug:3.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python-werkzeug:python_werkzeug:3.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:python-werkzeug:3.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:python_werkzeug:3.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python-werkzeug:werkzeug:3.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:werkzeug:3.0.1:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:python-werkzeug:3.0.1:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:python_werkzeug:3.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python:python-werkzeug:3.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python:python_werkzeug:3.0.1:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:werkzeug:3.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python:werkzeug:3.0.1:*:*:*:*:*:*:*"],"purl":"pkg:pypi/werkzeug@3.0.1","upstreams":[]}},{"vulnerability":{"id":"GHSA-248v-346w-9cwc","dataSource":"https://github.com/advisories/GHSA-248v-346w-9cwc","namespace":"github:language:python","severity":"Low","urls":[],"description":"Certifi removes GLOBALTRUST root certificate","cvss":[],"epss":[{"cve":"CVE-2024-39689","epss":0.01928,"percentile":0.82506,"date":"2025-06-02"}],"fix":{"versions":["2024.7.4"],"state":"fixed"},"advisories":[],"risk":0.5783999999999999},"relatedVulnerabilities":[{"id":"CVE-2024-39689","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-39689","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/certifi/python-certifi/commit/bd8153872e9c6fc98f4023df9c2deaffea2fa463","https://github.com/certifi/python-certifi/security/advisories/GHSA-248v-346w-9cwc","https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI","https://github.com/certifi/python-certifi/commit/bd8153872e9c6fc98f4023df9c2deaffea2fa463","https://github.com/certifi/python-certifi/security/advisories/GHSA-248v-346w-9cwc","https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI","https://security.netapp.com/advisory/ntap-20241206-0001/"],"description":"Certifi is a curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts. Certifi starting in 2021.5.30 and prior to 2024.7.4 recognized root certificates from `GLOBALTRUST`. Certifi 2024.7.04 removes root certificates from `GLOBALTRUST` from the root store. These are in the process of being removed from Mozilla's trust store. `GLOBALTRUST`'s root certificates are being removed pursuant to an investigation which identified \"long-running and unresolved compliance issues.\"","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-39689","epss":0.01928,"percentile":0.82506,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"certifi","version":"2024.2.2"}},"found":{"versionConstraint":">=2021.5.30,<2024.7.4 (python)","vulnerabilityID":"GHSA-248v-346w-9cwc"},"fix":{"suggestedVersion":"2024.7.4"}}],"artifact":{"id":"385baad47aa78163","name":"certifi","version":"2024.2.2","type":"python","locations":[{"path":"/lib/python3.8/site-packages/certifi-2024.2.2.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/certifi-2024.2.2.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/certifi-2024.2.2.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/certifi-2024.2.2.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/certifi-2024.2.2.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/certifi-2024.2.2.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MPL-2.0"],"cpes":["cpe:2.3:a:certifi:certifi:2024.2.2:*:*:*:*:python:*:*"],"purl":"pkg:pypi/certifi@2024.2.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-5rjg-fvgr-3xxf","dataSource":"https://github.com/advisories/GHSA-5rjg-fvgr-3xxf","namespace":"github:language:python","severity":"High","urls":[],"description":"setuptools has a path traversal vulnerability in PackageIndex.download that leads to Arbitrary File Write","cvss":[],"epss":[{"cve":"CVE-2025-47273","epss":0.00435,"percentile":0.6206,"date":"2025-06-02"}],"fix":{"versions":["78.1.1"],"state":"fixed"},"advisories":[],"risk":0.32625},"relatedVulnerabilities":[{"id":"CVE-2025-47273","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-47273","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pypa/setuptools/blob/6ead555c5fb29bc57fe6105b1bffc163f56fd558/setuptools/package_index.py#L810C1-L825C88","https://github.com/pypa/setuptools/commit/250a6d17978f9f6ac3ac887091f2d32886fbbb0b","https://github.com/pypa/setuptools/issues/4946","https://github.com/pypa/setuptools/security/advisories/GHSA-5rjg-fvgr-3xxf","https://lists.debian.org/debian-lts-announce/2025/05/msg00035.html","https://github.com/pypa/setuptools/issues/4946"],"description":"setuptools is a package that allows users to download, build, install, upgrade, and uninstall Python packages. A path traversal vulnerability in `PackageIndex` is present in setuptools prior to version 78.1.1. An attacker would be allowed to write files to arbitrary locations on the filesystem with the permissions of the process running the Python code, which could escalate to remote code execution depending on the context. Version 78.1.1 fixes the issue.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:H/VA:N/SC:N/SI:N/SA:N/E:P/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":7.7},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-47273","epss":0.00435,"percentile":0.6206,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"setuptools","version":"44.0.0"}},"found":{"versionConstraint":"<78.1.1 (python)","vulnerabilityID":"GHSA-5rjg-fvgr-3xxf"},"fix":{"suggestedVersion":"78.1.1"}}],"artifact":{"id":"cbc2bdef91f3ae0f","name":"setuptools","version":"44.0.0","type":"python","locations":[{"path":"/lib/python3.8/site-packages/setuptools-44.0.0.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/setuptools-44.0.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/setuptools-44.0.0.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/setuptools-44.0.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/setuptools-44.0.0.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/setuptools-44.0.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["UNKNOWN"],"cpes":["cpe:2.3:a:python:setuptools:44.0.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/setuptools@44.0.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-r9hx-vwmv-q579","dataSource":"https://github.com/advisories/GHSA-r9hx-vwmv-q579","namespace":"github:language:python","severity":"High","urls":[],"description":"pypa/setuptools vulnerable to Regular Expression Denial of Service (ReDoS)","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-40897","epss":0.00318,"percentile":0.54322,"date":"2025-06-02"}],"fix":{"versions":["65.5.1"],"state":"fixed"},"advisories":[],"risk":0.2385},"relatedVulnerabilities":[{"id":"CVE-2022-40897","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2022-40897","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pypa/setuptools/blob/fe8a98e696241487ba6ac9f91faa38ade939ec5d/setuptools/package_index.py#L200","https://github.com/pypa/setuptools/commit/43a9c9bfa6aa626ec2a22540bea28d2ca77964be","https://github.com/pypa/setuptools/compare/v65.5.0...v65.5.1","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H/","https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/","https://pyup.io/vulnerabilities/CVE-2022-40897/52495/","https://security.netapp.com/advisory/ntap-20230214-0001/","https://security.netapp.com/advisory/ntap-20240621-0006/","https://github.com/pypa/setuptools/blob/fe8a98e696241487ba6ac9f91faa38ade939ec5d/setuptools/package_index.py#L200","https://github.com/pypa/setuptools/commit/43a9c9bfa6aa626ec2a22540bea28d2ca77964be","https://github.com/pypa/setuptools/compare/v65.5.0...v65.5.1","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H/","https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/","https://pyup.io/vulnerabilities/CVE-2022-40897/52495/","https://security.netapp.com/advisory/ntap-20230214-0001/","https://security.netapp.com/advisory/ntap-20240621-0006/"],"description":"Python Packaging Authority (PyPA) setuptools before 65.5.1 allows remote attackers to cause a denial of service via HTML in a crafted package or custom PackageIndex page. There is a Regular Expression Denial of Service (ReDoS) in package_index.py.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-40897","epss":0.00318,"percentile":0.54322,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"setuptools","version":"44.0.0"}},"found":{"versionConstraint":"<65.5.1 (python)","vulnerabilityID":"GHSA-r9hx-vwmv-q579"},"fix":{"suggestedVersion":"65.5.1"}}],"artifact":{"id":"cbc2bdef91f3ae0f","name":"setuptools","version":"44.0.0","type":"python","locations":[{"path":"/lib/python3.8/site-packages/setuptools-44.0.0.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/setuptools-44.0.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/setuptools-44.0.0.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/setuptools-44.0.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/setuptools-44.0.0.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/setuptools-44.0.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["UNKNOWN"],"cpes":["cpe:2.3:a:python:setuptools:44.0.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/setuptools@44.0.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-cx63-2mw6-8hw5","dataSource":"https://github.com/advisories/GHSA-cx63-2mw6-8hw5","namespace":"github:language:python","severity":"High","urls":[],"description":"setuptools vulnerable to Command Injection via package URL","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.8,"exploitabilityScore":2.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-6345","epss":0.00227,"percentile":0.45716,"date":"2025-06-02"}],"fix":{"versions":["70.0.0"],"state":"fixed"},"advisories":[],"risk":0.185005},"relatedVulnerabilities":[{"id":"CVE-2024-6345","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-6345","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pypa/setuptools/commit/88807c7062788254f654ea8c03427adc859321f0","https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5","https://github.com/pypa/setuptools/commit/88807c7062788254f654ea8c03427adc859321f0","https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5"],"description":"A vulnerability in the package_index module of pypa/setuptools versions up to 69.1.1 allows for remote code execution via its download functions. These functions, which are used to download packages from URLs provided by users or retrieved from package index servers, are susceptible to code injection. If these functions are exposed to user-controlled inputs, such as package URLs, they can execute arbitrary commands on the system. The issue is fixed in version 70.0.","cvss":[{"source":"security@huntr.dev","type":"Secondary","version":"3.0","vector":"CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.8,"exploitabilityScore":2.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-6345","epss":0.00227,"percentile":0.45716,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"setuptools","version":"44.0.0"}},"found":{"versionConstraint":"<70.0.0 (python)","vulnerabilityID":"GHSA-cx63-2mw6-8hw5"},"fix":{"suggestedVersion":"70.0.0"}}],"artifact":{"id":"cbc2bdef91f3ae0f","name":"setuptools","version":"44.0.0","type":"python","locations":[{"path":"/lib/python3.8/site-packages/setuptools-44.0.0.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/setuptools-44.0.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/setuptools-44.0.0.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/setuptools-44.0.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/setuptools-44.0.0.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/setuptools-44.0.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["UNKNOWN"],"cpes":["cpe:2.3:a:python:setuptools:44.0.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/setuptools@44.0.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-3f84-rpwh-47g6","dataSource":"https://github.com/advisories/GHSA-3f84-rpwh-47g6","namespace":"github:language:python","severity":"High","urls":[],"description":"Waitress vulnerable to DoS leading to high CPU usage/resource exhaustion","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-49769","epss":0.00226,"percentile":0.45623,"date":"2025-06-02"}],"fix":{"versions":["3.0.1"],"state":"fixed"},"advisories":[],"risk":0.16949999999999998},"relatedVulnerabilities":[{"id":"CVE-2024-49769","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-49769","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/Pylons/waitress/commit/1ae4e894c9f76543bee06584001583fc6fa8c95c","https://github.com/Pylons/waitress/issues/418","https://github.com/Pylons/waitress/pull/435","https://github.com/Pylons/waitress/security/advisories/GHSA-3f84-rpwh-47g6","https://lists.debian.org/debian-lts-announce/2024/11/msg00012.html"],"description":"Waitress is a Web Server Gateway Interface server for Python 2 and 3. When a remote client closes the connection before waitress has had the opportunity to call getpeername() waitress won't correctly clean up the connection leading to the main thread attempting to write to a socket that no longer exists, but not removing it from the list of sockets to attempt to process. This leads to a busy-loop calling the write function. A remote attacker could run waitress out of available sockets with very little resources required. Waitress 3.0.1 contains fixes that remove the race condition.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-49769","epss":0.00226,"percentile":0.45623,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"waitress","version":"3.0.0"}},"found":{"versionConstraint":"<3.0.1 (python)","vulnerabilityID":"GHSA-3f84-rpwh-47g6"},"fix":{"suggestedVersion":"3.0.1"}}],"artifact":{"id":"7c24096ecd6911b6","name":"waitress","version":"3.0.0","type":"python","locations":[{"path":"/lib/python3.8/site-packages/waitress-3.0.0.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/waitress-3.0.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/waitress-3.0.0.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/waitress-3.0.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/waitress-3.0.0.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/waitress-3.0.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["ZPL 2.1"],"cpes":["cpe:2.3:a:zope_foundation_and_contributors_project:python-waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_foundation_and_contributors_project:python_waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_foundation_and_contributorsproject:python-waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_foundation_and_contributorsproject:python_waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_foundation_and_contributors_project:waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_foundation_and_contributors:python-waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_foundation_and_contributors:python_waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_foundation_and_contributorsproject:waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_foundation_and_contributors:waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_dev_project:python-waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_dev_project:python_waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:python-waitress:python-waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:python-waitress:python_waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:python_waitress:python-waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:python_waitress:python_waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_devproject:python-waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_devproject:python_waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_dev_project:waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:python-waitress:waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:python_waitress:waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:waitress:python-waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:waitress:python_waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope-dev:python-waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope-dev:python_waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_dev:python-waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_dev:python_waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_devproject:waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python-waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python_waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:waitress:waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope-dev:waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_dev:waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:python:waitress:3.0.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/waitress@3.0.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-5xp3-jfq3-5q8x","dataSource":"https://github.com/advisories/GHSA-5xp3-jfq3-5q8x","namespace":"github:language:python","severity":"High","urls":[],"description":"Improper Input Validation in pip","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:N/I:H/A:N","metrics":{"baseScore":5.7,"exploitabilityScore":2.1,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-3572","epss":0.0024,"percentile":0.47549,"date":"2025-06-02"}],"fix":{"versions":["21.1"],"state":"fixed"},"advisories":[],"risk":0.15839999999999999},"relatedVulnerabilities":[{"id":"CVE-2021-3572","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2021-3572","namespace":"nvd:cpe","severity":"Medium","urls":["https://bugzilla.redhat.com/show_bug.cgi?id=1962856","https://security.netapp.com/advisory/ntap-20240621-0006/","https://www.oracle.com/security-alerts/cpuapr2022.html","https://www.oracle.com/security-alerts/cpujul2022.html","https://bugzilla.redhat.com/show_bug.cgi?id=1962856","https://security.netapp.com/advisory/ntap-20240621-0006/","https://www.oracle.com/security-alerts/cpuapr2022.html","https://www.oracle.com/security-alerts/cpujul2022.html"],"description":"A flaw was found in python-pip in the way it handled Unicode separators in git references. A remote attacker could possibly use this issue to install a different revision on a repository. The highest threat from this vulnerability is to data integrity. This is fixed in python-pip version 21.1.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:N/I:H/A:N","metrics":{"baseScore":5.7,"exploitabilityScore":2.1,"impactScore":3.6},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:M/Au:S/C:N/I:P/A:N","metrics":{"baseScore":3.5,"exploitabilityScore":6.9,"impactScore":2.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-3572","epss":0.0024,"percentile":0.47549,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"pip","version":"20.0.2"}},"found":{"versionConstraint":"<21.1 (python)","vulnerabilityID":"GHSA-5xp3-jfq3-5q8x"},"fix":{"suggestedVersion":"21.1"}}],"artifact":{"id":"b95ce6a904dca7bb","name":"pip","version":"20.0.2","type":"python","locations":[{"path":"/lib/python3.8/site-packages/pip-20.0.2.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/pip-20.0.2.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/pip-20.0.2.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/pip-20.0.2.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/pip-20.0.2.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/pip-20.0.2.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:pip_developers_project:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers_project:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev_project:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev_project:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers_project:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_devproject:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_devproject:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev_project:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa-dev:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa-dev:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_devproject:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa-dev:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip:pip:20.0.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/pip@20.0.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-q2x7-8rv6-6q7h","dataSource":"https://github.com/advisories/GHSA-q2x7-8rv6-6q7h","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Jinja has a sandbox breakout through indirect reference to format method","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":7.8,"exploitabilityScore":1.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-56326","epss":0.00103,"percentile":0.29451,"date":"2025-06-02"}],"fix":{"versions":["3.1.5"],"state":"fixed"},"advisories":[],"risk":0.06592},"relatedVulnerabilities":[{"id":"CVE-2024-56326","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-56326","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pallets/jinja/commit/48b0687e05a5466a91cd5812d604fa37ad0943b4","https://github.com/pallets/jinja/releases/tag/3.1.5","https://github.com/pallets/jinja/security/advisories/GHSA-q2x7-8rv6-6q7h"],"description":"Jinja is an extensible templating engine. Prior to 3.1.5, An oversight in how the Jinja sandboxed environment detects calls to str.format allows an attacker that controls the content of a template to execute arbitrary Python code. To exploit the vulnerability, an attacker needs to control the content of a template. Whether that is the case depends on the type of application using Jinja. This vulnerability impacts users of applications which execute untrusted templates. Jinja's sandbox does catch calls to str.format and ensures they don't escape the sandbox. However, it's possible to store a reference to a malicious string's format method, then pass that to a filter that calls it. No such filters are built-in to Jinja, but could be present through custom filters in an application. After the fix, such indirect calls are also handled by the sandbox. This vulnerability is fixed in 3.1.5.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:L/AC:L/AT:P/PR:L/UI:P/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":5.4},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":7.8,"exploitabilityScore":1.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-56326","epss":0.00103,"percentile":0.29451,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"jinja2","version":"3.1.3"}},"found":{"versionConstraint":"<=3.1.4 (python)","vulnerabilityID":"GHSA-q2x7-8rv6-6q7h"},"fix":{"suggestedVersion":"3.1.5"}}],"artifact":{"id":"07533c8fe1039d15","name":"jinja2","version":"3.1.3","type":"python","locations":[{"path":"/lib/python3.8/site-packages/Jinja2-3.1.3.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/Jinja2-3.1.3.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/Jinja2-3.1.3.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/Jinja2-3.1.3.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/Jinja2-3.1.3.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/Jinja2-3.1.3.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:python-jinja2:python-jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:python_jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python-jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python_jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python-jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python_jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python-jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python_jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python:jinja2:3.1.3:*:*:*:*:*:*:*"],"purl":"pkg:pypi/jinja2@3.1.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-h75v-3vvj-5mfj","dataSource":"https://github.com/advisories/GHSA-h75v-3vvj-5mfj","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Jinja vulnerable to HTML attribute injection when passing user input as keys to xmlattr filter","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N","metrics":{"baseScore":5.4,"exploitabilityScore":2.9,"impactScore":2.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-34064","epss":0.00085,"percentile":0.25888,"date":"2025-06-02"}],"fix":{"versions":["3.1.4"],"state":"fixed"},"advisories":[],"risk":0.0442},"relatedVulnerabilities":[{"id":"CVE-2024-34064","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-34064","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pallets/jinja/commit/0668239dc6b44ef38e7a6c9f91f312fd4ca581cb","https://github.com/pallets/jinja/security/advisories/GHSA-h75v-3vvj-5mfj","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/567XIGSZMABG6TSMYWD7MIYNJSUQQRUC/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/GCLF44KY43BSVMTE6S53B4V5WP3FRRSE/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SSCBHIL6BYKR5NRCBXP4XMP2CEEKGFVS/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZALNWE3TXPPHVPSI3AZ5CTMSTAVN5UMS/","https://github.com/pallets/jinja/commit/0668239dc6b44ef38e7a6c9f91f312fd4ca581cb","https://github.com/pallets/jinja/security/advisories/GHSA-h75v-3vvj-5mfj","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/567XIGSZMABG6TSMYWD7MIYNJSUQQRUC/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/GCLF44KY43BSVMTE6S53B4V5WP3FRRSE/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SSCBHIL6BYKR5NRCBXP4XMP2CEEKGFVS/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZALNWE3TXPPHVPSI3AZ5CTMSTAVN5UMS/"],"description":"Jinja is an extensible templating engine. The `xmlattr` filter in affected versions of Jinja accepts keys containing non-attribute characters. XML/HTML attributes cannot contain spaces, `/`, `>`, or `=`, as each would then be interpreted as starting a separate attribute. If an application accepts keys (as opposed to only values) as user input, and renders these in pages that other users see as well, an attacker could use this to inject other attributes and perform XSS. The fix for CVE-2024-22195 only addressed spaces but not other characters. Accepting keys as user input is now explicitly considered an unintended use case of the `xmlattr` filter, and code that does so without otherwise validating the input should be flagged as insecure, regardless of Jinja version. Accepting _values_ as user input continues to be safe. This vulnerability is fixed in 3.1.4.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N","metrics":{"baseScore":5.4,"exploitabilityScore":2.9,"impactScore":2.6},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N","metrics":{"baseScore":5.4,"exploitabilityScore":2.9,"impactScore":2.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-34064","epss":0.00085,"percentile":0.25888,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"jinja2","version":"3.1.3"}},"found":{"versionConstraint":"<3.1.4 (python)","vulnerabilityID":"GHSA-h75v-3vvj-5mfj"},"fix":{"suggestedVersion":"3.1.4"}}],"artifact":{"id":"07533c8fe1039d15","name":"jinja2","version":"3.1.3","type":"python","locations":[{"path":"/lib/python3.8/site-packages/Jinja2-3.1.3.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/Jinja2-3.1.3.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/Jinja2-3.1.3.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/Jinja2-3.1.3.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/Jinja2-3.1.3.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/Jinja2-3.1.3.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:python-jinja2:python-jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:python_jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python-jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python_jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python-jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python_jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python-jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python_jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python:jinja2:3.1.3:*:*:*:*:*:*:*"],"purl":"pkg:pypi/jinja2@3.1.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-gmj6-6f8f-6699","dataSource":"https://github.com/advisories/GHSA-gmj6-6f8f-6699","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Jinja has a sandbox breakout through malicious filenames","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.8,"exploitabilityScore":2.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-56201","epss":0.00064,"percentile":0.20401,"date":"2025-06-02"}],"fix":{"versions":["3.1.5"],"state":"fixed"},"advisories":[],"risk":0.044160000000000005},"relatedVulnerabilities":[{"id":"CVE-2024-56201","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-56201","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pallets/jinja/commit/767b23617628419ae3709ccfb02f9602ae9fe51f","https://github.com/pallets/jinja/issues/1792","https://github.com/pallets/jinja/releases/tag/3.1.5","https://github.com/pallets/jinja/security/advisories/GHSA-gmj6-6f8f-6699"],"description":"Jinja is an extensible templating engine. In versions on the 3.x branch prior to 3.1.5, a bug in the Jinja compiler allows an attacker that controls both the content and filename of a template to execute arbitrary Python code, regardless of if Jinja's sandbox is used. To exploit the vulnerability, an attacker needs to control both the filename and the contents of a template. Whether that is the case depends on the type of application using Jinja. This vulnerability impacts users of applications which execute untrusted templates where the template author can also choose the template filename. This vulnerability is fixed in 3.1.5.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:L/AC:L/AT:P/PR:L/UI:P/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":5.4},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-56201","epss":0.00064,"percentile":0.20401,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"jinja2","version":"3.1.3"}},"found":{"versionConstraint":">=3.0.0,<=3.1.4 (python)","vulnerabilityID":"GHSA-gmj6-6f8f-6699"},"fix":{"suggestedVersion":"3.1.5"}}],"artifact":{"id":"07533c8fe1039d15","name":"jinja2","version":"3.1.3","type":"python","locations":[{"path":"/lib/python3.8/site-packages/Jinja2-3.1.3.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/Jinja2-3.1.3.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/Jinja2-3.1.3.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/Jinja2-3.1.3.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/Jinja2-3.1.3.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/Jinja2-3.1.3.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:python-jinja2:python-jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:python_jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python-jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python_jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python-jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python_jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python-jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python_jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python:jinja2:3.1.3:*:*:*:*:*:*:*"],"purl":"pkg:pypi/jinja2@3.1.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-2g68-c3qc-8985","dataSource":"https://github.com/advisories/GHSA-2g68-c3qc-8985","namespace":"github:language:python","severity":"High","urls":[],"description":"Werkzeug debugger vulnerable to remote execution when interacting with attacker controlled domain","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":1.7,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-34069","epss":0.0005,"percentile":0.15341,"date":"2025-06-02"}],"fix":{"versions":["3.0.3"],"state":"fixed"},"advisories":[],"risk":0.0375},"relatedVulnerabilities":[{"id":"CVE-2024-34069","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-34069","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pallets/werkzeug/commit/3386395b24c7371db11a5b8eaac0c91da5362692","https://github.com/pallets/werkzeug/security/advisories/GHSA-2g68-c3qc-8985","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/H4SH32AM3CTPMAAEOIDAN7VU565LO4IR/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HFERFN7PINV4MOGMGA3DPIXJPDCYOEJZ/","https://security.netapp.com/advisory/ntap-20240614-0004/","https://github.com/pallets/werkzeug/commit/3386395b24c7371db11a5b8eaac0c91da5362692","https://github.com/pallets/werkzeug/security/advisories/GHSA-2g68-c3qc-8985","https://lists.debian.org/debian-lts-announce/2025/02/msg00026.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/H4SH32AM3CTPMAAEOIDAN7VU565LO4IR/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HFERFN7PINV4MOGMGA3DPIXJPDCYOEJZ/","https://security.netapp.com/advisory/ntap-20240614-0004/"],"description":"Werkzeug is a comprehensive WSGI web application library. The debugger in affected versions of Werkzeug can allow an attacker to execute code on a developer's machine under some circumstances. This requires the attacker to get the developer to interact with a domain and subdomain they control, and enter the debugger PIN, but if they are successful it allows access to the debugger even if it is only running on localhost. This also requires the attacker to guess a URL in the developer's application that will trigger the debugger. This vulnerability is fixed in 3.0.3.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":1.7,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-34069","epss":0.0005,"percentile":0.15341,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"werkzeug","version":"3.0.1"}},"found":{"versionConstraint":"<3.0.3 (python)","vulnerabilityID":"GHSA-2g68-c3qc-8985"},"fix":{"suggestedVersion":"3.0.3"}}],"artifact":{"id":"32446d0ea1bb1b4f","name":"werkzeug","version":"3.0.1","type":"python","locations":[{"path":"/lib/python3.8/site-packages/werkzeug-3.0.1.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/werkzeug-3.0.1.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/werkzeug-3.0.1.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/werkzeug-3.0.1.dist-info/RECORD","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:python-werkzeug:python-werkzeug:3.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python-werkzeug:python_werkzeug:3.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:python-werkzeug:3.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:python_werkzeug:3.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python-werkzeug:werkzeug:3.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:werkzeug:3.0.1:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:python-werkzeug:3.0.1:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:python_werkzeug:3.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python:python-werkzeug:3.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python:python_werkzeug:3.0.1:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:werkzeug:3.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python:werkzeug:3.0.1:*:*:*:*:*:*:*"],"purl":"pkg:pypi/werkzeug@3.0.1","upstreams":[]}},{"vulnerability":{"id":"GHSA-jfmj-5v4g-7637","dataSource":"https://github.com/advisories/GHSA-jfmj-5v4g-7637","namespace":"github:language:python","severity":"Medium","urls":[],"description":"zipp Denial of Service vulnerability","cvss":[{"type":"Secondary","version":"3.0","vector":"CVSS:3.0/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":6.2,"exploitabilityScore":2.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-5569","epss":0.00042,"percentile":0.12225,"date":"2025-06-02"}],"fix":{"versions":["3.19.1"],"state":"fixed"},"advisories":[],"risk":0.023520000000000003},"relatedVulnerabilities":[{"id":"CVE-2024-5569","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-5569","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/jaraco/zipp/commit/fd604bd34f0343472521a36da1fbd22e793e14fd","https://huntr.com/bounties/be898306-11f9-46b4-b28c-f4c4aa4ffbae","https://github.com/jaraco/zipp/commit/fd604bd34f0343472521a36da1fbd22e793e14fd","https://huntr.com/bounties/be898306-11f9-46b4-b28c-f4c4aa4ffbae"],"description":"A Denial of Service (DoS) vulnerability exists in the jaraco/zipp library, affecting all versions prior to 3.19.1. The vulnerability is triggered when processing a specially crafted zip file that leads to an infinite loop. This issue also impacts the zipfile module of CPython, as features from the third-party zipp library are later merged into CPython, and the affected code is identical in both projects. The infinite loop can be initiated through the use of functions affecting the `Path` module in both zipp and zipfile, such as `joinpath`, the overloaded division operator, and `iterdir`. Although the infinite loop is not resource exhaustive, it prevents the application from responding. The vulnerability was addressed in version 3.19.1 of jaraco/zipp.","cvss":[{"source":"security@huntr.dev","type":"Secondary","version":"3.0","vector":"CVSS:3.0/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":6.2,"exploitabilityScore":2.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-5569","epss":0.00042,"percentile":0.12225,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"zipp","version":"3.17.0"}},"found":{"versionConstraint":"<3.19.1 (python)","vulnerabilityID":"GHSA-jfmj-5v4g-7637"},"fix":{"suggestedVersion":"3.19.1"}}],"artifact":{"id":"83048dcef6f63c18","name":"zipp","version":"3.17.0","type":"python","locations":[{"path":"/lib/python3.8/site-packages/zipp-3.17.0.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/zipp-3.17.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/zipp-3.17.0.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/zipp-3.17.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/zipp-3.17.0.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/zipp-3.17.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:jason_r__coombs_project:python-zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jason_r__coombs_project:python_zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jason_r__coombsproject:python-zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jason_r__coombsproject:python_zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jason_r__coombs_project:zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jason_r__coombs:python-zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jason_r__coombs:python_zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jason_r__coombsproject:zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jaraco_project:python-zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jaraco_project:python_zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jaracoproject:python-zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jaracoproject:python_zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:python-zipp:python-zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:python-zipp:python_zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:python_zipp:python-zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:python_zipp:python_zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jason_r__coombs:zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jaraco_project:zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jaraco:python-zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jaraco:python_zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jaracoproject:zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python-zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python_zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:python-zipp:zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:python_zipp:zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:zipp:python-zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:zipp:python_zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jaraco:zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:python:zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:zipp:zipp:3.17.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/zipp@3.17.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-mq26-g339-26xf","dataSource":"https://github.com/advisories/GHSA-mq26-g339-26xf","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Command Injection in pip when used with Mercurial","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-5752","epss":0.0004,"percentile":0.11732,"date":"2025-06-02"}],"fix":{"versions":["23.3"],"state":"fixed"},"advisories":[],"risk":0.021},"relatedVulnerabilities":[{"id":"CVE-2023-5752","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-5752","namespace":"nvd:cpe","severity":"Low","urls":["https://github.com/pypa/pip/pull/12306","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/622OZXWG72ISQPLM5Y57YCVIMWHD4C3U/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/65UKKF5LBHEFDCUSPBHUN4IHYX7SRMHH/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FXUVMJM25PUAZRQZBF54OFVKTY3MINPW/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KFC2SPFG5FLCZBYY2K3T5MFW2D22NG6E/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YBSB3SUPQ3VIFYUMHPO3MEQI4BJAXKCZ/","https://mail.python.org/archives/list/security-announce@python.org/thread/F4PL35U6X4VVHZ5ILJU3PWUWN7H7LZXL/","https://github.com/pypa/pip/pull/12306","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/622OZXWG72ISQPLM5Y57YCVIMWHD4C3U/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/65UKKF5LBHEFDCUSPBHUN4IHYX7SRMHH/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FXUVMJM25PUAZRQZBF54OFVKTY3MINPW/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KFC2SPFG5FLCZBYY2K3T5MFW2D22NG6E/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YBSB3SUPQ3VIFYUMHPO3MEQI4BJAXKCZ/","https://mail.python.org/archives/list/security-announce@python.org/thread/F4PL35U6X4VVHZ5ILJU3PWUWN7H7LZXL/"],"description":"When installing a package from a Mercurial VCS URL  (ie \"pip install \nhg+...\") with pip prior to v23.3, the specified Mercurial revision could\n be used to inject arbitrary configuration options to the \"hg clone\" \ncall (ie \"--config\"). Controlling the Mercurial configuration can modify\n how and which repository is installed. This vulnerability does not \naffect users who aren't installing from Mercurial.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:N","metrics":{"baseScore":3.3,"exploitabilityScore":1.9,"impactScore":1.5},"vendorMetadata":{}},{"source":"cna@python.org","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-5752","epss":0.0004,"percentile":0.11732,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"pip","version":"20.0.2"}},"found":{"versionConstraint":"<23.3 (python)","vulnerabilityID":"GHSA-mq26-g339-26xf"},"fix":{"suggestedVersion":"23.3"}}],"artifact":{"id":"b95ce6a904dca7bb","name":"pip","version":"20.0.2","type":"python","locations":[{"path":"/lib/python3.8/site-packages/pip-20.0.2.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/pip-20.0.2.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/pip-20.0.2.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/pip-20.0.2.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/pip-20.0.2.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/pip-20.0.2.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:pip_developers_project:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers_project:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev_project:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev_project:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers_project:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_devproject:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_devproject:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev_project:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa-dev:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa-dev:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_devproject:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa-dev:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip:pip:20.0.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/pip@20.0.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-9298-4cf8-g4wj","dataSource":"https://github.com/advisories/GHSA-9298-4cf8-g4wj","namespace":"github:language:python","severity":"Critical","urls":[],"description":"Waitress has request processing race condition in HTTP pipelining with invalid first request","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N","metrics":{"baseScore":9.1,"exploitabilityScore":3.9,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-49768","epss":0.0002,"percentile":0.03727,"date":"2025-06-02"}],"fix":{"versions":["3.0.1"],"state":"fixed"},"advisories":[],"risk":0.0181},"relatedVulnerabilities":[{"id":"CVE-2024-49768","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-49768","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/Pylons/waitress/commit/e4359018537af376cf24bd13616d861e2fb76f65","https://github.com/Pylons/waitress/security/advisories/GHSA-9298-4cf8-g4wj"],"description":"Waitress is a Web Server Gateway Interface server for Python 2 and 3. A remote client may send a request that is exactly recv_bytes (defaults to 8192) long, followed by a secondary request using HTTP pipelining. When request lookahead is disabled (default) we won't read any more requests, and when the first request fails due to a parsing error, we simply close the connection. However when request lookahead is enabled, it is possible to process and receive the first request, start sending the error message back to the client while we read the next request and queue it. This will allow the secondary request to be serviced by the worker thread while the connection should be closed. Waitress 3.0.1 fixes the race condition. As a workaround, disable channel_request_lookahead, this is set to 0 by default disabling this feature.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N","metrics":{"baseScore":4.8,"exploitabilityScore":2.3,"impactScore":2.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N","metrics":{"baseScore":9.1,"exploitabilityScore":3.9,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-49768","epss":0.0002,"percentile":0.03727,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"waitress","version":"3.0.0"}},"found":{"versionConstraint":">=2.0.0,<3.0.1 (python)","vulnerabilityID":"GHSA-9298-4cf8-g4wj"},"fix":{"suggestedVersion":"3.0.1"}}],"artifact":{"id":"7c24096ecd6911b6","name":"waitress","version":"3.0.0","type":"python","locations":[{"path":"/lib/python3.8/site-packages/waitress-3.0.0.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/waitress-3.0.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/waitress-3.0.0.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/waitress-3.0.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/waitress-3.0.0.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/waitress-3.0.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["ZPL 2.1"],"cpes":["cpe:2.3:a:zope_foundation_and_contributors_project:python-waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_foundation_and_contributors_project:python_waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_foundation_and_contributorsproject:python-waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_foundation_and_contributorsproject:python_waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_foundation_and_contributors_project:waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_foundation_and_contributors:python-waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_foundation_and_contributors:python_waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_foundation_and_contributorsproject:waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_foundation_and_contributors:waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_dev_project:python-waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_dev_project:python_waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:python-waitress:python-waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:python-waitress:python_waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:python_waitress:python-waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:python_waitress:python_waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_devproject:python-waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_devproject:python_waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_dev_project:waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:python-waitress:waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:python_waitress:waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:waitress:python-waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:waitress:python_waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope-dev:python-waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope-dev:python_waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_dev:python-waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_dev:python_waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_devproject:waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python-waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python_waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:waitress:waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope-dev:waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:zope_dev:waitress:3.0.0:*:*:*:*:*:*:*","cpe:2.3:a:python:waitress:3.0.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/waitress@3.0.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-f9vj-2wh5-fj8j","dataSource":"https://github.com/advisories/GHSA-f9vj-2wh5-fj8j","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Werkzeug safe_join not safe on Windows","cvss":[],"epss":[{"cve":"CVE-2024-49766","epss":0.00036,"percentile":0.09088,"date":"2025-06-02"}],"fix":{"versions":["3.0.6"],"state":"fixed"},"advisories":[],"risk":0.018000000000000002},"relatedVulnerabilities":[{"id":"CVE-2024-49766","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-49766","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pallets/werkzeug/commit/2767bcb10a7dd1c297d812cc5e6d11a474c1f092","https://github.com/pallets/werkzeug/releases/tag/3.0.6","https://github.com/pallets/werkzeug/security/advisories/GHSA-f9vj-2wh5-fj8j","https://security.netapp.com/advisory/ntap-20250131-0005/"],"description":"Werkzeug is a Web Server Gateway Interface web application library. On Python < 3.11 on Windows, os.path.isabs() does not catch UNC paths like //server/share. Werkzeug's safe_join() relies on this check, and so can produce a path that is not safe, potentially allowing unintended access to data. Applications using Python >= 3.11, or not using Windows, are not vulnerable. Werkzeug version 3.0.6 contains a patch.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:H/AT:N/PR:N/UI:N/VC:L/VI:N/VA:N/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":6.3},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-49766","epss":0.00036,"percentile":0.09088,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"werkzeug","version":"3.0.1"}},"found":{"versionConstraint":"<=3.0.5 (python)","vulnerabilityID":"GHSA-f9vj-2wh5-fj8j"},"fix":{"suggestedVersion":"3.0.6"}}],"artifact":{"id":"32446d0ea1bb1b4f","name":"werkzeug","version":"3.0.1","type":"python","locations":[{"path":"/lib/python3.8/site-packages/werkzeug-3.0.1.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/werkzeug-3.0.1.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/werkzeug-3.0.1.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/werkzeug-3.0.1.dist-info/RECORD","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:python-werkzeug:python-werkzeug:3.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python-werkzeug:python_werkzeug:3.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:python-werkzeug:3.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:python_werkzeug:3.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python-werkzeug:werkzeug:3.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:werkzeug:3.0.1:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:python-werkzeug:3.0.1:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:python_werkzeug:3.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python:python-werkzeug:3.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python:python_werkzeug:3.0.1:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:werkzeug:3.0.1:*:*:*:*:*:*:*","cpe:2.3:a:python:werkzeug:3.0.1:*:*:*:*:*:*:*"],"purl":"pkg:pypi/werkzeug@3.0.1","upstreams":[]}},{"vulnerability":{"id":"GHSA-cpwx-vrp4-4pq7","dataSource":"https://github.com/advisories/GHSA-cpwx-vrp4-4pq7","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Jinja2 vulnerable to sandbox breakout through attr filter selecting format method","cvss":[],"epss":[{"cve":"CVE-2025-27516","epss":0.00034,"percentile":0.08503,"date":"2025-06-02"}],"fix":{"versions":["3.1.6"],"state":"fixed"},"advisories":[],"risk":0.017},"relatedVulnerabilities":[{"id":"CVE-2025-27516","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-27516","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pallets/jinja/commit/90457bbf33b8662926ae65cdde4c4c32e756e403","https://github.com/pallets/jinja/security/advisories/GHSA-cpwx-vrp4-4pq7","https://lists.debian.org/debian-lts-announce/2025/04/msg00045.html"],"description":"Jinja is an extensible templating engine. Prior to 3.1.6, an oversight in how the Jinja sandboxed environment interacts with the |attr filter allows an attacker that controls the content of a template to execute arbitrary Python code. To exploit the vulnerability, an attacker needs to control the content of a template. Whether that is the case depends on the type of application using Jinja. This vulnerability impacts users of applications which execute untrusted templates. Jinja's sandbox does catch calls to str.format and ensures they don't escape the sandbox. However, it's possible to use the |attr filter to get a reference to a string's plain format method, bypassing the sandbox. After the fix, the |attr filter no longer bypasses the environment's attribute lookup. This vulnerability is fixed in 3.1.6.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:L/AC:L/AT:P/PR:L/UI:P/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":5.4},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-27516","epss":0.00034,"percentile":0.08503,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"jinja2","version":"3.1.3"}},"found":{"versionConstraint":"<=3.1.5 (python)","vulnerabilityID":"GHSA-cpwx-vrp4-4pq7"},"fix":{"suggestedVersion":"3.1.6"}}],"artifact":{"id":"07533c8fe1039d15","name":"jinja2","version":"3.1.3","type":"python","locations":[{"path":"/lib/python3.8/site-packages/Jinja2-3.1.3.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/Jinja2-3.1.3.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/Jinja2-3.1.3.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/Jinja2-3.1.3.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/Jinja2-3.1.3.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/Jinja2-3.1.3.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:python-jinja2:python-jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:python_jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python-jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:python_jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python-jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:python_jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python-jinja2:jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python-jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python_jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python_jinja2:jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:jinja2:jinja2:3.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python:jinja2:3.1.3:*:*:*:*:*:*:*"],"purl":"pkg:pypi/jinja2@3.1.3","upstreams":[]}}],"source":{"type":"sbom-file","target":"eisenradio-syft.json"},"distro":{"name":"","version":"","idLike":null},"descriptor":{"name":"grype","version":"0.92.2","configuration":{"output":["json=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-05-21/eisenradio-grype.json","template=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-05-21/eisenradio-grype.html"],"file":"","pretty":false,"distro":"","add-cpes-if-none":false,"output-template-file":"../html.tmpl","check-for-app-update":true,"only-fixed":false,"only-notfixed":false,"ignore-wontfix":"","platform":"","search":{"scope":"squashed","unindexed-archives":false,"indexed-archives":true},"ignore":[{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"kernel-headers","version":"","language":"","type":"rpm","location":"","upstream-name":"kernel"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux(-.*)?-headers-.*","version":"","language":"","type":"deb","location":"","upstream-name":"linux.*"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux-libc-dev","version":"","language":"","type":"deb","location":"","upstream-name":"linux"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"}],"exclude":[],"externalSources":{"enable":false,"maven":{"searchUpstreamBySha1":true,"baseUrl":"https://search.maven.org/solrsearch/select","rateLimit":300000000}},"match":{"java":{"using-cpes":false},"jvm":{"using-cpes":true},"dotnet":{"using-cpes":false},"golang":{"using-cpes":false,"always-use-cpe-for-stdlib":true,"allow-main-module-pseudo-version-comparison":false},"javascript":{"using-cpes":false},"python":{"using-cpes":false},"ruby":{"using-cpes":false},"rust":{"using-cpes":false},"stock":{"using-cpes":true}},"fail-on-severity":"","registry":{"insecure-skip-tls-verify":false,"insecure-use-http":false,"auth":null,"ca-cert":""},"show-suppressed":false,"by-cve":false,"SortBy":{"sort-by":"risk"},"name":"","default-image-pull-source":"","vex-documents":[],"vex-add":[],"match-upstream-kernel-headers":false,"db":{"cache-dir":"/Users/alan/Library/Caches/grype/db","update-url":"https://grype.anchore.io/databases","ca-cert":"","auto-update":true,"validate-by-hash-on-start":true,"validate-age":true,"max-allowed-built-age":432000000000000,"require-update-check":false,"update-available-timeout":30000000000,"update-download-timeout":300000000000,"max-update-check-frequency":7200000000000},"exp":{},"dev":{"db":{"debug":false}}},"db":{"status":{"schemaVersion":"v6.0.2","from":"https://grype.anchore.io/databases/v6/vulnerability-db_v6.0.2_2025-06-03T01:32:03Z_1748923962.tar.zst?checksum=sha256%3A02a6127217518a93e0ef8739cb9f2d659109fff0d9cc25f0c13d5ca8b307a118","built":"2025-06-03T04:12:42Z","path":"/Users/alan/Library/Caches/grype/db/6/vulnerability.db","valid":true},"providers":{"alpine":{"captured":"2025-06-03T01:32:27Z","input":"xxh64:a6a065ece392f6d1"},"amazon":{"captured":"2025-06-03T01:32:10Z","input":"xxh64:b65d458d6858d72a"},"chainguard":{"captured":"2025-06-03T01:32:15Z","input":"xxh64:bad092583f78d4dd"},"debian":{"captured":"2025-06-03T01:32:22Z","input":"xxh64:b4717cad509f50d8"},"epss":{"captured":"2025-06-03T01:32:43Z","input":"xxh64:2f9660be834e0ce6"},"github":{"captured":"2025-06-03T01:32:21Z","input":"xxh64:cdd94f1952fcf607"},"kev":{"captured":"2025-06-03T01:32:03Z","input":"xxh64:575844c3434cc70b"},"mariner":{"captured":"2025-06-03T01:32:11Z","input":"xxh64:7628f1adb0b9b12b"},"nvd":{"captured":"2025-06-03T01:32:30Z","input":"xxh64:463c4e9a1d401101"},"oracle":{"captured":"2025-06-03T01:32:27Z","input":"xxh64:257df3059d28d823"},"rhel":{"captured":"2025-06-03T01:33:04Z","input":"xxh64:59e7d70bf674afdc"},"sles":{"captured":"2025-06-03T01:32:46Z","input":"xxh64:3cf7f372ea0c981a"},"ubuntu":{"captured":"2025-06-03T01:33:20Z","input":"xxh64:075be8afc080f2be"},"wolfi":{"captured":"2025-06-03T01:32:31Z","input":"xxh64:1aa0b26b004bdd38"}}},"timestamp":"2025-06-03T13:03:39.526097+01:00"}}
