{"matches":[{"vulnerability":{"id":"CVE-2025-0938","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-0938","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/python/cpython/commit/526617ed68cde460236c973e5d0a8bad4de896ba","https://github.com/python/cpython/commit/90e526ae67b172ed7c6c56e7edad36263b0f9403","https://github.com/python/cpython/commit/a7084f6075c9595ba60119ce8c62f1496f50c568","https://github.com/python/cpython/commit/b8b4b713c5f8ec0958c7ef8d29d6711889bc94ab","https://github.com/python/cpython/commit/d89a5f6a6e65511a5f6e0618c4c30a7aa5aba56a","https://github.com/python/cpython/commit/ff4e5c25666f63544071a6b075ae8b25c98b7a32","https://github.com/python/cpython/issues/105704","https://github.com/python/cpython/pull/129418","https://mail.python.org/archives/list/security-announce@python.org/thread/K4EUG6EKV6JYFIC24BASYOZS4M5XOQIB/","https://security.netapp.com/advisory/ntap-20250314-0002/"],"description":"The Python standard library functions `urllib.parse.urlsplit` and `urlparse` accepted domain names that included square brackets which isn't valid according to RFC 3986. Square brackets are only meant to be used as delimiters for specifying IPv6 and IPvFuture hosts in URLs. This could result in differential parsing across the Python URL parser and other specification-compliant URL parsers.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:H/AT:P/PR:N/UI:N/VC:N/VI:L/VA:N/SC:N/SI:L/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":6.3},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-0938","epss":0.01039,"percentile":0.76414,"date":"2025-06-02"}],"fix":{"versions":["3.9.22","3.10.17","3.11.12","3.12.9","3.13.2","3.14.0a5"],"state":"fixed"},"advisories":[],"risk":0.5870349999999999},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.11.10:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.11.10"}},"found":{"vulnerabilityID":"CVE-2025-0938","versionConstraint":"< 3.9.22,>= 3.10.0, < 3.10.17,>= 3.11.0, < 3.11.12,>= 3.12.0, < 3.12.9,>= 3.13.0, < 3.13.2,>= 3.14.0a1, < 3.14.0a5 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.11.12"}}],"artifact":{"id":"8c3b47afaa19befa","name":"python","version":"3.11.10","type":"binary","locations":[{"path":"/tools/python3/python3.11","accessPath":"/tools/python3/python3.11","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.11.10:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.11.10:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.11.10","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-9287","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-9287","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/python/cpython/commit/633555735a023d3e4d92ba31da35b1205f9ecbd7","https://github.com/python/cpython/commit/8450b2482586857d689b6658f08de9c8179af7db","https://github.com/python/cpython/commit/9286ab3a107ea41bd3f3c3682ce2512692bdded8","https://github.com/python/cpython/commit/ae961ae94bf19c8f8c7fbea3d1c25cc55ce8ae97","https://github.com/python/cpython/commit/d48cc82ed25e26b02eb97c6263d95dcaa1e9111b","https://github.com/python/cpython/commit/e52095a0c1005a87eed2276af7a1f2f66e2b6483","https://github.com/python/cpython/issues/124651","https://github.com/python/cpython/pull/124712","https://mail.python.org/archives/list/security-announce@python.org/thread/RSPJ2B5JL22FG3TKUJ7D7DQ4N5JRRBZL/","https://security.netapp.com/advisory/ntap-20250425-0006/"],"description":"A vulnerability has been found in the CPython `venv` module and CLI where path names provided when creating a virtual environment were not quoted properly, allowing the creator to inject commands into virtual environment \"activation\" scripts (ie \"source venv/bin/activate\"). This means that attacker-controlled virtual environments are able to run commands when the virtual environment is activated. Virtual environments which are not created by an attacker or which aren't activated before being used (ie \"./venv/bin/python\") are not affected.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":7.8,"exploitabilityScore":1.9,"impactScore":5.9},"vendorMetadata":{}},{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:L/AC:L/AT:P/PR:H/UI:A/VC:H/VI:H/VA:N/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:Green","metrics":{"baseScore":5.3},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-9287","epss":0.00038,"percentile":0.10564,"date":"2025-06-02"}],"fix":{"versions":["3.9.21","3.10.16","3.11.11","3.12.8","3.13.1","3.14.0a2"],"state":"fixed"},"advisories":[],"risk":0.026695},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.11.10:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.11.10"}},"found":{"vulnerabilityID":"CVE-2024-9287","versionConstraint":"< 3.9.21,>= 3.10.0, < 3.10.16,>= 3.11.0, < 3.11.11,>= 3.12.0, < 3.12.8,>= 3.13.0, < 3.13.1,>= 3.14.0a1, < 3.14.0a2 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.11.11"}}],"artifact":{"id":"8c3b47afaa19befa","name":"python","version":"3.11.10","type":"binary","locations":[{"path":"/tools/python3/python3.11","accessPath":"/tools/python3/python3.11","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.11.10:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.11.10:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.11.10","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-3220","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-3220","namespace":"nvd:cpe","severity":"Low","urls":["https://mail.python.org/archives/list/security-announce@python.org/thread/CDXW34ND2LSAOYAR5N6UNONP4ZBX4D6R/","http://www.openwall.com/lists/oss-security/2025/02/14/8","https://security.netapp.com/advisory/ntap-20250314-0001/"],"description":"There is a defect in the CPython standard library module “mimetypes” where on Windows the default list of known file locations are writable meaning other users can create invalid files to cause MemoryError to be raised on Python runtime startup or have file extensions be interpreted as the incorrect file type.\n\nThis defect is caused by the default locations of Linux and macOS platforms (such as “/etc/mime.types”) also being used on Windows, where they are user-writable locations (“C:\\etc\\mime.types”).\n\nTo work-around this issue a user can call mimetypes.init() with an empty list (“[]”) on Windows platforms to avoid using the default list of known file locations.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:L/AT:P/PR:L/UI:N/VC:N/VI:L/VA:L/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":2.3},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-3220","epss":0.00088,"percentile":0.26555,"date":"2025-06-02"}],"fix":{"versions":["3.14.0"],"state":"fixed"},"advisories":[],"risk":0.023320000000000004},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.11.10:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.11.10"}},"found":{"vulnerabilityID":"CVE-2024-3220","versionConstraint":"< 3.14.0 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.14.0"}}],"artifact":{"id":"8c3b47afaa19befa","name":"python","version":"3.11.10","type":"binary","locations":[{"path":"/tools/python3/python3.11","accessPath":"/tools/python3/python3.11","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.11.10:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.11.10:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.11.10","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-50602","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-50602","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/libexpat/libexpat/pull/915","https://lists.debian.org/debian-lts-announce/2025/04/msg00040.html","https://security.netapp.com/advisory/ntap-20250404-0008/"],"description":"An issue was discovered in libexpat before 2.6.4. There is a crash within the XML_ResumeParser function because XML_StopParser can stop/suspend an unstarted parser.","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-50602","epss":0.00037,"percentile":0.10035,"date":"2025-06-02"}],"fix":{"versions":["3.9.21","3.10.16","3.11.11","3.12.8","3.13.1"],"state":"fixed"},"advisories":[],"risk":0.020165000000000002},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.11.10:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.11.10"}},"found":{"vulnerabilityID":"CVE-2024-50602","versionConstraint":"< 3.9.21,>= 3.10, < 3.10.16,>= 3.11, < 3.11.11,>= 3.12, < 3.12.8,>= 3.13, < 3.13.1 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.11.11"}}],"artifact":{"id":"8c3b47afaa19befa","name":"python","version":"3.11.10","type":"binary","locations":[{"path":"/tools/python3/python3.11","accessPath":"/tools/python3/python3.11","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.11.10:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.11.10:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.11.10","upstreams":[]}},{"vulnerability":{"id":"CVE-2025-4516","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-4516","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/python/cpython/commit/69b4387f78f413e8c47572a85b3478c47eba8142","https://github.com/python/cpython/commit/9f69a58623bd01349a18ba0c7a9cb1dad6a51e8e","https://github.com/python/cpython/issues/133767","https://github.com/python/cpython/pull/129648","https://mail.python.org/archives/list/security-announce@python.org/thread/L75IPBBTSCYEF56I2M4KIW353BB3AY74/","http://www.openwall.com/lists/oss-security/2025/05/16/4","http://www.openwall.com/lists/oss-security/2025/05/19/1"],"description":"There is an issue in CPython when using `bytes.decode(\"unicode_escape\", error=\"ignore|replace\")`. If you are not using the \"unicode_escape\" encoding or an error handler your usage is not affected. To work-around this issue you may stop using the error= handler and instead wrap the bytes.decode() call in a try-except catching the DecodeError.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:L/AC:H/AT:P/PR:N/UI:N/VC:N/VI:N/VA:H/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-4516","epss":0.00018,"percentile":0.03232,"date":"2025-06-02"}],"fix":{"versions":["3.14.0b1"],"state":"fixed"},"advisories":[],"risk":0.009810000000000001},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.11.10:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.11.10"}},"found":{"vulnerabilityID":"CVE-2025-4516","versionConstraint":"< 3.14.0b1 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.14.0b1"}}],"artifact":{"id":"8c3b47afaa19befa","name":"python","version":"3.11.10","type":"binary","locations":[{"path":"/tools/python3/python3.11","accessPath":"/tools/python3/python3.11","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.11.10:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.11.10:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.11.10","upstreams":[]}}],"source":{"type":"sbom-file","target":"iowarp-syft.json"},"distro":{"name":"","version":"","idLike":null},"descriptor":{"name":"grype","version":"0.92.2","configuration":{"output":["json=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-05-21/iowarp-grype.json","template=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-05-21/iowarp-grype.html"],"file":"","pretty":false,"distro":"","add-cpes-if-none":false,"output-template-file":"../html.tmpl","check-for-app-update":true,"only-fixed":false,"only-notfixed":false,"ignore-wontfix":"","platform":"","search":{"scope":"squashed","unindexed-archives":false,"indexed-archives":true},"ignore":[{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"kernel-headers","version":"","language":"","type":"rpm","location":"","upstream-name":"kernel"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux(-.*)?-headers-.*","version":"","language":"","type":"deb","location":"","upstream-name":"linux.*"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux-libc-dev","version":"","language":"","type":"deb","location":"","upstream-name":"linux"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"}],"exclude":[],"externalSources":{"enable":false,"maven":{"searchUpstreamBySha1":true,"baseUrl":"https://search.maven.org/solrsearch/select","rateLimit":300000000}},"match":{"java":{"using-cpes":false},"jvm":{"using-cpes":true},"dotnet":{"using-cpes":false},"golang":{"using-cpes":false,"always-use-cpe-for-stdlib":true,"allow-main-module-pseudo-version-comparison":false},"javascript":{"using-cpes":false},"python":{"using-cpes":false},"ruby":{"using-cpes":false},"rust":{"using-cpes":false},"stock":{"using-cpes":true}},"fail-on-severity":"","registry":{"insecure-skip-tls-verify":false,"insecure-use-http":false,"auth":null,"ca-cert":""},"show-suppressed":false,"by-cve":false,"SortBy":{"sort-by":"risk"},"name":"","default-image-pull-source":"","vex-documents":[],"vex-add":[],"match-upstream-kernel-headers":false,"db":{"cache-dir":"/Users/alan/Library/Caches/grype/db","update-url":"https://grype.anchore.io/databases","ca-cert":"","auto-update":true,"validate-by-hash-on-start":true,"validate-age":true,"max-allowed-built-age":432000000000000,"require-update-check":false,"update-available-timeout":30000000000,"update-download-timeout":300000000000,"max-update-check-frequency":7200000000000},"exp":{},"dev":{"db":{"debug":false}}},"db":{"status":{"schemaVersion":"v6.0.2","from":"https://grype.anchore.io/databases/v6/vulnerability-db_v6.0.2_2025-06-03T01:32:03Z_1748923962.tar.zst?checksum=sha256%3A02a6127217518a93e0ef8739cb9f2d659109fff0d9cc25f0c13d5ca8b307a118","built":"2025-06-03T04:12:42Z","path":"/Users/alan/Library/Caches/grype/db/6/vulnerability.db","valid":true},"providers":{"alpine":{"captured":"2025-06-03T01:32:27Z","input":"xxh64:a6a065ece392f6d1"},"amazon":{"captured":"2025-06-03T01:32:10Z","input":"xxh64:b65d458d6858d72a"},"chainguard":{"captured":"2025-06-03T01:32:15Z","input":"xxh64:bad092583f78d4dd"},"debian":{"captured":"2025-06-03T01:32:22Z","input":"xxh64:b4717cad509f50d8"},"epss":{"captured":"2025-06-03T01:32:43Z","input":"xxh64:2f9660be834e0ce6"},"github":{"captured":"2025-06-03T01:32:21Z","input":"xxh64:cdd94f1952fcf607"},"kev":{"captured":"2025-06-03T01:32:03Z","input":"xxh64:575844c3434cc70b"},"mariner":{"captured":"2025-06-03T01:32:11Z","input":"xxh64:7628f1adb0b9b12b"},"nvd":{"captured":"2025-06-03T01:32:30Z","input":"xxh64:463c4e9a1d401101"},"oracle":{"captured":"2025-06-03T01:32:27Z","input":"xxh64:257df3059d28d823"},"rhel":{"captured":"2025-06-03T01:33:04Z","input":"xxh64:59e7d70bf674afdc"},"sles":{"captured":"2025-06-03T01:32:46Z","input":"xxh64:3cf7f372ea0c981a"},"ubuntu":{"captured":"2025-06-03T01:33:20Z","input":"xxh64:075be8afc080f2be"},"wolfi":{"captured":"2025-06-03T01:32:31Z","input":"xxh64:1aa0b26b004bdd38"}}},"timestamp":"2025-06-03T13:06:18.487716+01:00"}}
