{"matches":[{"vulnerability":{"id":"GHSA-3rq5-2g8h-59hc","dataSource":"https://github.com/advisories/GHSA-3rq5-2g8h-59hc","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Potential DoS via the Tudoor mechanism in eventlet and dnspython","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-29483","epss":0.01082,"percentile":0.76846,"date":"2025-06-02"}],"fix":{"versions":["2.6.1"],"state":"fixed"},"advisories":[],"risk":0.58969},"relatedVulnerabilities":[{"id":"CVE-2023-29483","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-29483","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/eventlet/eventlet/issues/913","https://github.com/eventlet/eventlet/releases/tag/v0.35.2","https://github.com/rthalley/dnspython/issues/1045","https://github.com/rthalley/dnspython/releases/tag/v2.6.0","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NLRKR57IFVKQC2GCXZBFLCLBAWBWL3F6/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VOHJOO3OM65UIUUUVDEXMCTXNM6LXZEH/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/X3BNSIK5NFYSAP53Y45GOCMOQHHDLGIF/","https://security.netapp.com/advisory/ntap-20240510-0001/","https://security.snyk.io/vuln/SNYK-PYTHON-DNSPYTHON-6241713","https://www.dnspython.org/","https://github.com/eventlet/eventlet/issues/913","https://github.com/eventlet/eventlet/releases/tag/v0.35.2","https://github.com/rthalley/dnspython/issues/1045","https://github.com/rthalley/dnspython/releases/tag/v2.6.0","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NLRKR57IFVKQC2GCXZBFLCLBAWBWL3F6/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VOHJOO3OM65UIUUUVDEXMCTXNM6LXZEH/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/X3BNSIK5NFYSAP53Y45GOCMOQHHDLGIF/","https://security.netapp.com/advisory/ntap-20240510-0001/","https://security.snyk.io/vuln/SNYK-PYTHON-DNSPYTHON-6241713","https://www.dnspython.org/"],"description":"eventlet before 0.35.2, as used in dnspython before 2.6.0, allows remote attackers to interfere with DNS name resolution by quickly sending an invalid packet from the expected IP address and source port, aka a \"TuDoor\" attack. In other words, dnspython does not have the preferred behavior in which the DNS name resolution algorithm would proceed, within the full time window, in order to wait for a valid packet. NOTE: dnspython 2.6.0 is unusable for a different reason that was addressed in 2.6.1.","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:H","metrics":{"baseScore":7,"exploitabilityScore":2.3,"impactScore":4.8},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-29483","epss":0.01082,"percentile":0.76846,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"dnspython","version":"2.2.1"}},"found":{"versionConstraint":"<2.6.1 (python)","vulnerabilityID":"GHSA-3rq5-2g8h-59hc"},"fix":{"suggestedVersion":"2.6.1"}}],"artifact":{"id":"f10acce53d2cac66","name":"dnspython","version":"2.2.1","type":"python","locations":[{"path":"/lib/python3.10/site-packages/dnspython-2.2.1.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/dnspython-2.2.1.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/dnspython-2.2.1.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/dnspython-2.2.1.dist-info/RECORD","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["ISC"],"cpes":["cpe:2.3:a:bob_halley_project:python-dnspython:2.2.1:*:*:*:*:*:*:*","cpe:2.3:a:bob_halley_project:python_dnspython:2.2.1:*:*:*:*:*:*:*","cpe:2.3:a:bob_halleyproject:python-dnspython:2.2.1:*:*:*:*:*:*:*","cpe:2.3:a:bob_halleyproject:python_dnspython:2.2.1:*:*:*:*:*:*:*","cpe:2.3:a:python-dnspython:python-dnspython:2.2.1:*:*:*:*:*:*:*","cpe:2.3:a:python-dnspython:python_dnspython:2.2.1:*:*:*:*:*:*:*","cpe:2.3:a:python_dnspython:python-dnspython:2.2.1:*:*:*:*:*:*:*","cpe:2.3:a:python_dnspython:python_dnspython:2.2.1:*:*:*:*:*:*:*","cpe:2.3:a:halley_project:python-dnspython:2.2.1:*:*:*:*:*:*:*","cpe:2.3:a:halley_project:python_dnspython:2.2.1:*:*:*:*:*:*:*","cpe:2.3:a:halleyproject:python-dnspython:2.2.1:*:*:*:*:*:*:*","cpe:2.3:a:halleyproject:python_dnspython:2.2.1:*:*:*:*:*:*:*","cpe:2.3:a:bob_halley_project:dnspython:2.2.1:*:*:*:*:*:*:*","cpe:2.3:a:bob_halley:python-dnspython:2.2.1:*:*:*:*:*:*:*","cpe:2.3:a:bob_halley:python_dnspython:2.2.1:*:*:*:*:*:*:*","cpe:2.3:a:bob_halleyproject:dnspython:2.2.1:*:*:*:*:*:*:*","cpe:2.3:a:dnspython:python-dnspython:2.2.1:*:*:*:*:*:*:*","cpe:2.3:a:dnspython:python_dnspython:2.2.1:*:*:*:*:*:*:*","cpe:2.3:a:python-dnspython:dnspython:2.2.1:*:*:*:*:*:*:*","cpe:2.3:a:python_dnspython:dnspython:2.2.1:*:*:*:*:*:*:*","cpe:2.3:a:halley_project:dnspython:2.2.1:*:*:*:*:*:*:*","cpe:2.3:a:halley:python-dnspython:2.2.1:*:*:*:*:*:*:*","cpe:2.3:a:halley:python_dnspython:2.2.1:*:*:*:*:*:*:*","cpe:2.3:a:halleyproject:dnspython:2.2.1:*:*:*:*:*:*:*","cpe:2.3:a:python:python-dnspython:2.2.1:*:*:*:*:*:*:*","cpe:2.3:a:python:python_dnspython:2.2.1:*:*:*:*:*:*:*","cpe:2.3:a:bob_halley:dnspython:2.2.1:*:*:*:*:*:*:*","cpe:2.3:a:dnspython:dnspython:2.2.1:*:*:*:*:*:*:*","cpe:2.3:a:halley:dnspython:2.2.1:*:*:*:*:*:*:*","cpe:2.3:a:python:dnspython:2.2.1:*:*:*:*:*:*:*"],"purl":"pkg:pypi/dnspython@2.2.1","upstreams":[]}},{"vulnerability":{"id":"GHSA-5rjg-fvgr-3xxf","dataSource":"https://github.com/advisories/GHSA-5rjg-fvgr-3xxf","namespace":"github:language:python","severity":"High","urls":[],"description":"setuptools has a path traversal vulnerability in PackageIndex.download that leads to Arbitrary File Write","cvss":[],"epss":[{"cve":"CVE-2025-47273","epss":0.00435,"percentile":0.6206,"date":"2025-06-02"}],"fix":{"versions":["78.1.1"],"state":"fixed"},"advisories":[],"risk":0.32625},"relatedVulnerabilities":[{"id":"CVE-2025-47273","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-47273","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pypa/setuptools/blob/6ead555c5fb29bc57fe6105b1bffc163f56fd558/setuptools/package_index.py#L810C1-L825C88","https://github.com/pypa/setuptools/commit/250a6d17978f9f6ac3ac887091f2d32886fbbb0b","https://github.com/pypa/setuptools/issues/4946","https://github.com/pypa/setuptools/security/advisories/GHSA-5rjg-fvgr-3xxf","https://lists.debian.org/debian-lts-announce/2025/05/msg00035.html","https://github.com/pypa/setuptools/issues/4946"],"description":"setuptools is a package that allows users to download, build, install, upgrade, and uninstall Python packages. A path traversal vulnerability in `PackageIndex` is present in setuptools prior to version 78.1.1. An attacker would be allowed to write files to arbitrary locations on the filesystem with the permissions of the process running the Python code, which could escalate to remote code execution depending on the context. Version 78.1.1 fixes the issue.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:H/VA:N/SC:N/SI:N/SA:N/E:P/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":7.7},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-47273","epss":0.00435,"percentile":0.6206,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"setuptools","version":"59.6.0"}},"found":{"versionConstraint":"<78.1.1 (python)","vulnerabilityID":"GHSA-5rjg-fvgr-3xxf"},"fix":{"suggestedVersion":"78.1.1"}}],"artifact":{"id":"82dc8f8937ca1fb8","name":"setuptools","version":"59.6.0","type":"python","locations":[{"path":"/lib/python3.10/site-packages/setuptools-59.6.0.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/setuptools-59.6.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/setuptools-59.6.0.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/setuptools-59.6.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/setuptools-59.6.0.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/setuptools-59.6.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["UNKNOWN"],"cpes":["cpe:2.3:a:python:setuptools:59.6.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/setuptools@59.6.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-r9hx-vwmv-q579","dataSource":"https://github.com/advisories/GHSA-r9hx-vwmv-q579","namespace":"github:language:python","severity":"High","urls":[],"description":"pypa/setuptools vulnerable to Regular Expression Denial of Service (ReDoS)","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-40897","epss":0.00318,"percentile":0.54322,"date":"2025-06-02"}],"fix":{"versions":["65.5.1"],"state":"fixed"},"advisories":[],"risk":0.2385},"relatedVulnerabilities":[{"id":"CVE-2022-40897","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2022-40897","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pypa/setuptools/blob/fe8a98e696241487ba6ac9f91faa38ade939ec5d/setuptools/package_index.py#L200","https://github.com/pypa/setuptools/commit/43a9c9bfa6aa626ec2a22540bea28d2ca77964be","https://github.com/pypa/setuptools/compare/v65.5.0...v65.5.1","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H/","https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/","https://pyup.io/vulnerabilities/CVE-2022-40897/52495/","https://security.netapp.com/advisory/ntap-20230214-0001/","https://security.netapp.com/advisory/ntap-20240621-0006/","https://github.com/pypa/setuptools/blob/fe8a98e696241487ba6ac9f91faa38ade939ec5d/setuptools/package_index.py#L200","https://github.com/pypa/setuptools/commit/43a9c9bfa6aa626ec2a22540bea28d2ca77964be","https://github.com/pypa/setuptools/compare/v65.5.0...v65.5.1","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H/","https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/","https://pyup.io/vulnerabilities/CVE-2022-40897/52495/","https://security.netapp.com/advisory/ntap-20230214-0001/","https://security.netapp.com/advisory/ntap-20240621-0006/"],"description":"Python Packaging Authority (PyPA) setuptools before 65.5.1 allows remote attackers to cause a denial of service via HTML in a crafted package or custom PackageIndex page. There is a Regular Expression Denial of Service (ReDoS) in package_index.py.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-40897","epss":0.00318,"percentile":0.54322,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"setuptools","version":"59.6.0"}},"found":{"versionConstraint":"<65.5.1 (python)","vulnerabilityID":"GHSA-r9hx-vwmv-q579"},"fix":{"suggestedVersion":"65.5.1"}}],"artifact":{"id":"82dc8f8937ca1fb8","name":"setuptools","version":"59.6.0","type":"python","locations":[{"path":"/lib/python3.10/site-packages/setuptools-59.6.0.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/setuptools-59.6.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/setuptools-59.6.0.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/setuptools-59.6.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/setuptools-59.6.0.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/setuptools-59.6.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["UNKNOWN"],"cpes":["cpe:2.3:a:python:setuptools:59.6.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/setuptools@59.6.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-cx63-2mw6-8hw5","dataSource":"https://github.com/advisories/GHSA-cx63-2mw6-8hw5","namespace":"github:language:python","severity":"High","urls":[],"description":"setuptools vulnerable to Command Injection via package URL","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.8,"exploitabilityScore":2.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-6345","epss":0.00227,"percentile":0.45716,"date":"2025-06-02"}],"fix":{"versions":["70.0.0"],"state":"fixed"},"advisories":[],"risk":0.185005},"relatedVulnerabilities":[{"id":"CVE-2024-6345","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-6345","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pypa/setuptools/commit/88807c7062788254f654ea8c03427adc859321f0","https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5","https://github.com/pypa/setuptools/commit/88807c7062788254f654ea8c03427adc859321f0","https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5"],"description":"A vulnerability in the package_index module of pypa/setuptools versions up to 69.1.1 allows for remote code execution via its download functions. These functions, which are used to download packages from URLs provided by users or retrieved from package index servers, are susceptible to code injection. If these functions are exposed to user-controlled inputs, such as package URLs, they can execute arbitrary commands on the system. The issue is fixed in version 70.0.","cvss":[{"source":"security@huntr.dev","type":"Secondary","version":"3.0","vector":"CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.8,"exploitabilityScore":2.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-6345","epss":0.00227,"percentile":0.45716,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"setuptools","version":"59.6.0"}},"found":{"versionConstraint":"<70.0.0 (python)","vulnerabilityID":"GHSA-cx63-2mw6-8hw5"},"fix":{"suggestedVersion":"70.0.0"}}],"artifact":{"id":"82dc8f8937ca1fb8","name":"setuptools","version":"59.6.0","type":"python","locations":[{"path":"/lib/python3.10/site-packages/setuptools-59.6.0.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/setuptools-59.6.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/setuptools-59.6.0.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/setuptools-59.6.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/setuptools-59.6.0.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/setuptools-59.6.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["UNKNOWN"],"cpes":["cpe:2.3:a:python:setuptools:59.6.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/setuptools@59.6.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-mr82-8j83-vxmv","dataSource":"https://github.com/advisories/GHSA-mr82-8j83-vxmv","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Pydantic regular expression denial of service","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-3772","epss":0.0028,"percentile":0.51268,"date":"2025-06-02"}],"fix":{"versions":["1.10.13"],"state":"fixed"},"advisories":[],"risk":0.1526},"relatedVulnerabilities":[{"id":"CVE-2024-3772","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-3772","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pydantic/pydantic/pull/7360","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6JBZLMSH4GAZOVBMT2JUO2LXHY7M2ALI/","https://github.com/pydantic/pydantic/pull/7360","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6JBZLMSH4GAZOVBMT2JUO2LXHY7M2ALI/"],"description":"Regular expression denial of service in Pydanic < 2.4.0, < 1.10.13 allows remote attackers to cause denial of service via a crafted email string.","cvss":[{"source":"430a6cef-dc26-47e3-9fa8-52fb7f19644e","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-3772","epss":0.0028,"percentile":0.51268,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"pydantic","version":"1.10.2"}},"found":{"versionConstraint":"<1.10.13 (python)","vulnerabilityID":"GHSA-mr82-8j83-vxmv"},"fix":{"suggestedVersion":"1.10.13"}}],"artifact":{"id":"add53c94bdb1f5fc","name":"pydantic","version":"1.10.2","type":"python","locations":[{"path":"/lib/python3.10/site-packages/pydantic-1.10.2.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/pydantic-1.10.2.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/pydantic-1.10.2.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/pydantic-1.10.2.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/pydantic-1.10.2.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/pydantic-1.10.2.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:samuel_colvin_project:python-pydantic:1.10.2:*:*:*:*:*:*:*","cpe:2.3:a:samuel_colvin_project:python_pydantic:1.10.2:*:*:*:*:*:*:*","cpe:2.3:a:samuel_colvinproject:python-pydantic:1.10.2:*:*:*:*:*:*:*","cpe:2.3:a:samuel_colvinproject:python_pydantic:1.10.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pydantic:python-pydantic:1.10.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pydantic:python_pydantic:1.10.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pydantic:python-pydantic:1.10.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pydantic:python_pydantic:1.10.2:*:*:*:*:*:*:*","cpe:2.3:a:samuel_colvin_project:pydantic:1.10.2:*:*:*:*:*:*:*","cpe:2.3:a:samuel_colvin:python-pydantic:1.10.2:*:*:*:*:*:*:*","cpe:2.3:a:samuel_colvin:python_pydantic:1.10.2:*:*:*:*:*:*:*","cpe:2.3:a:samuel_colvinproject:pydantic:1.10.2:*:*:*:*:*:*:*","cpe:2.3:a:s_project:python-pydantic:1.10.2:*:*:*:*:*:*:*","cpe:2.3:a:s_project:python_pydantic:1.10.2:*:*:*:*:*:*:*","cpe:2.3:a:pydantic:python-pydantic:1.10.2:*:*:*:*:*:*:*","cpe:2.3:a:pydantic:python_pydantic:1.10.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pydantic:pydantic:1.10.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pydantic:pydantic:1.10.2:*:*:*:*:*:*:*","cpe:2.3:a:sproject:python-pydantic:1.10.2:*:*:*:*:*:*:*","cpe:2.3:a:sproject:python_pydantic:1.10.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python-pydantic:1.10.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python_pydantic:1.10.2:*:*:*:*:*:*:*","cpe:2.3:a:samuel_colvin:pydantic:1.10.2:*:*:*:*:*:*:*","cpe:2.3:a:s_project:pydantic:1.10.2:*:*:*:*:*:*:*","cpe:2.3:a:pydantic:pydantic:1.10.2:*:*:*:*:*:*:*","cpe:2.3:a:s:python-pydantic:1.10.2:*:*:*:*:*:*:*","cpe:2.3:a:s:python_pydantic:1.10.2:*:*:*:*:*:*:*","cpe:2.3:a:sproject:pydantic:1.10.2:*:*:*:*:*:*:*","cpe:2.3:a:python:pydantic:1.10.2:*:*:*:*:*:*:*","cpe:2.3:a:s:pydantic:1.10.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/pydantic@1.10.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-m87m-mmvp-v9qm","dataSource":"https://github.com/advisories/GHSA-m87m-mmvp-v9qm","namespace":"github:language:python","severity":"Medium","urls":[],"description":"PyMongo Out-of-bounds Read in the bson module","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:L/I:N/A:L","metrics":{"baseScore":4.7,"exploitabilityScore":1.7,"impactScore":2.8},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-5629","epss":0.00238,"percentile":0.47071,"date":"2025-06-02"}],"fix":{"versions":["4.6.3"],"state":"fixed"},"advisories":[],"risk":0.11543},"relatedVulnerabilities":[{"id":"CVE-2024-5629","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-5629","namespace":"nvd:cpe","severity":"High","urls":["https://jira.mongodb.org/browse/PYTHON-4305","https://lists.debian.org/debian-lts-announce/2024/06/msg00007.html","https://jira.mongodb.org/browse/PYTHON-4305","https://lists.debian.org/debian-lts-announce/2024/06/msg00007.html","https://lists.debian.org/debian-lts-announce/2024/09/msg00032.html"],"description":"An out-of-bounds read in the 'bson' module of PyMongo 4.6.2 or earlier allows deserialization of malformed BSON provided by a Server to raise an exception which may contain arbitrary application memory.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:N/A:H","metrics":{"baseScore":8.1,"exploitabilityScore":2.9,"impactScore":5.2},"vendorMetadata":{}},{"source":"cna@mongodb.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:L/I:N/A:L","metrics":{"baseScore":4.7,"exploitabilityScore":1.7,"impactScore":2.8},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-5629","epss":0.00238,"percentile":0.47071,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"pymongo","version":"4.3.2"}},"found":{"versionConstraint":"<4.6.3 (python)","vulnerabilityID":"GHSA-m87m-mmvp-v9qm"},"fix":{"suggestedVersion":"4.6.3"}}],"artifact":{"id":"f0c95f3055bb945c","name":"pymongo","version":"4.3.2","type":"python","locations":[{"path":"/lib/python3.10/site-packages/pymongo-4.3.2.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/pymongo-4.3.2.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/pymongo-4.3.2.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/pymongo-4.3.2.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/pymongo-4.3.2.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/pymongo-4.3.2.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache License, Version 2.0"],"cpes":["cpe:2.3:a:mongodb_python_team_project:python-pymongo:4.3.2:*:*:*:*:*:*:*","cpe:2.3:a:mongodb_python_team_project:python_pymongo:4.3.2:*:*:*:*:*:*:*","cpe:2.3:a:mongodb_python_teamproject:python-pymongo:4.3.2:*:*:*:*:*:*:*","cpe:2.3:a:mongodb_python_teamproject:python_pymongo:4.3.2:*:*:*:*:*:*:*","cpe:2.3:a:mongodb_python_team_project:pymongo:4.3.2:*:*:*:*:*:*:*","cpe:2.3:a:mongodb_python_team:python-pymongo:4.3.2:*:*:*:*:*:*:*","cpe:2.3:a:mongodb_python_team:python_pymongo:4.3.2:*:*:*:*:*:*:*","cpe:2.3:a:mongodb_python_teamproject:pymongo:4.3.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pymongo:python-pymongo:4.3.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pymongo:python_pymongo:4.3.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pymongo:python-pymongo:4.3.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pymongo:python_pymongo:4.3.2:*:*:*:*:*:*:*","cpe:2.3:a:mongodb_python_team:pymongo:4.3.2:*:*:*:*:*:*:*","cpe:2.3:a:pymongo:python-pymongo:4.3.2:*:*:*:*:*:*:*","cpe:2.3:a:pymongo:python_pymongo:4.3.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pymongo:pymongo:4.3.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pymongo:pymongo:4.3.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python-pymongo:4.3.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python_pymongo:4.3.2:*:*:*:*:*:*:*","cpe:2.3:a:pymongo:pymongo:4.3.2:*:*:*:*:*:*:*","cpe:2.3:a:python:pymongo:4.3.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/pymongo@4.3.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-mq26-g339-26xf","dataSource":"https://github.com/advisories/GHSA-mq26-g339-26xf","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Command Injection in pip when used with Mercurial","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-5752","epss":0.0004,"percentile":0.11732,"date":"2025-06-02"}],"fix":{"versions":["23.3"],"state":"fixed"},"advisories":[],"risk":0.021},"relatedVulnerabilities":[{"id":"CVE-2023-5752","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-5752","namespace":"nvd:cpe","severity":"Low","urls":["https://github.com/pypa/pip/pull/12306","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/622OZXWG72ISQPLM5Y57YCVIMWHD4C3U/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/65UKKF5LBHEFDCUSPBHUN4IHYX7SRMHH/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FXUVMJM25PUAZRQZBF54OFVKTY3MINPW/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KFC2SPFG5FLCZBYY2K3T5MFW2D22NG6E/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YBSB3SUPQ3VIFYUMHPO3MEQI4BJAXKCZ/","https://mail.python.org/archives/list/security-announce@python.org/thread/F4PL35U6X4VVHZ5ILJU3PWUWN7H7LZXL/","https://github.com/pypa/pip/pull/12306","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/622OZXWG72ISQPLM5Y57YCVIMWHD4C3U/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/65UKKF5LBHEFDCUSPBHUN4IHYX7SRMHH/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FXUVMJM25PUAZRQZBF54OFVKTY3MINPW/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KFC2SPFG5FLCZBYY2K3T5MFW2D22NG6E/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YBSB3SUPQ3VIFYUMHPO3MEQI4BJAXKCZ/","https://mail.python.org/archives/list/security-announce@python.org/thread/F4PL35U6X4VVHZ5ILJU3PWUWN7H7LZXL/"],"description":"When installing a package from a Mercurial VCS URL  (ie \"pip install \nhg+...\") with pip prior to v23.3, the specified Mercurial revision could\n be used to inject arbitrary configuration options to the \"hg clone\" \ncall (ie \"--config\"). Controlling the Mercurial configuration can modify\n how and which repository is installed. This vulnerability does not \naffect users who aren't installing from Mercurial.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:N","metrics":{"baseScore":3.3,"exploitabilityScore":1.9,"impactScore":1.5},"vendorMetadata":{}},{"source":"cna@python.org","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-5752","epss":0.0004,"percentile":0.11732,"date":"2025-06-02"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"pip","version":"22.0.2"}},"found":{"versionConstraint":"<23.3 (python)","vulnerabilityID":"GHSA-mq26-g339-26xf"},"fix":{"suggestedVersion":"23.3"}}],"artifact":{"id":"12c1005ddfcdff00","name":"pip","version":"22.0.2","type":"python","locations":[{"path":"/lib/python3.10/site-packages/pip-22.0.2.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/pip-22.0.2.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/pip-22.0.2.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/pip-22.0.2.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/pip-22.0.2.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/pip-22.0.2.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:pip_developers_project:python-pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers_project:python_pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sig_project:python-pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sig_project:python_pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:python-pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:python_pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sigproject:python-pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sigproject:python_pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers_project:pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sig_project:pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:python-pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:python_pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils-sig:python-pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils-sig:python_pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sig:python-pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sig:python_pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sigproject:pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:python-pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:python_pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:python-pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:python_pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils-sig:pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:distutils_sig:pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python-pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python_pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa:python-pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa:python_pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip:python-pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip:python_pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python:pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa:pip:22.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip:pip:22.0.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/pip@22.0.2","upstreams":[]}}],"source":{"type":"sbom-file","target":"tasker-syft.json"},"distro":{"name":"","version":"","idLike":null},"descriptor":{"name":"grype","version":"0.92.2","configuration":{"output":["json=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-05-21/tasker-grype.json","template=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-05-21/tasker-grype.html"],"file":"","pretty":false,"distro":"","add-cpes-if-none":false,"output-template-file":"../html.tmpl","check-for-app-update":true,"only-fixed":false,"only-notfixed":false,"ignore-wontfix":"","platform":"","search":{"scope":"squashed","unindexed-archives":false,"indexed-archives":true},"ignore":[{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"kernel-headers","version":"","language":"","type":"rpm","location":"","upstream-name":"kernel"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux(-.*)?-headers-.*","version":"","language":"","type":"deb","location":"","upstream-name":"linux.*"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux-libc-dev","version":"","language":"","type":"deb","location":"","upstream-name":"linux"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"}],"exclude":[],"externalSources":{"enable":false,"maven":{"searchUpstreamBySha1":true,"baseUrl":"https://search.maven.org/solrsearch/select","rateLimit":300000000}},"match":{"java":{"using-cpes":false},"jvm":{"using-cpes":true},"dotnet":{"using-cpes":false},"golang":{"using-cpes":false,"always-use-cpe-for-stdlib":true,"allow-main-module-pseudo-version-comparison":false},"javascript":{"using-cpes":false},"python":{"using-cpes":false},"ruby":{"using-cpes":false},"rust":{"using-cpes":false},"stock":{"using-cpes":true}},"fail-on-severity":"","registry":{"insecure-skip-tls-verify":false,"insecure-use-http":false,"auth":null,"ca-cert":""},"show-suppressed":false,"by-cve":false,"SortBy":{"sort-by":"risk"},"name":"","default-image-pull-source":"","vex-documents":[],"vex-add":[],"match-upstream-kernel-headers":false,"db":{"cache-dir":"/Users/alan/Library/Caches/grype/db","update-url":"https://grype.anchore.io/databases","ca-cert":"","auto-update":true,"validate-by-hash-on-start":true,"validate-age":true,"max-allowed-built-age":432000000000000,"require-update-check":false,"update-available-timeout":30000000000,"update-download-timeout":300000000000,"max-update-check-frequency":7200000000000},"exp":{},"dev":{"db":{"debug":false}}},"db":{"status":{"schemaVersion":"v6.0.2","from":"https://grype.anchore.io/databases/v6/vulnerability-db_v6.0.2_2025-06-03T01:32:03Z_1748923962.tar.zst?checksum=sha256%3A02a6127217518a93e0ef8739cb9f2d659109fff0d9cc25f0c13d5ca8b307a118","built":"2025-06-03T04:12:42Z","path":"/Users/alan/Library/Caches/grype/db/6/vulnerability.db","valid":true},"providers":{"alpine":{"captured":"2025-06-03T01:32:27Z","input":"xxh64:a6a065ece392f6d1"},"amazon":{"captured":"2025-06-03T01:32:10Z","input":"xxh64:b65d458d6858d72a"},"chainguard":{"captured":"2025-06-03T01:32:15Z","input":"xxh64:bad092583f78d4dd"},"debian":{"captured":"2025-06-03T01:32:22Z","input":"xxh64:b4717cad509f50d8"},"epss":{"captured":"2025-06-03T01:32:43Z","input":"xxh64:2f9660be834e0ce6"},"github":{"captured":"2025-06-03T01:32:21Z","input":"xxh64:cdd94f1952fcf607"},"kev":{"captured":"2025-06-03T01:32:03Z","input":"xxh64:575844c3434cc70b"},"mariner":{"captured":"2025-06-03T01:32:11Z","input":"xxh64:7628f1adb0b9b12b"},"nvd":{"captured":"2025-06-03T01:32:30Z","input":"xxh64:463c4e9a1d401101"},"oracle":{"captured":"2025-06-03T01:32:27Z","input":"xxh64:257df3059d28d823"},"rhel":{"captured":"2025-06-03T01:33:04Z","input":"xxh64:59e7d70bf674afdc"},"sles":{"captured":"2025-06-03T01:32:46Z","input":"xxh64:3cf7f372ea0c981a"},"ubuntu":{"captured":"2025-06-03T01:33:20Z","input":"xxh64:075be8afc080f2be"},"wolfi":{"captured":"2025-06-03T01:32:31Z","input":"xxh64:1aa0b26b004bdd38"}}},"timestamp":"2025-06-03T13:13:28.026372+01:00"}}
