{"matches":[{"vulnerability":{"id":"GHSA-x4qr-2fvf-3mr5","dataSource":"https://github.com/advisories/GHSA-x4qr-2fvf-3mr5","namespace":"github:language:python","severity":"High","urls":[],"description":"Vulnerable OpenSSL included in cryptography wheels","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:H","metrics":{"baseScore":7.4,"exploitabilityScore":2.3,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-0286","epss":0.8576,"percentile":0.99335,"date":"2025-06-03"}],"fix":{"versions":["39.0.1"],"state":"fixed"},"advisories":[],"risk":63.891200000000005},"relatedVulnerabilities":[{"id":"CVE-2023-0286","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-0286","namespace":"nvd:cpe","severity":"High","urls":["https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.6.2-relnotes.txt","https://ftp.openbsd.org/pub/OpenBSD/patches/7.2/common/018_x509.patch.sig","https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=2c6c9d439b484e1ba9830d8454a34fa4f80fdfe9","https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=2f7530077e0ef79d98718138716bc51ca0cad658","https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=fd2af07dc083a350c959147097003a14a5e8ac4d","https://security.gentoo.org/glsa/202402-08","https://www.openssl.org/news/secadv/20230207.txt","https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.6.2-relnotes.txt","https://ftp.openbsd.org/pub/OpenBSD/patches/7.2/common/018_x509.patch.sig","https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=2c6c9d439b484e1ba9830d8454a34fa4f80fdfe9","https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=2f7530077e0ef79d98718138716bc51ca0cad658","https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=fd2af07dc083a350c959147097003a14a5e8ac4d","https://security.gentoo.org/glsa/202402-08","https://www.openssl.org/news/secadv/20230207.txt"],"description":"There is a type confusion vulnerability relating to X.400 address processing\ninside an X.509 GeneralName. X.400 addresses were parsed as an ASN1_STRING but\nthe public structure definition for GENERAL_NAME incorrectly specified the type\nof the x400Address field as ASN1_TYPE. This field is subsequently interpreted by\nthe OpenSSL function GENERAL_NAME_cmp as an ASN1_TYPE rather than an\nASN1_STRING.\n\nWhen CRL checking is enabled (i.e. the application sets the\nX509_V_FLAG_CRL_CHECK flag), this vulnerability may allow an attacker to pass\narbitrary pointers to a memcmp call, enabling them to read memory contents or\nenact a denial of service. In most cases, the attack requires the attacker to\nprovide both the certificate chain and CRL, neither of which need to have a\nvalid signature. If the attacker only controls one of these inputs, the other\ninput must already contain an X.400 address as a CRL distribution point, which\nis uncommon. As such, this vulnerability is most likely to only affect\napplications which have implemented their own functionality for retrieving CRLs\nover a network.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:H","metrics":{"baseScore":7.4,"exploitabilityScore":2.3,"impactScore":5.2},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:H","metrics":{"baseScore":7.4,"exploitabilityScore":2.3,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-0286","epss":0.8576,"percentile":0.99335,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"3.2.1"}},"found":{"versionConstraint":">=0.8.1,<39.0.1 (python)","vulnerabilityID":"GHSA-x4qr-2fvf-3mr5"},"fix":{"suggestedVersion":"39.0.1"}}],"artifact":{"id":"45a2789cece8d69f","name":"cryptography","version":"3.2.1","type":"python","locations":[{"path":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD or Apache License, Version 2.0"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:3.2.1:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:3.2.1:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@3.2.1","upstreams":[]}},{"vulnerability":{"id":"GHSA-45x7-px36-x8w8","dataSource":"https://github.com/advisories/GHSA-45x7-px36-x8w8","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Prefix Truncation Attack against ChaCha20-Poly1305 and Encrypt-then-MAC aka Terrapin","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-48795","epss":0.67021,"percentile":0.98446,"date":"2025-06-03"}],"fix":{"versions":["3.4.0"],"state":"fixed"},"advisories":[],"risk":36.526445},"relatedVulnerabilities":[{"id":"CVE-2023-48795","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-48795","namespace":"nvd:cpe","severity":"Medium","urls":["http://packetstormsecurity.com/files/176280/Terrapin-SSH-Connection-Weakening.html","http://seclists.org/fulldisclosure/2024/Mar/21","http://www.openwall.com/lists/oss-security/2023/12/18/3","http://www.openwall.com/lists/oss-security/2023/12/19/5","http://www.openwall.com/lists/oss-security/2023/12/20/3","http://www.openwall.com/lists/oss-security/2024/03/06/3","http://www.openwall.com/lists/oss-security/2024/04/17/8","https://access.redhat.com/security/cve/cve-2023-48795","https://arstechnica.com/security/2023/12/hackers-can-break-ssh-channel-integrity-using-novel-data-corruption-attack/","https://bugs.gentoo.org/920280","https://bugzilla.redhat.com/show_bug.cgi?id=2254210","https://bugzilla.suse.com/show_bug.cgi?id=1217950","https://crates.io/crates/thrussh/versions","https://filezilla-project.org/versions.php","https://forum.netgate.com/topic/184941/terrapin-ssh-attack","https://git.libssh.org/projects/libssh.git/commit/?h=stable-0.10&id=10e09e273f69e149389b3e0e5d44b8c221c2e7f6","https://github.com/NixOS/nixpkgs/pull/275249","https://github.com/PowerShell/Win32-OpenSSH/issues/2189","https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v9.5.0.0p1-Beta","https://github.com/TeraTermProject/teraterm/commit/7279fbd6ef4d0c8bdd6a90af4ada2899d786eec0","https://github.com/TeraTermProject/teraterm/releases/tag/v5.1","https://github.com/advisories/GHSA-45x7-px36-x8w8","https://github.com/apache/mina-sshd/issues/445","https://github.com/connectbot/sshlib/commit/5c8b534f6e97db7ac0e0e579331213aa25c173ab","https://github.com/connectbot/sshlib/compare/2.2.21...2.2.22","https://github.com/cyd01/KiTTY/issues/520","https://github.com/drakkan/sftpgo/releases/tag/v2.5.6","https://github.com/erlang/otp/blob/d1b43dc0f1361d2ad67601169e90a7fc50bb0369/lib/ssh/doc/src/notes.xml#L39-L42","https://github.com/erlang/otp/releases/tag/OTP-26.2.1","https://github.com/golang/crypto/commit/9d2ee975ef9fe627bf0a6f01c1f69e8ef1d4f05d","https://github.com/hierynomus/sshj/issues/916","https://github.com/janmojzis/tinyssh/issues/81","https://github.com/jtesta/ssh-audit/commit/8e972c5e94b460379fe0c7d20209c16df81538a5","https://github.com/libssh2/libssh2/pull/1291","https://github.com/mkj/dropbear/blob/17657c36cce6df7716d5ff151ec09a665382d5dd/CHANGES#L25","https://github.com/mscdex/ssh2/commit/97b223f8891b96d6fc054df5ab1d5a1a545da2a3","https://github.com/mwiede/jsch/compare/jsch-0.2.14...jsch-0.2.15","https://github.com/mwiede/jsch/issues/457","https://github.com/mwiede/jsch/pull/461","https://github.com/net-ssh/net-ssh/blob/2e65064a52d73396bfc3806c9196fc8108f33cd8/CHANGES.txt#L14-L16","https://github.com/openssh/openssh-portable/commits/master","https://github.com/paramiko/paramiko/issues/2337","https://github.com/proftpd/proftpd/blob/0a7ea9b0ba9fcdf368374a226370d08f10397d99/RELEASE_NOTES","https://github.com/proftpd/proftpd/blob/d21e7a2e47e9b38f709bec58e3fa711f759ad0e1/RELEASE_NOTES","https://github.com/proftpd/proftpd/blob/master/RELEASE_NOTES","https://github.com/proftpd/proftpd/issues/456","https://github.com/rapier1/hpn-ssh/releases","https://github.com/ronf/asyncssh/blob/develop/docs/changes.rst","https://github.com/ronf/asyncssh/tags","https://github.com/ssh-mitm/ssh-mitm/issues/165","https://github.com/warp-tech/russh/releases/tag/v0.40.2","https://gitlab.com/libssh/libssh-mirror/-/tags","https://groups.google.com/g/golang-announce/c/-n5WqVC18LQ","https://groups.google.com/g/golang-announce/c/qA3XtxvMUyg","https://help.panic.com/releasenotes/transmit5/","https://jadaptive.com/important-java-ssh-security-update-new-ssh-vulnerability-discovered-cve-2023-48795/","https://lists.debian.org/debian-lts-announce/2023/12/msg00017.html","https://lists.debian.org/debian-lts-announce/2024/01/msg00013.html","https://lists.debian.org/debian-lts-announce/2024/01/msg00014.html","https://lists.debian.org/debian-lts-announce/2024/04/msg00016.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/33XHJUB6ROFUOH2OQNENFROTVH6MHSHA/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/3CAYYW35MUTNO65RVAELICTNZZFMT2XS/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/3JIMLVBDWOP4FUPXPTB4PGHHIOMGFLQE/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/3YQLUQWLIHDB5QCXQEX7HXHAWMOKPP5O/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/6Y74KVCPEPT4MVU3LHDWCNNOXOE5ZLUR/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/APYIXIQOVDCRWLHTGB4VYMAUIAQLKYJ3/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/BL5KTLOSLH2KHRN4HCXJPK3JUVLDGEL6/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/C3AFMZ6MH2UHHOPIWT5YLSFV3D2VB3AC/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/CHHITS4PUOZAKFIUBQAQZC7JWXMOYE4B/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/F7EYCFQCTSGJXWO3ZZ44MGKFC5HA7G3Y/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HYEDEXIKFKTUJIN43RG4B7T5ZS6MHUSP/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/I724O3LSRCPO4WNVIXTZCT4VVRMXMMSG/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/KEOTKBUPZXHE3F352JBYNTSNRXYLWD6P/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/KMZCVGUGJZZVDPCVDA7TEB22VUCNEXDD/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/L5Y6MNNVAPIJSXJERQ6PKZVCIUXSNJK7/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/LZQVUHWVWRH73YBXUQJOD6CKHDQBU3DM/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/MKQRBF3DWMWPH36LBCOBUTSIZRTPEZXB/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/QI3EHAHABFQK7OABNCSF5GMYP6TONTI7/","https://matt.ucc.asn.au/dropbear/CHANGES","https://nest.pijul.com/pijul/thrussh/changes/D6H7OWTTMHHX6BTB3B6MNBOBX2L66CBL4LGSEUSAI2MCRCJDQFRQC","https://news.ycombinator.com/item?id=38684904","https://news.ycombinator.com/item?id=38685286","https://news.ycombinator.com/item?id=38732005","https://nova.app/releases/#v11.8","https://oryx-embedded.com/download/#changelog","https://psirt.global.sonicwall.com/vuln-detail/SNWLID-2024-0002","https://roumenpetrov.info/secsh/#news20231220","https://security-tracker.debian.org/tracker/CVE-2023-48795","https://security-tracker.debian.org/tracker/source-package/libssh2","https://security-tracker.debian.org/tracker/source-package/proftpd-dfsg","https://security-tracker.debian.org/tracker/source-package/trilead-ssh2","https://security.gentoo.org/glsa/202312-16","https://security.gentoo.org/glsa/202312-17","https://security.netapp.com/advisory/ntap-20240105-0004/","https://support.apple.com/kb/HT214084","https://thorntech.com/cve-2023-48795-and-sftp-gateway/","https://twitter.com/TrueSkrillor/status/1736774389725565005","https://ubuntu.com/security/CVE-2023-48795","https://winscp.net/eng/docs/history#6.2.2","https://www.bitvise.com/ssh-client-version-history#933","https://www.bitvise.com/ssh-server-version-history","https://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html","https://www.crushftp.com/crush10wiki/Wiki.jsp?page=Update","https://www.debian.org/security/2023/dsa-5586","https://www.debian.org/security/2023/dsa-5588","https://www.freebsd.org/security/advisories/FreeBSD-SA-23:19.openssh.asc","https://www.lancom-systems.de/service-support/allgemeine-sicherheitshinweise#c243508","https://www.netsarang.com/en/xshell-update-history/","https://www.openssh.com/openbsd.html","https://www.openssh.com/txt/release-9.6","https://www.openwall.com/lists/oss-security/2023/12/18/2","https://www.openwall.com/lists/oss-security/2023/12/20/3","https://www.paramiko.org/changelog.html","https://www.reddit.com/r/sysadmin/comments/18idv52/cve202348795_why_is_this_cve_still_undisclosed/","https://www.suse.com/c/suse-addresses-the-ssh-v2-protocol-terrapin-attack-aka-cve-2023-48795/","https://www.terrapin-attack.com","https://www.theregister.com/2023/12/20/terrapin_attack_ssh","https://www.vandyke.com/products/securecrt/history.txt","http://packetstormsecurity.com/files/176280/Terrapin-SSH-Connection-Weakening.html","http://seclists.org/fulldisclosure/2024/Mar/21","http://www.openwall.com/lists/oss-security/2023/12/18/3","http://www.openwall.com/lists/oss-security/2023/12/19/5","http://www.openwall.com/lists/oss-security/2023/12/20/3","http://www.openwall.com/lists/oss-security/2024/03/06/3","http://www.openwall.com/lists/oss-security/2024/04/17/8","https://access.redhat.com/security/cve/cve-2023-48795","https://arstechnica.com/security/2023/12/hackers-can-break-ssh-channel-integrity-using-novel-data-corruption-attack/","https://bugs.gentoo.org/920280","https://bugzilla.redhat.com/show_bug.cgi?id=2254210","https://bugzilla.suse.com/show_bug.cgi?id=1217950","https://crates.io/crates/thrussh/versions","https://filezilla-project.org/versions.php","https://forum.netgate.com/topic/184941/terrapin-ssh-attack","https://git.libssh.org/projects/libssh.git/commit/?h=stable-0.10&id=10e09e273f69e149389b3e0e5d44b8c221c2e7f6","https://github.com/NixOS/nixpkgs/pull/275249","https://github.com/PowerShell/Win32-OpenSSH/issues/2189","https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v9.5.0.0p1-Beta","https://github.com/TeraTermProject/teraterm/commit/7279fbd6ef4d0c8bdd6a90af4ada2899d786eec0","https://github.com/TeraTermProject/teraterm/releases/tag/v5.1","https://github.com/advisories/GHSA-45x7-px36-x8w8","https://github.com/apache/mina-sshd/issues/445","https://github.com/connectbot/sshlib/commit/5c8b534f6e97db7ac0e0e579331213aa25c173ab","https://github.com/connectbot/sshlib/compare/2.2.21...2.2.22","https://github.com/cyd01/KiTTY/issues/520","https://github.com/drakkan/sftpgo/releases/tag/v2.5.6","https://github.com/erlang/otp/blob/d1b43dc0f1361d2ad67601169e90a7fc50bb0369/lib/ssh/doc/src/notes.xml#L39-L42","https://github.com/erlang/otp/releases/tag/OTP-26.2.1","https://github.com/golang/crypto/commit/9d2ee975ef9fe627bf0a6f01c1f69e8ef1d4f05d","https://github.com/hierynomus/sshj/issues/916","https://github.com/janmojzis/tinyssh/issues/81","https://github.com/jtesta/ssh-audit/commit/8e972c5e94b460379fe0c7d20209c16df81538a5","https://github.com/libssh2/libssh2/pull/1291","https://github.com/mkj/dropbear/blob/17657c36cce6df7716d5ff151ec09a665382d5dd/CHANGES#L25","https://github.com/mscdex/ssh2/commit/97b223f8891b96d6fc054df5ab1d5a1a545da2a3","https://github.com/mwiede/jsch/compare/jsch-0.2.14...jsch-0.2.15","https://github.com/mwiede/jsch/issues/457","https://github.com/mwiede/jsch/pull/461","https://github.com/net-ssh/net-ssh/blob/2e65064a52d73396bfc3806c9196fc8108f33cd8/CHANGES.txt#L14-L16","https://github.com/openssh/openssh-portable/commits/master","https://github.com/paramiko/paramiko/issues/2337","https://github.com/proftpd/proftpd/blob/0a7ea9b0ba9fcdf368374a226370d08f10397d99/RELEASE_NOTES","https://github.com/proftpd/proftpd/blob/d21e7a2e47e9b38f709bec58e3fa711f759ad0e1/RELEASE_NOTES","https://github.com/proftpd/proftpd/blob/master/RELEASE_NOTES","https://github.com/proftpd/proftpd/issues/456","https://github.com/rapier1/hpn-ssh/releases","https://github.com/ronf/asyncssh/blob/develop/docs/changes.rst","https://github.com/ronf/asyncssh/tags","https://github.com/ssh-mitm/ssh-mitm/issues/165","https://github.com/warp-tech/russh/releases/tag/v0.40.2","https://gitlab.com/libssh/libssh-mirror/-/tags","https://groups.google.com/g/golang-announce/c/-n5WqVC18LQ","https://groups.google.com/g/golang-announce/c/qA3XtxvMUyg","https://help.panic.com/releasenotes/transmit5/","https://jadaptive.com/important-java-ssh-security-update-new-ssh-vulnerability-discovered-cve-2023-48795/","https://lists.debian.org/debian-lts-announce/2023/12/msg00017.html","https://lists.debian.org/debian-lts-announce/2024/01/msg00013.html","https://lists.debian.org/debian-lts-announce/2024/01/msg00014.html","https://lists.debian.org/debian-lts-announce/2024/04/msg00016.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/33XHJUB6ROFUOH2OQNENFROTVH6MHSHA/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/3CAYYW35MUTNO65RVAELICTNZZFMT2XS/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/3JIMLVBDWOP4FUPXPTB4PGHHIOMGFLQE/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/3YQLUQWLIHDB5QCXQEX7HXHAWMOKPP5O/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/6Y74KVCPEPT4MVU3LHDWCNNOXOE5ZLUR/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/APYIXIQOVDCRWLHTGB4VYMAUIAQLKYJ3/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/BL5KTLOSLH2KHRN4HCXJPK3JUVLDGEL6/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/C3AFMZ6MH2UHHOPIWT5YLSFV3D2VB3AC/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/CHHITS4PUOZAKFIUBQAQZC7JWXMOYE4B/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/F7EYCFQCTSGJXWO3ZZ44MGKFC5HA7G3Y/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HYEDEXIKFKTUJIN43RG4B7T5ZS6MHUSP/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/I724O3LSRCPO4WNVIXTZCT4VVRMXMMSG/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/KEOTKBUPZXHE3F352JBYNTSNRXYLWD6P/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/KMZCVGUGJZZVDPCVDA7TEB22VUCNEXDD/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/L5Y6MNNVAPIJSXJERQ6PKZVCIUXSNJK7/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/LZQVUHWVWRH73YBXUQJOD6CKHDQBU3DM/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/MKQRBF3DWMWPH36LBCOBUTSIZRTPEZXB/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/QI3EHAHABFQK7OABNCSF5GMYP6TONTI7/","https://matt.ucc.asn.au/dropbear/CHANGES","https://nest.pijul.com/pijul/thrussh/changes/D6H7OWTTMHHX6BTB3B6MNBOBX2L66CBL4LGSEUSAI2MCRCJDQFRQC","https://news.ycombinator.com/item?id=38684904","https://news.ycombinator.com/item?id=38685286","https://news.ycombinator.com/item?id=38732005","https://nova.app/releases/#v11.8","https://oryx-embedded.com/download/#changelog","https://psirt.global.sonicwall.com/vuln-detail/SNWLID-2024-0002","https://roumenpetrov.info/secsh/#news20231220","https://security-tracker.debian.org/tracker/CVE-2023-48795","https://security-tracker.debian.org/tracker/source-package/libssh2","https://security-tracker.debian.org/tracker/source-package/proftpd-dfsg","https://security-tracker.debian.org/tracker/source-package/trilead-ssh2","https://security.gentoo.org/glsa/202312-16","https://security.gentoo.org/glsa/202312-17","https://security.netapp.com/advisory/ntap-20240105-0004/","https://support.apple.com/kb/HT214084","https://thorntech.com/cve-2023-48795-and-sftp-gateway/","https://twitter.com/TrueSkrillor/status/1736774389725565005","https://ubuntu.com/security/CVE-2023-48795","https://winscp.net/eng/docs/history#6.2.2","https://www.bitvise.com/ssh-client-version-history#933","https://www.bitvise.com/ssh-server-version-history","https://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html","https://www.crushftp.com/crush10wiki/Wiki.jsp?page=Update","https://www.debian.org/security/2023/dsa-5586","https://www.debian.org/security/2023/dsa-5588","https://www.freebsd.org/security/advisories/FreeBSD-SA-23:19.openssh.asc","https://www.lancom-systems.de/service-support/allgemeine-sicherheitshinweise#c243508","https://www.netsarang.com/en/xshell-update-history/","https://www.openssh.com/openbsd.html","https://www.openssh.com/txt/release-9.6","https://www.openwall.com/lists/oss-security/2023/12/18/2","https://www.openwall.com/lists/oss-security/2023/12/20/3","https://www.paramiko.org/changelog.html","https://www.reddit.com/r/sysadmin/comments/18idv52/cve202348795_why_is_this_cve_still_undisclosed/","https://www.suse.com/c/suse-addresses-the-ssh-v2-protocol-terrapin-attack-aka-cve-2023-48795/","https://www.terrapin-attack.com","https://www.theregister.com/2023/12/20/terrapin_attack_ssh","https://www.vandyke.com/products/securecrt/history.txt","https://www.vicarius.io/vsociety/posts/cve-2023-48795-detect-openssh-vulnerabilit","https://www.vicarius.io/vsociety/posts/cve-2023-48795-mitigate-openssh-vulnerability"],"description":"The SSH transport protocol with certain OpenSSH extensions, found in OpenSSH before 9.6 and other products, allows remote attackers to bypass integrity checks such that some packets are omitted (from the extension negotiation message), and a client and server may consequently end up with a connection for which some security features have been downgraded or disabled, aka a Terrapin attack. This occurs because the SSH Binary Packet Protocol (BPP), implemented by these extensions, mishandles the handshake phase and mishandles use of sequence numbers. For example, there is an effective attack against SSH's use of ChaCha20-Poly1305 (and CBC with Encrypt-then-MAC). The bypass occurs in chacha20-poly1305@openssh.com and (if CBC is used) the -etm@openssh.com MAC algorithms. This also affects Maverick Synergy Java SSH API before 3.1.0-SNAPSHOT, Dropbear through 2022.83, Ssh before 5.1.1 in Erlang/OTP, PuTTY before 0.80, AsyncSSH before 2.14.2, golang.org/x/crypto before 0.17.0, libssh before 0.10.6, libssh2 through 1.11.0, Thorn Tech SFTP Gateway before 3.4.6, Tera Term before 5.1, Paramiko before 3.4.0, jsch before 0.2.15, SFTPGo before 2.5.6, Netgate pfSense Plus through 23.09.1, Netgate pfSense CE through 2.7.2, HPN-SSH through 18.2.0, ProFTPD before 1.3.8b (and before 1.3.9rc2), ORYX CycloneSSH before 2.3.4, NetSarang XShell 7 before Build 0144, CrushFTP before 10.6.0, ConnectBot SSH library before 2.2.22, Apache MINA sshd through 2.11.0, sshj through 0.37.0, TinySSH through 20230101, trilead-ssh2 6401, LANCOM LCOS and LANconfig, FileZilla before 3.66.4, Nova before 11.8, PKIX-SSH before 14.4, SecureCRT before 9.4.3, Transmit5 before 5.10.4, Win32-OpenSSH before 9.5.0.0p1-Beta, WinSCP before 6.2.2, Bitvise SSH Server before 9.32, Bitvise SSH Client before 9.33, KiTTY through 0.76.1.13, the net-ssh gem 7.2.0 for Ruby, the mscdex ssh2 module before 1.15.0 for Node.js, the thrussh library before 0.35.1 for Rust, and the Russh crate before 0.40.2 for Rust.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-48795","epss":0.67021,"percentile":0.98446,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"paramiko","version":"2.7.2"}},"found":{"versionConstraint":">=2.5.0,<3.4.0 (python)","vulnerabilityID":"GHSA-45x7-px36-x8w8"},"fix":{"suggestedVersion":"3.4.0"}}],"artifact":{"id":"34f4e3af26488282","name":"paramiko","version":"2.7.2","type":"python","locations":[{"path":"/lib/python3.8/site-packages/paramiko-2.7.2.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/paramiko-2.7.2.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/paramiko-2.7.2.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/paramiko-2.7.2.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/paramiko-2.7.2.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/paramiko-2.7.2.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["LGPL"],"cpes":["cpe:2.3:a:jeff_forcier_project:python-paramiko:2.7.2:*:*:*:*:*:*:*","cpe:2.3:a:jeff_forcier_project:python_paramiko:2.7.2:*:*:*:*:*:*:*","cpe:2.3:a:jeff_forcierproject:python-paramiko:2.7.2:*:*:*:*:*:*:*","cpe:2.3:a:jeff_forcierproject:python_paramiko:2.7.2:*:*:*:*:*:*:*","cpe:2.3:a:python-paramiko:python-paramiko:2.7.2:*:*:*:*:*:*:*","cpe:2.3:a:python-paramiko:python_paramiko:2.7.2:*:*:*:*:*:*:*","cpe:2.3:a:python_paramiko:python-paramiko:2.7.2:*:*:*:*:*:*:*","cpe:2.3:a:python_paramiko:python_paramiko:2.7.2:*:*:*:*:*:*:*","cpe:2.3:a:jeff_forcier_project:paramiko:2.7.2:*:*:*:*:*:*:*","cpe:2.3:a:jeff_forcier:python-paramiko:2.7.2:*:*:*:*:*:*:*","cpe:2.3:a:jeff_forcier:python_paramiko:2.7.2:*:*:*:*:*:*:*","cpe:2.3:a:jeff_forcierproject:paramiko:2.7.2:*:*:*:*:*:*:*","cpe:2.3:a:jeff_project:python-paramiko:2.7.2:*:*:*:*:*:*:*","cpe:2.3:a:jeff_project:python_paramiko:2.7.2:*:*:*:*:*:*:*","cpe:2.3:a:jeffproject:python-paramiko:2.7.2:*:*:*:*:*:*:*","cpe:2.3:a:jeffproject:python_paramiko:2.7.2:*:*:*:*:*:*:*","cpe:2.3:a:paramiko:python-paramiko:2.7.2:*:*:*:*:*:*:*","cpe:2.3:a:paramiko:python_paramiko:2.7.2:*:*:*:*:*:*:*","cpe:2.3:a:python-paramiko:paramiko:2.7.2:*:*:*:*:*:*:*","cpe:2.3:a:python_paramiko:paramiko:2.7.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python-paramiko:2.7.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python_paramiko:2.7.2:*:*:*:*:*:*:*","cpe:2.3:a:jeff_forcier:paramiko:2.7.2:*:*:*:*:*:*:*","cpe:2.3:a:jeff_project:paramiko:2.7.2:*:*:*:*:*:*:*","cpe:2.3:a:jeff:python-paramiko:2.7.2:*:*:*:*:*:*:*","cpe:2.3:a:jeff:python_paramiko:2.7.2:*:*:*:*:*:*:*","cpe:2.3:a:jeffproject:paramiko:2.7.2:*:*:*:*:*:*:*","cpe:2.3:a:paramiko:paramiko:2.7.2:*:*:*:*:*:*:*","cpe:2.3:a:python:paramiko:2.7.2:*:*:*:*:*:*:*","cpe:2.3:a:jeff:paramiko:2.7.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/paramiko@2.7.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-8q59-q68h-6hv4","dataSource":"https://github.com/advisories/GHSA-8q59-q68h-6hv4","namespace":"github:language:python","severity":"Critical","urls":[],"description":"Improper Input Validation in PyYAML","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":9.8,"exploitabilityScore":3.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2020-14343","epss":0.14625,"percentile":0.94147,"date":"2025-06-03"}],"fix":{"versions":["5.4"],"state":"fixed"},"advisories":[],"risk":13.747500000000002},"relatedVulnerabilities":[{"id":"CVE-2020-14343","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2020-14343","namespace":"nvd:cpe","severity":"Critical","urls":["https://bugzilla.redhat.com/show_bug.cgi?id=1860466","https://github.com/SeldonIO/seldon-core/issues/2252","https://github.com/yaml/pyyaml/issues/420","https://www.oracle.com/security-alerts/cpuapr2022.html","https://www.oracle.com/security-alerts/cpujul2022.html","https://bugzilla.redhat.com/show_bug.cgi?id=1860466","https://github.com/SeldonIO/seldon-core/issues/2252","https://github.com/yaml/pyyaml/issues/420","https://www.oracle.com/security-alerts/cpuapr2022.html","https://www.oracle.com/security-alerts/cpujul2022.html"],"description":"A vulnerability was discovered in the PyYAML library in versions before 5.4, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. This flaw allows an attacker to execute arbitrary code on the system by abusing the python/object/new constructor. This flaw is due to an incomplete fix for CVE-2020-1747.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":9.8,"exploitabilityScore":3.9,"impactScore":5.9},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:L/Au:N/C:C/I:C/A:C","metrics":{"baseScore":10,"exploitabilityScore":10,"impactScore":10.1},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2020-14343","epss":0.14625,"percentile":0.94147,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"pyyaml","version":"5.3.1"}},"found":{"versionConstraint":"<5.4 (python)","vulnerabilityID":"GHSA-8q59-q68h-6hv4"},"fix":{"suggestedVersion":"5.4"}}],"artifact":{"id":"b351faa026ebb9af","name":"pyyaml","version":"5.3.1","type":"python","locations":[{"path":"/lib/python3.8/site-packages/PyYAML-5.3.1.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/PyYAML-5.3.1.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/PyYAML-5.3.1.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/PyYAML-5.3.1.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/PyYAML-5.3.1.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/PyYAML-5.3.1.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:kirill_simonov_project:python-pyyaml:5.3.1:*:*:*:*:*:*:*","cpe:2.3:a:kirill_simonov_project:python_pyyaml:5.3.1:*:*:*:*:*:*:*","cpe:2.3:a:kirill_simonovproject:python-pyyaml:5.3.1:*:*:*:*:*:*:*","cpe:2.3:a:kirill_simonovproject:python_pyyaml:5.3.1:*:*:*:*:*:*:*","cpe:2.3:a:kirill_simonov_project:pyyaml:5.3.1:*:*:*:*:*:*:*","cpe:2.3:a:kirill_simonov:python-pyyaml:5.3.1:*:*:*:*:*:*:*","cpe:2.3:a:kirill_simonov:python_pyyaml:5.3.1:*:*:*:*:*:*:*","cpe:2.3:a:kirill_simonovproject:pyyaml:5.3.1:*:*:*:*:*:*:*","cpe:2.3:a:python-pyyaml:python-pyyaml:5.3.1:*:*:*:*:*:*:*","cpe:2.3:a:python-pyyaml:python_pyyaml:5.3.1:*:*:*:*:*:*:*","cpe:2.3:a:python_pyyaml:python-pyyaml:5.3.1:*:*:*:*:*:*:*","cpe:2.3:a:python_pyyaml:python_pyyaml:5.3.1:*:*:*:*:*:*:*","cpe:2.3:a:xi_project:python-pyyaml:5.3.1:*:*:*:*:*:*:*","cpe:2.3:a:xi_project:python_pyyaml:5.3.1:*:*:*:*:*:*:*","cpe:2.3:a:xiproject:python-pyyaml:5.3.1:*:*:*:*:*:*:*","cpe:2.3:a:xiproject:python_pyyaml:5.3.1:*:*:*:*:*:*:*","cpe:2.3:a:kirill_simonov:pyyaml:5.3.1:*:*:*:*:*:*:*","cpe:2.3:a:python-pyyaml:pyyaml:5.3.1:*:*:*:*:*:*:*","cpe:2.3:a:python:python-pyyaml:5.3.1:*:*:*:*:*:*:*","cpe:2.3:a:python:python_pyyaml:5.3.1:*:*:*:*:*:*:*","cpe:2.3:a:python_pyyaml:pyyaml:5.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pyyaml:python-pyyaml:5.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pyyaml:python_pyyaml:5.3.1:*:*:*:*:*:*:*","cpe:2.3:a:xi_project:pyyaml:5.3.1:*:*:*:*:*:*:*","cpe:2.3:a:xi:python-pyyaml:5.3.1:*:*:*:*:*:*:*","cpe:2.3:a:xi:python_pyyaml:5.3.1:*:*:*:*:*:*:*","cpe:2.3:a:xiproject:pyyaml:5.3.1:*:*:*:*:*:*:*","cpe:2.3:a:python:pyyaml:5.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pyyaml:pyyaml:5.3.1:*:*:*:*:*:*:*","cpe:2.3:a:xi:pyyaml:5.3.1:*:*:*:*:*:*:*"],"purl":"pkg:pypi/pyyaml@5.3.1","upstreams":[]}},{"vulnerability":{"id":"GHSA-j8r2-6x86-q33q","dataSource":"https://github.com/advisories/GHSA-j8r2-6x86-q33q","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Unintended leak of Proxy-Authorization header in requests","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N","metrics":{"baseScore":6.1,"exploitabilityScore":1.7,"impactScore":4},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-32681","epss":0.04731,"percentile":0.88915,"date":"2025-06-03"}],"fix":{"versions":["2.31.0"],"state":"fixed"},"advisories":[],"risk":2.6257049999999995},"relatedVulnerabilities":[{"id":"CVE-2023-32681","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-32681","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/psf/requests/commit/74ea7cf7a6a27a4eeb2ae24e162bcc942a6706d5","https://github.com/psf/requests/releases/tag/v2.31.0","https://github.com/psf/requests/security/advisories/GHSA-j8r2-6x86-q33q","https://lists.debian.org/debian-lts-announce/2023/06/msg00018.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AW7HNFGYP44RT3DUDQXG2QT3OEV2PJ7Y/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KOYASTZDGQG2BWLSNBPL3TQRL2G7QYNZ/","https://security.gentoo.org/glsa/202309-08","https://github.com/psf/requests/commit/74ea7cf7a6a27a4eeb2ae24e162bcc942a6706d5","https://github.com/psf/requests/releases/tag/v2.31.0","https://github.com/psf/requests/security/advisories/GHSA-j8r2-6x86-q33q","https://lists.debian.org/debian-lts-announce/2023/06/msg00018.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AW7HNFGYP44RT3DUDQXG2QT3OEV2PJ7Y/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KOYASTZDGQG2BWLSNBPL3TQRL2G7QYNZ/","https://security.gentoo.org/glsa/202309-08"],"description":"Requests is a HTTP library. Since Requests 2.3.0, Requests has been leaking Proxy-Authorization headers to destination servers when redirected to an HTTPS endpoint. This is a product of how we use `rebuild_proxies` to reattach the `Proxy-Authorization` header to requests. For HTTP connections sent through the tunnel, the proxy will identify the header in the request itself and remove it prior to forwarding to the destination server. However when sent over HTTPS, the `Proxy-Authorization` header must be sent in the CONNECT request as the proxy has no visibility into the tunneled request. This results in Requests forwarding proxy credentials to the destination server unintentionally, allowing a malicious actor to potentially exfiltrate sensitive information. This issue has been patched in version 2.31.0.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N","metrics":{"baseScore":6.1,"exploitabilityScore":1.7,"impactScore":4},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N","metrics":{"baseScore":6.1,"exploitabilityScore":1.7,"impactScore":4},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-32681","epss":0.04731,"percentile":0.88915,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"requests","version":"2.25.0"}},"found":{"versionConstraint":">=2.3.0,<2.31.0 (python)","vulnerabilityID":"GHSA-j8r2-6x86-q33q"},"fix":{"suggestedVersion":"2.31.0"}}],"artifact":{"id":"a823a315c8146163","name":"requests","version":"2.25.0","type":"python","locations":[{"path":"/lib/python3.8/site-packages/requests-2.25.0.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/requests-2.25.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/requests-2.25.0.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/requests-2.25.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/requests-2.25.0.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/requests-2.25.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache 2.0"],"cpes":["cpe:2.3:a:python:requests:2.25.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/requests@2.25.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-q2q7-5pp4-w6pg","dataSource":"https://github.com/advisories/GHSA-q2q7-5pp4-w6pg","namespace":"github:language:python","severity":"High","urls":[],"description":"Catastrophic backtracking in URL authority parser when passed URL containing many @ characters","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-33503","epss":0.00863,"percentile":0.74071,"date":"2025-06-03"}],"fix":{"versions":["1.26.5"],"state":"fixed"},"advisories":[],"risk":0.6472500000000001},"relatedVulnerabilities":[{"id":"CVE-2021-33503","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2021-33503","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/advisories/GHSA-q2q7-5pp4-w6pg","https://github.com/urllib3/urllib3/commit/2d4a3fee6de2fa45eb82169361918f759269b4ec","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/6SCV7ZNAHS3E6PBFLJGENCDRDRWRZZ6W/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/FMUGWEAUYGGHTPPXT6YBD53WYXQGVV73/","https://security.gentoo.org/glsa/202107-36","https://www.oracle.com/security-alerts/cpuoct2021.html","https://github.com/advisories/GHSA-q2q7-5pp4-w6pg","https://github.com/urllib3/urllib3/commit/2d4a3fee6de2fa45eb82169361918f759269b4ec","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/6SCV7ZNAHS3E6PBFLJGENCDRDRWRZZ6W/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/FMUGWEAUYGGHTPPXT6YBD53WYXQGVV73/","https://security.gentoo.org/glsa/202107-36","https://www.oracle.com/security-alerts/cpuoct2021.html"],"description":"An issue was discovered in urllib3 before 1.26.5. When provided with a URL containing many @ characters in the authority component, the authority regular expression exhibits catastrophic backtracking, causing a denial of service if a URL were passed as a parameter or redirected to via an HTTP redirect.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:L/Au:N/C:N/I:N/A:P","metrics":{"baseScore":5,"exploitabilityScore":10,"impactScore":2.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-33503","epss":0.00863,"percentile":0.74071,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"urllib3","version":"1.26.2"}},"found":{"versionConstraint":">=1.25.4,<1.26.5 (python)","vulnerabilityID":"GHSA-q2q7-5pp4-w6pg"},"fix":{"suggestedVersion":"1.26.5"}}],"artifact":{"id":"a9c3d78ade6ae399","name":"urllib3","version":"1.26.2","type":"python","locations":[{"path":"/lib/python3.8/site-packages/urllib3-1.26.2.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/urllib3-1.26.2.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/urllib3-1.26.2.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/urllib3-1.26.2.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/urllib3-1.26.2.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/urllib3-1.26.2.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:urllib3:1.26.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/urllib3@1.26.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-rhm9-p9w5-fwm7","dataSource":"https://github.com/advisories/GHSA-rhm9-p9w5-fwm7","namespace":"github:language:python","severity":"High","urls":[],"description":"PyCA Cryptography symmetrically encrypting large values can lead to integer overflow","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:H","metrics":{"baseScore":9.1,"exploitabilityScore":3.9,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2020-36242","epss":0.00499,"percentile":0.64891,"date":"2025-06-03"}],"fix":{"versions":["3.3.2"],"state":"fixed"},"advisories":[],"risk":0.41417},"relatedVulnerabilities":[{"id":"CVE-2020-36242","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2020-36242","namespace":"nvd:cpe","severity":"Critical","urls":["https://github.com/pyca/cryptography/blob/master/CHANGELOG.rst","https://github.com/pyca/cryptography/compare/3.3.1...3.3.2","https://github.com/pyca/cryptography/issues/5615","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/L7RGQLK4J5ZQFRLKCHVVG6BKZTUQMG7E/","https://www.oracle.com/security-alerts/cpuapr2022.html","https://www.oracle.com/security-alerts/cpujul2022.html","https://github.com/pyca/cryptography/blob/master/CHANGELOG.rst","https://github.com/pyca/cryptography/compare/3.3.1...3.3.2","https://github.com/pyca/cryptography/issues/5615","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/L7RGQLK4J5ZQFRLKCHVVG6BKZTUQMG7E/","https://www.oracle.com/security-alerts/cpuapr2022.html","https://www.oracle.com/security-alerts/cpujul2022.html"],"description":"In the cryptography package before 3.3.2 for Python, certain sequences of update calls to symmetrically encrypt multi-GB values could result in an integer overflow and buffer overflow, as demonstrated by the Fernet class.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:H","metrics":{"baseScore":9.1,"exploitabilityScore":3.9,"impactScore":5.2},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:L/Au:N/C:P/I:N/A:P","metrics":{"baseScore":6.4,"exploitabilityScore":10,"impactScore":5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2020-36242","epss":0.00499,"percentile":0.64891,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"3.2.1"}},"found":{"versionConstraint":">=3.1,<3.3.2 (python)","vulnerabilityID":"GHSA-rhm9-p9w5-fwm7"},"fix":{"suggestedVersion":"3.3.2"}}],"artifact":{"id":"45a2789cece8d69f","name":"cryptography","version":"3.2.1","type":"python","locations":[{"path":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD or Apache License, Version 2.0"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:3.2.1:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:3.2.1:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@3.2.1","upstreams":[]}},{"vulnerability":{"id":"GHSA-3ww4-gg4f-jr7f","dataSource":"https://github.com/advisories/GHSA-3ww4-gg4f-jr7f","namespace":"github:language:python","severity":"High","urls":[],"description":"Python Cryptography package vulnerable to Bleichenbacher timing oracle attack","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-50782","epss":0.00521,"percentile":0.6593,"date":"2025-06-03"}],"fix":{"versions":["42.0.0"],"state":"fixed"},"advisories":[],"risk":0.39075000000000004},"relatedVulnerabilities":[{"id":"CVE-2023-50782","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-50782","namespace":"nvd:cpe","severity":"High","urls":["https://access.redhat.com/security/cve/CVE-2023-50782","https://bugzilla.redhat.com/show_bug.cgi?id=2254432","https://access.redhat.com/security/cve/CVE-2023-50782","https://bugzilla.redhat.com/show_bug.cgi?id=2254432","https://www.couchbase.com/alerts/"],"description":"A flaw was found in the python-cryptography package. This issue may allow a remote attacker to decrypt captured messages in TLS servers that use RSA key exchanges, which may lead to exposure of confidential or sensitive data.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"secalert@redhat.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-50782","epss":0.00521,"percentile":0.6593,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"3.2.1"}},"found":{"versionConstraint":"<42.0.0 (python)","vulnerabilityID":"GHSA-3ww4-gg4f-jr7f"},"fix":{"suggestedVersion":"42.0.0"}}],"artifact":{"id":"45a2789cece8d69f","name":"cryptography","version":"3.2.1","type":"python","locations":[{"path":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD or Apache License, Version 2.0"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:3.2.1:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:3.2.1:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@3.2.1","upstreams":[]}},{"vulnerability":{"id":"GHSA-v845-jxx5-vc9f","dataSource":"https://github.com/advisories/GHSA-v845-jxx5-vc9f","namespace":"github:language:python","severity":"High","urls":[],"description":"`Cookie` HTTP header isn't stripped on cross-origin redirects","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:H/A:N","metrics":{"baseScore":5.9,"exploitabilityScore":0.8,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-43804","epss":0.00554,"percentile":0.67072,"date":"2025-06-03"}],"fix":{"versions":["1.26.17"],"state":"fixed"},"advisories":[],"risk":0.37118},"relatedVulnerabilities":[{"id":"CVE-2023-43804","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-43804","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/urllib3/urllib3/commit/01220354d389cd05474713f8c982d05c9b17aafb","https://github.com/urllib3/urllib3/commit/644124ecd0b6e417c527191f866daa05a5a2056d","https://github.com/urllib3/urllib3/security/advisories/GHSA-v845-jxx5-vc9f","https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/I3PR7C6RJ6JUBQKIJ644DMIJSUP36VDY/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NDAGZXYJ7H2G3SB47M453VQVNAWKAEJJ/","https://github.com/urllib3/urllib3/commit/01220354d389cd05474713f8c982d05c9b17aafb","https://github.com/urllib3/urllib3/commit/644124ecd0b6e417c527191f866daa05a5a2056d","https://github.com/urllib3/urllib3/security/advisories/GHSA-v845-jxx5-vc9f","https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/I3PR7C6RJ6JUBQKIJ644DMIJSUP36VDY/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NDAGZXYJ7H2G3SB47M453VQVNAWKAEJJ/","https://security.netapp.com/advisory/ntap-20241213-0007/","https://www.vicarius.io/vsociety/posts/cve-2023-43804-urllib3-vulnerability-3"],"description":"urllib3 is a user-friendly HTTP client library for Python. urllib3 doesn't treat the `Cookie` HTTP header special or provide any helpers for managing cookies over HTTP, that is the responsibility of the user. However, it is possible for a user to specify a `Cookie` header and unknowingly leak information via HTTP redirects to a different origin if that user doesn't disable redirects explicitly. This issue has been patched in urllib3 version 1.26.17 or 2.0.5.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N","metrics":{"baseScore":8.1,"exploitabilityScore":2.9,"impactScore":5.2},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:H/A:N","metrics":{"baseScore":5.9,"exploitabilityScore":0.8,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-43804","epss":0.00554,"percentile":0.67072,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"urllib3","version":"1.26.2"}},"found":{"versionConstraint":"<1.26.17 (python)","vulnerabilityID":"GHSA-v845-jxx5-vc9f"},"fix":{"suggestedVersion":"1.26.17"}}],"artifact":{"id":"a9c3d78ade6ae399","name":"urllib3","version":"1.26.2","type":"python","locations":[{"path":"/lib/python3.8/site-packages/urllib3-1.26.2.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/urllib3-1.26.2.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/urllib3-1.26.2.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/urllib3-1.26.2.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/urllib3-1.26.2.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/urllib3-1.26.2.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:urllib3:1.26.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/urllib3@1.26.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-5rjg-fvgr-3xxf","dataSource":"https://github.com/advisories/GHSA-5rjg-fvgr-3xxf","namespace":"github:language:python","severity":"High","urls":[],"description":"setuptools has a path traversal vulnerability in PackageIndex.download that leads to Arbitrary File Write","cvss":[],"epss":[{"cve":"CVE-2025-47273","epss":0.00435,"percentile":0.62062,"date":"2025-06-03"}],"fix":{"versions":["78.1.1"],"state":"fixed"},"advisories":[],"risk":0.32625},"relatedVulnerabilities":[{"id":"CVE-2025-47273","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-47273","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pypa/setuptools/blob/6ead555c5fb29bc57fe6105b1bffc163f56fd558/setuptools/package_index.py#L810C1-L825C88","https://github.com/pypa/setuptools/commit/250a6d17978f9f6ac3ac887091f2d32886fbbb0b","https://github.com/pypa/setuptools/issues/4946","https://github.com/pypa/setuptools/security/advisories/GHSA-5rjg-fvgr-3xxf","https://lists.debian.org/debian-lts-announce/2025/05/msg00035.html","https://github.com/pypa/setuptools/issues/4946"],"description":"setuptools is a package that allows users to download, build, install, upgrade, and uninstall Python packages. A path traversal vulnerability in `PackageIndex` is present in setuptools prior to version 78.1.1. An attacker would be allowed to write files to arbitrary locations on the filesystem with the permissions of the process running the Python code, which could escalate to remote code execution depending on the context. Version 78.1.1 fixes the issue.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:H/VA:N/SC:N/SI:N/SA:N/E:P/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":7.7},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-47273","epss":0.00435,"percentile":0.62062,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"setuptools","version":"50.3.2"}},"found":{"versionConstraint":"<78.1.1 (python)","vulnerabilityID":"GHSA-5rjg-fvgr-3xxf"},"fix":{"suggestedVersion":"78.1.1"}}],"artifact":{"id":"e9423d39c362c15e","name":"setuptools","version":"50.3.2","type":"python","locations":[{"path":"/lib/python3.8/site-packages/setuptools-50.3.2.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/setuptools-50.3.2.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/setuptools-50.3.2.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/setuptools-50.3.2.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/setuptools-50.3.2.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/setuptools-50.3.2.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["UNKNOWN"],"cpes":["cpe:2.3:a:python:setuptools:50.3.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/setuptools@50.3.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-jfhm-5ghh-2f97","dataSource":"https://github.com/advisories/GHSA-jfhm-5ghh-2f97","namespace":"github:language:python","severity":"Medium","urls":[],"description":"cryptography vulnerable to NULL-dereference when loading PKCS7 certificates","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-49083","epss":0.00457,"percentile":0.63032,"date":"2025-06-03"}],"fix":{"versions":["41.0.6"],"state":"fixed"},"advisories":[],"risk":0.24906500000000004},"relatedVulnerabilities":[{"id":"CVE-2023-49083","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-49083","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pyca/cryptography/commit/f09c261ca10a31fe41b1262306db7f8f1da0e48a","https://github.com/pyca/cryptography/pull/9926","https://github.com/pyca/cryptography/security/advisories/GHSA-jfhm-5ghh-2f97","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QMNTYMUGFJSDBYBU22FUYBHFRZODRKXV/","https://github.com/pyca/cryptography/commit/f09c261ca10a31fe41b1262306db7f8f1da0e48a","https://github.com/pyca/cryptography/pull/9926","https://github.com/pyca/cryptography/security/advisories/GHSA-jfhm-5ghh-2f97","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QMNTYMUGFJSDBYBU22FUYBHFRZODRKXV/"],"description":"cryptography is a package designed to expose cryptographic primitives and recipes to Python developers. Calling `load_pem_pkcs7_certificates` or `load_der_pkcs7_certificates` could lead to a NULL-pointer dereference and segfault. Exploitation of this vulnerability poses a serious risk of Denial of Service (DoS) for any application attempting to deserialize a PKCS7 blob/certificate. The consequences extend to potential disruptions in system availability and stability. This vulnerability has been patched in version 41.0.6.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-49083","epss":0.00457,"percentile":0.63032,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"3.2.1"}},"found":{"versionConstraint":">=3.1,<41.0.6 (python)","vulnerabilityID":"GHSA-jfhm-5ghh-2f97"},"fix":{"suggestedVersion":"41.0.6"}}],"artifact":{"id":"45a2789cece8d69f","name":"cryptography","version":"3.2.1","type":"python","locations":[{"path":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD or Apache License, Version 2.0"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:3.2.1:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:3.2.1:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@3.2.1","upstreams":[]}},{"vulnerability":{"id":"GHSA-jjg7-2v4v-x38h","dataSource":"https://github.com/advisories/GHSA-jjg7-2v4v-x38h","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Internationalized Domain Names in Applications (IDNA) vulnerable to denial of service from specially crafted inputs to idna.encode","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":6.2,"exploitabilityScore":2.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-3651","epss":0.00436,"percentile":0.62113,"date":"2025-06-03"}],"fix":{"versions":["3.7"],"state":"fixed"},"advisories":[],"risk":0.24416000000000004},"relatedVulnerabilities":[{"id":"CVE-2024-3651","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-3651","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/kjd/idna/commit/1d365e17e10d72d0b7876316fc7b9ca0eebdd38d","https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb","https://github.com/kjd/idna/commit/1d365e17e10d72d0b7876316fc7b9ca0eebdd38d","https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb"],"description":"A vulnerability was identified in the kjd/idna library, specifically within the `idna.encode()` function, affecting version 3.6. The issue arises from the function's handling of crafted input strings, which can lead to quadratic complexity and consequently, a denial of service condition. This vulnerability is triggered by a crafted input that causes the `idna.encode()` function to process the input with considerable computational load, significantly increasing the processing time in a quadratic manner relative to the input size.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security@huntr.dev","type":"Secondary","version":"3.0","vector":"CVSS:3.0/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":6.2,"exploitabilityScore":2.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-3651","epss":0.00436,"percentile":0.62113,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"idna","version":"2.10"}},"found":{"versionConstraint":"<3.7 (python)","vulnerabilityID":"GHSA-jjg7-2v4v-x38h"},"fix":{"suggestedVersion":"3.7"}}],"artifact":{"id":"9c29469d864f8698","name":"idna","version":"2.10","type":"python","locations":[{"path":"/lib/python3.8/site-packages/idna-2.10.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/idna-2.10.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/idna-2.10.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/idna-2.10.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/idna-2.10.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/idna-2.10.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-like"],"cpes":["cpe:2.3:a:kim_davies_project:python-idna:2.10:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_project:python_idna:2.10:*:*:*:*:*:*:*","cpe:2.3:a:kim_daviesproject:python-idna:2.10:*:*:*:*:*:*:*","cpe:2.3:a:kim_daviesproject:python_idna:2.10:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_project:idna:2.10:*:*:*:*:*:*:*","cpe:2.3:a:kim_project:python-idna:2.10:*:*:*:*:*:*:*","cpe:2.3:a:kim_project:python_idna:2.10:*:*:*:*:*:*:*","cpe:2.3:a:python-idna:python-idna:2.10:*:*:*:*:*:*:*","cpe:2.3:a:python-idna:python_idna:2.10:*:*:*:*:*:*:*","cpe:2.3:a:python_idna:python-idna:2.10:*:*:*:*:*:*:*","cpe:2.3:a:python_idna:python_idna:2.10:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies:python-idna:2.10:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies:python_idna:2.10:*:*:*:*:*:*:*","cpe:2.3:a:kim_daviesproject:idna:2.10:*:*:*:*:*:*:*","cpe:2.3:a:kimproject:python-idna:2.10:*:*:*:*:*:*:*","cpe:2.3:a:kimproject:python_idna:2.10:*:*:*:*:*:*:*","cpe:2.3:a:python:python-idna:2.10:*:*:*:*:*:*:*","cpe:2.3:a:python:python_idna:2.10:*:*:*:*:*:*:*","cpe:2.3:a:idna:python-idna:2.10:*:*:*:*:*:*:*","cpe:2.3:a:idna:python_idna:2.10:*:*:*:*:*:*:*","cpe:2.3:a:kim_project:idna:2.10:*:*:*:*:*:*:*","cpe:2.3:a:python-idna:idna:2.10:*:*:*:*:*:*:*","cpe:2.3:a:python_idna:idna:2.10:*:*:*:*:*:*:*","cpe:2.3:a:kim:python-idna:2.10:*:*:*:*:*:*:*","cpe:2.3:a:kim:python_idna:2.10:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies:idna:2.10:*:*:*:*:*:*:*","cpe:2.3:a:kimproject:idna:2.10:*:*:*:*:*:*:*","cpe:2.3:a:python:idna:2.10:*:*:*:*:*:*:*","cpe:2.3:a:idna:idna:2.10:*:*:*:*:*:*:*","cpe:2.3:a:kim:idna:2.10:*:*:*:*:*:*:*"],"purl":"pkg:pypi/idna@2.10","upstreams":[]}},{"vulnerability":{"id":"GHSA-r9hx-vwmv-q579","dataSource":"https://github.com/advisories/GHSA-r9hx-vwmv-q579","namespace":"github:language:python","severity":"High","urls":[],"description":"pypa/setuptools vulnerable to Regular Expression Denial of Service (ReDoS)","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-40897","epss":0.00318,"percentile":0.54328,"date":"2025-06-03"}],"fix":{"versions":["65.5.1"],"state":"fixed"},"advisories":[],"risk":0.2385},"relatedVulnerabilities":[{"id":"CVE-2022-40897","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2022-40897","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pypa/setuptools/blob/fe8a98e696241487ba6ac9f91faa38ade939ec5d/setuptools/package_index.py#L200","https://github.com/pypa/setuptools/commit/43a9c9bfa6aa626ec2a22540bea28d2ca77964be","https://github.com/pypa/setuptools/compare/v65.5.0...v65.5.1","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H/","https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/","https://pyup.io/vulnerabilities/CVE-2022-40897/52495/","https://security.netapp.com/advisory/ntap-20230214-0001/","https://security.netapp.com/advisory/ntap-20240621-0006/","https://github.com/pypa/setuptools/blob/fe8a98e696241487ba6ac9f91faa38ade939ec5d/setuptools/package_index.py#L200","https://github.com/pypa/setuptools/commit/43a9c9bfa6aa626ec2a22540bea28d2ca77964be","https://github.com/pypa/setuptools/compare/v65.5.0...v65.5.1","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H/","https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/","https://pyup.io/vulnerabilities/CVE-2022-40897/52495/","https://security.netapp.com/advisory/ntap-20230214-0001/","https://security.netapp.com/advisory/ntap-20240621-0006/"],"description":"Python Packaging Authority (PyPA) setuptools before 65.5.1 allows remote attackers to cause a denial of service via HTML in a crafted package or custom PackageIndex page. There is a Regular Expression Denial of Service (ReDoS) in package_index.py.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-40897","epss":0.00318,"percentile":0.54328,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"setuptools","version":"50.3.2"}},"found":{"versionConstraint":"<65.5.1 (python)","vulnerabilityID":"GHSA-r9hx-vwmv-q579"},"fix":{"suggestedVersion":"65.5.1"}}],"artifact":{"id":"e9423d39c362c15e","name":"setuptools","version":"50.3.2","type":"python","locations":[{"path":"/lib/python3.8/site-packages/setuptools-50.3.2.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/setuptools-50.3.2.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/setuptools-50.3.2.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/setuptools-50.3.2.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/setuptools-50.3.2.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/setuptools-50.3.2.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["UNKNOWN"],"cpes":["cpe:2.3:a:python:setuptools:50.3.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/setuptools@50.3.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-w7pp-m8wf-vj6r","dataSource":"https://github.com/advisories/GHSA-w7pp-m8wf-vj6r","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Cipher.update_into can corrupt memory if passed an immutable python object as the outbuf","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:L","metrics":{"baseScore":6.5,"exploitabilityScore":3.9,"impactScore":2.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-23931","epss":0.00331,"percentile":0.5554,"date":"2025-06-03"}],"fix":{"versions":["39.0.1"],"state":"fixed"},"advisories":[],"risk":0.19032499999999997},"relatedVulnerabilities":[{"id":"CVE-2023-23931","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-23931","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pyca/cryptography/pull/8230/commits/94a50a9731f35405f0357fa5f3b177d46a726ab3","https://github.com/pyca/cryptography/security/advisories/GHSA-w7pp-m8wf-vj6r","https://github.com/pyca/cryptography/pull/8230/commits/94a50a9731f35405f0357fa5f3b177d46a726ab3","https://github.com/pyca/cryptography/security/advisories/GHSA-w7pp-m8wf-vj6r","https://security.netapp.com/advisory/ntap-20230324-0007/"],"description":"cryptography is a package designed to expose cryptographic primitives and recipes to Python developers. In affected versions `Cipher.update_into` would accept Python objects which implement the buffer protocol, but provide only immutable buffers. This would allow immutable objects (such as `bytes`) to be mutated, thus violating fundamental rules of Python and resulting in corrupted output. This now correctly raises an exception. This issue has been present since `update_into` was originally introduced in cryptography 1.8.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:L","metrics":{"baseScore":6.5,"exploitabilityScore":3.9,"impactScore":2.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:L/A:L","metrics":{"baseScore":4.8,"exploitabilityScore":2.3,"impactScore":2.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-23931","epss":0.00331,"percentile":0.5554,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"3.2.1"}},"found":{"versionConstraint":">=1.8,<39.0.1 (python)","vulnerabilityID":"GHSA-w7pp-m8wf-vj6r"},"fix":{"suggestedVersion":"39.0.1"}}],"artifact":{"id":"45a2789cece8d69f","name":"cryptography","version":"3.2.1","type":"python","locations":[{"path":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD or Apache License, Version 2.0"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:3.2.1:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:3.2.1:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@3.2.1","upstreams":[]}},{"vulnerability":{"id":"GHSA-cx63-2mw6-8hw5","dataSource":"https://github.com/advisories/GHSA-cx63-2mw6-8hw5","namespace":"github:language:python","severity":"High","urls":[],"description":"setuptools vulnerable to Command Injection via package URL","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.8,"exploitabilityScore":2.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-6345","epss":0.00227,"percentile":0.45699,"date":"2025-06-03"}],"fix":{"versions":["70.0.0"],"state":"fixed"},"advisories":[],"risk":0.185005},"relatedVulnerabilities":[{"id":"CVE-2024-6345","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-6345","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pypa/setuptools/commit/88807c7062788254f654ea8c03427adc859321f0","https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5","https://github.com/pypa/setuptools/commit/88807c7062788254f654ea8c03427adc859321f0","https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5"],"description":"A vulnerability in the package_index module of pypa/setuptools versions up to 69.1.1 allows for remote code execution via its download functions. These functions, which are used to download packages from URLs provided by users or retrieved from package index servers, are susceptible to code injection. If these functions are exposed to user-controlled inputs, such as package URLs, they can execute arbitrary commands on the system. The issue is fixed in version 70.0.","cvss":[{"source":"security@huntr.dev","type":"Secondary","version":"3.0","vector":"CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.8,"exploitabilityScore":2.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-6345","epss":0.00227,"percentile":0.45699,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"setuptools","version":"50.3.2"}},"found":{"versionConstraint":"<70.0.0 (python)","vulnerabilityID":"GHSA-cx63-2mw6-8hw5"},"fix":{"suggestedVersion":"70.0.0"}}],"artifact":{"id":"e9423d39c362c15e","name":"setuptools","version":"50.3.2","type":"python","locations":[{"path":"/lib/python3.8/site-packages/setuptools-50.3.2.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/setuptools-50.3.2.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/setuptools-50.3.2.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/setuptools-50.3.2.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/setuptools-50.3.2.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/setuptools-50.3.2.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["UNKNOWN"],"cpes":["cpe:2.3:a:python:setuptools:50.3.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/setuptools@50.3.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-5xp3-jfq3-5q8x","dataSource":"https://github.com/advisories/GHSA-5xp3-jfq3-5q8x","namespace":"github:language:python","severity":"High","urls":[],"description":"Improper Input Validation in pip","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:N/I:H/A:N","metrics":{"baseScore":5.7,"exploitabilityScore":2.1,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-3572","epss":0.0024,"percentile":0.4753,"date":"2025-06-03"}],"fix":{"versions":["21.1"],"state":"fixed"},"advisories":[],"risk":0.15839999999999999},"relatedVulnerabilities":[{"id":"CVE-2021-3572","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2021-3572","namespace":"nvd:cpe","severity":"Medium","urls":["https://bugzilla.redhat.com/show_bug.cgi?id=1962856","https://security.netapp.com/advisory/ntap-20240621-0006/","https://www.oracle.com/security-alerts/cpuapr2022.html","https://www.oracle.com/security-alerts/cpujul2022.html","https://bugzilla.redhat.com/show_bug.cgi?id=1962856","https://security.netapp.com/advisory/ntap-20240621-0006/","https://www.oracle.com/security-alerts/cpuapr2022.html","https://www.oracle.com/security-alerts/cpujul2022.html"],"description":"A flaw was found in python-pip in the way it handled Unicode separators in git references. A remote attacker could possibly use this issue to install a different revision on a repository. The highest threat from this vulnerability is to data integrity. This is fixed in python-pip version 21.1.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:N/I:H/A:N","metrics":{"baseScore":5.7,"exploitabilityScore":2.1,"impactScore":3.6},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:M/Au:S/C:N/I:P/A:N","metrics":{"baseScore":3.5,"exploitabilityScore":6.9,"impactScore":2.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-3572","epss":0.0024,"percentile":0.4753,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"pip","version":"20.0.2"}},"found":{"versionConstraint":"<21.1 (python)","vulnerabilityID":"GHSA-5xp3-jfq3-5q8x"},"fix":{"suggestedVersion":"21.1"}}],"artifact":{"id":"e82731344f755f57","name":"pip","version":"20.0.2","type":"python","locations":[{"path":"/lib/python3.8/site-packages/pip-20.0.2.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/pip-20.0.2.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/pip-20.0.2.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/pip-20.0.2.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/pip-20.0.2.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/pip-20.0.2.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:pip_developers_project:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers_project:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev_project:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev_project:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers_project:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_devproject:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_devproject:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev_project:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa-dev:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa-dev:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_devproject:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa-dev:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip:pip:20.0.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/pip@20.0.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-8ch4-58qp-g3mp","dataSource":"https://github.com/advisories/GHSA-8ch4-58qp-g3mp","namespace":"github:language:python","severity":"High","urls":[],"description":"Observable Timing Discrepancy in aaugustin websockets library","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-33880","epss":0.00192,"percentile":0.41834,"date":"2025-06-03"}],"fix":{"versions":["9.1"],"state":"fixed"},"advisories":[],"risk":0.12864},"relatedVulnerabilities":[{"id":"CVE-2021-33880","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2021-33880","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/aaugustin/websockets/commit/547a26b685d08cac0aa64e5e65f7867ac0ea9bc0","https://www.oracle.com/security-alerts/cpuapr2022.html","https://www.oracle.com/security-alerts/cpujan2022.html","https://github.com/aaugustin/websockets/commit/547a26b685d08cac0aa64e5e65f7867ac0ea9bc0","https://www.oracle.com/security-alerts/cpuapr2022.html","https://www.oracle.com/security-alerts/cpujan2022.html"],"description":"The aaugustin websockets library before 9.1 for Python has an Observable Timing Discrepancy on servers when HTTP Basic Authentication is enabled with basic_auth_protocol_factory(credentials=...). An attacker may be able to guess a password via a timing attack.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:H/Au:N/C:P/I:N/A:N","metrics":{"baseScore":2.6,"exploitabilityScore":5,"impactScore":2.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-33880","epss":0.00192,"percentile":0.41834,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"websockets","version":"7.0"}},"found":{"versionConstraint":"<9.1 (python)","vulnerabilityID":"GHSA-8ch4-58qp-g3mp"},"fix":{"suggestedVersion":"9.1"}}],"artifact":{"id":"5fb318a1c6777f26","name":"websockets","version":"7.0","type":"python","locations":[{"path":"/lib/python3.8/site-packages/websockets-7.0.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/websockets-7.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/websockets-7.0.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/websockets-7.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/websockets-7.0.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/websockets-7.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD"],"cpes":["cpe:2.3:a:aymeric_augustin_project:python-websockets:7.0:*:*:*:*:*:*:*","cpe:2.3:a:aymeric_augustin_project:python_websockets:7.0:*:*:*:*:*:*:*","cpe:2.3:a:aymeric_augustinproject:python-websockets:7.0:*:*:*:*:*:*:*","cpe:2.3:a:aymeric_augustinproject:python_websockets:7.0:*:*:*:*:*:*:*","cpe:2.3:a:aymeric_augustin_project:websockets:7.0:*:*:*:*:*:*:*","cpe:2.3:a:python-websockets:python-websockets:7.0:*:*:*:*:*:*:*","cpe:2.3:a:python-websockets:python_websockets:7.0:*:*:*:*:*:*:*","cpe:2.3:a:python_websockets:python-websockets:7.0:*:*:*:*:*:*:*","cpe:2.3:a:python_websockets:python_websockets:7.0:*:*:*:*:*:*:*","cpe:2.3:a:aymeric-augustin:python-websockets:7.0:*:*:*:*:*:*:*","cpe:2.3:a:aymeric-augustin:python_websockets:7.0:*:*:*:*:*:*:*","cpe:2.3:a:aymeric_augustin:python-websockets:7.0:*:*:*:*:*:*:*","cpe:2.3:a:aymeric_augustin:python_websockets:7.0:*:*:*:*:*:*:*","cpe:2.3:a:aymeric_augustinproject:websockets:7.0:*:*:*:*:*:*:*","cpe:2.3:a:python-websockets:websockets:7.0:*:*:*:*:*:*:*","cpe:2.3:a:python_websockets:websockets:7.0:*:*:*:*:*:*:*","cpe:2.3:a:websockets:python-websockets:7.0:*:*:*:*:*:*:*","cpe:2.3:a:websockets:python_websockets:7.0:*:*:*:*:*:*:*","cpe:2.3:a:aymeric-augustin:websockets:7.0:*:*:*:*:*:*:*","cpe:2.3:a:aymeric_augustin:websockets:7.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python-websockets:7.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python_websockets:7.0:*:*:*:*:*:*:*","cpe:2.3:a:websockets:websockets:7.0:*:*:*:*:*:*:*","cpe:2.3:a:python:websockets:7.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/websockets@7.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-77rm-9x9h-xj3g","dataSource":"https://github.com/advisories/GHSA-77rm-9x9h-xj3g","namespace":"github:language:python","severity":"High","urls":[],"description":"NULL Pointer Dereference in Protocol Buffers","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-22570","epss":0.00131,"percentile":0.33965,"date":"2025-06-03"}],"fix":{"versions":["3.15.0"],"state":"fixed"},"advisories":[],"risk":0.09824999999999999},"relatedVulnerabilities":[{"id":"CVE-2021-22570","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2021-22570","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.0","https://lists.debian.org/debian-lts-announce/2023/04/msg00019.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/3DVUZPALAQ34TQP6KFNLM4IZS6B32XSA/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/5PAGL5M2KGYPN3VEQCRJJE6NA7D5YG5X/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/BTRGBRC5KGCA4SK5MUNLPYJRAGXMBIYY/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/IFX6KPNOFHYD6L4XES5PCM3QNSKZBOTQ/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/KQJB6ZPRLKV6WCMX2PRRRQBFAOXFBK6B/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/MRWRAXAFR3JR7XCFWTHC2KALSZKWACCE/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NVTWVQRB5OCCTMKEQFY5MYED3DXDVSLP/","https://security.netapp.com/advisory/ntap-20220429-0005/","https://www.oracle.com/security-alerts/cpuapr2022.html","https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.0","https://lists.debian.org/debian-lts-announce/2023/04/msg00019.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/3DVUZPALAQ34TQP6KFNLM4IZS6B32XSA/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/5PAGL5M2KGYPN3VEQCRJJE6NA7D5YG5X/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/BTRGBRC5KGCA4SK5MUNLPYJRAGXMBIYY/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/IFX6KPNOFHYD6L4XES5PCM3QNSKZBOTQ/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/KQJB6ZPRLKV6WCMX2PRRRQBFAOXFBK6B/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/MRWRAXAFR3JR7XCFWTHC2KALSZKWACCE/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NVTWVQRB5OCCTMKEQFY5MYED3DXDVSLP/","https://security.netapp.com/advisory/ntap-20220429-0005/","https://www.oracle.com/security-alerts/cpuapr2022.html"],"description":"Nullptr dereference when a null char is present in a proto symbol. The symbol is parsed incorrectly, leading to an unchecked call into the proto file's name during generation of the resulting error message. Since the symbol is incorrectly parsed, the file is nullptr. We recommend upgrading to version 3.15.0 or greater.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:L/AC:L/Au:N/C:N/I:N/A:P","metrics":{"baseScore":2.1,"exploitabilityScore":4,"impactScore":2.9},"vendorMetadata":{}},{"source":"cve-coordination@google.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":6.5,"exploitabilityScore":2.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-22570","epss":0.00131,"percentile":0.33965,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"protobuf","version":"3.14.0"}},"found":{"versionConstraint":"<3.15.0 (python)","vulnerabilityID":"GHSA-77rm-9x9h-xj3g"},"fix":{"suggestedVersion":"3.15.0"}}],"artifact":{"id":"3bbb5ef81324b056","name":"protobuf","version":"3.14.0","type":"python","locations":[{"path":"/lib/python3.8/site-packages/protobuf-3.14.0.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/protobuf-3.14.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/protobuf-3.14.0.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/protobuf-3.14.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/protobuf-3.14.0.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/protobuf-3.14.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["3-Clause BSD License"],"cpes":["cpe:2.3:a:google:protobuf-python:3.14.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/protobuf@3.14.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-xqr8-7jwr-rhp7","dataSource":"https://github.com/advisories/GHSA-xqr8-7jwr-rhp7","namespace":"github:language:python","severity":"High","urls":[],"description":"Removal of e-Tugra root certificate","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-37920","epss":0.00112,"percentile":0.30835,"date":"2025-06-03"}],"fix":{"versions":["2023.7.22"],"state":"fixed"},"advisories":[],"risk":0.08399999999999999},"relatedVulnerabilities":[{"id":"CVE-2023-37920","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-37920","namespace":"nvd:cpe","severity":"Critical","urls":["https://github.com/certifi/python-certifi/commit/8fb96ed81f71e7097ed11bc4d9b19afd7ea5c909","https://github.com/certifi/python-certifi/security/advisories/GHSA-xqr8-7jwr-rhp7","https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/C-HrP1SEq1A","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5EX6NG7WUFNUKGFHLM35KHHU3GAKXRTG/","https://github.com/certifi/python-certifi/commit/8fb96ed81f71e7097ed11bc4d9b19afd7ea5c909","https://github.com/certifi/python-certifi/security/advisories/GHSA-xqr8-7jwr-rhp7","https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/C-HrP1SEq1A","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5EX6NG7WUFNUKGFHLM35KHHU3GAKXRTG/","https://security.netapp.com/advisory/ntap-20240912-0002/"],"description":"Certifi is a curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts. Certifi prior to version 2023.07.22 recognizes \"e-Tugra\" root certificates. e-Tugra's root certificates were subject to an investigation prompted by reporting of security issues in their systems. Certifi 2023.07.22 removes root certificates from \"e-Tugra\" from the root store.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":9.8,"exploitabilityScore":3.9,"impactScore":5.9},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-37920","epss":0.00112,"percentile":0.30835,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"certifi","version":"2020.11.8"}},"found":{"versionConstraint":">=2015.4.28,<2023.7.22 (python)","vulnerabilityID":"GHSA-xqr8-7jwr-rhp7"},"fix":{"suggestedVersion":"2023.7.22"}}],"artifact":{"id":"ab9a4d1e157d99f0","name":"certifi","version":"2020.11.8","type":"python","locations":[{"path":"/lib/python3.8/site-packages/certifi-2020.11.8.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/certifi-2020.11.8.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/certifi-2020.11.8.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/certifi-2020.11.8.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/certifi-2020.11.8.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/certifi-2020.11.8.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MPL-2.0"],"cpes":["cpe:2.3:a:certifi:certifi:2020.11.8:*:*:*:*:python:*:*"],"purl":"pkg:pypi/certifi@2020.11.8","upstreams":[]}},{"vulnerability":{"id":"GHSA-8gq9-2x98-w8hf","dataSource":"https://github.com/advisories/GHSA-8gq9-2x98-w8hf","namespace":"github:language:python","severity":"High","urls":[],"description":"protobuf-cpp and protobuf-python have potential Denial of Service issue","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-1941","epss":0.0011,"percentile":0.30551,"date":"2025-06-03"}],"fix":{"versions":["3.18.3"],"state":"fixed"},"advisories":[],"risk":0.0825},"relatedVulnerabilities":[{"id":"CVE-2022-1941","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2022-1941","namespace":"nvd:cpe","severity":"High","urls":["http://www.openwall.com/lists/oss-security/2022/09/27/1","https://cloud.google.com/support/bulletins#GCP-2022-019","https://github.com/protocolbuffers/protobuf/security/advisories/GHSA-8gq9-2x98-w8hf","https://lists.debian.org/debian-lts-announce/2023/04/msg00019.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/CBAUKJQL6O4TIWYBENORSY5P43TVB4M3/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/MPCGUT3T5L6C3IDWUPSUO22QDCGQKTOP/","https://security.netapp.com/advisory/ntap-20240705-0001/","http://www.openwall.com/lists/oss-security/2022/09/27/1","https://cloud.google.com/support/bulletins#GCP-2022-019","https://github.com/protocolbuffers/protobuf/security/advisories/GHSA-8gq9-2x98-w8hf","https://lists.debian.org/debian-lts-announce/2023/04/msg00019.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/CBAUKJQL6O4TIWYBENORSY5P43TVB4M3/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/MPCGUT3T5L6C3IDWUPSUO22QDCGQKTOP/","https://security.netapp.com/advisory/ntap-20240705-0001/"],"description":"A parsing vulnerability for the MessageSet type in the ProtocolBuffers versions prior to and including 3.16.1, 3.17.3, 3.18.2, 3.19.4, 3.20.1 and 3.21.5 for protobuf-cpp, and versions prior to and including 3.16.1, 3.17.3, 3.18.2, 3.19.4, 3.20.1 and 4.21.5 for protobuf-python can lead to out of memory failures. A specially crafted message with multiple key-value per elements creates parsing issues, and can lead to a Denial of Service against services receiving unsanitized input. We recommend upgrading to versions 3.18.3, 3.19.5, 3.20.2, 3.21.6 for protobuf-cpp and 3.18.3, 3.19.5, 3.20.2, 4.21.6 for protobuf-python. Versions for 3.16 and 3.17 are no longer updated.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-1941","epss":0.0011,"percentile":0.30551,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"protobuf","version":"3.14.0"}},"found":{"versionConstraint":"<3.18.3 (python)","vulnerabilityID":"GHSA-8gq9-2x98-w8hf"},"fix":{"suggestedVersion":"3.18.3"}}],"artifact":{"id":"3bbb5ef81324b056","name":"protobuf","version":"3.14.0","type":"python","locations":[{"path":"/lib/python3.8/site-packages/protobuf-3.14.0.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/protobuf-3.14.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/protobuf-3.14.0.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/protobuf-3.14.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/protobuf-3.14.0.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/protobuf-3.14.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["3-Clause BSD License"],"cpes":["cpe:2.3:a:google:protobuf-python:3.14.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/protobuf@3.14.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-qwmp-2cf2-g9g6","dataSource":"https://github.com/advisories/GHSA-qwmp-2cf2-g9g6","namespace":"github:language:python","severity":"High","urls":[],"description":"pypa/wheel vulnerable to Regular Expression denial of service (ReDoS)","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-40898","epss":0.00108,"percentile":0.30278,"date":"2025-06-03"}],"fix":{"versions":["0.38.1"],"state":"fixed"},"advisories":[],"risk":0.08099999999999999},"relatedVulnerabilities":[{"id":"CVE-2022-40898","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2022-40898","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pypa/wheel/blob/main/src/wheel/wheelfile.py#L18","https://pypi.org/project/wheel/","https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/","https://github.com/pypa/wheel/blob/main/src/wheel/wheelfile.py#L18","https://pypi.org/project/wheel/","https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/"],"description":"An issue discovered in Python Packaging Authority (PyPA) Wheel 0.37.1 and earlier allows remote attackers to cause a denial of service via attacker controlled input to wheel cli.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-40898","epss":0.00108,"percentile":0.30278,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"wheel","version":"0.36.0"}},"found":{"versionConstraint":"<0.38.1 (python)","vulnerabilityID":"GHSA-qwmp-2cf2-g9g6"},"fix":{"suggestedVersion":"0.38.1"}}],"artifact":{"id":"11491dff771c4fe3","name":"wheel","version":"0.36.0","type":"python","locations":[{"path":"/lib/python3.8/site-packages/wheel-0.36.0.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/wheel-0.36.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/wheel-0.36.0.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/wheel-0.36.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/wheel-0.36.0.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/wheel-0.36.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:daniel_holth_project:python-wheel:0.36.0:*:*:*:*:*:*:*","cpe:2.3:a:daniel_holth_project:python_wheel:0.36.0:*:*:*:*:*:*:*","cpe:2.3:a:daniel_holthproject:python-wheel:0.36.0:*:*:*:*:*:*:*","cpe:2.3:a:daniel_holthproject:python_wheel:0.36.0:*:*:*:*:*:*:*","cpe:2.3:a:dholth_project:python-wheel:0.36.0:*:*:*:*:*:*:*","cpe:2.3:a:dholth_project:python_wheel:0.36.0:*:*:*:*:*:*:*","cpe:2.3:a:daniel_holth_project:wheel:0.36.0:*:*:*:*:*:*:*","cpe:2.3:a:dholthproject:python-wheel:0.36.0:*:*:*:*:*:*:*","cpe:2.3:a:dholthproject:python_wheel:0.36.0:*:*:*:*:*:*:*","cpe:2.3:a:daniel_holth:python-wheel:0.36.0:*:*:*:*:*:*:*","cpe:2.3:a:daniel_holth:python_wheel:0.36.0:*:*:*:*:*:*:*","cpe:2.3:a:daniel_holthproject:wheel:0.36.0:*:*:*:*:*:*:*","cpe:2.3:a:python-wheel:python-wheel:0.36.0:*:*:*:*:*:*:*","cpe:2.3:a:python-wheel:python_wheel:0.36.0:*:*:*:*:*:*:*","cpe:2.3:a:python_wheel:python-wheel:0.36.0:*:*:*:*:*:*:*","cpe:2.3:a:python_wheel:python_wheel:0.36.0:*:*:*:*:*:*:*","cpe:2.3:a:dholth_project:wheel:0.36.0:*:*:*:*:*:*:*","cpe:2.3:a:dholth:python-wheel:0.36.0:*:*:*:*:*:*:*","cpe:2.3:a:dholth:python_wheel:0.36.0:*:*:*:*:*:*:*","cpe:2.3:a:dholthproject:wheel:0.36.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python-wheel:0.36.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python_wheel:0.36.0:*:*:*:*:*:*:*","cpe:2.3:a:daniel_holth:wheel:0.36.0:*:*:*:*:*:*:*","cpe:2.3:a:python-wheel:wheel:0.36.0:*:*:*:*:*:*:*","cpe:2.3:a:python_wheel:wheel:0.36.0:*:*:*:*:*:*:*","cpe:2.3:a:wheel:python-wheel:0.36.0:*:*:*:*:*:*:*","cpe:2.3:a:wheel:python_wheel:0.36.0:*:*:*:*:*:*:*","cpe:2.3:a:dholth:wheel:0.36.0:*:*:*:*:*:*:*","cpe:2.3:a:python:wheel:0.36.0:*:*:*:*:*:*:*","cpe:2.3:a:wheel:wheel:0.36.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/wheel@0.36.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-5phf-pp7p-vc2r","dataSource":"https://github.com/advisories/GHSA-5phf-pp7p-vc2r","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Using default SSLContext for HTTPS requests in an HTTPS proxy doesn't verify certificate hostname for proxy connection","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N","metrics":{"baseScore":6.5,"exploitabilityScore":3.9,"impactScore":2.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-28363","epss":0.00134,"percentile":0.34454,"date":"2025-06-03"}],"fix":{"versions":["1.26.4"],"state":"fixed"},"advisories":[],"risk":0.07705},"relatedVulnerabilities":[{"id":"CVE-2021-28363","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2021-28363","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/urllib3/urllib3/commit/8d65ea1ecf6e2cdc27d42124e587c1b83a3118b0","https://github.com/urllib3/urllib3/commits/main","https://github.com/urllib3/urllib3/security/advisories/GHSA-5phf-pp7p-vc2r","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4S65ZQVZ2ODGB52IC7VJDBUK4M5INCXL/","https://pypi.org/project/urllib3/1.26.4/","https://security.gentoo.org/glsa/202107-36","https://security.gentoo.org/glsa/202305-02","https://security.netapp.com/advisory/ntap-20240621-0007/","https://www.oracle.com/security-alerts/cpuoct2021.html","https://github.com/urllib3/urllib3/commit/8d65ea1ecf6e2cdc27d42124e587c1b83a3118b0","https://github.com/urllib3/urllib3/commits/main","https://github.com/urllib3/urllib3/security/advisories/GHSA-5phf-pp7p-vc2r","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4S65ZQVZ2ODGB52IC7VJDBUK4M5INCXL/","https://pypi.org/project/urllib3/1.26.4/","https://security.gentoo.org/glsa/202107-36","https://security.gentoo.org/glsa/202305-02","https://security.netapp.com/advisory/ntap-20240621-0007/","https://www.oracle.com/security-alerts/cpuoct2021.html"],"description":"The urllib3 library 1.26.x before 1.26.4 for Python omits SSL certificate validation in some cases involving HTTPS to HTTPS proxies. The initial connection to the HTTPS proxy (if an SSLContext isn't given via proxy_config) doesn't verify the hostname of the certificate. This means certificates for different servers that still validate properly with the default urllib3 SSLContext will be silently accepted.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N","metrics":{"baseScore":6.5,"exploitabilityScore":3.9,"impactScore":2.6},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:L/Au:N/C:P/I:P/A:N","metrics":{"baseScore":6.4,"exploitabilityScore":10,"impactScore":5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-28363","epss":0.00134,"percentile":0.34454,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"urllib3","version":"1.26.2"}},"found":{"versionConstraint":">=1.26.0,<1.26.4 (python)","vulnerabilityID":"GHSA-5phf-pp7p-vc2r"},"fix":{"suggestedVersion":"1.26.4"}}],"artifact":{"id":"a9c3d78ade6ae399","name":"urllib3","version":"1.26.2","type":"python","locations":[{"path":"/lib/python3.8/site-packages/urllib3-1.26.2.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/urllib3-1.26.2.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/urllib3-1.26.2.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/urllib3-1.26.2.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/urllib3-1.26.2.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/urllib3-1.26.2.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:urllib3:1.26.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/urllib3@1.26.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-9v9h-cgj8-h64p","dataSource":"https://github.com/advisories/GHSA-9v9h-cgj8-h64p","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Null pointer dereference in PKCS12 parsing","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-0727","epss":0.00103,"percentile":0.29443,"date":"2025-06-03"}],"fix":{"versions":["42.0.2"],"state":"fixed"},"advisories":[],"risk":0.05407500000000001},"relatedVulnerabilities":[{"id":"CVE-2024-0727","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-0727","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/openssl/openssl/commit/09df4395b5071217b76dc7d3d2e630eb8c5a79c2","https://github.com/openssl/openssl/commit/775acfdbd0c6af9ac855f34969cdab0c0c90844a","https://github.com/openssl/openssl/commit/d135eeab8a5dbf72b3da5240bab9ddb7678dbd2c","https://github.openssl.org/openssl/extended-releases/commit/03b3941d60c4bce58fab69a0c22377ab439bc0e8","https://github.openssl.org/openssl/extended-releases/commit/aebaa5883e31122b404e450732dc833dc9dee539","https://www.openssl.org/news/secadv/20240125.txt","http://www.openwall.com/lists/oss-security/2024/03/11/1","https://github.com/openssl/openssl/commit/09df4395b5071217b76dc7d3d2e630eb8c5a79c2","https://github.com/openssl/openssl/commit/775acfdbd0c6af9ac855f34969cdab0c0c90844a","https://github.com/openssl/openssl/commit/d135eeab8a5dbf72b3da5240bab9ddb7678dbd2c","https://github.openssl.org/openssl/extended-releases/commit/03b3941d60c4bce58fab69a0c22377ab439bc0e8","https://github.openssl.org/openssl/extended-releases/commit/aebaa5883e31122b404e450732dc833dc9dee539","https://security.netapp.com/advisory/ntap-20240208-0006/","https://www.openssl.org/news/secadv/20240125.txt"],"description":"Issue summary: Processing a maliciously formatted PKCS12 file may lead OpenSSL\nto crash leading to a potential Denial of Service attack\n\nImpact summary: Applications loading files in the PKCS12 format from untrusted\nsources might terminate abruptly.\n\nA file in PKCS12 format can contain certificates and keys and may come from an\nuntrusted source. The PKCS12 specification allows certain fields to be NULL, but\nOpenSSL does not correctly check for this case. This can lead to a NULL pointer\ndereference that results in OpenSSL crashing. If an application processes PKCS12\nfiles from an untrusted source using the OpenSSL APIs then that application will\nbe vulnerable to this issue.\n\nOpenSSL APIs that are vulnerable to this are: PKCS12_parse(),\nPKCS12_unpack_p7data(), PKCS12_unpack_p7encdata(), PKCS12_unpack_authsafes()\nand PKCS12_newpass().\n\nWe have also fixed a similar issue in SMIME_write_PKCS7(). However since this\nfunction is related to writing data we do not consider it security significant.\n\nThe FIPS modules in 3.2, 3.1 and 3.0 are not affected by this issue.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-0727","epss":0.00103,"percentile":0.29443,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"3.2.1"}},"found":{"versionConstraint":"<42.0.2 (python)","vulnerabilityID":"GHSA-9v9h-cgj8-h64p"},"fix":{"suggestedVersion":"42.0.2"}}],"artifact":{"id":"45a2789cece8d69f","name":"cryptography","version":"3.2.1","type":"python","locations":[{"path":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD or Apache License, Version 2.0"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:3.2.1:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:3.2.1:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@3.2.1","upstreams":[]}},{"vulnerability":{"id":"GHSA-g4mx-q9vg-27p4","dataSource":"https://github.com/advisories/GHSA-g4mx-q9vg-27p4","namespace":"github:language:python","severity":"Medium","urls":[],"description":"urllib3's request body not stripped after redirect from 303 status changes request method to GET","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.2,"exploitabilityScore":0.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-45803","epss":0.00062,"percentile":0.1968,"date":"2025-06-03"}],"fix":{"versions":["1.26.18"],"state":"fixed"},"advisories":[],"risk":0.02852},"relatedVulnerabilities":[{"id":"CVE-2023-45803","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-45803","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/urllib3/urllib3/commit/4e98d57809dacab1cbe625fddeec1a290c478ea9","https://github.com/urllib3/urllib3/security/advisories/GHSA-g4mx-q9vg-27p4","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4R2Y5XK3WALSR3FNAGN7JBYV2B343ZKB/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PPDPLM6UUMN55ESPQWJFLLIZY4ZKCNRX/","https://www.rfc-editor.org/rfc/rfc9110.html#name-get","https://github.com/urllib3/urllib3/commit/4e98d57809dacab1cbe625fddeec1a290c478ea9","https://github.com/urllib3/urllib3/security/advisories/GHSA-g4mx-q9vg-27p4","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4R2Y5XK3WALSR3FNAGN7JBYV2B343ZKB/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PPDPLM6UUMN55ESPQWJFLLIZY4ZKCNRX/","https://www.rfc-editor.org/rfc/rfc9110.html#name-get"],"description":"urllib3 is a user-friendly HTTP client library for Python. urllib3 previously wouldn't remove the HTTP request body when an HTTP redirect response using status 301, 302, or 303 after the request had its method changed from one that could accept a request body (like `POST`) to `GET` as is required by HTTP RFCs. Although this behavior is not specified in the section for redirects, it can be inferred by piecing together information from different sections and we have observed the behavior in other major HTTP client implementations like curl and web browsers. Because the vulnerability requires a previously trusted service to become compromised in order to have an impact on confidentiality we believe the exploitability of this vulnerability is low. Additionally, many users aren't putting sensitive data in HTTP request bodies, if this is the case then this vulnerability isn't exploitable. Both of the following conditions must be true to be affected by this vulnerability: 1. Using urllib3 and submitting sensitive information in the HTTP request body (such as form data or JSON) and 2. The origin service is compromised and starts redirecting using 301, 302, or 303 to a malicious peer or the redirected-to service becomes compromised. This issue has been addressed in versions 1.26.18 and 2.0.7 and users are advised to update to resolve this issue. Users unable to update should disable redirects for services that aren't expecting to respond with redirects with `redirects=False` and disable automatic redirects with `redirects=False` and handle 301, 302, and 303 redirects manually by stripping the HTTP request body.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.2,"exploitabilityScore":0.6,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.2,"exploitabilityScore":0.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-45803","epss":0.00062,"percentile":0.1968,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"urllib3","version":"1.26.2"}},"found":{"versionConstraint":">=0,<1.26.18 (python)","vulnerabilityID":"GHSA-g4mx-q9vg-27p4"},"fix":{"suggestedVersion":"1.26.18"}}],"artifact":{"id":"a9c3d78ade6ae399","name":"urllib3","version":"1.26.2","type":"python","locations":[{"path":"/lib/python3.8/site-packages/urllib3-1.26.2.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/urllib3-1.26.2.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/urllib3-1.26.2.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/urllib3-1.26.2.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/urllib3-1.26.2.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/urllib3-1.26.2.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:urllib3:1.26.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/urllib3@1.26.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-43fp-rhv2-5gv8","dataSource":"https://github.com/advisories/GHSA-43fp-rhv2-5gv8","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Certifi removing TrustCor root certificate","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:C/C:N/I:H/A:N","metrics":{"baseScore":6.8,"exploitabilityScore":2.3,"impactScore":4},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-23491","epss":0.00038,"percentile":0.10381,"date":"2025-06-03"}],"fix":{"versions":["2022.12.07"],"state":"fixed"},"advisories":[],"risk":0.02242},"relatedVulnerabilities":[{"id":"CVE-2022-23491","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2022-23491","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/certifi/python-certifi/security/advisories/GHSA-43fp-rhv2-5gv8","https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/oxX69KFvsm4/m/yLohoVqtCgAJ","https://github.com/certifi/python-certifi/security/advisories/GHSA-43fp-rhv2-5gv8","https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/oxX69KFvsm4/m/yLohoVqtCgAJ","https://security.netapp.com/advisory/ntap-20230223-0010/"],"description":"Certifi is a curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts. Certifi 2022.12.07 removes root certificates from \"TrustCor\" from the root store. These are in the process of being removed from Mozilla's trust store. TrustCor's root certificates are being removed pursuant to an investigation prompted by media reporting that TrustCor's ownership also operated a business that produced spyware. Conclusions of Mozilla's investigation can be found in the linked google group discussion.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:C/C:N/I:H/A:N","metrics":{"baseScore":6.8,"exploitabilityScore":2.3,"impactScore":4},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-23491","epss":0.00038,"percentile":0.10381,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"certifi","version":"2020.11.8"}},"found":{"versionConstraint":">=2017.11.05,<2022.12.07 (python)","vulnerabilityID":"GHSA-43fp-rhv2-5gv8"},"fix":{"suggestedVersion":"2022.12.07"}}],"artifact":{"id":"ab9a4d1e157d99f0","name":"certifi","version":"2020.11.8","type":"python","locations":[{"path":"/lib/python3.8/site-packages/certifi-2020.11.8.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/certifi-2020.11.8.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/certifi-2020.11.8.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/certifi-2020.11.8.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/certifi-2020.11.8.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/certifi-2020.11.8.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MPL-2.0"],"cpes":["cpe:2.3:a:certifi:certifi:2020.11.8:*:*:*:*:python:*:*"],"purl":"pkg:pypi/certifi@2020.11.8","upstreams":[]}},{"vulnerability":{"id":"GHSA-mq26-g339-26xf","dataSource":"https://github.com/advisories/GHSA-mq26-g339-26xf","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Command Injection in pip when used with Mercurial","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-5752","epss":0.0004,"percentile":0.11691,"date":"2025-06-03"}],"fix":{"versions":["23.3"],"state":"fixed"},"advisories":[],"risk":0.021},"relatedVulnerabilities":[{"id":"CVE-2023-5752","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-5752","namespace":"nvd:cpe","severity":"Low","urls":["https://github.com/pypa/pip/pull/12306","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/622OZXWG72ISQPLM5Y57YCVIMWHD4C3U/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/65UKKF5LBHEFDCUSPBHUN4IHYX7SRMHH/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FXUVMJM25PUAZRQZBF54OFVKTY3MINPW/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KFC2SPFG5FLCZBYY2K3T5MFW2D22NG6E/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YBSB3SUPQ3VIFYUMHPO3MEQI4BJAXKCZ/","https://mail.python.org/archives/list/security-announce@python.org/thread/F4PL35U6X4VVHZ5ILJU3PWUWN7H7LZXL/","https://github.com/pypa/pip/pull/12306","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/622OZXWG72ISQPLM5Y57YCVIMWHD4C3U/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/65UKKF5LBHEFDCUSPBHUN4IHYX7SRMHH/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FXUVMJM25PUAZRQZBF54OFVKTY3MINPW/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KFC2SPFG5FLCZBYY2K3T5MFW2D22NG6E/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YBSB3SUPQ3VIFYUMHPO3MEQI4BJAXKCZ/","https://mail.python.org/archives/list/security-announce@python.org/thread/F4PL35U6X4VVHZ5ILJU3PWUWN7H7LZXL/"],"description":"When installing a package from a Mercurial VCS URL  (ie \"pip install \nhg+...\") with pip prior to v23.3, the specified Mercurial revision could\n be used to inject arbitrary configuration options to the \"hg clone\" \ncall (ie \"--config\"). Controlling the Mercurial configuration can modify\n how and which repository is installed. This vulnerability does not \naffect users who aren't installing from Mercurial.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:N","metrics":{"baseScore":3.3,"exploitabilityScore":1.9,"impactScore":1.5},"vendorMetadata":{}},{"source":"cna@python.org","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-5752","epss":0.0004,"percentile":0.11691,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"pip","version":"20.0.2"}},"found":{"versionConstraint":"<23.3 (python)","vulnerabilityID":"GHSA-mq26-g339-26xf"},"fix":{"suggestedVersion":"23.3"}}],"artifact":{"id":"e82731344f755f57","name":"pip","version":"20.0.2","type":"python","locations":[{"path":"/lib/python3.8/site-packages/pip-20.0.2.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/pip-20.0.2.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/pip-20.0.2.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/pip-20.0.2.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/pip-20.0.2.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/pip-20.0.2.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:pip_developers_project:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers_project:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev_project:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev_project:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers_project:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_devproject:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_devproject:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev_project:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa-dev:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa-dev:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_devproject:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa-dev:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip:pip:20.0.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/pip@20.0.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-34jh-p97f-mpxf","dataSource":"https://github.com/advisories/GHSA-34jh-p97f-mpxf","namespace":"github:language:python","severity":"Medium","urls":[],"description":"urllib3's Proxy-Authorization request header isn't stripped during cross-origin redirects","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.4,"exploitabilityScore":0.8,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-37891","epss":0.00033,"percentile":0.08049,"date":"2025-06-03"}],"fix":{"versions":["1.26.19"],"state":"fixed"},"advisories":[],"risk":0.01551},"relatedVulnerabilities":[{"id":"CVE-2024-37891","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-37891","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/urllib3/urllib3/commit/accff72ecc2f6cf5a76d9570198a93ac7c90270e","https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf","https://github.com/urllib3/urllib3/commit/accff72ecc2f6cf5a76d9570198a93ac7c90270e","https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf","https://security.netapp.com/advisory/ntap-20240822-0003/","https://www.vicarius.io/vsociety/posts/proxy-authorization-header-handling-vulnerability-in-urllib3-cve-2024-37891"],"description":"urllib3 is a user-friendly HTTP client library for Python. When using urllib3's proxy support with `ProxyManager`, the `Proxy-Authorization` header is only sent to the configured proxy, as expected. However, when sending HTTP requests *without* using urllib3's proxy support, it's possible to accidentally configure the `Proxy-Authorization` header even though it won't have any effect as the request is not using a forwarding proxy or a tunneling proxy. In those cases, urllib3 doesn't treat the `Proxy-Authorization` HTTP header as one carrying authentication material and thus doesn't strip the header on cross-origin redirects. Because this is a highly unlikely scenario, we believe the severity of this vulnerability is low for almost all users. Out of an abundance of caution urllib3 will automatically strip the `Proxy-Authorization` header during cross-origin redirects to avoid the small chance that users are doing this on accident. Users should use urllib3's proxy support or disable automatic redirects to achieve safe processing of the `Proxy-Authorization` header, but we still decided to strip the header by default in order to further protect users who aren't using the correct approach. We believe the number of usages affected by this advisory is low. It requires all of the following to be true to be exploited: 1. Setting the `Proxy-Authorization` header without using urllib3's built-in proxy support. 2. Not disabling HTTP redirects. 3. Either not using an HTTPS origin server or for the proxy or target origin to redirect to a malicious origin. Users are advised to update to either version 1.26.19 or version 2.2.2. Users unable to upgrade may use the `Proxy-Authorization` header with urllib3's `ProxyManager`, disable HTTP redirects using `redirects=False` when sending requests, or not user the `Proxy-Authorization` header as mitigations.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.4,"exploitabilityScore":0.8,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-37891","epss":0.00033,"percentile":0.08049,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"urllib3","version":"1.26.2"}},"found":{"versionConstraint":"<1.26.19 (python)","vulnerabilityID":"GHSA-34jh-p97f-mpxf"},"fix":{"suggestedVersion":"1.26.19"}}],"artifact":{"id":"a9c3d78ade6ae399","name":"urllib3","version":"1.26.2","type":"python","locations":[{"path":"/lib/python3.8/site-packages/urllib3-1.26.2.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/urllib3-1.26.2.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/urllib3-1.26.2.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/urllib3-1.26.2.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/urllib3-1.26.2.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/urllib3-1.26.2.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:urllib3:1.26.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/urllib3@1.26.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-9wx4-h78v-vm56","dataSource":"https://github.com/advisories/GHSA-9wx4-h78v-vm56","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Requests `Session` object does not verify requests after making first request with verify=False","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N","metrics":{"baseScore":5.6,"exploitabilityScore":0.4,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-35195","epss":0.00009,"percentile":0.00549,"date":"2025-06-03"}],"fix":{"versions":["2.32.0"],"state":"fixed"},"advisories":[],"risk":0.004770000000000001},"relatedVulnerabilities":[{"id":"CVE-2024-35195","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-35195","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac","https://github.com/psf/requests/pull/6655","https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ/","https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac","https://github.com/psf/requests/pull/6655","https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ/"],"description":"Requests is a HTTP library. Prior to 2.32.0, when making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same host will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool. This vulnerability is fixed in 2.32.0.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N","metrics":{"baseScore":5.6,"exploitabilityScore":0.4,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-35195","epss":0.00009,"percentile":0.00549,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"requests","version":"2.25.0"}},"found":{"versionConstraint":"<2.32.0 (python)","vulnerabilityID":"GHSA-9wx4-h78v-vm56"},"fix":{"suggestedVersion":"2.32.0"}}],"artifact":{"id":"a823a315c8146163","name":"requests","version":"2.25.0","type":"python","locations":[{"path":"/lib/python3.8/site-packages/requests-2.25.0.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/requests-2.25.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/requests-2.25.0.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/requests-2.25.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/requests-2.25.0.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/requests-2.25.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache 2.0"],"cpes":["cpe:2.3:a:python:requests:2.25.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/requests@2.25.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-5cpq-8wj7-hf2v","dataSource":"https://github.com/advisories/GHSA-5cpq-8wj7-hf2v","namespace":"github:language:python","severity":"Low","urls":[],"description":"Vulnerable OpenSSL included in cryptography wheels","cvss":[],"fix":{"versions":["41.0.0"],"state":"fixed"},"advisories":[],"risk":0},"relatedVulnerabilities":[],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"3.2.1"}},"found":{"versionConstraint":">=0.5,<=40.0.2 (python)","vulnerabilityID":"GHSA-5cpq-8wj7-hf2v"},"fix":{"suggestedVersion":"41.0.0"}}],"artifact":{"id":"45a2789cece8d69f","name":"cryptography","version":"3.2.1","type":"python","locations":[{"path":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD or Apache License, Version 2.0"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:3.2.1:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:3.2.1:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@3.2.1","upstreams":[]}},{"vulnerability":{"id":"GHSA-jm77-qphf-c4w8","dataSource":"https://github.com/advisories/GHSA-jm77-qphf-c4w8","namespace":"github:language:python","severity":"Low","urls":[],"description":"pyca/cryptography's wheels include vulnerable OpenSSL","cvss":[],"fix":{"versions":["41.0.3"],"state":"fixed"},"advisories":[],"risk":0},"relatedVulnerabilities":[],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"3.2.1"}},"found":{"versionConstraint":">=0.8,<41.0.3 (python)","vulnerabilityID":"GHSA-jm77-qphf-c4w8"},"fix":{"suggestedVersion":"41.0.3"}}],"artifact":{"id":"45a2789cece8d69f","name":"cryptography","version":"3.2.1","type":"python","locations":[{"path":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD or Apache License, Version 2.0"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:3.2.1:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:3.2.1:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@3.2.1","upstreams":[]}},{"vulnerability":{"id":"GHSA-v8gr-m533-ghj9","dataSource":"https://github.com/advisories/GHSA-v8gr-m533-ghj9","namespace":"github:language:python","severity":"Low","urls":[],"description":"Vulnerable OpenSSL included in cryptography wheels","cvss":[],"fix":{"versions":["41.0.4"],"state":"fixed"},"advisories":[],"risk":0},"relatedVulnerabilities":[],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"3.2.1"}},"found":{"versionConstraint":">=2.5,<41.0.4 (python)","vulnerabilityID":"GHSA-v8gr-m533-ghj9"},"fix":{"suggestedVersion":"41.0.4"}}],"artifact":{"id":"45a2789cece8d69f","name":"cryptography","version":"3.2.1","type":"python","locations":[{"path":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/METADATA","accessPath":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/RECORD","accessPath":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/top_level.txt","accessPath":"/lib/python3.8/site-packages/cryptography-3.2.1.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD or Apache License, Version 2.0"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:3.2.1:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:3.2.1:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@3.2.1","upstreams":[]}}],"source":{"type":"sbom-file","target":"governor-broker-syft.json"},"distro":{"name":"","version":"","idLike":null},"descriptor":{"name":"grype","version":"0.92.2","configuration":{"output":["json=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-06-04/governor-broker-grype.json","template=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-06-04/governor-broker-grype.html"],"file":"","pretty":false,"distro":"","add-cpes-if-none":false,"output-template-file":"../html.tmpl","check-for-app-update":true,"only-fixed":false,"only-notfixed":false,"ignore-wontfix":"","platform":"","search":{"scope":"squashed","unindexed-archives":false,"indexed-archives":true},"ignore":[{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"kernel-headers","version":"","language":"","type":"rpm","location":"","upstream-name":"kernel"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux(-.*)?-headers-.*","version":"","language":"","type":"deb","location":"","upstream-name":"linux.*"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux-libc-dev","version":"","language":"","type":"deb","location":"","upstream-name":"linux"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"}],"exclude":[],"externalSources":{"enable":false,"maven":{"searchUpstreamBySha1":true,"baseUrl":"https://search.maven.org/solrsearch/select","rateLimit":300000000}},"match":{"java":{"using-cpes":false},"jvm":{"using-cpes":true},"dotnet":{"using-cpes":false},"golang":{"using-cpes":false,"always-use-cpe-for-stdlib":true,"allow-main-module-pseudo-version-comparison":false},"javascript":{"using-cpes":false},"python":{"using-cpes":false},"ruby":{"using-cpes":false},"rust":{"using-cpes":false},"stock":{"using-cpes":true}},"fail-on-severity":"","registry":{"insecure-skip-tls-verify":false,"insecure-use-http":false,"auth":null,"ca-cert":""},"show-suppressed":false,"by-cve":false,"SortBy":{"sort-by":"risk"},"name":"","default-image-pull-source":"","vex-documents":[],"vex-add":[],"match-upstream-kernel-headers":false,"db":{"cache-dir":"/Users/alan/Library/Caches/grype/db","update-url":"https://grype.anchore.io/databases","ca-cert":"","auto-update":true,"validate-by-hash-on-start":true,"validate-age":true,"max-allowed-built-age":432000000000000,"require-update-check":false,"update-available-timeout":30000000000,"update-download-timeout":300000000000,"max-update-check-frequency":7200000000000},"exp":{},"dev":{"db":{"debug":false}}},"db":{"status":{"schemaVersion":"v6.0.2","from":"https://grype.anchore.io/databases/v6/vulnerability-db_v6.0.2_2025-06-04T01:32:23Z_1749035557.tar.zst?checksum=sha256%3A77238f4ffbc7cf72bf4dedabbb21a3d0dd3ade90fb5d9df7c4da2870f8d1a9b7","built":"2025-06-04T11:12:37Z","path":"/Users/alan/Library/Caches/grype/db/6/vulnerability.db","valid":true},"providers":{"alpine":{"captured":"2025-06-04T01:32:23Z","input":"xxh64:a6a065ece392f6d1"},"amazon":{"captured":"2025-06-04T01:32:32Z","input":"xxh64:b65d458d6858d72a"},"chainguard":{"captured":"2025-06-04T01:32:33Z","input":"xxh64:03c9c4d182d77791"},"debian":{"captured":"2025-06-04T01:32:49Z","input":"xxh64:169ceb8fbcb8d6f1"},"epss":{"captured":"2025-06-04T01:32:42Z","input":"xxh64:bf87c4c234d02346"},"github":{"captured":"2025-06-04T01:32:30Z","input":"xxh64:3dab0be50635e057"},"kev":{"captured":"2025-06-04T01:32:45Z","input":"xxh64:a934e75f468f4e09"},"mariner":{"captured":"2025-06-04T01:32:43Z","input":"xxh64:ac698752085c186f"},"nvd":{"captured":"2025-06-04T01:33:28Z","input":"xxh64:389887843a59d29c"},"oracle":{"captured":"2025-06-04T01:32:35Z","input":"xxh64:0b8aabcfb6505b62"},"rhel":{"captured":"2025-06-04T04:49:10Z","input":"xxh64:947d0caeb19e9ccc"},"sles":{"captured":"2025-06-04T01:32:34Z","input":"xxh64:1c50b1219296628a"},"ubuntu":{"captured":"2025-06-04T01:33:14Z","input":"xxh64:71e22d5c5bbe7d14"},"wolfi":{"captured":"2025-06-04T01:32:42Z","input":"xxh64:e68fca5a870c6769"}}},"timestamp":"2025-06-04T19:22:41.078314+01:00"}}
