{"matches":[{"vulnerability":{"id":"GHSA-j7hp-h8jx-5ppr","dataSource":"https://github.com/advisories/GHSA-j7hp-h8jx-5ppr","namespace":"github:language:python","severity":"High","urls":[],"description":"libwebp: OOB write in BuildHuffmanTable","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.8,"exploitabilityScore":2.9,"impactScore":5.9},"vendorMetadata":{}}],"knownExploited":[{"cve":"CVE-2023-4863","vendorProject":"Google","product":"Chromium WebP","dateAdded":"2023-09-13","requiredAction":"Apply mitigations per vendor instructions or discontinue use of the product if mitigations are unavailable.","dueDate":"2023-10-04","knownRansomwareCampaignUse":"unknown","urls":["https://chromereleases.googleblog.com/2023/09/stable-channel-update-for-desktop_11.html?m=1","https://nvd.nist.gov/vuln/detail/CVE-2023-4863"],"cwes":["CWE-787"]}],"epss":[{"cve":"CVE-2023-4863","epss":0.93991,"percentile":0.99881,"date":"2025-06-03"}],"fix":{"versions":["10.0.1"],"state":"fixed"},"advisories":[],"risk":85.57500000000002},"relatedVulnerabilities":[{"id":"CVE-2023-4863","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-4863","namespace":"nvd:cpe","severity":"High","urls":["http://www.openwall.com/lists/oss-security/2023/09/21/4","http://www.openwall.com/lists/oss-security/2023/09/22/1","http://www.openwall.com/lists/oss-security/2023/09/22/3","http://www.openwall.com/lists/oss-security/2023/09/22/4","http://www.openwall.com/lists/oss-security/2023/09/22/5","http://www.openwall.com/lists/oss-security/2023/09/22/6","http://www.openwall.com/lists/oss-security/2023/09/22/7","http://www.openwall.com/lists/oss-security/2023/09/22/8","http://www.openwall.com/lists/oss-security/2023/09/26/1","http://www.openwall.com/lists/oss-security/2023/09/26/7","http://www.openwall.com/lists/oss-security/2023/09/28/1","http://www.openwall.com/lists/oss-security/2023/09/28/2","http://www.openwall.com/lists/oss-security/2023/09/28/4","https://adamcaudill.com/2023/09/14/whose-cve-is-it-anyway/","https://blog.isosceles.com/the-webp-0day/","https://bugzilla.suse.com/show_bug.cgi?id=1215231","https://chromereleases.googleblog.com/2023/09/stable-channel-update-for-desktop_11.html","https://crbug.com/1479274","https://en.bandisoft.com/honeyview/history/","https://github.com/webmproject/libwebp/commit/902bc9190331343b2017211debcec8d2ab87e17a","https://github.com/webmproject/libwebp/releases/tag/v1.3.2","https://lists.debian.org/debian-lts-announce/2023/09/msg00015.html","https://lists.debian.org/debian-lts-announce/2023/09/msg00016.html","https://lists.debian.org/debian-lts-announce/2023/09/msg00017.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6T655QF7CQ3DYAMPFV7IECQYGDEUIVVT/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FYYKLG6CRGEDTNRBSU26EEWAO6D6U645/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KUQ7CTX3W372X3UY56VVNAHCH6H2F4X3/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OZDGWWMJREPAGKWCJKSCM4WYLANSKIFX/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PYZV7TMKF4QHZ54SFJX54BDN52VHGGCX/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WHOLML7N2G5KCAZXFWC5IDFFHSQS5SDB/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WTRUIS3564P7ZLM2S2IH4Y4KZ327LI4I/","https://msrc.microsoft.com/update-guide/vulnerability/CVE-2023-4863","https://news.ycombinator.com/item?id=37478403","https://security-tracker.debian.org/tracker/CVE-2023-4863","https://security.gentoo.org/glsa/202309-05","https://security.gentoo.org/glsa/202401-10","https://security.netapp.com/advisory/ntap-20230929-0011/","https://sethmlarson.dev/security-developer-in-residence-weekly-report-16","https://stackdiary.com/critical-vulnerability-in-webp-codec-cve-2023-4863/","https://www.bentley.com/advisories/be-2023-0001/","https://www.bleepingcomputer.com/news/google/google-fixes-another-chrome-zero-day-bug-exploited-in-attacks/","https://www.debian.org/security/2023/dsa-5496","https://www.debian.org/security/2023/dsa-5497","https://www.debian.org/security/2023/dsa-5498","https://www.mozilla.org/en-US/security/advisories/mfsa2023-40/","http://www.openwall.com/lists/oss-security/2023/09/21/4","http://www.openwall.com/lists/oss-security/2023/09/22/1","http://www.openwall.com/lists/oss-security/2023/09/22/3","http://www.openwall.com/lists/oss-security/2023/09/22/4","http://www.openwall.com/lists/oss-security/2023/09/22/5","http://www.openwall.com/lists/oss-security/2023/09/22/6","http://www.openwall.com/lists/oss-security/2023/09/22/7","http://www.openwall.com/lists/oss-security/2023/09/22/8","http://www.openwall.com/lists/oss-security/2023/09/26/1","http://www.openwall.com/lists/oss-security/2023/09/26/7","http://www.openwall.com/lists/oss-security/2023/09/28/1","http://www.openwall.com/lists/oss-security/2023/09/28/2","http://www.openwall.com/lists/oss-security/2023/09/28/4","https://adamcaudill.com/2023/09/14/whose-cve-is-it-anyway/","https://blog.isosceles.com/the-webp-0day/","https://bugzilla.suse.com/show_bug.cgi?id=1215231","https://chromereleases.googleblog.com/2023/09/stable-channel-update-for-desktop_11.html","https://crbug.com/1479274","https://en.bandisoft.com/honeyview/history/","https://github.com/webmproject/libwebp/commit/902bc9190331343b2017211debcec8d2ab87e17a","https://github.com/webmproject/libwebp/releases/tag/v1.3.2","https://lists.debian.org/debian-lts-announce/2023/09/msg00015.html","https://lists.debian.org/debian-lts-announce/2023/09/msg00016.html","https://lists.debian.org/debian-lts-announce/2023/09/msg00017.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6T655QF7CQ3DYAMPFV7IECQYGDEUIVVT/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FYYKLG6CRGEDTNRBSU26EEWAO6D6U645/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KUQ7CTX3W372X3UY56VVNAHCH6H2F4X3/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OZDGWWMJREPAGKWCJKSCM4WYLANSKIFX/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PYZV7TMKF4QHZ54SFJX54BDN52VHGGCX/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WHOLML7N2G5KCAZXFWC5IDFFHSQS5SDB/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WTRUIS3564P7ZLM2S2IH4Y4KZ327LI4I/","https://msrc.microsoft.com/update-guide/vulnerability/CVE-2023-4863","https://news.ycombinator.com/item?id=37478403","https://security-tracker.debian.org/tracker/CVE-2023-4863","https://security.gentoo.org/glsa/202309-05","https://security.gentoo.org/glsa/202401-10","https://security.netapp.com/advisory/ntap-20230929-0011/","https://sethmlarson.dev/security-developer-in-residence-weekly-report-16","https://stackdiary.com/critical-vulnerability-in-webp-codec-cve-2023-4863/","https://www.bentley.com/advisories/be-2023-0001/","https://www.bleepingcomputer.com/news/google/google-fixes-another-chrome-zero-day-bug-exploited-in-attacks/","https://www.debian.org/security/2023/dsa-5496","https://www.debian.org/security/2023/dsa-5497","https://www.debian.org/security/2023/dsa-5498","https://www.mozilla.org/en-US/security/advisories/mfsa2023-40/","https://www.vicarius.io/vsociety/posts/zero-day-webp-vulnerability-cve-2023-4863"],"description":"Heap buffer overflow in libwebp in Google Chrome prior to 116.0.5845.187 and libwebp 1.3.2 allowed a remote attacker to perform an out of bounds memory write via a crafted HTML page. (Chromium security severity: Critical)","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.8,"exploitabilityScore":2.9,"impactScore":5.9},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.8,"exploitabilityScore":2.9,"impactScore":5.9},"vendorMetadata":{}}],"knownExploited":[{"cve":"CVE-2023-4863","vendorProject":"Google","product":"Chromium WebP","dateAdded":"2023-09-13","requiredAction":"Apply mitigations per vendor instructions or discontinue use of the product if mitigations are unavailable.","dueDate":"2023-10-04","knownRansomwareCampaignUse":"unknown","urls":["https://chromereleases.googleblog.com/2023/09/stable-channel-update-for-desktop_11.html?m=1","https://nvd.nist.gov/vuln/detail/CVE-2023-4863"],"cwes":["CWE-787"]}],"epss":[{"cve":"CVE-2023-4863","epss":0.93991,"percentile":0.99881,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"pillow","version":"9.5.0"}},"found":{"versionConstraint":"<10.0.1 (python)","vulnerabilityID":"GHSA-j7hp-h8jx-5ppr"},"fix":{"suggestedVersion":"10.0.1"}}],"artifact":{"id":"5af0725ffdaf09cf","name":"pillow","version":"9.5.0","type":"python","locations":[{"path":"/usr/lib/python3.10/dist-packages/Pillow-9.5.0.dist-info/METADATA","accessPath":"/usr/lib/python3.10/dist-packages/Pillow-9.5.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3.10/dist-packages/Pillow-9.5.0.dist-info/RECORD","accessPath":"/usr/lib/python3.10/dist-packages/Pillow-9.5.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/usr/lib/python3.10/dist-packages/Pillow-9.5.0.dist-info/top_level.txt","accessPath":"/usr/lib/python3.10/dist-packages/Pillow-9.5.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["HPND"],"cpes":["cpe:2.3:a:jeffrey_a__clark_(alex)_project:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex)_project:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex)project:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex)project:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex)_project:pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex):python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex):python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex)project:pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex):pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclark_project:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclark_project:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclarkproject:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclarkproject:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python-pillow:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python-pillow:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python_pillow:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python_pillow:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclark_project:pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclark:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclark:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclarkproject:pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:pillow:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:pillow:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python-pillow:pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python_pillow:pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclark:pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:pillow:pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python:pillow:9.5.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/pillow@9.5.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-5h86-8mv2-jq9f","dataSource":"https://github.com/advisories/GHSA-5h86-8mv2-jq9f","namespace":"github:language:python","severity":"High","urls":[],"description":"aiohttp is vulnerable to directory traversal","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-23334","epss":0.93393,"percentile":0.9981,"date":"2025-06-03"}],"fix":{"versions":["3.9.2"],"state":"fixed"},"advisories":[],"risk":62.573310000000006},"relatedVulnerabilities":[{"id":"CVE-2024-23334","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-23334","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/aio-libs/aiohttp/commit/1c335944d6a8b1298baf179b7c0b3069f10c514b","https://github.com/aio-libs/aiohttp/pull/8079","https://github.com/aio-libs/aiohttp/security/advisories/GHSA-5h86-8mv2-jq9f","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ICUOCFGTB25WUT336BZ4UNYLSZOUVKBD/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XXWVZIVAYWEBHNRIILZVB3R3SDQNNAA7/","https://github.com/aio-libs/aiohttp/commit/1c335944d6a8b1298baf179b7c0b3069f10c514b","https://github.com/aio-libs/aiohttp/pull/8079","https://github.com/aio-libs/aiohttp/security/advisories/GHSA-5h86-8mv2-jq9f","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ICUOCFGTB25WUT336BZ4UNYLSZOUVKBD/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XXWVZIVAYWEBHNRIILZVB3R3SDQNNAA7/"],"description":"aiohttp is an asynchronous HTTP client/server framework for asyncio and Python. When using aiohttp as a web server and configuring static routes, it is necessary to specify the root path for static files. Additionally, the option 'follow_symlinks' can be used to determine whether to follow symbolic links outside the static root directory. When 'follow_symlinks' is set to True, there is no validation to check if reading a file is within the root directory. This can lead to directory traversal vulnerabilities, resulting in unauthorized access to arbitrary files on the system, even when symlinks are not present.  Disabling follow_symlinks and using a reverse proxy are encouraged mitigations.  Version 3.9.2 fixes this issue.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-23334","epss":0.93393,"percentile":0.9981,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"aiohttp","version":"3.8.4"}},"found":{"versionConstraint":">=1.0.5,<3.9.2 (python)","vulnerabilityID":"GHSA-5h86-8mv2-jq9f"},"fix":{"suggestedVersion":"3.9.2"}}],"artifact":{"id":"11d61989037c7a8e","name":"aiohttp","version":"3.8.4","type":"python","locations":[{"path":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/METADATA","accessPath":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/RECORD","accessPath":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/top_level.txt","accessPath":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache 2"],"cpes":["cpe:2.3:a:python-aiohttp:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python-aiohttp:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python-aiohttp:aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python:aiohttp:3.8.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/aiohttp@3.8.4","upstreams":[]}},{"vulnerability":{"id":"GHSA-45c4-8wx5-qw6w","dataSource":"https://github.com/advisories/GHSA-45c4-8wx5-qw6w","namespace":"github:language:python","severity":"Medium","urls":[],"description":"aiohttp.web.Application vulnerable to HTTP request smuggling via llhttp HTTP request parser","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N","metrics":{"baseScore":5.3,"exploitabilityScore":3.9,"impactScore":1.5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-37276","epss":0.05842,"percentile":0.9011,"date":"2025-06-03"}],"fix":{"versions":["3.8.5"],"state":"fixed"},"advisories":[],"risk":3.00863},"relatedVulnerabilities":[{"id":"CVE-2023-37276","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-37276","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/aio-libs/aiohttp/blob/v3.8.4/.gitmodules","https://github.com/aio-libs/aiohttp/commit/9337fb3f2ab2b5f38d7e98a194bde6f7e3d16c40","https://github.com/aio-libs/aiohttp/security/advisories/GHSA-45c4-8wx5-qw6w","https://hackerone.com/reports/2001873","https://github.com/aio-libs/aiohttp/blob/v3.8.4/.gitmodules","https://github.com/aio-libs/aiohttp/commit/9337fb3f2ab2b5f38d7e98a194bde6f7e3d16c40","https://github.com/aio-libs/aiohttp/security/advisories/GHSA-45c4-8wx5-qw6w","https://hackerone.com/reports/2001873"],"description":"aiohttp is an asynchronous HTTP client/server framework for asyncio and Python. aiohttp v3.8.4 and earlier are bundled with llhttp v6.0.6. Vulnerable code is used by aiohttp for its HTTP request parser when available which is the default case when installing from a wheel. This vulnerability only affects users of aiohttp as an HTTP server (ie `aiohttp.Application`), you are not affected by this vulnerability if you are using aiohttp as an HTTP client library (ie `aiohttp.ClientSession`). Sending a crafted HTTP request will cause the server to misinterpret one of the HTTP header values leading to HTTP request smuggling. This issue has been addressed in version 3.8.5. Users are advised to upgrade. Users unable to upgrade can reinstall aiohttp using `AIOHTTP_NO_EXTENSIONS=1` as an environment variable to disable the llhttp HTTP request parser implementation. The pure Python implementation isn't vulnerable.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N","metrics":{"baseScore":5.3,"exploitabilityScore":3.9,"impactScore":1.5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-37276","epss":0.05842,"percentile":0.9011,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"aiohttp","version":"3.8.4"}},"found":{"versionConstraint":"<=3.8.4 (python)","vulnerabilityID":"GHSA-45c4-8wx5-qw6w"},"fix":{"suggestedVersion":"3.8.5"}}],"artifact":{"id":"11d61989037c7a8e","name":"aiohttp","version":"3.8.4","type":"python","locations":[{"path":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/METADATA","accessPath":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/RECORD","accessPath":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/top_level.txt","accessPath":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache 2"],"cpes":["cpe:2.3:a:python-aiohttp:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python-aiohttp:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python-aiohttp:aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python:aiohttp:3.8.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/aiohttp@3.8.4","upstreams":[]}},{"vulnerability":{"id":"GHSA-j8r2-6x86-q33q","dataSource":"https://github.com/advisories/GHSA-j8r2-6x86-q33q","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Unintended leak of Proxy-Authorization header in requests","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N","metrics":{"baseScore":6.1,"exploitabilityScore":1.7,"impactScore":4},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-32681","epss":0.04731,"percentile":0.88915,"date":"2025-06-03"}],"fix":{"versions":["2.31.0"],"state":"fixed"},"advisories":[],"risk":2.6257049999999995},"relatedVulnerabilities":[{"id":"CVE-2023-32681","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-32681","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/psf/requests/commit/74ea7cf7a6a27a4eeb2ae24e162bcc942a6706d5","https://github.com/psf/requests/releases/tag/v2.31.0","https://github.com/psf/requests/security/advisories/GHSA-j8r2-6x86-q33q","https://lists.debian.org/debian-lts-announce/2023/06/msg00018.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AW7HNFGYP44RT3DUDQXG2QT3OEV2PJ7Y/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KOYASTZDGQG2BWLSNBPL3TQRL2G7QYNZ/","https://security.gentoo.org/glsa/202309-08","https://github.com/psf/requests/commit/74ea7cf7a6a27a4eeb2ae24e162bcc942a6706d5","https://github.com/psf/requests/releases/tag/v2.31.0","https://github.com/psf/requests/security/advisories/GHSA-j8r2-6x86-q33q","https://lists.debian.org/debian-lts-announce/2023/06/msg00018.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AW7HNFGYP44RT3DUDQXG2QT3OEV2PJ7Y/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KOYASTZDGQG2BWLSNBPL3TQRL2G7QYNZ/","https://security.gentoo.org/glsa/202309-08"],"description":"Requests is a HTTP library. Since Requests 2.3.0, Requests has been leaking Proxy-Authorization headers to destination servers when redirected to an HTTPS endpoint. This is a product of how we use `rebuild_proxies` to reattach the `Proxy-Authorization` header to requests. For HTTP connections sent through the tunnel, the proxy will identify the header in the request itself and remove it prior to forwarding to the destination server. However when sent over HTTPS, the `Proxy-Authorization` header must be sent in the CONNECT request as the proxy has no visibility into the tunneled request. This results in Requests forwarding proxy credentials to the destination server unintentionally, allowing a malicious actor to potentially exfiltrate sensitive information. This issue has been patched in version 2.31.0.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N","metrics":{"baseScore":6.1,"exploitabilityScore":1.7,"impactScore":4},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N","metrics":{"baseScore":6.1,"exploitabilityScore":1.7,"impactScore":4},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-32681","epss":0.04731,"percentile":0.88915,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"requests","version":"2.29.0"}},"found":{"versionConstraint":">=2.3.0,<2.31.0 (python)","vulnerabilityID":"GHSA-j8r2-6x86-q33q"},"fix":{"suggestedVersion":"2.31.0"}}],"artifact":{"id":"7e0742443744a00c","name":"requests","version":"2.29.0","type":"python","locations":[{"path":"/usr/lib/python3.10/dist-packages/requests-2.29.0.dist-info/METADATA","accessPath":"/usr/lib/python3.10/dist-packages/requests-2.29.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3.10/dist-packages/requests-2.29.0.dist-info/RECORD","accessPath":"/usr/lib/python3.10/dist-packages/requests-2.29.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/usr/lib/python3.10/dist-packages/requests-2.29.0.dist-info/top_level.txt","accessPath":"/usr/lib/python3.10/dist-packages/requests-2.29.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache 2.0"],"cpes":["cpe:2.3:a:python:requests:2.29.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/requests@2.29.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-248v-346w-9cwc","dataSource":"https://github.com/advisories/GHSA-248v-346w-9cwc","namespace":"github:language:python","severity":"Low","urls":[],"description":"Certifi removes GLOBALTRUST root certificate","cvss":[],"epss":[{"cve":"CVE-2024-39689","epss":0.01928,"percentile":0.82507,"date":"2025-06-03"}],"fix":{"versions":["2024.7.4"],"state":"fixed"},"advisories":[],"risk":0.5783999999999999},"relatedVulnerabilities":[{"id":"CVE-2024-39689","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-39689","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/certifi/python-certifi/commit/bd8153872e9c6fc98f4023df9c2deaffea2fa463","https://github.com/certifi/python-certifi/security/advisories/GHSA-248v-346w-9cwc","https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI","https://github.com/certifi/python-certifi/commit/bd8153872e9c6fc98f4023df9c2deaffea2fa463","https://github.com/certifi/python-certifi/security/advisories/GHSA-248v-346w-9cwc","https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI","https://security.netapp.com/advisory/ntap-20241206-0001/"],"description":"Certifi is a curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts. Certifi starting in 2021.5.30 and prior to 2024.7.4 recognized root certificates from `GLOBALTRUST`. Certifi 2024.7.04 removes root certificates from `GLOBALTRUST` from the root store. These are in the process of being removed from Mozilla's trust store. `GLOBALTRUST`'s root certificates are being removed pursuant to an investigation which identified \"long-running and unresolved compliance issues.\"","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-39689","epss":0.01928,"percentile":0.82507,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"certifi","version":"2023.5.7"}},"found":{"versionConstraint":">=2021.5.30,<2024.7.4 (python)","vulnerabilityID":"GHSA-248v-346w-9cwc"},"fix":{"suggestedVersion":"2024.7.4"}}],"artifact":{"id":"a4c1ed83980cae3b","name":"certifi","version":"2023.5.7","type":"python","locations":[{"path":"/usr/lib/python3.10/dist-packages/certifi-2023.5.7.dist-info/METADATA","accessPath":"/usr/lib/python3.10/dist-packages/certifi-2023.5.7.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3.10/dist-packages/certifi-2023.5.7.dist-info/RECORD","accessPath":"/usr/lib/python3.10/dist-packages/certifi-2023.5.7.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/usr/lib/python3.10/dist-packages/certifi-2023.5.7.dist-info/top_level.txt","accessPath":"/usr/lib/python3.10/dist-packages/certifi-2023.5.7.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MPL-2.0"],"cpes":["cpe:2.3:a:certifi:certifi:2023.5.7:*:*:*:*:python:*:*"],"purl":"pkg:pypi/certifi@2023.5.7","upstreams":[]}},{"vulnerability":{"id":"GHSA-v845-jxx5-vc9f","dataSource":"https://github.com/advisories/GHSA-v845-jxx5-vc9f","namespace":"github:language:python","severity":"High","urls":[],"description":"`Cookie` HTTP header isn't stripped on cross-origin redirects","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:H/A:N","metrics":{"baseScore":5.9,"exploitabilityScore":0.8,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-43804","epss":0.00554,"percentile":0.67072,"date":"2025-06-03"}],"fix":{"versions":["1.26.17"],"state":"fixed"},"advisories":[],"risk":0.37118},"relatedVulnerabilities":[{"id":"CVE-2023-43804","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-43804","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/urllib3/urllib3/commit/01220354d389cd05474713f8c982d05c9b17aafb","https://github.com/urllib3/urllib3/commit/644124ecd0b6e417c527191f866daa05a5a2056d","https://github.com/urllib3/urllib3/security/advisories/GHSA-v845-jxx5-vc9f","https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/I3PR7C6RJ6JUBQKIJ644DMIJSUP36VDY/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NDAGZXYJ7H2G3SB47M453VQVNAWKAEJJ/","https://github.com/urllib3/urllib3/commit/01220354d389cd05474713f8c982d05c9b17aafb","https://github.com/urllib3/urllib3/commit/644124ecd0b6e417c527191f866daa05a5a2056d","https://github.com/urllib3/urllib3/security/advisories/GHSA-v845-jxx5-vc9f","https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/I3PR7C6RJ6JUBQKIJ644DMIJSUP36VDY/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NDAGZXYJ7H2G3SB47M453VQVNAWKAEJJ/","https://security.netapp.com/advisory/ntap-20241213-0007/","https://www.vicarius.io/vsociety/posts/cve-2023-43804-urllib3-vulnerability-3"],"description":"urllib3 is a user-friendly HTTP client library for Python. urllib3 doesn't treat the `Cookie` HTTP header special or provide any helpers for managing cookies over HTTP, that is the responsibility of the user. However, it is possible for a user to specify a `Cookie` header and unknowingly leak information via HTTP redirects to a different origin if that user doesn't disable redirects explicitly. This issue has been patched in urllib3 version 1.26.17 or 2.0.5.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N","metrics":{"baseScore":8.1,"exploitabilityScore":2.9,"impactScore":5.2},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:H/A:N","metrics":{"baseScore":5.9,"exploitabilityScore":0.8,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-43804","epss":0.00554,"percentile":0.67072,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"urllib3","version":"1.26.16"}},"found":{"versionConstraint":"<1.26.17 (python)","vulnerabilityID":"GHSA-v845-jxx5-vc9f"},"fix":{"suggestedVersion":"1.26.17"}}],"artifact":{"id":"f7b86876c271b569","name":"urllib3","version":"1.26.16","type":"python","locations":[{"path":"/usr/lib/python3.10/dist-packages/urllib3-1.26.16.dist-info/METADATA","accessPath":"/usr/lib/python3.10/dist-packages/urllib3-1.26.16.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3.10/dist-packages/urllib3-1.26.16.dist-info/RECORD","accessPath":"/usr/lib/python3.10/dist-packages/urllib3-1.26.16.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/usr/lib/python3.10/dist-packages/urllib3-1.26.16.dist-info/top_level.txt","accessPath":"/usr/lib/python3.10/dist-packages/urllib3-1.26.16.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:urllib3:1.26.16:*:*:*:*:*:*:*"],"purl":"pkg:pypi/urllib3@1.26.16","upstreams":[]}},{"vulnerability":{"id":"GHSA-3f63-hfp8-52jq","dataSource":"https://github.com/advisories/GHSA-3f63-hfp8-52jq","namespace":"github:language:python","severity":"Critical","urls":[],"description":"Arbitrary Code Execution in Pillow","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.1,"exploitabilityScore":2.3,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-50447","epss":0.00408,"percentile":0.60391,"date":"2025-06-03"}],"fix":{"versions":["10.2.0"],"state":"fixed"},"advisories":[],"risk":0.34884},"relatedVulnerabilities":[{"id":"CVE-2023-50447","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-50447","namespace":"nvd:cpe","severity":"High","urls":["http://www.openwall.com/lists/oss-security/2024/01/20/1","https://devhub.checkmarx.com/cve-details/CVE-2023-50447/","https://duartecsantos.github.io/2024-01-02-CVE-2023-50447/","https://github.com/python-pillow/Pillow/releases","https://lists.debian.org/debian-lts-announce/2024/01/msg00019.html","http://www.openwall.com/lists/oss-security/2024/01/20/1","https://devhub.checkmarx.com/cve-details/CVE-2023-50447/","https://duartecsantos.github.io/2024-01-02-CVE-2023-50447/","https://github.com/python-pillow/Pillow/releases","https://lists.debian.org/debian-lts-announce/2024/01/msg00019.html"],"description":"Pillow through 10.1.0 allows PIL.ImageMath.eval Arbitrary Code Execution via the environment parameter, a different vulnerability than CVE-2022-22817 (which was about the expression parameter).","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.1,"exploitabilityScore":2.3,"impactScore":5.9},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.1,"exploitabilityScore":2.3,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-50447","epss":0.00408,"percentile":0.60391,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"pillow","version":"9.5.0"}},"found":{"versionConstraint":"<10.2.0 (python)","vulnerabilityID":"GHSA-3f63-hfp8-52jq"},"fix":{"suggestedVersion":"10.2.0"}}],"artifact":{"id":"5af0725ffdaf09cf","name":"pillow","version":"9.5.0","type":"python","locations":[{"path":"/usr/lib/python3.10/dist-packages/Pillow-9.5.0.dist-info/METADATA","accessPath":"/usr/lib/python3.10/dist-packages/Pillow-9.5.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3.10/dist-packages/Pillow-9.5.0.dist-info/RECORD","accessPath":"/usr/lib/python3.10/dist-packages/Pillow-9.5.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/usr/lib/python3.10/dist-packages/Pillow-9.5.0.dist-info/top_level.txt","accessPath":"/usr/lib/python3.10/dist-packages/Pillow-9.5.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["HPND"],"cpes":["cpe:2.3:a:jeffrey_a__clark_(alex)_project:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex)_project:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex)project:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex)project:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex)_project:pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex):python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex):python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex)project:pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex):pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclark_project:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclark_project:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclarkproject:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclarkproject:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python-pillow:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python-pillow:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python_pillow:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python_pillow:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclark_project:pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclark:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclark:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclarkproject:pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:pillow:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:pillow:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python-pillow:pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python_pillow:pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclark:pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:pillow:pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python:pillow:9.5.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/pillow@9.5.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-jjg7-2v4v-x38h","dataSource":"https://github.com/advisories/GHSA-jjg7-2v4v-x38h","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Internationalized Domain Names in Applications (IDNA) vulnerable to denial of service from specially crafted inputs to idna.encode","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":6.2,"exploitabilityScore":2.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-3651","epss":0.00436,"percentile":0.62113,"date":"2025-06-03"}],"fix":{"versions":["3.7"],"state":"fixed"},"advisories":[],"risk":0.24416000000000004},"relatedVulnerabilities":[{"id":"CVE-2024-3651","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-3651","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/kjd/idna/commit/1d365e17e10d72d0b7876316fc7b9ca0eebdd38d","https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb","https://github.com/kjd/idna/commit/1d365e17e10d72d0b7876316fc7b9ca0eebdd38d","https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb"],"description":"A vulnerability was identified in the kjd/idna library, specifically within the `idna.encode()` function, affecting version 3.6. The issue arises from the function's handling of crafted input strings, which can lead to quadratic complexity and consequently, a denial of service condition. This vulnerability is triggered by a crafted input that causes the `idna.encode()` function to process the input with considerable computational load, significantly increasing the processing time in a quadratic manner relative to the input size.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security@huntr.dev","type":"Secondary","version":"3.0","vector":"CVSS:3.0/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":6.2,"exploitabilityScore":2.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-3651","epss":0.00436,"percentile":0.62113,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"idna","version":"3.4"}},"found":{"versionConstraint":"<3.7 (python)","vulnerabilityID":"GHSA-jjg7-2v4v-x38h"},"fix":{"suggestedVersion":"3.7"}}],"artifact":{"id":"c13be3af19dbc196","name":"idna","version":"3.4","type":"python","locations":[{"path":"/usr/lib/python3.10/dist-packages/idna-3.4.dist-info/METADATA","accessPath":"/usr/lib/python3.10/dist-packages/idna-3.4.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3.10/dist-packages/idna-3.4.dist-info/RECORD","accessPath":"/usr/lib/python3.10/dist-packages/idna-3.4.dist-info/RECORD","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:kim_davies_<kim_project:python-idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kim_project:python_idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kimproject:python-idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kimproject:python_idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kim_project:idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:kim-davies-<kim:python-idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:kim-davies-<kim:python_idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kim:python-idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kim:python_idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kimproject:idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:python-idna:python-idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:python-idna:python_idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:python_idna:python-idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:python_idna:python_idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:kim-davies-<kim:idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kim:idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python-idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python_idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:idna:python-idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:idna:python_idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:python-idna:idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:python_idna:idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:python:idna:3.4:*:*:*:*:*:*:*","cpe:2.3:a:idna:idna:3.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/idna@3.4","upstreams":[]}},{"vulnerability":{"id":"GHSA-5m98-qgg9-wh84","dataSource":"https://github.com/advisories/GHSA-5m98-qgg9-wh84","namespace":"github:language:python","severity":"High","urls":[],"description":"aiohttp vulnerable to Denial of Service when trying to parse malformed POST requests","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-30251","epss":0.00288,"percentile":0.52063,"date":"2025-06-03"}],"fix":{"versions":["3.9.4"],"state":"fixed"},"advisories":[],"risk":0.216},"relatedVulnerabilities":[{"id":"CVE-2024-30251","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-30251","namespace":"nvd:cpe","severity":"High","urls":["http://www.openwall.com/lists/oss-security/2024/05/02/4","https://github.com/aio-libs/aiohttp/commit/7eecdff163ccf029fbb1ddc9de4169d4aaeb6597","https://github.com/aio-libs/aiohttp/commit/cebe526b9c34dc3a3da9140409db63014bc4cf19","https://github.com/aio-libs/aiohttp/commit/f21c6f2ca512a026ce7f0f6c6311f62d6a638866","https://github.com/aio-libs/aiohttp/security/advisories/GHSA-5m98-qgg9-wh84","http://www.openwall.com/lists/oss-security/2024/05/02/4","https://github.com/aio-libs/aiohttp/commit/7eecdff163ccf029fbb1ddc9de4169d4aaeb6597","https://github.com/aio-libs/aiohttp/commit/cebe526b9c34dc3a3da9140409db63014bc4cf19","https://github.com/aio-libs/aiohttp/commit/f21c6f2ca512a026ce7f0f6c6311f62d6a638866","https://github.com/aio-libs/aiohttp/security/advisories/GHSA-5m98-qgg9-wh84"],"description":"aiohttp is an asynchronous HTTP client/server framework for asyncio and Python. In affected versions an attacker can send a specially crafted POST (multipart/form-data) request. When the aiohttp server processes it, the server will enter an infinite loop and be unable to process any further requests. An attacker can stop the application from serving requests after sending a single request. This issue has been addressed in version 3.9.4. Users are advised to upgrade. Users unable to upgrade may manually apply a patch to their systems. Please see the linked GHSA for instructions.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-30251","epss":0.00288,"percentile":0.52063,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"aiohttp","version":"3.8.4"}},"found":{"versionConstraint":"<3.9.4 (python)","vulnerabilityID":"GHSA-5m98-qgg9-wh84"},"fix":{"suggestedVersion":"3.9.4"}}],"artifact":{"id":"11d61989037c7a8e","name":"aiohttp","version":"3.8.4","type":"python","locations":[{"path":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/METADATA","accessPath":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/RECORD","accessPath":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/top_level.txt","accessPath":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache 2"],"cpes":["cpe:2.3:a:python-aiohttp:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python-aiohttp:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python-aiohttp:aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python:aiohttp:3.8.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/aiohttp@3.8.4","upstreams":[]}},{"vulnerability":{"id":"GHSA-q3qx-c6g2-7pw2","dataSource":"https://github.com/advisories/GHSA-q3qx-c6g2-7pw2","namespace":"github:language:python","severity":"Medium","urls":[],"description":"aiohttp's ClientSession is vulnerable to CRLF injection via version","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:L/I:L/A:N","metrics":{"baseScore":7.2,"exploitabilityScore":3.9,"impactScore":2.8},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-49081","epss":0.00242,"percentile":0.47717,"date":"2025-06-03"}],"fix":{"versions":["3.9.0"],"state":"fixed"},"advisories":[],"risk":0.14761999999999997},"relatedVulnerabilities":[{"id":"CVE-2023-49081","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-49081","namespace":"nvd:cpe","severity":"Medium","urls":["https://gist.github.com/jnovikov/184afb593d9c2114d77f508e0ccd508e","https://github.com/aio-libs/aiohttp/commit/1e86b777e61cf4eefc7d92fa57fa19dcc676013b","https://github.com/aio-libs/aiohttp/pull/7835/files","https://github.com/aio-libs/aiohttp/security/advisories/GHSA-q3qx-c6g2-7pw2","https://gist.github.com/jnovikov/184afb593d9c2114d77f508e0ccd508e","https://github.com/aio-libs/aiohttp/commit/1e86b777e61cf4eefc7d92fa57fa19dcc676013b","https://github.com/aio-libs/aiohttp/pull/7835/files","https://github.com/aio-libs/aiohttp/security/advisories/GHSA-q3qx-c6g2-7pw2"],"description":"aiohttp is an asynchronous HTTP client/server framework for asyncio and Python. Improper validation made it possible for an attacker to modify the HTTP request (e.g. to insert a new header) or create a new HTTP request if the attacker controls the HTTP version. The vulnerability only occurs if the attacker can control the HTTP version of the request. This issue has been patched in version 3.9.0.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N","metrics":{"baseScore":5.3,"exploitabilityScore":3.9,"impactScore":1.5},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:L/I:L/A:N","metrics":{"baseScore":7.2,"exploitabilityScore":3.9,"impactScore":2.8},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-49081","epss":0.00242,"percentile":0.47717,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"aiohttp","version":"3.8.4"}},"found":{"versionConstraint":"<3.9.0 (python)","vulnerabilityID":"GHSA-q3qx-c6g2-7pw2"},"fix":{"suggestedVersion":"3.9.0"}}],"artifact":{"id":"11d61989037c7a8e","name":"aiohttp","version":"3.8.4","type":"python","locations":[{"path":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/METADATA","accessPath":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/RECORD","accessPath":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/top_level.txt","accessPath":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache 2"],"cpes":["cpe:2.3:a:python-aiohttp:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python-aiohttp:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python-aiohttp:aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python:aiohttp:3.8.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/aiohttp@3.8.4","upstreams":[]}},{"vulnerability":{"id":"GHSA-8qpw-xqxj-h4r2","dataSource":"https://github.com/advisories/GHSA-8qpw-xqxj-h4r2","namespace":"github:language:python","severity":"Medium","urls":[],"description":"aiohttp's HTTP parser (the python one, not llhttp) still overly lenient about separators","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:L","metrics":{"baseScore":6.5,"exploitabilityScore":3.9,"impactScore":2.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-23829","epss":0.0023,"percentile":0.45983,"date":"2025-06-03"}],"fix":{"versions":["3.9.2"],"state":"fixed"},"advisories":[],"risk":0.13224999999999998},"relatedVulnerabilities":[{"id":"CVE-2024-23829","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-23829","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/aio-libs/aiohttp/commit/33ccdfb0a12690af5bb49bda2319ec0907fa7827","https://github.com/aio-libs/aiohttp/pull/8074","https://github.com/aio-libs/aiohttp/security/advisories/GHSA-8qpw-xqxj-h4r2","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ICUOCFGTB25WUT336BZ4UNYLSZOUVKBD/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XXWVZIVAYWEBHNRIILZVB3R3SDQNNAA7/","https://github.com/aio-libs/aiohttp/commit/33ccdfb0a12690af5bb49bda2319ec0907fa7827","https://github.com/aio-libs/aiohttp/pull/8074","https://github.com/aio-libs/aiohttp/security/advisories/GHSA-8qpw-xqxj-h4r2","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ICUOCFGTB25WUT336BZ4UNYLSZOUVKBD/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XXWVZIVAYWEBHNRIILZVB3R3SDQNNAA7/"],"description":"aiohttp is an asynchronous HTTP client/server framework for asyncio and Python. Security-sensitive parts of the Python HTTP parser retained minor differences in allowable character sets, that must trigger error handling to robustly match frame boundaries of proxies in order to protect against injection of additional requests. Additionally, validation could trigger exceptions that were not handled consistently with processing of other malformed input.  Being more lenient than internet standards require could, depending on deployment environment, assist in request smuggling. The unhandled exception could cause excessive resource consumption on the application server and/or its logging facilities. This vulnerability exists due to an incomplete fix for CVE-2023-47627. Version 3.9.2 fixes this vulnerability.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:L","metrics":{"baseScore":6.5,"exploitabilityScore":3.9,"impactScore":2.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:L","metrics":{"baseScore":6.5,"exploitabilityScore":3.9,"impactScore":2.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-23829","epss":0.0023,"percentile":0.45983,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"aiohttp","version":"3.8.4"}},"found":{"versionConstraint":"<3.9.2 (python)","vulnerabilityID":"GHSA-8qpw-xqxj-h4r2"},"fix":{"suggestedVersion":"3.9.2"}}],"artifact":{"id":"11d61989037c7a8e","name":"aiohttp","version":"3.8.4","type":"python","locations":[{"path":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/METADATA","accessPath":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/RECORD","accessPath":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/top_level.txt","accessPath":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache 2"],"cpes":["cpe:2.3:a:python-aiohttp:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python-aiohttp:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python-aiohttp:aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python:aiohttp:3.8.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/aiohttp@3.8.4","upstreams":[]}},{"vulnerability":{"id":"GHSA-8ghj-p4vj-mr35","dataSource":"https://github.com/advisories/GHSA-8ghj-p4vj-mr35","namespace":"github:language:python","severity":"High","urls":[],"description":"Pillow Denial of Service vulnerability","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-44271","epss":0.00148,"percentile":0.36583,"date":"2025-06-03"}],"fix":{"versions":["10.0.0"],"state":"fixed"},"advisories":[],"risk":0.11099999999999999},"relatedVulnerabilities":[{"id":"CVE-2023-44271","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-44271","namespace":"nvd:cpe","severity":"High","urls":["https://devhub.checkmarx.com/cve-details/CVE-2023-44271/","https://github.com/python-pillow/Pillow/commit/1fe1bb49c452b0318cad12ea9d97c3bef188e9a7","https://github.com/python-pillow/Pillow/pull/7244","https://lists.debian.org/debian-lts-announce/2024/03/msg00021.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/N2JOEDUJDQLCUII2LQYZYSM7RJL2I3P4/","https://devhub.checkmarx.com/cve-details/CVE-2023-44271/","https://github.com/python-pillow/Pillow/commit/1fe1bb49c452b0318cad12ea9d97c3bef188e9a7","https://github.com/python-pillow/Pillow/pull/7244","https://lists.debian.org/debian-lts-announce/2024/03/msg00021.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/N2JOEDUJDQLCUII2LQYZYSM7RJL2I3P4/"],"description":"An issue was discovered in Pillow before 10.0.0. It is a Denial of Service that uncontrollably allocates memory to process a given task, potentially causing a service to crash by having it run out of memory. This occurs for truetype in ImageFont when textlength in an ImageDraw instance operates on a long text argument.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-44271","epss":0.00148,"percentile":0.36583,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"pillow","version":"9.5.0"}},"found":{"versionConstraint":">=0,<10.0.0 (python)","vulnerabilityID":"GHSA-8ghj-p4vj-mr35"},"fix":{"suggestedVersion":"10.0.0"}}],"artifact":{"id":"5af0725ffdaf09cf","name":"pillow","version":"9.5.0","type":"python","locations":[{"path":"/usr/lib/python3.10/dist-packages/Pillow-9.5.0.dist-info/METADATA","accessPath":"/usr/lib/python3.10/dist-packages/Pillow-9.5.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3.10/dist-packages/Pillow-9.5.0.dist-info/RECORD","accessPath":"/usr/lib/python3.10/dist-packages/Pillow-9.5.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/usr/lib/python3.10/dist-packages/Pillow-9.5.0.dist-info/top_level.txt","accessPath":"/usr/lib/python3.10/dist-packages/Pillow-9.5.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["HPND"],"cpes":["cpe:2.3:a:jeffrey_a__clark_(alex)_project:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex)_project:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex)project:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex)project:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex)_project:pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex):python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex):python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex)project:pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex):pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclark_project:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclark_project:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclarkproject:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclarkproject:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python-pillow:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python-pillow:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python_pillow:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python_pillow:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclark_project:pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclark:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclark:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclarkproject:pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:pillow:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:pillow:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python-pillow:pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python_pillow:pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclark:pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:pillow:pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python:pillow:9.5.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/pillow@9.5.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-jwhx-xcg6-8xhj","dataSource":"https://github.com/advisories/GHSA-jwhx-xcg6-8xhj","namespace":"github:language:python","severity":"Medium","urls":[],"description":"In aiohttp, compressed files as symlinks are not protected from path traversal","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N","metrics":{"baseScore":4.8,"exploitabilityScore":2.3,"impactScore":2.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-42367","epss":0.00203,"percentile":0.4306,"date":"2025-06-03"}],"fix":{"versions":["3.10.2"],"state":"fixed"},"advisories":[],"risk":0.09947},"relatedVulnerabilities":[{"id":"CVE-2024-42367","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-42367","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/aio-libs/aiohttp/blob/e0ff5246e1d29b7710ab1a2bbc972b48169f1c05/aiohttp/web_fileresponse.py#L177","https://github.com/aio-libs/aiohttp/blob/e0ff5246e1d29b7710ab1a2bbc972b48169f1c05/aiohttp/web_urldispatcher.py#L674","https://github.com/aio-libs/aiohttp/commit/ce2e9758814527589b10759a20783fb03b98339f","https://github.com/aio-libs/aiohttp/pull/8653","https://github.com/aio-libs/aiohttp/security/advisories/GHSA-jwhx-xcg6-8xhj"],"description":"aiohttp is an asynchronous HTTP client/server framework for asyncio and Python. Prior to version 3.10.2, static routes which contain files with compressed variants (`.gz` or `.br` extension) are vulnerable to path traversal outside the root directory if those variants are symbolic links. The server protects static routes from path traversal outside the root directory when `follow_symlinks=False` (default).  It does this by resolving the requested URL to an absolute path and then checking that path relative to the root. However, these checks are not performed when looking for compressed variants in the `FileResponse` class, and symbolic links are then automatically followed when performing the `Path.stat()` and `Path.open()` to send the file. Version 3.10.2 contains a patch for the issue.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N","metrics":{"baseScore":4.8,"exploitabilityScore":2.3,"impactScore":2.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-42367","epss":0.00203,"percentile":0.4306,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"aiohttp","version":"3.8.4"}},"found":{"versionConstraint":"<3.10.2 (python)","vulnerabilityID":"GHSA-jwhx-xcg6-8xhj"},"fix":{"suggestedVersion":"3.10.2"}}],"artifact":{"id":"11d61989037c7a8e","name":"aiohttp","version":"3.8.4","type":"python","locations":[{"path":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/METADATA","accessPath":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/RECORD","accessPath":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/top_level.txt","accessPath":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache 2"],"cpes":["cpe:2.3:a:python-aiohttp:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python-aiohttp:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python-aiohttp:aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python:aiohttp:3.8.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/aiohttp@3.8.4","upstreams":[]}},{"vulnerability":{"id":"GHSA-gfw2-4jvh-wgfg","dataSource":"https://github.com/advisories/GHSA-gfw2-4jvh-wgfg","namespace":"github:language:python","severity":"Medium","urls":[],"description":"AIOHTTP has problems in HTTP parser (the python one, not llhttp)","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N","metrics":{"baseScore":5.3,"exploitabilityScore":3.9,"impactScore":1.5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-47627","epss":0.00181,"percentile":0.40533,"date":"2025-06-03"}],"fix":{"versions":["3.8.6"],"state":"fixed"},"advisories":[],"risk":0.09321499999999999},"relatedVulnerabilities":[{"id":"CVE-2023-47627","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-47627","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/aio-libs/aiohttp/commit/d5c12ba890557a575c313bb3017910d7616fce3d","https://github.com/aio-libs/aiohttp/security/advisories/GHSA-gfw2-4jvh-wgfg","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FUSJVQ7OQ55RWL4XAX2F5EZ73N4ZSH6U/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VDKQ6HM3KNDU4OQI476ZWT4O7DMSIT35/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WQYQL6WV535EEKSNH7KRARLLMOW5WXDM/","https://github.com/aio-libs/aiohttp/commit/d5c12ba890557a575c313bb3017910d7616fce3d","https://github.com/aio-libs/aiohttp/security/advisories/GHSA-gfw2-4jvh-wgfg","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FUSJVQ7OQ55RWL4XAX2F5EZ73N4ZSH6U/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VDKQ6HM3KNDU4OQI476ZWT4O7DMSIT35/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WQYQL6WV535EEKSNH7KRARLLMOW5WXDM/"],"description":"aiohttp is an asynchronous HTTP client/server framework for asyncio and Python. The HTTP parser in AIOHTTP has numerous problems with header parsing, which could lead to request smuggling. This parser is only used when AIOHTTP_NO_EXTENSIONS is enabled (or not using a prebuilt wheel). These bugs have been addressed in commit `d5c12ba89` which has been included in release version 3.8.6. Users are advised to upgrade. There are no known workarounds for these issues.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N","metrics":{"baseScore":5.3,"exploitabilityScore":3.9,"impactScore":1.5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-47627","epss":0.00181,"percentile":0.40533,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"aiohttp","version":"3.8.4"}},"found":{"versionConstraint":"<3.8.6 (python)","vulnerabilityID":"GHSA-gfw2-4jvh-wgfg"},"fix":{"suggestedVersion":"3.8.6"}}],"artifact":{"id":"11d61989037c7a8e","name":"aiohttp","version":"3.8.4","type":"python","locations":[{"path":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/METADATA","accessPath":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/RECORD","accessPath":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/top_level.txt","accessPath":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache 2"],"cpes":["cpe:2.3:a:python-aiohttp:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python-aiohttp:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python-aiohttp:aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python:aiohttp:3.8.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/aiohttp@3.8.4","upstreams":[]}},{"vulnerability":{"id":"GHSA-xqr8-7jwr-rhp7","dataSource":"https://github.com/advisories/GHSA-xqr8-7jwr-rhp7","namespace":"github:language:python","severity":"High","urls":[],"description":"Removal of e-Tugra root certificate","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-37920","epss":0.00112,"percentile":0.30835,"date":"2025-06-03"}],"fix":{"versions":["2023.7.22"],"state":"fixed"},"advisories":[],"risk":0.08399999999999999},"relatedVulnerabilities":[{"id":"CVE-2023-37920","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-37920","namespace":"nvd:cpe","severity":"Critical","urls":["https://github.com/certifi/python-certifi/commit/8fb96ed81f71e7097ed11bc4d9b19afd7ea5c909","https://github.com/certifi/python-certifi/security/advisories/GHSA-xqr8-7jwr-rhp7","https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/C-HrP1SEq1A","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5EX6NG7WUFNUKGFHLM35KHHU3GAKXRTG/","https://github.com/certifi/python-certifi/commit/8fb96ed81f71e7097ed11bc4d9b19afd7ea5c909","https://github.com/certifi/python-certifi/security/advisories/GHSA-xqr8-7jwr-rhp7","https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/C-HrP1SEq1A","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5EX6NG7WUFNUKGFHLM35KHHU3GAKXRTG/","https://security.netapp.com/advisory/ntap-20240912-0002/"],"description":"Certifi is a curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts. Certifi prior to version 2023.07.22 recognizes \"e-Tugra\" root certificates. e-Tugra's root certificates were subject to an investigation prompted by reporting of security issues in their systems. Certifi 2023.07.22 removes root certificates from \"e-Tugra\" from the root store.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":9.8,"exploitabilityScore":3.9,"impactScore":5.9},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-37920","epss":0.00112,"percentile":0.30835,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"certifi","version":"2023.5.7"}},"found":{"versionConstraint":">=2015.4.28,<2023.7.22 (python)","vulnerabilityID":"GHSA-xqr8-7jwr-rhp7"},"fix":{"suggestedVersion":"2023.7.22"}}],"artifact":{"id":"a4c1ed83980cae3b","name":"certifi","version":"2023.5.7","type":"python","locations":[{"path":"/usr/lib/python3.10/dist-packages/certifi-2023.5.7.dist-info/METADATA","accessPath":"/usr/lib/python3.10/dist-packages/certifi-2023.5.7.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3.10/dist-packages/certifi-2023.5.7.dist-info/RECORD","accessPath":"/usr/lib/python3.10/dist-packages/certifi-2023.5.7.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/usr/lib/python3.10/dist-packages/certifi-2023.5.7.dist-info/top_level.txt","accessPath":"/usr/lib/python3.10/dist-packages/certifi-2023.5.7.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MPL-2.0"],"cpes":["cpe:2.3:a:certifi:certifi:2023.5.7:*:*:*:*:python:*:*"],"purl":"pkg:pypi/certifi@2023.5.7","upstreams":[]}},{"vulnerability":{"id":"GHSA-qvrw-v9rv-5rjx","dataSource":"https://github.com/advisories/GHSA-qvrw-v9rv-5rjx","namespace":"github:language:python","severity":"Medium","urls":[],"description":"aiohttp's ClientSession is vulnerable to CRLF injection via method","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N","metrics":{"baseScore":5.3,"exploitabilityScore":3.9,"impactScore":1.5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-49082","epss":0.00159,"percentile":0.37966,"date":"2025-06-03"}],"fix":{"versions":["3.9.0"],"state":"fixed"},"advisories":[],"risk":0.08188500000000001},"relatedVulnerabilities":[{"id":"CVE-2023-49082","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-49082","namespace":"nvd:cpe","severity":"Medium","urls":["https://gist.github.com/jnovikov/7f411ae9fe6a9a7804cf162a3bdbb44b","https://github.com/aio-libs/aiohttp/commit/e4ae01c2077d2cfa116aa82e4ff6866857f7c466","https://github.com/aio-libs/aiohttp/pull/7806/files","https://github.com/aio-libs/aiohttp/security/advisories/GHSA-qvrw-v9rv-5rjx","https://gist.github.com/jnovikov/7f411ae9fe6a9a7804cf162a3bdbb44b","https://github.com/aio-libs/aiohttp/commit/e4ae01c2077d2cfa116aa82e4ff6866857f7c466","https://github.com/aio-libs/aiohttp/pull/7806/files","https://github.com/aio-libs/aiohttp/security/advisories/GHSA-qvrw-v9rv-5rjx"],"description":"aiohttp is an asynchronous HTTP client/server framework for asyncio and Python. Improper validation makes it possible for an attacker to modify the HTTP request (e.g. insert a new header) or even create a new HTTP request if the attacker controls the HTTP method. The vulnerability occurs only if the attacker can control the HTTP method (GET, POST etc.) of the request. If the attacker can control the HTTP version of the request it will be able to modify the request (request smuggling). This issue has been patched in version 3.9.0.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N","metrics":{"baseScore":5.3,"exploitabilityScore":3.9,"impactScore":1.5},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N","metrics":{"baseScore":5.3,"exploitabilityScore":3.9,"impactScore":1.5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-49082","epss":0.00159,"percentile":0.37966,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"aiohttp","version":"3.8.4"}},"found":{"versionConstraint":"<3.9.0 (python)","vulnerabilityID":"GHSA-qvrw-v9rv-5rjx"},"fix":{"suggestedVersion":"3.9.0"}}],"artifact":{"id":"11d61989037c7a8e","name":"aiohttp","version":"3.8.4","type":"python","locations":[{"path":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/METADATA","accessPath":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/RECORD","accessPath":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/top_level.txt","accessPath":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache 2"],"cpes":["cpe:2.3:a:python-aiohttp:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python-aiohttp:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python-aiohttp:aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python:aiohttp:3.8.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/aiohttp@3.8.4","upstreams":[]}},{"vulnerability":{"id":"GHSA-8495-4g3g-x7pr","dataSource":"https://github.com/advisories/GHSA-8495-4g3g-x7pr","namespace":"github:language:python","severity":"Medium","urls":[],"description":"aiohttp allows request smuggling due to incorrect parsing of chunk extensions","cvss":[],"epss":[{"cve":"CVE-2024-52304","epss":0.00153,"percentile":0.3721,"date":"2025-06-03"}],"fix":{"versions":["3.10.11"],"state":"fixed"},"advisories":[],"risk":0.0765},"relatedVulnerabilities":[{"id":"CVE-2024-52304","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-52304","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/aio-libs/aiohttp/commit/259edc369075de63e6f3a4eaade058c62af0df71","https://github.com/aio-libs/aiohttp/security/advisories/GHSA-8495-4g3g-x7pr"],"description":"aiohttp is an asynchronous HTTP client/server framework for asyncio and Python. Prior to version 3.10.11, the Python parser parses newlines in chunk extensions incorrectly which can lead to request smuggling vulnerabilities under certain conditions. If a pure Python version of aiohttp is installed (i.e. without the usual C extensions) or `AIOHTTP_NO_EXTENSIONS` is enabled, then an attacker may be able to execute a request smuggling attack to bypass certain firewalls or proxy protections. Version 3.10.11 fixes the issue.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:L/AT:P/PR:N/UI:N/VC:N/VI:L/VA:N/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":6.3},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-52304","epss":0.00153,"percentile":0.3721,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"aiohttp","version":"3.8.4"}},"found":{"versionConstraint":"<=3.10.10 (python)","vulnerabilityID":"GHSA-8495-4g3g-x7pr"},"fix":{"suggestedVersion":"3.10.11"}}],"artifact":{"id":"11d61989037c7a8e","name":"aiohttp","version":"3.8.4","type":"python","locations":[{"path":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/METADATA","accessPath":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/RECORD","accessPath":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/top_level.txt","accessPath":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache 2"],"cpes":["cpe:2.3:a:python-aiohttp:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python-aiohttp:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python-aiohttp:aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python:aiohttp:3.8.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/aiohttp@3.8.4","upstreams":[]}},{"vulnerability":{"id":"GHSA-7gpw-8wmc-pm8g","dataSource":"https://github.com/advisories/GHSA-7gpw-8wmc-pm8g","namespace":"github:language:python","severity":"Medium","urls":[],"description":"aiohttp Cross-site Scripting vulnerability on index pages for static file handling","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N","metrics":{"baseScore":6.1,"exploitabilityScore":2.9,"impactScore":2.8},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-27306","epss":0.00132,"percentile":0.34199,"date":"2025-06-03"}],"fix":{"versions":["3.9.4"],"state":"fixed"},"advisories":[],"risk":0.07325999999999999},"relatedVulnerabilities":[{"id":"CVE-2024-27306","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-27306","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/aio-libs/aiohttp/commit/28335525d1eac015a7e7584137678cbb6ff19397","https://github.com/aio-libs/aiohttp/pull/8319","https://github.com/aio-libs/aiohttp/security/advisories/GHSA-7gpw-8wmc-pm8g","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/2EXRGTN2WG7VZLUZ7WOXU5GQJKCPPHKP/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NWEI6NIHZ3G7DURDZVMRK7ZEFC2BTD3U/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZIVBMPEY7WWOFMC3CWXFBRQPFECV4SW3/","https://github.com/aio-libs/aiohttp/commit/28335525d1eac015a7e7584137678cbb6ff19397","https://github.com/aio-libs/aiohttp/pull/8319","https://github.com/aio-libs/aiohttp/security/advisories/GHSA-7gpw-8wmc-pm8g","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/2EXRGTN2WG7VZLUZ7WOXU5GQJKCPPHKP/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NWEI6NIHZ3G7DURDZVMRK7ZEFC2BTD3U/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZIVBMPEY7WWOFMC3CWXFBRQPFECV4SW3/"],"description":"aiohttp is an asynchronous HTTP client/server framework for asyncio and Python. A XSS vulnerability exists on index pages for static file handling. This vulnerability is fixed in 3.9.4. We have always recommended using a reverse proxy server (e.g. nginx) for serving static files. Users following the recommendation are unaffected. Other users can disable `show_index` if unable to upgrade.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N","metrics":{"baseScore":6.1,"exploitabilityScore":2.9,"impactScore":2.8},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-27306","epss":0.00132,"percentile":0.34199,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"aiohttp","version":"3.8.4"}},"found":{"versionConstraint":"<3.9.4 (python)","vulnerabilityID":"GHSA-7gpw-8wmc-pm8g"},"fix":{"suggestedVersion":"3.9.4"}}],"artifact":{"id":"11d61989037c7a8e","name":"aiohttp","version":"3.8.4","type":"python","locations":[{"path":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/METADATA","accessPath":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/RECORD","accessPath":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/top_level.txt","accessPath":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache 2"],"cpes":["cpe:2.3:a:python-aiohttp:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python-aiohttp:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python-aiohttp:aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python:aiohttp:3.8.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/aiohttp@3.8.4","upstreams":[]}},{"vulnerability":{"id":"GHSA-44wm-f244-xhp3","dataSource":"https://github.com/advisories/GHSA-44wm-f244-xhp3","namespace":"github:language:python","severity":"High","urls":[],"description":"Pillow buffer overflow vulnerability","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:H/PR:L/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":6.7,"exploitabilityScore":0.8,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-28219","epss":0.00095,"percentile":0.27869,"date":"2025-06-03"}],"fix":{"versions":["10.3.0"],"state":"fixed"},"advisories":[],"risk":0.06745},"relatedVulnerabilities":[{"id":"CVE-2024-28219","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-28219","namespace":"nvd:cpe","severity":"Medium","urls":["https://lists.debian.org/debian-lts-announce/2024/04/msg00008.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4XLPUT3VK4GQ6EVY525TT2QNUIXNRU5M/","https://pillow.readthedocs.io/en/stable/releasenotes/10.3.0.html#security","https://lists.debian.org/debian-lts-announce/2024/04/msg00008.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4XLPUT3VK4GQ6EVY525TT2QNUIXNRU5M/","https://pillow.readthedocs.io/en/stable/releasenotes/10.3.0.html#security"],"description":"In _imagingcms.c in Pillow before 10.3.0, a buffer overflow exists because strcpy is used instead of strncpy.","cvss":[{"source":"cve@mitre.org","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:H/PR:L/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":6.7,"exploitabilityScore":0.8,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-28219","epss":0.00095,"percentile":0.27869,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"pillow","version":"9.5.0"}},"found":{"versionConstraint":"<10.3.0 (python)","vulnerabilityID":"GHSA-44wm-f244-xhp3"},"fix":{"suggestedVersion":"10.3.0"}}],"artifact":{"id":"5af0725ffdaf09cf","name":"pillow","version":"9.5.0","type":"python","locations":[{"path":"/usr/lib/python3.10/dist-packages/Pillow-9.5.0.dist-info/METADATA","accessPath":"/usr/lib/python3.10/dist-packages/Pillow-9.5.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3.10/dist-packages/Pillow-9.5.0.dist-info/RECORD","accessPath":"/usr/lib/python3.10/dist-packages/Pillow-9.5.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/usr/lib/python3.10/dist-packages/Pillow-9.5.0.dist-info/top_level.txt","accessPath":"/usr/lib/python3.10/dist-packages/Pillow-9.5.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["HPND"],"cpes":["cpe:2.3:a:jeffrey_a__clark_(alex)_project:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex)_project:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex)project:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex)project:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex)_project:pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex):python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex):python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex)project:pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:jeffrey_a__clark_(alex):pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclark_project:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclark_project:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclarkproject:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclarkproject:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python-pillow:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python-pillow:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python_pillow:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python_pillow:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclark_project:pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclark:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclark:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclarkproject:pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:pillow:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:pillow:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python-pillow:pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python-pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python_pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python_pillow:pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:aclark:pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:pillow:pillow:9.5.0:*:*:*:*:*:*:*","cpe:2.3:a:python:pillow:9.5.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/pillow@9.5.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-g4mx-q9vg-27p4","dataSource":"https://github.com/advisories/GHSA-g4mx-q9vg-27p4","namespace":"github:language:python","severity":"Medium","urls":[],"description":"urllib3's request body not stripped after redirect from 303 status changes request method to GET","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.2,"exploitabilityScore":0.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-45803","epss":0.00062,"percentile":0.1968,"date":"2025-06-03"}],"fix":{"versions":["1.26.18"],"state":"fixed"},"advisories":[],"risk":0.02852},"relatedVulnerabilities":[{"id":"CVE-2023-45803","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-45803","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/urllib3/urllib3/commit/4e98d57809dacab1cbe625fddeec1a290c478ea9","https://github.com/urllib3/urllib3/security/advisories/GHSA-g4mx-q9vg-27p4","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4R2Y5XK3WALSR3FNAGN7JBYV2B343ZKB/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PPDPLM6UUMN55ESPQWJFLLIZY4ZKCNRX/","https://www.rfc-editor.org/rfc/rfc9110.html#name-get","https://github.com/urllib3/urllib3/commit/4e98d57809dacab1cbe625fddeec1a290c478ea9","https://github.com/urllib3/urllib3/security/advisories/GHSA-g4mx-q9vg-27p4","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4R2Y5XK3WALSR3FNAGN7JBYV2B343ZKB/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PPDPLM6UUMN55ESPQWJFLLIZY4ZKCNRX/","https://www.rfc-editor.org/rfc/rfc9110.html#name-get"],"description":"urllib3 is a user-friendly HTTP client library for Python. urllib3 previously wouldn't remove the HTTP request body when an HTTP redirect response using status 301, 302, or 303 after the request had its method changed from one that could accept a request body (like `POST`) to `GET` as is required by HTTP RFCs. Although this behavior is not specified in the section for redirects, it can be inferred by piecing together information from different sections and we have observed the behavior in other major HTTP client implementations like curl and web browsers. Because the vulnerability requires a previously trusted service to become compromised in order to have an impact on confidentiality we believe the exploitability of this vulnerability is low. Additionally, many users aren't putting sensitive data in HTTP request bodies, if this is the case then this vulnerability isn't exploitable. Both of the following conditions must be true to be affected by this vulnerability: 1. Using urllib3 and submitting sensitive information in the HTTP request body (such as form data or JSON) and 2. The origin service is compromised and starts redirecting using 301, 302, or 303 to a malicious peer or the redirected-to service becomes compromised. This issue has been addressed in versions 1.26.18 and 2.0.7 and users are advised to update to resolve this issue. Users unable to update should disable redirects for services that aren't expecting to respond with redirects with `redirects=False` and disable automatic redirects with `redirects=False` and handle 301, 302, and 303 redirects manually by stripping the HTTP request body.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.2,"exploitabilityScore":0.6,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.2,"exploitabilityScore":0.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-45803","epss":0.00062,"percentile":0.1968,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"urllib3","version":"1.26.16"}},"found":{"versionConstraint":">=0,<1.26.18 (python)","vulnerabilityID":"GHSA-g4mx-q9vg-27p4"},"fix":{"suggestedVersion":"1.26.18"}}],"artifact":{"id":"f7b86876c271b569","name":"urllib3","version":"1.26.16","type":"python","locations":[{"path":"/usr/lib/python3.10/dist-packages/urllib3-1.26.16.dist-info/METADATA","accessPath":"/usr/lib/python3.10/dist-packages/urllib3-1.26.16.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3.10/dist-packages/urllib3-1.26.16.dist-info/RECORD","accessPath":"/usr/lib/python3.10/dist-packages/urllib3-1.26.16.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/usr/lib/python3.10/dist-packages/urllib3-1.26.16.dist-info/top_level.txt","accessPath":"/usr/lib/python3.10/dist-packages/urllib3-1.26.16.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:urllib3:1.26.16:*:*:*:*:*:*:*"],"purl":"pkg:pypi/urllib3@1.26.16","upstreams":[]}},{"vulnerability":{"id":"GHSA-34jh-p97f-mpxf","dataSource":"https://github.com/advisories/GHSA-34jh-p97f-mpxf","namespace":"github:language:python","severity":"Medium","urls":[],"description":"urllib3's Proxy-Authorization request header isn't stripped during cross-origin redirects","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.4,"exploitabilityScore":0.8,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-37891","epss":0.00033,"percentile":0.08049,"date":"2025-06-03"}],"fix":{"versions":["1.26.19"],"state":"fixed"},"advisories":[],"risk":0.01551},"relatedVulnerabilities":[{"id":"CVE-2024-37891","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-37891","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/urllib3/urllib3/commit/accff72ecc2f6cf5a76d9570198a93ac7c90270e","https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf","https://github.com/urllib3/urllib3/commit/accff72ecc2f6cf5a76d9570198a93ac7c90270e","https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf","https://security.netapp.com/advisory/ntap-20240822-0003/","https://www.vicarius.io/vsociety/posts/proxy-authorization-header-handling-vulnerability-in-urllib3-cve-2024-37891"],"description":"urllib3 is a user-friendly HTTP client library for Python. When using urllib3's proxy support with `ProxyManager`, the `Proxy-Authorization` header is only sent to the configured proxy, as expected. However, when sending HTTP requests *without* using urllib3's proxy support, it's possible to accidentally configure the `Proxy-Authorization` header even though it won't have any effect as the request is not using a forwarding proxy or a tunneling proxy. In those cases, urllib3 doesn't treat the `Proxy-Authorization` HTTP header as one carrying authentication material and thus doesn't strip the header on cross-origin redirects. Because this is a highly unlikely scenario, we believe the severity of this vulnerability is low for almost all users. Out of an abundance of caution urllib3 will automatically strip the `Proxy-Authorization` header during cross-origin redirects to avoid the small chance that users are doing this on accident. Users should use urllib3's proxy support or disable automatic redirects to achieve safe processing of the `Proxy-Authorization` header, but we still decided to strip the header by default in order to further protect users who aren't using the correct approach. We believe the number of usages affected by this advisory is low. It requires all of the following to be true to be exploited: 1. Setting the `Proxy-Authorization` header without using urllib3's built-in proxy support. 2. Not disabling HTTP redirects. 3. Either not using an HTTPS origin server or for the proxy or target origin to redirect to a malicious origin. Users are advised to update to either version 1.26.19 or version 2.2.2. Users unable to upgrade may use the `Proxy-Authorization` header with urllib3's `ProxyManager`, disable HTTP redirects using `redirects=False` when sending requests, or not user the `Proxy-Authorization` header as mitigations.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.4,"exploitabilityScore":0.8,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-37891","epss":0.00033,"percentile":0.08049,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"urllib3","version":"1.26.16"}},"found":{"versionConstraint":"<1.26.19 (python)","vulnerabilityID":"GHSA-34jh-p97f-mpxf"},"fix":{"suggestedVersion":"1.26.19"}}],"artifact":{"id":"f7b86876c271b569","name":"urllib3","version":"1.26.16","type":"python","locations":[{"path":"/usr/lib/python3.10/dist-packages/urllib3-1.26.16.dist-info/METADATA","accessPath":"/usr/lib/python3.10/dist-packages/urllib3-1.26.16.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3.10/dist-packages/urllib3-1.26.16.dist-info/RECORD","accessPath":"/usr/lib/python3.10/dist-packages/urllib3-1.26.16.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/usr/lib/python3.10/dist-packages/urllib3-1.26.16.dist-info/top_level.txt","accessPath":"/usr/lib/python3.10/dist-packages/urllib3-1.26.16.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:urllib3:1.26.16:*:*:*:*:*:*:*"],"purl":"pkg:pypi/urllib3@1.26.16","upstreams":[]}},{"vulnerability":{"id":"GHSA-g7vv-2v7x-gj9p","dataSource":"https://github.com/advisories/GHSA-g7vv-2v7x-gj9p","namespace":"github:language:python","severity":"Low","urls":[],"description":"tqdm CLI arguments injection attack","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:R/S:U/C:L/I:L/A:N","metrics":{"baseScore":3.9,"exploitabilityScore":1.4,"impactScore":2.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-34062","epss":0.00044,"percentile":0.13061,"date":"2025-06-03"}],"fix":{"versions":["4.66.3"],"state":"fixed"},"advisories":[],"risk":0.01518},"relatedVulnerabilities":[{"id":"CVE-2024-34062","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-34062","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/tqdm/tqdm/commit/4e613f84ed2ae029559f539464df83fa91feb316","https://github.com/tqdm/tqdm/security/advisories/GHSA-g7vv-2v7x-gj9p","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PA3GIGHPWAHCTT4UF57LTPZGWHAX3GW6/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QRECVQCCESHBS3UJOWNXQUIX725TKNY6/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VA337CYUS4SLRFV2P6MX6MZ2LKFURKJC/","https://github.com/tqdm/tqdm/commit/4e613f84ed2ae029559f539464df83fa91feb316","https://github.com/tqdm/tqdm/security/advisories/GHSA-g7vv-2v7x-gj9p","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PA3GIGHPWAHCTT4UF57LTPZGWHAX3GW6/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QRECVQCCESHBS3UJOWNXQUIX725TKNY6/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VA337CYUS4SLRFV2P6MX6MZ2LKFURKJC/"],"description":"tqdm is an open source progress bar for Python and CLI. Any optional non-boolean CLI arguments (e.g. `--delim`, `--buf-size`, `--manpath`) are passed through python's `eval`, allowing arbitrary code execution. This issue is only locally exploitable and had been addressed in release version 4.66.3. All users are advised to upgrade. There are no known workarounds for this vulnerability.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:R/S:U/C:L/I:L/A:L","metrics":{"baseScore":4.8,"exploitabilityScore":1.4,"impactScore":3.4},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-34062","epss":0.00044,"percentile":0.13061,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"tqdm","version":"4.65.0"}},"found":{"versionConstraint":">=4.4.0,<4.66.3 (python)","vulnerabilityID":"GHSA-g7vv-2v7x-gj9p"},"fix":{"suggestedVersion":"4.66.3"}}],"artifact":{"id":"d0dabbe40ed5ba8f","name":"tqdm","version":"4.65.0","type":"python","locations":[{"path":"/usr/lib/python3.10/dist-packages/tqdm-4.65.0.dist-info/METADATA","accessPath":"/usr/lib/python3.10/dist-packages/tqdm-4.65.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3.10/dist-packages/tqdm-4.65.0.dist-info/RECORD","accessPath":"/usr/lib/python3.10/dist-packages/tqdm-4.65.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/usr/lib/python3.10/dist-packages/tqdm-4.65.0.dist-info/top_level.txt","accessPath":"/usr/lib/python3.10/dist-packages/tqdm-4.65.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MPLv2.0, MIT Licences"],"cpes":["cpe:2.3:a:python-tqdm:python-tqdm:4.65.0:*:*:*:*:*:*:*","cpe:2.3:a:python-tqdm:python_tqdm:4.65.0:*:*:*:*:*:*:*","cpe:2.3:a:python_tqdm:python-tqdm:4.65.0:*:*:*:*:*:*:*","cpe:2.3:a:python_tqdm:python_tqdm:4.65.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python-tqdm:4.65.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python_tqdm:4.65.0:*:*:*:*:*:*:*","cpe:2.3:a:python-tqdm:tqdm:4.65.0:*:*:*:*:*:*:*","cpe:2.3:a:python_tqdm:tqdm:4.65.0:*:*:*:*:*:*:*","cpe:2.3:a:tqdm:python-tqdm:4.65.0:*:*:*:*:*:*:*","cpe:2.3:a:tqdm:python_tqdm:4.65.0:*:*:*:*:*:*:*","cpe:2.3:a:python:tqdm:4.65.0:*:*:*:*:*:*:*","cpe:2.3:a:tqdm:tqdm:4.65.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/tqdm@4.65.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-9wx4-h78v-vm56","dataSource":"https://github.com/advisories/GHSA-9wx4-h78v-vm56","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Requests `Session` object does not verify requests after making first request with verify=False","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N","metrics":{"baseScore":5.6,"exploitabilityScore":0.4,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-35195","epss":0.00009,"percentile":0.00549,"date":"2025-06-03"}],"fix":{"versions":["2.32.0"],"state":"fixed"},"advisories":[],"risk":0.004770000000000001},"relatedVulnerabilities":[{"id":"CVE-2024-35195","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-35195","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac","https://github.com/psf/requests/pull/6655","https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ/","https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac","https://github.com/psf/requests/pull/6655","https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ/"],"description":"Requests is a HTTP library. Prior to 2.32.0, when making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same host will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool. This vulnerability is fixed in 2.32.0.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N","metrics":{"baseScore":5.6,"exploitabilityScore":0.4,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-35195","epss":0.00009,"percentile":0.00549,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"requests","version":"2.29.0"}},"found":{"versionConstraint":"<2.32.0 (python)","vulnerabilityID":"GHSA-9wx4-h78v-vm56"},"fix":{"suggestedVersion":"2.32.0"}}],"artifact":{"id":"7e0742443744a00c","name":"requests","version":"2.29.0","type":"python","locations":[{"path":"/usr/lib/python3.10/dist-packages/requests-2.29.0.dist-info/METADATA","accessPath":"/usr/lib/python3.10/dist-packages/requests-2.29.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3.10/dist-packages/requests-2.29.0.dist-info/RECORD","accessPath":"/usr/lib/python3.10/dist-packages/requests-2.29.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/usr/lib/python3.10/dist-packages/requests-2.29.0.dist-info/top_level.txt","accessPath":"/usr/lib/python3.10/dist-packages/requests-2.29.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache 2.0"],"cpes":["cpe:2.3:a:python:requests:2.29.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/requests@2.29.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-pjjw-qhg8-p2p9","dataSource":"https://github.com/advisories/GHSA-pjjw-qhg8-p2p9","namespace":"github:language:python","severity":"Medium","urls":[],"description":"aiohttp has vulnerable dependency that is vulnerable to request smuggling","cvss":[],"fix":{"versions":["3.8.6"],"state":"fixed"},"advisories":[],"risk":0},"relatedVulnerabilities":[],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"aiohttp","version":"3.8.4"}},"found":{"versionConstraint":"<3.8.6 (python)","vulnerabilityID":"GHSA-pjjw-qhg8-p2p9"},"fix":{"suggestedVersion":"3.8.6"}}],"artifact":{"id":"11d61989037c7a8e","name":"aiohttp","version":"3.8.4","type":"python","locations":[{"path":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/METADATA","accessPath":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/RECORD","accessPath":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/top_level.txt","accessPath":"/usr/lib/python3.10/dist-packages/aiohttp-3.8.4.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache 2"],"cpes":["cpe:2.3:a:python-aiohttp:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python-aiohttp:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python-aiohttp:aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python-aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python_aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:aiohttp:3.8.4:*:*:*:*:*:*:*","cpe:2.3:a:python:aiohttp:3.8.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/aiohttp@3.8.4","upstreams":[]}}],"source":{"type":"sbom-file","target":"imaginer-syft.json"},"distro":{"name":"","version":"","idLike":null},"descriptor":{"name":"grype","version":"0.92.2","configuration":{"output":["json=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-06-04/imaginer-grype.json","template=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-06-04/imaginer-grype.html"],"file":"","pretty":false,"distro":"","add-cpes-if-none":false,"output-template-file":"../html.tmpl","check-for-app-update":true,"only-fixed":false,"only-notfixed":false,"ignore-wontfix":"","platform":"","search":{"scope":"squashed","unindexed-archives":false,"indexed-archives":true},"ignore":[{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"kernel-headers","version":"","language":"","type":"rpm","location":"","upstream-name":"kernel"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux(-.*)?-headers-.*","version":"","language":"","type":"deb","location":"","upstream-name":"linux.*"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux-libc-dev","version":"","language":"","type":"deb","location":"","upstream-name":"linux"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"}],"exclude":[],"externalSources":{"enable":false,"maven":{"searchUpstreamBySha1":true,"baseUrl":"https://search.maven.org/solrsearch/select","rateLimit":300000000}},"match":{"java":{"using-cpes":false},"jvm":{"using-cpes":true},"dotnet":{"using-cpes":false},"golang":{"using-cpes":false,"always-use-cpe-for-stdlib":true,"allow-main-module-pseudo-version-comparison":false},"javascript":{"using-cpes":false},"python":{"using-cpes":false},"ruby":{"using-cpes":false},"rust":{"using-cpes":false},"stock":{"using-cpes":true}},"fail-on-severity":"","registry":{"insecure-skip-tls-verify":false,"insecure-use-http":false,"auth":null,"ca-cert":""},"show-suppressed":false,"by-cve":false,"SortBy":{"sort-by":"risk"},"name":"","default-image-pull-source":"","vex-documents":[],"vex-add":[],"match-upstream-kernel-headers":false,"db":{"cache-dir":"/Users/alan/Library/Caches/grype/db","update-url":"https://grype.anchore.io/databases","ca-cert":"","auto-update":true,"validate-by-hash-on-start":true,"validate-age":true,"max-allowed-built-age":432000000000000,"require-update-check":false,"update-available-timeout":30000000000,"update-download-timeout":300000000000,"max-update-check-frequency":7200000000000},"exp":{},"dev":{"db":{"debug":false}}},"db":{"status":{"schemaVersion":"v6.0.2","from":"https://grype.anchore.io/databases/v6/vulnerability-db_v6.0.2_2025-06-04T01:32:23Z_1749035557.tar.zst?checksum=sha256%3A77238f4ffbc7cf72bf4dedabbb21a3d0dd3ade90fb5d9df7c4da2870f8d1a9b7","built":"2025-06-04T11:12:37Z","path":"/Users/alan/Library/Caches/grype/db/6/vulnerability.db","valid":true},"providers":{"alpine":{"captured":"2025-06-04T01:32:23Z","input":"xxh64:a6a065ece392f6d1"},"amazon":{"captured":"2025-06-04T01:32:32Z","input":"xxh64:b65d458d6858d72a"},"chainguard":{"captured":"2025-06-04T01:32:33Z","input":"xxh64:03c9c4d182d77791"},"debian":{"captured":"2025-06-04T01:32:49Z","input":"xxh64:169ceb8fbcb8d6f1"},"epss":{"captured":"2025-06-04T01:32:42Z","input":"xxh64:bf87c4c234d02346"},"github":{"captured":"2025-06-04T01:32:30Z","input":"xxh64:3dab0be50635e057"},"kev":{"captured":"2025-06-04T01:32:45Z","input":"xxh64:a934e75f468f4e09"},"mariner":{"captured":"2025-06-04T01:32:43Z","input":"xxh64:ac698752085c186f"},"nvd":{"captured":"2025-06-04T01:33:28Z","input":"xxh64:389887843a59d29c"},"oracle":{"captured":"2025-06-04T01:32:35Z","input":"xxh64:0b8aabcfb6505b62"},"rhel":{"captured":"2025-06-04T04:49:10Z","input":"xxh64:947d0caeb19e9ccc"},"sles":{"captured":"2025-06-04T01:32:34Z","input":"xxh64:1c50b1219296628a"},"ubuntu":{"captured":"2025-06-04T01:33:14Z","input":"xxh64:71e22d5c5bbe7d14"},"wolfi":{"captured":"2025-06-04T01:32:42Z","input":"xxh64:e68fca5a870c6769"}}},"timestamp":"2025-06-04T19:25:52.837572+01:00"}}
