{"matches":[{"vulnerability":{"id":"GHSA-248v-346w-9cwc","dataSource":"https://github.com/advisories/GHSA-248v-346w-9cwc","namespace":"github:language:python","severity":"Low","urls":[],"description":"Certifi removes GLOBALTRUST root certificate","cvss":[],"epss":[{"cve":"CVE-2024-39689","epss":0.01928,"percentile":0.82507,"date":"2025-06-03"}],"fix":{"versions":["2024.7.4"],"state":"fixed"},"advisories":[],"risk":0.5783999999999999},"relatedVulnerabilities":[{"id":"CVE-2024-39689","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-39689","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/certifi/python-certifi/commit/bd8153872e9c6fc98f4023df9c2deaffea2fa463","https://github.com/certifi/python-certifi/security/advisories/GHSA-248v-346w-9cwc","https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI","https://github.com/certifi/python-certifi/commit/bd8153872e9c6fc98f4023df9c2deaffea2fa463","https://github.com/certifi/python-certifi/security/advisories/GHSA-248v-346w-9cwc","https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI","https://security.netapp.com/advisory/ntap-20241206-0001/"],"description":"Certifi is a curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts. Certifi starting in 2021.5.30 and prior to 2024.7.4 recognized root certificates from `GLOBALTRUST`. Certifi 2024.7.04 removes root certificates from `GLOBALTRUST` from the root store. These are in the process of being removed from Mozilla's trust store. `GLOBALTRUST`'s root certificates are being removed pursuant to an investigation which identified \"long-running and unresolved compliance issues.\"","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-39689","epss":0.01928,"percentile":0.82507,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"certifi","version":"2024.6.2"}},"found":{"versionConstraint":">=2021.5.30,<2024.7.4 (python)","vulnerabilityID":"GHSA-248v-346w-9cwc"},"fix":{"suggestedVersion":"2024.7.4"}}],"artifact":{"id":"8c6d53990b20fd14","name":"certifi","version":"2024.6.2","type":"python","locations":[{"path":"/lib/certifi-2024.6.2.dist-info/METADATA","accessPath":"/lib/certifi-2024.6.2.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/certifi-2024.6.2.dist-info/RECORD","accessPath":"/lib/certifi-2024.6.2.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/certifi-2024.6.2.dist-info/top_level.txt","accessPath":"/lib/certifi-2024.6.2.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MPL-2.0"],"cpes":["cpe:2.3:a:certifi:certifi:2024.6.2:*:*:*:*:python:*:*"],"purl":"pkg:pypi/certifi@2024.6.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-5rjg-fvgr-3xxf","dataSource":"https://github.com/advisories/GHSA-5rjg-fvgr-3xxf","namespace":"github:language:python","severity":"High","urls":[],"description":"setuptools has a path traversal vulnerability in PackageIndex.download that leads to Arbitrary File Write","cvss":[],"epss":[{"cve":"CVE-2025-47273","epss":0.00435,"percentile":0.62062,"date":"2025-06-03"}],"fix":{"versions":["78.1.1"],"state":"fixed"},"advisories":[],"risk":0.32625},"relatedVulnerabilities":[{"id":"CVE-2025-47273","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-47273","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pypa/setuptools/blob/6ead555c5fb29bc57fe6105b1bffc163f56fd558/setuptools/package_index.py#L810C1-L825C88","https://github.com/pypa/setuptools/commit/250a6d17978f9f6ac3ac887091f2d32886fbbb0b","https://github.com/pypa/setuptools/issues/4946","https://github.com/pypa/setuptools/security/advisories/GHSA-5rjg-fvgr-3xxf","https://lists.debian.org/debian-lts-announce/2025/05/msg00035.html","https://github.com/pypa/setuptools/issues/4946"],"description":"setuptools is a package that allows users to download, build, install, upgrade, and uninstall Python packages. A path traversal vulnerability in `PackageIndex` is present in setuptools prior to version 78.1.1. An attacker would be allowed to write files to arbitrary locations on the filesystem with the permissions of the process running the Python code, which could escalate to remote code execution depending on the context. Version 78.1.1 fixes the issue.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:H/VA:N/SC:N/SI:N/SA:N/E:P/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":7.7},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-47273","epss":0.00435,"percentile":0.62062,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"setuptools","version":"44.0.0"}},"found":{"versionConstraint":"<78.1.1 (python)","vulnerabilityID":"GHSA-5rjg-fvgr-3xxf"},"fix":{"suggestedVersion":"78.1.1"}}],"artifact":{"id":"70198ade669f8744","name":"setuptools","version":"44.0.0","type":"python","locations":[{"path":"/lib/setuptools-44.0.0.dist-info/METADATA","accessPath":"/lib/setuptools-44.0.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/setuptools-44.0.0.dist-info/RECORD","accessPath":"/lib/setuptools-44.0.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/setuptools-44.0.0.dist-info/top_level.txt","accessPath":"/lib/setuptools-44.0.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["UNKNOWN"],"cpes":["cpe:2.3:a:python:setuptools:44.0.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/setuptools@44.0.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-5rjg-fvgr-3xxf","dataSource":"https://github.com/advisories/GHSA-5rjg-fvgr-3xxf","namespace":"github:language:python","severity":"High","urls":[],"description":"setuptools has a path traversal vulnerability in PackageIndex.download that leads to Arbitrary File Write","cvss":[],"epss":[{"cve":"CVE-2025-47273","epss":0.00435,"percentile":0.62062,"date":"2025-06-03"}],"fix":{"versions":["78.1.1"],"state":"fixed"},"advisories":[],"risk":0.32625},"relatedVulnerabilities":[{"id":"CVE-2025-47273","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-47273","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pypa/setuptools/blob/6ead555c5fb29bc57fe6105b1bffc163f56fd558/setuptools/package_index.py#L810C1-L825C88","https://github.com/pypa/setuptools/commit/250a6d17978f9f6ac3ac887091f2d32886fbbb0b","https://github.com/pypa/setuptools/issues/4946","https://github.com/pypa/setuptools/security/advisories/GHSA-5rjg-fvgr-3xxf","https://lists.debian.org/debian-lts-announce/2025/05/msg00035.html","https://github.com/pypa/setuptools/issues/4946"],"description":"setuptools is a package that allows users to download, build, install, upgrade, and uninstall Python packages. A path traversal vulnerability in `PackageIndex` is present in setuptools prior to version 78.1.1. An attacker would be allowed to write files to arbitrary locations on the filesystem with the permissions of the process running the Python code, which could escalate to remote code execution depending on the context. Version 78.1.1 fixes the issue.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:H/VA:N/SC:N/SI:N/SA:N/E:P/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":7.7},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-47273","epss":0.00435,"percentile":0.62062,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"setuptools","version":"45.2.0"}},"found":{"versionConstraint":"<78.1.1 (python)","vulnerabilityID":"GHSA-5rjg-fvgr-3xxf"},"fix":{"suggestedVersion":"78.1.1"}}],"artifact":{"id":"3832926b2c051df3","name":"setuptools","version":"45.2.0","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/setuptools-45.2.0.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/setuptools-45.2.0.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/setuptools-45.2.0.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/setuptools-45.2.0.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["UNKNOWN"],"cpes":["cpe:2.3:a:python:setuptools:45.2.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/setuptools@45.2.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-r9hx-vwmv-q579","dataSource":"https://github.com/advisories/GHSA-r9hx-vwmv-q579","namespace":"github:language:python","severity":"High","urls":[],"description":"pypa/setuptools vulnerable to Regular Expression Denial of Service (ReDoS)","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-40897","epss":0.00318,"percentile":0.54328,"date":"2025-06-03"}],"fix":{"versions":["65.5.1"],"state":"fixed"},"advisories":[],"risk":0.2385},"relatedVulnerabilities":[{"id":"CVE-2022-40897","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2022-40897","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pypa/setuptools/blob/fe8a98e696241487ba6ac9f91faa38ade939ec5d/setuptools/package_index.py#L200","https://github.com/pypa/setuptools/commit/43a9c9bfa6aa626ec2a22540bea28d2ca77964be","https://github.com/pypa/setuptools/compare/v65.5.0...v65.5.1","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H/","https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/","https://pyup.io/vulnerabilities/CVE-2022-40897/52495/","https://security.netapp.com/advisory/ntap-20230214-0001/","https://security.netapp.com/advisory/ntap-20240621-0006/","https://github.com/pypa/setuptools/blob/fe8a98e696241487ba6ac9f91faa38ade939ec5d/setuptools/package_index.py#L200","https://github.com/pypa/setuptools/commit/43a9c9bfa6aa626ec2a22540bea28d2ca77964be","https://github.com/pypa/setuptools/compare/v65.5.0...v65.5.1","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H/","https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/","https://pyup.io/vulnerabilities/CVE-2022-40897/52495/","https://security.netapp.com/advisory/ntap-20230214-0001/","https://security.netapp.com/advisory/ntap-20240621-0006/"],"description":"Python Packaging Authority (PyPA) setuptools before 65.5.1 allows remote attackers to cause a denial of service via HTML in a crafted package or custom PackageIndex page. There is a Regular Expression Denial of Service (ReDoS) in package_index.py.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-40897","epss":0.00318,"percentile":0.54328,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"setuptools","version":"44.0.0"}},"found":{"versionConstraint":"<65.5.1 (python)","vulnerabilityID":"GHSA-r9hx-vwmv-q579"},"fix":{"suggestedVersion":"65.5.1"}}],"artifact":{"id":"70198ade669f8744","name":"setuptools","version":"44.0.0","type":"python","locations":[{"path":"/lib/setuptools-44.0.0.dist-info/METADATA","accessPath":"/lib/setuptools-44.0.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/setuptools-44.0.0.dist-info/RECORD","accessPath":"/lib/setuptools-44.0.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/setuptools-44.0.0.dist-info/top_level.txt","accessPath":"/lib/setuptools-44.0.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["UNKNOWN"],"cpes":["cpe:2.3:a:python:setuptools:44.0.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/setuptools@44.0.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-r9hx-vwmv-q579","dataSource":"https://github.com/advisories/GHSA-r9hx-vwmv-q579","namespace":"github:language:python","severity":"High","urls":[],"description":"pypa/setuptools vulnerable to Regular Expression Denial of Service (ReDoS)","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-40897","epss":0.00318,"percentile":0.54328,"date":"2025-06-03"}],"fix":{"versions":["65.5.1"],"state":"fixed"},"advisories":[],"risk":0.2385},"relatedVulnerabilities":[{"id":"CVE-2022-40897","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2022-40897","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pypa/setuptools/blob/fe8a98e696241487ba6ac9f91faa38ade939ec5d/setuptools/package_index.py#L200","https://github.com/pypa/setuptools/commit/43a9c9bfa6aa626ec2a22540bea28d2ca77964be","https://github.com/pypa/setuptools/compare/v65.5.0...v65.5.1","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H/","https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/","https://pyup.io/vulnerabilities/CVE-2022-40897/52495/","https://security.netapp.com/advisory/ntap-20230214-0001/","https://security.netapp.com/advisory/ntap-20240621-0006/","https://github.com/pypa/setuptools/blob/fe8a98e696241487ba6ac9f91faa38ade939ec5d/setuptools/package_index.py#L200","https://github.com/pypa/setuptools/commit/43a9c9bfa6aa626ec2a22540bea28d2ca77964be","https://github.com/pypa/setuptools/compare/v65.5.0...v65.5.1","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H/","https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/","https://pyup.io/vulnerabilities/CVE-2022-40897/52495/","https://security.netapp.com/advisory/ntap-20230214-0001/","https://security.netapp.com/advisory/ntap-20240621-0006/"],"description":"Python Packaging Authority (PyPA) setuptools before 65.5.1 allows remote attackers to cause a denial of service via HTML in a crafted package or custom PackageIndex page. There is a Regular Expression Denial of Service (ReDoS) in package_index.py.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-40897","epss":0.00318,"percentile":0.54328,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"setuptools","version":"45.2.0"}},"found":{"versionConstraint":"<65.5.1 (python)","vulnerabilityID":"GHSA-r9hx-vwmv-q579"},"fix":{"suggestedVersion":"65.5.1"}}],"artifact":{"id":"3832926b2c051df3","name":"setuptools","version":"45.2.0","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/setuptools-45.2.0.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/setuptools-45.2.0.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/setuptools-45.2.0.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/setuptools-45.2.0.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["UNKNOWN"],"cpes":["cpe:2.3:a:python:setuptools:45.2.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/setuptools@45.2.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-cx63-2mw6-8hw5","dataSource":"https://github.com/advisories/GHSA-cx63-2mw6-8hw5","namespace":"github:language:python","severity":"High","urls":[],"description":"setuptools vulnerable to Command Injection via package URL","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.8,"exploitabilityScore":2.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-6345","epss":0.00227,"percentile":0.45699,"date":"2025-06-03"}],"fix":{"versions":["70.0.0"],"state":"fixed"},"advisories":[],"risk":0.185005},"relatedVulnerabilities":[{"id":"CVE-2024-6345","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-6345","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pypa/setuptools/commit/88807c7062788254f654ea8c03427adc859321f0","https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5","https://github.com/pypa/setuptools/commit/88807c7062788254f654ea8c03427adc859321f0","https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5"],"description":"A vulnerability in the package_index module of pypa/setuptools versions up to 69.1.1 allows for remote code execution via its download functions. These functions, which are used to download packages from URLs provided by users or retrieved from package index servers, are susceptible to code injection. If these functions are exposed to user-controlled inputs, such as package URLs, they can execute arbitrary commands on the system. The issue is fixed in version 70.0.","cvss":[{"source":"security@huntr.dev","type":"Secondary","version":"3.0","vector":"CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.8,"exploitabilityScore":2.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-6345","epss":0.00227,"percentile":0.45699,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"setuptools","version":"44.0.0"}},"found":{"versionConstraint":"<70.0.0 (python)","vulnerabilityID":"GHSA-cx63-2mw6-8hw5"},"fix":{"suggestedVersion":"70.0.0"}}],"artifact":{"id":"70198ade669f8744","name":"setuptools","version":"44.0.0","type":"python","locations":[{"path":"/lib/setuptools-44.0.0.dist-info/METADATA","accessPath":"/lib/setuptools-44.0.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/setuptools-44.0.0.dist-info/RECORD","accessPath":"/lib/setuptools-44.0.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/setuptools-44.0.0.dist-info/top_level.txt","accessPath":"/lib/setuptools-44.0.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["UNKNOWN"],"cpes":["cpe:2.3:a:python:setuptools:44.0.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/setuptools@44.0.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-cx63-2mw6-8hw5","dataSource":"https://github.com/advisories/GHSA-cx63-2mw6-8hw5","namespace":"github:language:python","severity":"High","urls":[],"description":"setuptools vulnerable to Command Injection via package URL","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.8,"exploitabilityScore":2.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-6345","epss":0.00227,"percentile":0.45699,"date":"2025-06-03"}],"fix":{"versions":["70.0.0"],"state":"fixed"},"advisories":[],"risk":0.185005},"relatedVulnerabilities":[{"id":"CVE-2024-6345","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-6345","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pypa/setuptools/commit/88807c7062788254f654ea8c03427adc859321f0","https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5","https://github.com/pypa/setuptools/commit/88807c7062788254f654ea8c03427adc859321f0","https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5"],"description":"A vulnerability in the package_index module of pypa/setuptools versions up to 69.1.1 allows for remote code execution via its download functions. These functions, which are used to download packages from URLs provided by users or retrieved from package index servers, are susceptible to code injection. If these functions are exposed to user-controlled inputs, such as package URLs, they can execute arbitrary commands on the system. The issue is fixed in version 70.0.","cvss":[{"source":"security@huntr.dev","type":"Secondary","version":"3.0","vector":"CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.8,"exploitabilityScore":2.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-6345","epss":0.00227,"percentile":0.45699,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"setuptools","version":"45.2.0"}},"found":{"versionConstraint":"<70.0.0 (python)","vulnerabilityID":"GHSA-cx63-2mw6-8hw5"},"fix":{"suggestedVersion":"70.0.0"}}],"artifact":{"id":"3832926b2c051df3","name":"setuptools","version":"45.2.0","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/setuptools-45.2.0.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/setuptools-45.2.0.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/setuptools-45.2.0.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/setuptools-45.2.0.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["UNKNOWN"],"cpes":["cpe:2.3:a:python:setuptools:45.2.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/setuptools@45.2.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-5xp3-jfq3-5q8x","dataSource":"https://github.com/advisories/GHSA-5xp3-jfq3-5q8x","namespace":"github:language:python","severity":"High","urls":[],"description":"Improper Input Validation in pip","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:N/I:H/A:N","metrics":{"baseScore":5.7,"exploitabilityScore":2.1,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-3572","epss":0.0024,"percentile":0.4753,"date":"2025-06-03"}],"fix":{"versions":["21.1"],"state":"fixed"},"advisories":[],"risk":0.15839999999999999},"relatedVulnerabilities":[{"id":"CVE-2021-3572","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2021-3572","namespace":"nvd:cpe","severity":"Medium","urls":["https://bugzilla.redhat.com/show_bug.cgi?id=1962856","https://security.netapp.com/advisory/ntap-20240621-0006/","https://www.oracle.com/security-alerts/cpuapr2022.html","https://www.oracle.com/security-alerts/cpujul2022.html","https://bugzilla.redhat.com/show_bug.cgi?id=1962856","https://security.netapp.com/advisory/ntap-20240621-0006/","https://www.oracle.com/security-alerts/cpuapr2022.html","https://www.oracle.com/security-alerts/cpujul2022.html"],"description":"A flaw was found in python-pip in the way it handled Unicode separators in git references. A remote attacker could possibly use this issue to install a different revision on a repository. The highest threat from this vulnerability is to data integrity. This is fixed in python-pip version 21.1.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:N/I:H/A:N","metrics":{"baseScore":5.7,"exploitabilityScore":2.1,"impactScore":3.6},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:M/Au:S/C:N/I:P/A:N","metrics":{"baseScore":3.5,"exploitabilityScore":6.9,"impactScore":2.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-3572","epss":0.0024,"percentile":0.4753,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"pip","version":"20.0.2"}},"found":{"versionConstraint":"<21.1 (python)","vulnerabilityID":"GHSA-5xp3-jfq3-5q8x"},"fix":{"suggestedVersion":"21.1"}}],"artifact":{"id":"ec14646fe07bc803","name":"pip","version":"20.0.2","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/pip-20.0.2.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/pip-20.0.2.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/pip-20.0.2.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/pip-20.0.2.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:pip_developers_project:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers_project:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev_project:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev_project:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers_project:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_devproject:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_devproject:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev_project:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa-dev:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa-dev:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_devproject:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa-dev:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip:pip:20.0.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/pip@20.0.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-5xp3-jfq3-5q8x","dataSource":"https://github.com/advisories/GHSA-5xp3-jfq3-5q8x","namespace":"github:language:python","severity":"High","urls":[],"description":"Improper Input Validation in pip","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:N/I:H/A:N","metrics":{"baseScore":5.7,"exploitabilityScore":2.1,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-3572","epss":0.0024,"percentile":0.4753,"date":"2025-06-03"}],"fix":{"versions":["21.1"],"state":"fixed"},"advisories":[],"risk":0.15839999999999999},"relatedVulnerabilities":[{"id":"CVE-2021-3572","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2021-3572","namespace":"nvd:cpe","severity":"Medium","urls":["https://bugzilla.redhat.com/show_bug.cgi?id=1962856","https://security.netapp.com/advisory/ntap-20240621-0006/","https://www.oracle.com/security-alerts/cpuapr2022.html","https://www.oracle.com/security-alerts/cpujul2022.html","https://bugzilla.redhat.com/show_bug.cgi?id=1962856","https://security.netapp.com/advisory/ntap-20240621-0006/","https://www.oracle.com/security-alerts/cpuapr2022.html","https://www.oracle.com/security-alerts/cpujul2022.html"],"description":"A flaw was found in python-pip in the way it handled Unicode separators in git references. A remote attacker could possibly use this issue to install a different revision on a repository. The highest threat from this vulnerability is to data integrity. This is fixed in python-pip version 21.1.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:N/I:H/A:N","metrics":{"baseScore":5.7,"exploitabilityScore":2.1,"impactScore":3.6},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:M/Au:S/C:N/I:P/A:N","metrics":{"baseScore":3.5,"exploitabilityScore":6.9,"impactScore":2.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-3572","epss":0.0024,"percentile":0.4753,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"pip","version":"20.0.2"}},"found":{"versionConstraint":"<21.1 (python)","vulnerabilityID":"GHSA-5xp3-jfq3-5q8x"},"fix":{"suggestedVersion":"21.1"}}],"artifact":{"id":"9b01d9de29e56f0a","name":"pip","version":"20.0.2","type":"python","locations":[{"path":"/lib/pip-20.0.2.dist-info/METADATA","accessPath":"/lib/pip-20.0.2.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/pip-20.0.2.dist-info/RECORD","accessPath":"/lib/pip-20.0.2.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/pip-20.0.2.dist-info/top_level.txt","accessPath":"/lib/pip-20.0.2.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:pip_developers_project:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers_project:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev_project:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev_project:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers_project:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_devproject:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_devproject:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev_project:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa-dev:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa-dev:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_devproject:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa-dev:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip:pip:20.0.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/pip@20.0.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-qwmp-2cf2-g9g6","dataSource":"https://github.com/advisories/GHSA-qwmp-2cf2-g9g6","namespace":"github:language:python","severity":"High","urls":[],"description":"pypa/wheel vulnerable to Regular Expression denial of service (ReDoS)","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-40898","epss":0.00108,"percentile":0.30278,"date":"2025-06-03"}],"fix":{"versions":["0.38.1"],"state":"fixed"},"advisories":[],"risk":0.08099999999999999},"relatedVulnerabilities":[{"id":"CVE-2022-40898","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2022-40898","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pypa/wheel/blob/main/src/wheel/wheelfile.py#L18","https://pypi.org/project/wheel/","https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/","https://github.com/pypa/wheel/blob/main/src/wheel/wheelfile.py#L18","https://pypi.org/project/wheel/","https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/"],"description":"An issue discovered in Python Packaging Authority (PyPA) Wheel 0.37.1 and earlier allows remote attackers to cause a denial of service via attacker controlled input to wheel cli.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-40898","epss":0.00108,"percentile":0.30278,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"wheel","version":"0.34.2"}},"found":{"versionConstraint":"<0.38.1 (python)","vulnerabilityID":"GHSA-qwmp-2cf2-g9g6"},"fix":{"suggestedVersion":"0.38.1"}}],"artifact":{"id":"0241b729b64b456a","name":"wheel","version":"0.34.2","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/wheel-0.34.2.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/wheel-0.34.2.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/wheel-0.34.2.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/wheel-0.34.2.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:daniel_holth_project:python-wheel:0.34.2:*:*:*:*:*:*:*","cpe:2.3:a:daniel_holth_project:python_wheel:0.34.2:*:*:*:*:*:*:*","cpe:2.3:a:daniel_holthproject:python-wheel:0.34.2:*:*:*:*:*:*:*","cpe:2.3:a:daniel_holthproject:python_wheel:0.34.2:*:*:*:*:*:*:*","cpe:2.3:a:dholth_project:python-wheel:0.34.2:*:*:*:*:*:*:*","cpe:2.3:a:dholth_project:python_wheel:0.34.2:*:*:*:*:*:*:*","cpe:2.3:a:daniel_holth_project:wheel:0.34.2:*:*:*:*:*:*:*","cpe:2.3:a:dholthproject:python-wheel:0.34.2:*:*:*:*:*:*:*","cpe:2.3:a:dholthproject:python_wheel:0.34.2:*:*:*:*:*:*:*","cpe:2.3:a:daniel_holth:python-wheel:0.34.2:*:*:*:*:*:*:*","cpe:2.3:a:daniel_holth:python_wheel:0.34.2:*:*:*:*:*:*:*","cpe:2.3:a:daniel_holthproject:wheel:0.34.2:*:*:*:*:*:*:*","cpe:2.3:a:python-wheel:python-wheel:0.34.2:*:*:*:*:*:*:*","cpe:2.3:a:python-wheel:python_wheel:0.34.2:*:*:*:*:*:*:*","cpe:2.3:a:python_wheel:python-wheel:0.34.2:*:*:*:*:*:*:*","cpe:2.3:a:python_wheel:python_wheel:0.34.2:*:*:*:*:*:*:*","cpe:2.3:a:dholth_project:wheel:0.34.2:*:*:*:*:*:*:*","cpe:2.3:a:dholth:python-wheel:0.34.2:*:*:*:*:*:*:*","cpe:2.3:a:dholth:python_wheel:0.34.2:*:*:*:*:*:*:*","cpe:2.3:a:dholthproject:wheel:0.34.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python-wheel:0.34.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python_wheel:0.34.2:*:*:*:*:*:*:*","cpe:2.3:a:daniel_holth:wheel:0.34.2:*:*:*:*:*:*:*","cpe:2.3:a:python-wheel:wheel:0.34.2:*:*:*:*:*:*:*","cpe:2.3:a:python_wheel:wheel:0.34.2:*:*:*:*:*:*:*","cpe:2.3:a:wheel:python-wheel:0.34.2:*:*:*:*:*:*:*","cpe:2.3:a:wheel:python_wheel:0.34.2:*:*:*:*:*:*:*","cpe:2.3:a:dholth:wheel:0.34.2:*:*:*:*:*:*:*","cpe:2.3:a:python:wheel:0.34.2:*:*:*:*:*:*:*","cpe:2.3:a:wheel:wheel:0.34.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/wheel@0.34.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-79v4-65xg-pq4g","dataSource":"https://github.com/advisories/GHSA-79v4-65xg-pq4g","namespace":"github:language:python","severity":"Low","urls":[],"description":"Vulnerable OpenSSL included in cryptography wheels","cvss":[],"epss":[{"cve":"CVE-2024-12797","epss":0.0013,"percentile":0.33811,"date":"2025-06-03"}],"fix":{"versions":["44.0.1"],"state":"fixed"},"advisories":[],"risk":0.039},"relatedVulnerabilities":[{"id":"CVE-2024-12797","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-12797","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/openssl/openssl/commit/738d4f9fdeaad57660dcba50a619fafced3fd5e9","https://github.com/openssl/openssl/commit/798779d43494549b611233f92652f0da5328fbe7","https://github.com/openssl/openssl/commit/87ebd203feffcf92ad5889df92f90bb0ee10a699","https://openssl-library.org/news/secadv/20250211.txt","http://www.openwall.com/lists/oss-security/2025/02/11/3","http://www.openwall.com/lists/oss-security/2025/02/11/4","https://security.netapp.com/advisory/ntap-20250214-0001/"],"description":"Issue summary: Clients using RFC7250 Raw Public Keys (RPKs) to authenticate a\nserver may fail to notice that the server was not authenticated, because\nhandshakes don't abort as expected when the SSL_VERIFY_PEER verification mode\nis set.\n\nImpact summary: TLS and DTLS connections using raw public keys may be\nvulnerable to man-in-middle attacks when server authentication failure is not\ndetected by clients.\n\nRPKs are disabled by default in both TLS clients and TLS servers.  The issue\nonly arises when TLS clients explicitly enable RPK use by the server, and the\nserver, likewise, enables sending of an RPK instead of an X.509 certificate\nchain.  The affected clients are those that then rely on the handshake to\nfail when the server's RPK fails to match one of the expected public keys,\nby setting the verification mode to SSL_VERIFY_PEER.\n\nClients that enable server-side raw public keys can still find out that raw\npublic key verification failed by calling SSL_get_verify_result(), and those\nthat do, and take appropriate action, are not affected.  This issue was\nintroduced in the initial implementation of RPK support in OpenSSL 3.2.\n\nThe FIPS modules in 3.4, 3.3, 3.2, 3.1 and 3.0 are not affected by this issue.","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:L","metrics":{"baseScore":6.3,"exploitabilityScore":2.9,"impactScore":3.4},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-12797","epss":0.0013,"percentile":0.33811,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"42.0.8"}},"found":{"versionConstraint":">=42.0.0,<44.0.1 (python)","vulnerabilityID":"GHSA-79v4-65xg-pq4g"},"fix":{"suggestedVersion":"44.0.1"}}],"artifact":{"id":"0eb319b6ec444ffc","name":"cryptography","version":"42.0.8","type":"python","locations":[{"path":"/lib/cryptography-42.0.8.dist-info/METADATA","accessPath":"/lib/cryptography-42.0.8.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/cryptography-42.0.8.dist-info/RECORD","accessPath":"/lib/cryptography-42.0.8.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/cryptography-42.0.8.dist-info/top_level.txt","accessPath":"/lib/cryptography-42.0.8.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache-2.0 OR BSD-3-Clause"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:42.0.8:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:42.0.8:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@42.0.8","upstreams":[]}},{"vulnerability":{"id":"GHSA-mq26-g339-26xf","dataSource":"https://github.com/advisories/GHSA-mq26-g339-26xf","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Command Injection in pip when used with Mercurial","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-5752","epss":0.0004,"percentile":0.11691,"date":"2025-06-03"}],"fix":{"versions":["23.3"],"state":"fixed"},"advisories":[],"risk":0.021},"relatedVulnerabilities":[{"id":"CVE-2023-5752","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-5752","namespace":"nvd:cpe","severity":"Low","urls":["https://github.com/pypa/pip/pull/12306","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/622OZXWG72ISQPLM5Y57YCVIMWHD4C3U/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/65UKKF5LBHEFDCUSPBHUN4IHYX7SRMHH/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FXUVMJM25PUAZRQZBF54OFVKTY3MINPW/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KFC2SPFG5FLCZBYY2K3T5MFW2D22NG6E/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YBSB3SUPQ3VIFYUMHPO3MEQI4BJAXKCZ/","https://mail.python.org/archives/list/security-announce@python.org/thread/F4PL35U6X4VVHZ5ILJU3PWUWN7H7LZXL/","https://github.com/pypa/pip/pull/12306","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/622OZXWG72ISQPLM5Y57YCVIMWHD4C3U/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/65UKKF5LBHEFDCUSPBHUN4IHYX7SRMHH/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FXUVMJM25PUAZRQZBF54OFVKTY3MINPW/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KFC2SPFG5FLCZBYY2K3T5MFW2D22NG6E/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YBSB3SUPQ3VIFYUMHPO3MEQI4BJAXKCZ/","https://mail.python.org/archives/list/security-announce@python.org/thread/F4PL35U6X4VVHZ5ILJU3PWUWN7H7LZXL/"],"description":"When installing a package from a Mercurial VCS URL  (ie \"pip install \nhg+...\") with pip prior to v23.3, the specified Mercurial revision could\n be used to inject arbitrary configuration options to the \"hg clone\" \ncall (ie \"--config\"). Controlling the Mercurial configuration can modify\n how and which repository is installed. This vulnerability does not \naffect users who aren't installing from Mercurial.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:N","metrics":{"baseScore":3.3,"exploitabilityScore":1.9,"impactScore":1.5},"vendorMetadata":{}},{"source":"cna@python.org","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-5752","epss":0.0004,"percentile":0.11691,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"pip","version":"20.0.2"}},"found":{"versionConstraint":"<23.3 (python)","vulnerabilityID":"GHSA-mq26-g339-26xf"},"fix":{"suggestedVersion":"23.3"}}],"artifact":{"id":"9b01d9de29e56f0a","name":"pip","version":"20.0.2","type":"python","locations":[{"path":"/lib/pip-20.0.2.dist-info/METADATA","accessPath":"/lib/pip-20.0.2.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/pip-20.0.2.dist-info/RECORD","accessPath":"/lib/pip-20.0.2.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/pip-20.0.2.dist-info/top_level.txt","accessPath":"/lib/pip-20.0.2.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:pip_developers_project:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers_project:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev_project:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev_project:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers_project:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_devproject:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_devproject:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev_project:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa-dev:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa-dev:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_devproject:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa-dev:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip:pip:20.0.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/pip@20.0.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-mq26-g339-26xf","dataSource":"https://github.com/advisories/GHSA-mq26-g339-26xf","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Command Injection in pip when used with Mercurial","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-5752","epss":0.0004,"percentile":0.11691,"date":"2025-06-03"}],"fix":{"versions":["23.3"],"state":"fixed"},"advisories":[],"risk":0.021},"relatedVulnerabilities":[{"id":"CVE-2023-5752","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-5752","namespace":"nvd:cpe","severity":"Low","urls":["https://github.com/pypa/pip/pull/12306","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/622OZXWG72ISQPLM5Y57YCVIMWHD4C3U/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/65UKKF5LBHEFDCUSPBHUN4IHYX7SRMHH/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FXUVMJM25PUAZRQZBF54OFVKTY3MINPW/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KFC2SPFG5FLCZBYY2K3T5MFW2D22NG6E/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YBSB3SUPQ3VIFYUMHPO3MEQI4BJAXKCZ/","https://mail.python.org/archives/list/security-announce@python.org/thread/F4PL35U6X4VVHZ5ILJU3PWUWN7H7LZXL/","https://github.com/pypa/pip/pull/12306","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/622OZXWG72ISQPLM5Y57YCVIMWHD4C3U/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/65UKKF5LBHEFDCUSPBHUN4IHYX7SRMHH/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FXUVMJM25PUAZRQZBF54OFVKTY3MINPW/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KFC2SPFG5FLCZBYY2K3T5MFW2D22NG6E/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YBSB3SUPQ3VIFYUMHPO3MEQI4BJAXKCZ/","https://mail.python.org/archives/list/security-announce@python.org/thread/F4PL35U6X4VVHZ5ILJU3PWUWN7H7LZXL/"],"description":"When installing a package from a Mercurial VCS URL  (ie \"pip install \nhg+...\") with pip prior to v23.3, the specified Mercurial revision could\n be used to inject arbitrary configuration options to the \"hg clone\" \ncall (ie \"--config\"). Controlling the Mercurial configuration can modify\n how and which repository is installed. This vulnerability does not \naffect users who aren't installing from Mercurial.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:N","metrics":{"baseScore":3.3,"exploitabilityScore":1.9,"impactScore":1.5},"vendorMetadata":{}},{"source":"cna@python.org","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-5752","epss":0.0004,"percentile":0.11691,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"pip","version":"20.0.2"}},"found":{"versionConstraint":"<23.3 (python)","vulnerabilityID":"GHSA-mq26-g339-26xf"},"fix":{"suggestedVersion":"23.3"}}],"artifact":{"id":"ec14646fe07bc803","name":"pip","version":"20.0.2","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/pip-20.0.2.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/pip-20.0.2.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/pip-20.0.2.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/pip-20.0.2.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:pip_developers_project:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers_project:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev_project:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev_project:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers_project:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_devproject:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_devproject:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev_project:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa-dev:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa-dev:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_devproject:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip:python-pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip:python_pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa-dev:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:python:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pypa:pip:20.0.2:*:*:*:*:*:*:*","cpe:2.3:a:pip:pip:20.0.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/pip@20.0.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-9wx4-h78v-vm56","dataSource":"https://github.com/advisories/GHSA-9wx4-h78v-vm56","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Requests `Session` object does not verify requests after making first request with verify=False","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N","metrics":{"baseScore":5.6,"exploitabilityScore":0.4,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-35195","epss":0.00009,"percentile":0.00549,"date":"2025-06-03"}],"fix":{"versions":["2.32.0"],"state":"fixed"},"advisories":[],"risk":0.004770000000000001},"relatedVulnerabilities":[{"id":"CVE-2024-35195","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-35195","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac","https://github.com/psf/requests/pull/6655","https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ/","https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac","https://github.com/psf/requests/pull/6655","https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ/"],"description":"Requests is a HTTP library. Prior to 2.32.0, when making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same host will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool. This vulnerability is fixed in 2.32.0.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N","metrics":{"baseScore":5.6,"exploitabilityScore":0.4,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-35195","epss":0.00009,"percentile":0.00549,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"requests","version":"2.31.0"}},"found":{"versionConstraint":"<2.32.0 (python)","vulnerabilityID":"GHSA-9wx4-h78v-vm56"},"fix":{"suggestedVersion":"2.32.0"}}],"artifact":{"id":"ce14136bd0fc579e","name":"requests","version":"2.31.0","type":"python","locations":[{"path":"/lib/requests-2.31.0.dist-info/METADATA","accessPath":"/lib/requests-2.31.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/requests-2.31.0.dist-info/RECORD","accessPath":"/lib/requests-2.31.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/requests-2.31.0.dist-info/top_level.txt","accessPath":"/lib/requests-2.31.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache 2.0"],"cpes":["cpe:2.3:a:python:requests:2.31.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/requests@2.31.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-h4gh-qq45-vh27","dataSource":"https://github.com/advisories/GHSA-h4gh-qq45-vh27","namespace":"github:language:python","severity":"Medium","urls":[],"description":"pyca/cryptography has a vulnerable OpenSSL included in cryptography wheels","cvss":[],"fix":{"versions":["43.0.1"],"state":"fixed"},"advisories":[],"risk":0},"relatedVulnerabilities":[],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"42.0.8"}},"found":{"versionConstraint":">=37.0.0,<43.0.1 (python)","vulnerabilityID":"GHSA-h4gh-qq45-vh27"},"fix":{"suggestedVersion":"43.0.1"}}],"artifact":{"id":"0eb319b6ec444ffc","name":"cryptography","version":"42.0.8","type":"python","locations":[{"path":"/lib/cryptography-42.0.8.dist-info/METADATA","accessPath":"/lib/cryptography-42.0.8.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/cryptography-42.0.8.dist-info/RECORD","accessPath":"/lib/cryptography-42.0.8.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/cryptography-42.0.8.dist-info/top_level.txt","accessPath":"/lib/cryptography-42.0.8.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache-2.0 OR BSD-3-Clause"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:42.0.8:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:42.0.8:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@42.0.8","upstreams":[]}}],"source":{"type":"sbom-file","target":"lpci-syft.json"},"distro":{"name":"","version":"","idLike":null},"descriptor":{"name":"grype","version":"0.92.2","configuration":{"output":["json=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-06-04/lpci-grype.json","template=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-06-04/lpci-grype.html"],"file":"","pretty":false,"distro":"","add-cpes-if-none":false,"output-template-file":"../html.tmpl","check-for-app-update":true,"only-fixed":false,"only-notfixed":false,"ignore-wontfix":"","platform":"","search":{"scope":"squashed","unindexed-archives":false,"indexed-archives":true},"ignore":[{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"kernel-headers","version":"","language":"","type":"rpm","location":"","upstream-name":"kernel"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux(-.*)?-headers-.*","version":"","language":"","type":"deb","location":"","upstream-name":"linux.*"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux-libc-dev","version":"","language":"","type":"deb","location":"","upstream-name":"linux"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"}],"exclude":[],"externalSources":{"enable":false,"maven":{"searchUpstreamBySha1":true,"baseUrl":"https://search.maven.org/solrsearch/select","rateLimit":300000000}},"match":{"java":{"using-cpes":false},"jvm":{"using-cpes":true},"dotnet":{"using-cpes":false},"golang":{"using-cpes":false,"always-use-cpe-for-stdlib":true,"allow-main-module-pseudo-version-comparison":false},"javascript":{"using-cpes":false},"python":{"using-cpes":false},"ruby":{"using-cpes":false},"rust":{"using-cpes":false},"stock":{"using-cpes":true}},"fail-on-severity":"","registry":{"insecure-skip-tls-verify":false,"insecure-use-http":false,"auth":null,"ca-cert":""},"show-suppressed":false,"by-cve":false,"SortBy":{"sort-by":"risk"},"name":"","default-image-pull-source":"","vex-documents":[],"vex-add":[],"match-upstream-kernel-headers":false,"db":{"cache-dir":"/Users/alan/Library/Caches/grype/db","update-url":"https://grype.anchore.io/databases","ca-cert":"","auto-update":true,"validate-by-hash-on-start":true,"validate-age":true,"max-allowed-built-age":432000000000000,"require-update-check":false,"update-available-timeout":30000000000,"update-download-timeout":300000000000,"max-update-check-frequency":7200000000000},"exp":{},"dev":{"db":{"debug":false}}},"db":{"status":{"schemaVersion":"v6.0.2","from":"https://grype.anchore.io/databases/v6/vulnerability-db_v6.0.2_2025-06-04T01:32:23Z_1749035557.tar.zst?checksum=sha256%3A77238f4ffbc7cf72bf4dedabbb21a3d0dd3ade90fb5d9df7c4da2870f8d1a9b7","built":"2025-06-04T11:12:37Z","path":"/Users/alan/Library/Caches/grype/db/6/vulnerability.db","valid":true},"providers":{"alpine":{"captured":"2025-06-04T01:32:23Z","input":"xxh64:a6a065ece392f6d1"},"amazon":{"captured":"2025-06-04T01:32:32Z","input":"xxh64:b65d458d6858d72a"},"chainguard":{"captured":"2025-06-04T01:32:33Z","input":"xxh64:03c9c4d182d77791"},"debian":{"captured":"2025-06-04T01:32:49Z","input":"xxh64:169ceb8fbcb8d6f1"},"epss":{"captured":"2025-06-04T01:32:42Z","input":"xxh64:bf87c4c234d02346"},"github":{"captured":"2025-06-04T01:32:30Z","input":"xxh64:3dab0be50635e057"},"kev":{"captured":"2025-06-04T01:32:45Z","input":"xxh64:a934e75f468f4e09"},"mariner":{"captured":"2025-06-04T01:32:43Z","input":"xxh64:ac698752085c186f"},"nvd":{"captured":"2025-06-04T01:33:28Z","input":"xxh64:389887843a59d29c"},"oracle":{"captured":"2025-06-04T01:32:35Z","input":"xxh64:0b8aabcfb6505b62"},"rhel":{"captured":"2025-06-04T04:49:10Z","input":"xxh64:947d0caeb19e9ccc"},"sles":{"captured":"2025-06-04T01:32:34Z","input":"xxh64:1c50b1219296628a"},"ubuntu":{"captured":"2025-06-04T01:33:14Z","input":"xxh64:71e22d5c5bbe7d14"},"wolfi":{"captured":"2025-06-04T01:32:42Z","input":"xxh64:e68fca5a870c6769"}}},"timestamp":"2025-06-04T19:30:27.620095+01:00"}}
