{"matches":[{"vulnerability":{"id":"GHSA-x4qr-2fvf-3mr5","dataSource":"https://github.com/advisories/GHSA-x4qr-2fvf-3mr5","namespace":"github:language:python","severity":"High","urls":[],"description":"Vulnerable OpenSSL included in cryptography wheels","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:H","metrics":{"baseScore":7.4,"exploitabilityScore":2.3,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-0286","epss":0.8576,"percentile":0.99335,"date":"2025-06-03"}],"fix":{"versions":["39.0.1"],"state":"fixed"},"advisories":[],"risk":63.891200000000005},"relatedVulnerabilities":[{"id":"CVE-2023-0286","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-0286","namespace":"nvd:cpe","severity":"High","urls":["https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.6.2-relnotes.txt","https://ftp.openbsd.org/pub/OpenBSD/patches/7.2/common/018_x509.patch.sig","https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=2c6c9d439b484e1ba9830d8454a34fa4f80fdfe9","https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=2f7530077e0ef79d98718138716bc51ca0cad658","https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=fd2af07dc083a350c959147097003a14a5e8ac4d","https://security.gentoo.org/glsa/202402-08","https://www.openssl.org/news/secadv/20230207.txt","https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.6.2-relnotes.txt","https://ftp.openbsd.org/pub/OpenBSD/patches/7.2/common/018_x509.patch.sig","https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=2c6c9d439b484e1ba9830d8454a34fa4f80fdfe9","https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=2f7530077e0ef79d98718138716bc51ca0cad658","https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=fd2af07dc083a350c959147097003a14a5e8ac4d","https://security.gentoo.org/glsa/202402-08","https://www.openssl.org/news/secadv/20230207.txt"],"description":"There is a type confusion vulnerability relating to X.400 address processing\ninside an X.509 GeneralName. X.400 addresses were parsed as an ASN1_STRING but\nthe public structure definition for GENERAL_NAME incorrectly specified the type\nof the x400Address field as ASN1_TYPE. This field is subsequently interpreted by\nthe OpenSSL function GENERAL_NAME_cmp as an ASN1_TYPE rather than an\nASN1_STRING.\n\nWhen CRL checking is enabled (i.e. the application sets the\nX509_V_FLAG_CRL_CHECK flag), this vulnerability may allow an attacker to pass\narbitrary pointers to a memcmp call, enabling them to read memory contents or\nenact a denial of service. In most cases, the attack requires the attacker to\nprovide both the certificate chain and CRL, neither of which need to have a\nvalid signature. If the attacker only controls one of these inputs, the other\ninput must already contain an X.400 address as a CRL distribution point, which\nis uncommon. As such, this vulnerability is most likely to only affect\napplications which have implemented their own functionality for retrieving CRLs\nover a network.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:H","metrics":{"baseScore":7.4,"exploitabilityScore":2.3,"impactScore":5.2},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:H","metrics":{"baseScore":7.4,"exploitabilityScore":2.3,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-0286","epss":0.8576,"percentile":0.99335,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"3.4.8"}},"found":{"versionConstraint":">=0.8.1,<39.0.1 (python)","vulnerabilityID":"GHSA-x4qr-2fvf-3mr5"},"fix":{"suggestedVersion":"39.0.1"}}],"artifact":{"id":"8ab3d91ea77f3b32","name":"cryptography","version":"3.4.8","type":"python","locations":[{"path":"/lib/python3/dist-packages/cryptography-3.4.8.egg-info/PKG-INFO","accessPath":"/lib/python3/dist-packages/cryptography-3.4.8.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/lib/python3/dist-packages/cryptography-3.4.8.egg-info/top_level.txt","accessPath":"/lib/python3/dist-packages/cryptography-3.4.8.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD or Apache License, Version 2.0"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:3.4.8:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:3.4.8:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@3.4.8","upstreams":[]}},{"vulnerability":{"id":"GHSA-j8r2-6x86-q33q","dataSource":"https://github.com/advisories/GHSA-j8r2-6x86-q33q","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Unintended leak of Proxy-Authorization header in requests","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N","metrics":{"baseScore":6.1,"exploitabilityScore":1.7,"impactScore":4},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-32681","epss":0.04731,"percentile":0.88915,"date":"2025-06-03"}],"fix":{"versions":["2.31.0"],"state":"fixed"},"advisories":[],"risk":2.6257049999999995},"relatedVulnerabilities":[{"id":"CVE-2023-32681","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-32681","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/psf/requests/commit/74ea7cf7a6a27a4eeb2ae24e162bcc942a6706d5","https://github.com/psf/requests/releases/tag/v2.31.0","https://github.com/psf/requests/security/advisories/GHSA-j8r2-6x86-q33q","https://lists.debian.org/debian-lts-announce/2023/06/msg00018.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AW7HNFGYP44RT3DUDQXG2QT3OEV2PJ7Y/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KOYASTZDGQG2BWLSNBPL3TQRL2G7QYNZ/","https://security.gentoo.org/glsa/202309-08","https://github.com/psf/requests/commit/74ea7cf7a6a27a4eeb2ae24e162bcc942a6706d5","https://github.com/psf/requests/releases/tag/v2.31.0","https://github.com/psf/requests/security/advisories/GHSA-j8r2-6x86-q33q","https://lists.debian.org/debian-lts-announce/2023/06/msg00018.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AW7HNFGYP44RT3DUDQXG2QT3OEV2PJ7Y/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KOYASTZDGQG2BWLSNBPL3TQRL2G7QYNZ/","https://security.gentoo.org/glsa/202309-08"],"description":"Requests is a HTTP library. Since Requests 2.3.0, Requests has been leaking Proxy-Authorization headers to destination servers when redirected to an HTTPS endpoint. This is a product of how we use `rebuild_proxies` to reattach the `Proxy-Authorization` header to requests. For HTTP connections sent through the tunnel, the proxy will identify the header in the request itself and remove it prior to forwarding to the destination server. However when sent over HTTPS, the `Proxy-Authorization` header must be sent in the CONNECT request as the proxy has no visibility into the tunneled request. This results in Requests forwarding proxy credentials to the destination server unintentionally, allowing a malicious actor to potentially exfiltrate sensitive information. This issue has been patched in version 2.31.0.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N","metrics":{"baseScore":6.1,"exploitabilityScore":1.7,"impactScore":4},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N","metrics":{"baseScore":6.1,"exploitabilityScore":1.7,"impactScore":4},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-32681","epss":0.04731,"percentile":0.88915,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"requests","version":"2.25.1"}},"found":{"versionConstraint":">=2.3.0,<2.31.0 (python)","vulnerabilityID":"GHSA-j8r2-6x86-q33q"},"fix":{"suggestedVersion":"2.31.0"}}],"artifact":{"id":"d14a5be27a949d95","name":"requests","version":"2.25.1","type":"python","locations":[{"path":"/lib/python3/dist-packages/requests-2.25.1.egg-info/PKG-INFO","accessPath":"/lib/python3/dist-packages/requests-2.25.1.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/lib/python3/dist-packages/requests-2.25.1.egg-info/top_level.txt","accessPath":"/lib/python3/dist-packages/requests-2.25.1.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache 2.0"],"cpes":["cpe:2.3:a:python:requests:2.25.1:*:*:*:*:*:*:*"],"purl":"pkg:pypi/requests@2.25.1","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-6232","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-6232","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/python/cpython/commit/34ddb64d088dd7ccc321f6103d23153256caa5d4","https://github.com/python/cpython/commit/4eaf4891c12589e3c7bdad5f5b076e4c8392dd06","https://github.com/python/cpython/commit/743acbe872485dc18df4d8ab2dc7895187f062c4","https://github.com/python/cpython/commit/7d1f50cd92ff7e10a1c15a8f591dde8a6843a64d","https://github.com/python/cpython/commit/b4225ca91547aa97ed3aca391614afbb255bc877","https://github.com/python/cpython/commit/d449caf8a179e3b954268b3a88eb9170be3c8fbf","https://github.com/python/cpython/commit/ed3a49ea734ada357ff4442996fd4ae71d253373","https://github.com/python/cpython/issues/121285","https://github.com/python/cpython/pull/121286","https://mail.python.org/archives/list/security-announce@python.org/thread/JRYFTPRHZRTLMZLWQEUHZSJXNHM4ACTY/","http://www.openwall.com/lists/oss-security/2024/09/03/5","https://security.netapp.com/advisory/ntap-20241018-0007/"],"description":"There is a MEDIUM severity vulnerability affecting CPython.\n\n\n\n\n\nRegular expressions that allowed excessive backtracking during tarfile.TarFile header parsing are vulnerable to ReDoS via specifically-crafted tar archives.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-6232","epss":0.00834,"percentile":0.73566,"date":"2025-06-03"}],"fix":{"versions":["3.8.20","3.9.20","3.10.15","3.11.10","3.12.6","3.13.0rc2"],"state":"fixed"},"advisories":[],"risk":0.6255000000000001},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2024-6232","versionConstraint":"< 3.8.20,>= 3.10, < 3.10.15,>= 3.11, < 3.11.10,>= 3.12, < 3.12.6,>= 3.13, < 3.13.0rc2,>= 3.9, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.10.15"}}],"artifact":{"id":"b83d4cc9d7047529","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","accessPath":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"GHSA-q34m-jh98-gwm2","dataSource":"https://github.com/advisories/GHSA-q34m-jh98-gwm2","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Werkzeug possible resource exhaustion when parsing file data in forms","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-49767","epss":0.00974,"percentile":0.75666,"date":"2025-06-03"}],"fix":{"versions":["3.0.6"],"state":"fixed"},"advisories":[],"risk":0.60875},"relatedVulnerabilities":[{"id":"CVE-2024-49767","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-49767","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pallets/quart/commit/5e78c4169b8eb66b91ead3e62d44721b9e1644ee","https://github.com/pallets/quart/commit/abb04a512496206de279225340ed022852fbf51f","https://github.com/pallets/werkzeug/commit/50cfeebcb0727e18cc52ffbeb125f4a66551179b","https://github.com/pallets/werkzeug/releases/tag/3.0.6","https://github.com/pallets/werkzeug/security/advisories/GHSA-q34m-jh98-gwm2","https://security.netapp.com/advisory/ntap-20250103-0007/"],"description":"Werkzeug is a Web Server Gateway Interface web application library. Applications using `werkzeug.formparser.MultiPartParser` corresponding to a version of Werkzeug prior to 3.0.6 to parse `multipart/form-data` requests (e.g. all flask applications) are vulnerable to a relatively simple but effective resource exhaustion (denial of service) attack. A specifically crafted form submission request can cause the parser to allocate and block 3 to 8 times the upload size in main memory. There is no upper limit; a single upload at 1 Gbit/s can exhaust 32 GB of RAM in less than 60 seconds. Werkzeug version 3.0.6 fixes this issue.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:L/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":6.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-49767","epss":0.00974,"percentile":0.75666,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"werkzeug","version":"2.2.2"}},"found":{"versionConstraint":"<=3.0.5 (python)","vulnerabilityID":"GHSA-q34m-jh98-gwm2"},"fix":{"suggestedVersion":"3.0.6"}}],"artifact":{"id":"a523e09d35353d5e","name":"werkzeug","version":"2.2.2","type":"python","locations":[{"path":"/lib/python3/dist-packages/Werkzeug-2.2.2.egg-info/PKG-INFO","accessPath":"/lib/python3/dist-packages/Werkzeug-2.2.2.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/lib/python3/dist-packages/Werkzeug-2.2.2.egg-info/top_level.txt","accessPath":"/lib/python3/dist-packages/Werkzeug-2.2.2.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:armin_ronacher_project:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher_project:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher_project:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python-werkzeug:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python-werkzeug:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python-werkzeug:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python:werkzeug:2.2.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/werkzeug@2.2.2","upstreams":[]}},{"vulnerability":{"id":"CVE-2025-0938","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-0938","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/python/cpython/commit/526617ed68cde460236c973e5d0a8bad4de896ba","https://github.com/python/cpython/commit/90e526ae67b172ed7c6c56e7edad36263b0f9403","https://github.com/python/cpython/commit/a7084f6075c9595ba60119ce8c62f1496f50c568","https://github.com/python/cpython/commit/b8b4b713c5f8ec0958c7ef8d29d6711889bc94ab","https://github.com/python/cpython/commit/d89a5f6a6e65511a5f6e0618c4c30a7aa5aba56a","https://github.com/python/cpython/commit/ff4e5c25666f63544071a6b075ae8b25c98b7a32","https://github.com/python/cpython/issues/105704","https://github.com/python/cpython/pull/129418","https://mail.python.org/archives/list/security-announce@python.org/thread/K4EUG6EKV6JYFIC24BASYOZS4M5XOQIB/","https://security.netapp.com/advisory/ntap-20250314-0002/"],"description":"The Python standard library functions `urllib.parse.urlsplit` and `urlparse` accepted domain names that included square brackets which isn't valid according to RFC 3986. Square brackets are only meant to be used as delimiters for specifying IPv6 and IPvFuture hosts in URLs. This could result in differential parsing across the Python URL parser and other specification-compliant URL parsers.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:H/AT:P/PR:N/UI:N/VC:N/VI:L/VA:N/SC:N/SI:L/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":6.3},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-0938","epss":0.01039,"percentile":0.76414,"date":"2025-06-03"}],"fix":{"versions":["3.9.22","3.10.17","3.11.12","3.12.9","3.13.2","3.14.0a5"],"state":"fixed"},"advisories":[],"risk":0.5870349999999999},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2025-0938","versionConstraint":"< 3.9.22,>= 3.10.0, < 3.10.17,>= 3.11.0, < 3.11.12,>= 3.12.0, < 3.12.9,>= 3.13.0, < 3.13.2,>= 3.14.0a1, < 3.14.0a5 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.10.17"}}],"artifact":{"id":"b83d4cc9d7047529","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","accessPath":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-4032","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-4032","namespace":"nvd:cpe","severity":"High","urls":["http://www.openwall.com/lists/oss-security/2024/06/17/3","https://github.com/python/cpython/commit/22adf29da8d99933ffed8647d3e0726edd16f7f8","https://github.com/python/cpython/commit/40d75c2b7f5c67e254d0a025e0f2e2c7ada7f69f","https://github.com/python/cpython/commit/895f7e2ac23eff4743143beef0f0c5ac71ea27d3","https://github.com/python/cpython/commit/ba431579efdcbaed7a96f2ac4ea0775879a332fb","https://github.com/python/cpython/commit/c62c9e518b784fe44432a3f4fc265fb95b651906","https://github.com/python/cpython/commit/f86b17ac511e68192ba71f27e752321a3252cee3","https://github.com/python/cpython/issues/113171","https://github.com/python/cpython/pull/113179","https://mail.python.org/archives/list/security-announce@python.org/thread/NRUHDUS2IV2USIZM2CVMSFL6SCKU3RZA/","https://security.netapp.com/advisory/ntap-20240726-0004/","https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml","https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml","http://www.openwall.com/lists/oss-security/2024/06/17/3","https://github.com/python/cpython/commit/22adf29da8d99933ffed8647d3e0726edd16f7f8","https://github.com/python/cpython/commit/40d75c2b7f5c67e254d0a025e0f2e2c7ada7f69f","https://github.com/python/cpython/commit/895f7e2ac23eff4743143beef0f0c5ac71ea27d3","https://github.com/python/cpython/commit/ba431579efdcbaed7a96f2ac4ea0775879a332fb","https://github.com/python/cpython/commit/c62c9e518b784fe44432a3f4fc265fb95b651906","https://github.com/python/cpython/commit/f86b17ac511e68192ba71f27e752321a3252cee3","https://github.com/python/cpython/issues/113171","https://github.com/python/cpython/pull/113179","https://mail.python.org/archives/list/security-announce@python.org/thread/NRUHDUS2IV2USIZM2CVMSFL6SCKU3RZA/","https://security.netapp.com/advisory/ntap-20240726-0004/","https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml","https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml"],"description":"The “ipaddress” module contained incorrect information about whether certain IPv4 and IPv6 addresses were designated as “globally reachable” or “private”. This affected the is_private and is_global properties of the ipaddress.IPv4Address, ipaddress.IPv4Network, ipaddress.IPv6Address, and ipaddress.IPv6Network classes, where values wouldn’t be returned in accordance with the latest information from the IANA Special-Purpose Address Registries.\n\nCPython 3.12.4 and 3.13.0a6 contain updated information from these registries and thus have the intended behavior.","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-4032","epss":0.00526,"percentile":0.66091,"date":"2025-06-03"}],"fix":{"versions":["3.8.20","3.9.20","3.10.15","3.11.10","3.12.4","3.13.0a6"],"state":"fixed"},"advisories":[],"risk":0.39449999999999996},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2024-4032","versionConstraint":"< 3.8.20,>= 3.10.0, < 3.10.15,>= 3.11.0, < 3.11.10,>= 3.12.0, < 3.12.4,>= 3.13.0a1, < 3.13.0a6,>= 3.9.0, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.10.15"}}],"artifact":{"id":"b83d4cc9d7047529","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","accessPath":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"GHSA-3ww4-gg4f-jr7f","dataSource":"https://github.com/advisories/GHSA-3ww4-gg4f-jr7f","namespace":"github:language:python","severity":"High","urls":[],"description":"Python Cryptography package vulnerable to Bleichenbacher timing oracle attack","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-50782","epss":0.00521,"percentile":0.6593,"date":"2025-06-03"}],"fix":{"versions":["42.0.0"],"state":"fixed"},"advisories":[],"risk":0.39075000000000004},"relatedVulnerabilities":[{"id":"CVE-2023-50782","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-50782","namespace":"nvd:cpe","severity":"High","urls":["https://access.redhat.com/security/cve/CVE-2023-50782","https://bugzilla.redhat.com/show_bug.cgi?id=2254432","https://access.redhat.com/security/cve/CVE-2023-50782","https://bugzilla.redhat.com/show_bug.cgi?id=2254432","https://www.couchbase.com/alerts/"],"description":"A flaw was found in the python-cryptography package. This issue may allow a remote attacker to decrypt captured messages in TLS servers that use RSA key exchanges, which may lead to exposure of confidential or sensitive data.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"secalert@redhat.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-50782","epss":0.00521,"percentile":0.6593,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"3.4.8"}},"found":{"versionConstraint":"<42.0.0 (python)","vulnerabilityID":"GHSA-3ww4-gg4f-jr7f"},"fix":{"suggestedVersion":"42.0.0"}}],"artifact":{"id":"8ab3d91ea77f3b32","name":"cryptography","version":"3.4.8","type":"python","locations":[{"path":"/lib/python3/dist-packages/cryptography-3.4.8.egg-info/PKG-INFO","accessPath":"/lib/python3/dist-packages/cryptography-3.4.8.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/lib/python3/dist-packages/cryptography-3.4.8.egg-info/top_level.txt","accessPath":"/lib/python3/dist-packages/cryptography-3.4.8.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD or Apache License, Version 2.0"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:3.4.8:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:3.4.8:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@3.4.8","upstreams":[]}},{"vulnerability":{"id":"GHSA-v973-fxgf-6xhp","dataSource":"https://github.com/advisories/GHSA-v973-fxgf-6xhp","namespace":"github:language:python","severity":"High","urls":[],"description":"mako is vulnerable to Regular Expression Denial of Service","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-40023","epss":0.00514,"percentile":0.65631,"date":"2025-06-03"}],"fix":{"versions":["1.2.2"],"state":"fixed"},"advisories":[],"risk":0.3855},"relatedVulnerabilities":[{"id":"CVE-2022-40023","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2022-40023","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/sqlalchemy/mako/blob/c2f392e0be52dc67d1b9770ab8cce6a9c736d547/mako/ext/extract.py#L21","https://github.com/sqlalchemy/mako/commit/925760291d6efec64fda6e9dd1fd9cfbd5be068c","https://github.com/sqlalchemy/mako/issues/366","https://lists.debian.org/debian-lts-announce/2022/09/msg00026.html","https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/","https://pyup.io/vulnerabilities/CVE-2022-40023/50870/","https://github.com/sqlalchemy/mako/blob/c2f392e0be52dc67d1b9770ab8cce6a9c736d547/mako/ext/extract.py#L21","https://github.com/sqlalchemy/mako/commit/925760291d6efec64fda6e9dd1fd9cfbd5be068c","https://github.com/sqlalchemy/mako/issues/366","https://lists.debian.org/debian-lts-announce/2022/09/msg00026.html","https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/","https://pyup.io/vulnerabilities/CVE-2022-40023/50870/"],"description":"Sqlalchemy mako before 1.2.2 is vulnerable to Regular expression Denial of Service when using the Lexer class to parse. This also affects babelplugin and linguaplugin.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-40023","epss":0.00514,"percentile":0.65631,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"mako","version":"1.1.3"}},"found":{"versionConstraint":"<1.2.2 (python)","vulnerabilityID":"GHSA-v973-fxgf-6xhp"},"fix":{"suggestedVersion":"1.2.2"}}],"artifact":{"id":"dd83a952aed15b50","name":"mako","version":"1.1.3","type":"python","locations":[{"path":"/lib/python3/dist-packages/Mako-1.1.3-py3.10.egg-info/PKG-INFO","accessPath":"/lib/python3/dist-packages/Mako-1.1.3-py3.10.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/lib/python3/dist-packages/Mako-1.1.3-py3.10.egg-info/top_level.txt","accessPath":"/lib/python3/dist-packages/Mako-1.1.3-py3.10.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:mike_bayer_project:python-mako:1.1.3:*:*:*:*:*:*:*","cpe:2.3:a:mike_bayer_project:python_mako:1.1.3:*:*:*:*:*:*:*","cpe:2.3:a:mike_bayerproject:python-mako:1.1.3:*:*:*:*:*:*:*","cpe:2.3:a:mike_bayerproject:python_mako:1.1.3:*:*:*:*:*:*:*","cpe:2.3:a:mike_project:python-mako:1.1.3:*:*:*:*:*:*:*","cpe:2.3:a:mike_project:python_mako:1.1.3:*:*:*:*:*:*:*","cpe:2.3:a:mike_bayer_project:mako:1.1.3:*:*:*:*:*:*:*","cpe:2.3:a:mikeproject:python-mako:1.1.3:*:*:*:*:*:*:*","cpe:2.3:a:mikeproject:python_mako:1.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python-mako:python-mako:1.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python-mako:python_mako:1.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python_mako:python-mako:1.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python_mako:python_mako:1.1.3:*:*:*:*:*:*:*","cpe:2.3:a:mike_bayer:python-mako:1.1.3:*:*:*:*:*:*:*","cpe:2.3:a:mike_bayer:python_mako:1.1.3:*:*:*:*:*:*:*","cpe:2.3:a:mike_bayerproject:mako:1.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python-mako:1.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python_mako:1.1.3:*:*:*:*:*:*:*","cpe:2.3:a:mike_project:mako:1.1.3:*:*:*:*:*:*:*","cpe:2.3:a:mako:python-mako:1.1.3:*:*:*:*:*:*:*","cpe:2.3:a:mako:python_mako:1.1.3:*:*:*:*:*:*:*","cpe:2.3:a:mike:python-mako:1.1.3:*:*:*:*:*:*:*","cpe:2.3:a:mike:python_mako:1.1.3:*:*:*:*:*:*:*","cpe:2.3:a:mikeproject:mako:1.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python-mako:mako:1.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python_mako:mako:1.1.3:*:*:*:*:*:*:*","cpe:2.3:a:mike_bayer:mako:1.1.3:*:*:*:*:*:*:*","cpe:2.3:a:python:mako:1.1.3:*:*:*:*:*:*:*","cpe:2.3:a:mako:mako:1.1.3:*:*:*:*:*:*:*","cpe:2.3:a:mike:mako:1.1.3:*:*:*:*:*:*:*"],"purl":"pkg:pypi/mako@1.1.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-v845-jxx5-vc9f","dataSource":"https://github.com/advisories/GHSA-v845-jxx5-vc9f","namespace":"github:language:python","severity":"High","urls":[],"description":"`Cookie` HTTP header isn't stripped on cross-origin redirects","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:H/A:N","metrics":{"baseScore":5.9,"exploitabilityScore":0.8,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-43804","epss":0.00554,"percentile":0.67072,"date":"2025-06-03"}],"fix":{"versions":["1.26.17"],"state":"fixed"},"advisories":[],"risk":0.37118},"relatedVulnerabilities":[{"id":"CVE-2023-43804","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-43804","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/urllib3/urllib3/commit/01220354d389cd05474713f8c982d05c9b17aafb","https://github.com/urllib3/urllib3/commit/644124ecd0b6e417c527191f866daa05a5a2056d","https://github.com/urllib3/urllib3/security/advisories/GHSA-v845-jxx5-vc9f","https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/I3PR7C6RJ6JUBQKIJ644DMIJSUP36VDY/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NDAGZXYJ7H2G3SB47M453VQVNAWKAEJJ/","https://github.com/urllib3/urllib3/commit/01220354d389cd05474713f8c982d05c9b17aafb","https://github.com/urllib3/urllib3/commit/644124ecd0b6e417c527191f866daa05a5a2056d","https://github.com/urllib3/urllib3/security/advisories/GHSA-v845-jxx5-vc9f","https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/I3PR7C6RJ6JUBQKIJ644DMIJSUP36VDY/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NDAGZXYJ7H2G3SB47M453VQVNAWKAEJJ/","https://security.netapp.com/advisory/ntap-20241213-0007/","https://www.vicarius.io/vsociety/posts/cve-2023-43804-urllib3-vulnerability-3"],"description":"urllib3 is a user-friendly HTTP client library for Python. urllib3 doesn't treat the `Cookie` HTTP header special or provide any helpers for managing cookies over HTTP, that is the responsibility of the user. However, it is possible for a user to specify a `Cookie` header and unknowingly leak information via HTTP redirects to a different origin if that user doesn't disable redirects explicitly. This issue has been patched in urllib3 version 1.26.17 or 2.0.5.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N","metrics":{"baseScore":8.1,"exploitabilityScore":2.9,"impactScore":5.2},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:H/A:N","metrics":{"baseScore":5.9,"exploitabilityScore":0.8,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-43804","epss":0.00554,"percentile":0.67072,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"urllib3","version":"1.26.5"}},"found":{"versionConstraint":"<1.26.17 (python)","vulnerabilityID":"GHSA-v845-jxx5-vc9f"},"fix":{"suggestedVersion":"1.26.17"}}],"artifact":{"id":"ec3d240d7279ae9b","name":"urllib3","version":"1.26.5","type":"python","locations":[{"path":"/lib/python3/dist-packages/urllib3-1.26.5.egg-info/PKG-INFO","accessPath":"/lib/python3/dist-packages/urllib3-1.26.5.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/lib/python3/dist-packages/urllib3-1.26.5.egg-info/top_level.txt","accessPath":"/lib/python3/dist-packages/urllib3-1.26.5.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:urllib3:1.26.5:*:*:*:*:*:*:*"],"purl":"pkg:pypi/urllib3@1.26.5","upstreams":[]}},{"vulnerability":{"id":"GHSA-ffqj-6fqr-9h24","dataSource":"https://github.com/advisories/GHSA-ffqj-6fqr-9h24","namespace":"github:language:python","severity":"High","urls":[],"description":"Key confusion through non-blocklisted public key formats","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N","metrics":{"baseScore":7.4,"exploitabilityScore":2.3,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-29217","epss":0.00418,"percentile":0.61038,"date":"2025-06-03"}],"fix":{"versions":["2.4.0"],"state":"fixed"},"advisories":[],"risk":0.31140999999999996},"relatedVulnerabilities":[{"id":"CVE-2022-29217","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2022-29217","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/jpadilla/pyjwt/commit/9c528670c455b8d948aff95ed50e22940d1ad3fc","https://github.com/jpadilla/pyjwt/releases/tag/2.4.0","https://github.com/jpadilla/pyjwt/security/advisories/GHSA-ffqj-6fqr-9h24","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/5PK7IQCBVNLYJEFTPHBBPFP72H4WUFNX/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/6HIYEYZRQEP6QTHT3EHH3RGFYJIHIMAO/","https://github.com/jpadilla/pyjwt/commit/9c528670c455b8d948aff95ed50e22940d1ad3fc","https://github.com/jpadilla/pyjwt/releases/tag/2.4.0","https://github.com/jpadilla/pyjwt/security/advisories/GHSA-ffqj-6fqr-9h24","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/5PK7IQCBVNLYJEFTPHBBPFP72H4WUFNX/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/6HIYEYZRQEP6QTHT3EHH3RGFYJIHIMAO/","https://www.vicarius.io/vsociety/posts/risky-algorithms-algorithm-confusion-in-pyjwt-cve-2022-29217"],"description":"PyJWT is a Python implementation of RFC 7519. PyJWT supports multiple different JWT signing algorithms. With JWT, an attacker submitting the JWT token can choose the used signing algorithm. The PyJWT library requires that the application chooses what algorithms are supported. The application can specify `jwt.algorithms.get_default_algorithms()` to get support for all algorithms, or specify a single algorithm. The issue is not that big as `algorithms=jwt.algorithms.get_default_algorithms()` has to be used. Users should upgrade to v2.4.0 to receive a patch for this issue. As a workaround, always be explicit with the algorithms that are accepted and expected when decoding.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:L/Au:N/C:N/I:P/A:N","metrics":{"baseScore":5,"exploitabilityScore":10,"impactScore":2.9},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N","metrics":{"baseScore":7.4,"exploitabilityScore":2.3,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-29217","epss":0.00418,"percentile":0.61038,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"pyjwt","version":"2.3.0"}},"found":{"versionConstraint":">=1.5.0,<2.4.0 (python)","vulnerabilityID":"GHSA-ffqj-6fqr-9h24"},"fix":{"suggestedVersion":"2.4.0"}}],"artifact":{"id":"b076b748edc9161d","name":"pyjwt","version":"2.3.0","type":"python","locations":[{"path":"/lib/python3/dist-packages/PyJWT-2.3.0.egg-info/PKG-INFO","accessPath":"/lib/python3/dist-packages/PyJWT-2.3.0.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/lib/python3/dist-packages/PyJWT-2.3.0.egg-info/top_level.txt","accessPath":"/lib/python3/dist-packages/PyJWT-2.3.0.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:jose_padilla_project:python-pyjwt:2.3.0:*:*:*:*:*:*:*","cpe:2.3:a:jose_padilla_project:python_pyjwt:2.3.0:*:*:*:*:*:*:*","cpe:2.3:a:jose_padillaproject:python-pyjwt:2.3.0:*:*:*:*:*:*:*","cpe:2.3:a:jose_padillaproject:python_pyjwt:2.3.0:*:*:*:*:*:*:*","cpe:2.3:a:hello_project:python-pyjwt:2.3.0:*:*:*:*:*:*:*","cpe:2.3:a:hello_project:python_pyjwt:2.3.0:*:*:*:*:*:*:*","cpe:2.3:a:jose_padilla_project:pyjwt:2.3.0:*:*:*:*:*:*:*","cpe:2.3:a:helloproject:python-pyjwt:2.3.0:*:*:*:*:*:*:*","cpe:2.3:a:helloproject:python_pyjwt:2.3.0:*:*:*:*:*:*:*","cpe:2.3:a:jose_padilla:python-pyjwt:2.3.0:*:*:*:*:*:*:*","cpe:2.3:a:jose_padilla:python_pyjwt:2.3.0:*:*:*:*:*:*:*","cpe:2.3:a:jose_padillaproject:pyjwt:2.3.0:*:*:*:*:*:*:*","cpe:2.3:a:python-pyjwt:python-pyjwt:2.3.0:*:*:*:*:*:*:*","cpe:2.3:a:python-pyjwt:python_pyjwt:2.3.0:*:*:*:*:*:*:*","cpe:2.3:a:python_pyjwt:python-pyjwt:2.3.0:*:*:*:*:*:*:*","cpe:2.3:a:python_pyjwt:python_pyjwt:2.3.0:*:*:*:*:*:*:*","cpe:2.3:a:hello_project:pyjwt:2.3.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python-pyjwt:2.3.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python_pyjwt:2.3.0:*:*:*:*:*:*:*","cpe:2.3:a:hello:python-pyjwt:2.3.0:*:*:*:*:*:*:*","cpe:2.3:a:hello:python_pyjwt:2.3.0:*:*:*:*:*:*:*","cpe:2.3:a:helloproject:pyjwt:2.3.0:*:*:*:*:*:*:*","cpe:2.3:a:jose_padilla:pyjwt:2.3.0:*:*:*:*:*:*:*","cpe:2.3:a:pyjwt:python-pyjwt:2.3.0:*:*:*:*:*:*:*","cpe:2.3:a:pyjwt:python_pyjwt:2.3.0:*:*:*:*:*:*:*","cpe:2.3:a:python-pyjwt:pyjwt:2.3.0:*:*:*:*:*:*:*","cpe:2.3:a:python_pyjwt:pyjwt:2.3.0:*:*:*:*:*:*:*","cpe:2.3:a:python:pyjwt:2.3.0:*:*:*:*:*:*:*","cpe:2.3:a:hello:pyjwt:2.3.0:*:*:*:*:*:*:*","cpe:2.3:a:pyjwt:pyjwt:2.3.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/pyjwt@2.3.0","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-0397","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-0397","namespace":"nvd:cpe","severity":"High","urls":["http://www.openwall.com/lists/oss-security/2024/06/17/2","https://github.com/python/cpython/commit/01c37f1d0714f5822d34063ca7180b595abf589d","https://github.com/python/cpython/commit/29c97287d205bf2f410f4895ebce3f43b5160524","https://github.com/python/cpython/commit/37324b421b72b7bc9934e27aba85d48d4773002e","https://github.com/python/cpython/commit/542f3272f56f31ed04e74c40635a913fbc12d286","https://github.com/python/cpython/commit/b228655c227b2ca298a8ffac44d14ce3d22f6faa","https://github.com/python/cpython/commit/bce693111bff906ccf9281c22371331aaff766ab","https://github.com/python/cpython/issues/114572","https://github.com/python/cpython/pull/114573","https://mail.python.org/archives/list/security-announce@python.org/thread/BMAK5BCGKYWNJOACVUSLUF6SFGBIM4VP/","http://www.openwall.com/lists/oss-security/2024/06/17/2","https://github.com/python/cpython/commit/01c37f1d0714f5822d34063ca7180b595abf589d","https://github.com/python/cpython/commit/29c97287d205bf2f410f4895ebce3f43b5160524","https://github.com/python/cpython/commit/37324b421b72b7bc9934e27aba85d48d4773002e","https://github.com/python/cpython/commit/542f3272f56f31ed04e74c40635a913fbc12d286","https://github.com/python/cpython/commit/b228655c227b2ca298a8ffac44d14ce3d22f6faa","https://github.com/python/cpython/commit/bce693111bff906ccf9281c22371331aaff766ab","https://github.com/python/cpython/issues/114572","https://github.com/python/cpython/pull/114573","https://mail.python.org/archives/list/security-announce@python.org/thread/BMAK5BCGKYWNJOACVUSLUF6SFGBIM4VP/","https://security.netapp.com/advisory/ntap-20250411-0006/"],"description":"A defect was discovered in the Python “ssl” module where there is a memory\nrace condition with the ssl.SSLContext methods “cert_store_stats()” and\n“get_ca_certs()”. The race condition can be triggered if the methods are\ncalled at the same time as certificates are loaded into the SSLContext,\nsuch as during the TLS handshake with a certificate directory configured.\nThis issue is fixed in CPython 3.10.14, 3.11.9, 3.12.3, and 3.13.0a5.","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:H","metrics":{"baseScore":7.4,"exploitabilityScore":2.3,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-0397","epss":0.00393,"percentile":0.59513,"date":"2025-06-03"}],"fix":{"versions":["3.8.20","3.9.20","3.10.14","3.11.9","3.12.3","3.13.0a5"],"state":"fixed"},"advisories":[],"risk":0.292785},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2024-0397","versionConstraint":"< 3.8.20,>= 3.10.0, < 3.10.14,>= 3.11.0, < 3.11.9,>= 3.12.0, < 3.12.3,>= 3.13.0a1, < 3.13.0a5,>= 3.9.0, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.10.14"}}],"artifact":{"id":"b83d4cc9d7047529","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","accessPath":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"GHSA-jfhm-5ghh-2f97","dataSource":"https://github.com/advisories/GHSA-jfhm-5ghh-2f97","namespace":"github:language:python","severity":"Medium","urls":[],"description":"cryptography vulnerable to NULL-dereference when loading PKCS7 certificates","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-49083","epss":0.00457,"percentile":0.63032,"date":"2025-06-03"}],"fix":{"versions":["41.0.6"],"state":"fixed"},"advisories":[],"risk":0.24906500000000004},"relatedVulnerabilities":[{"id":"CVE-2023-49083","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-49083","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pyca/cryptography/commit/f09c261ca10a31fe41b1262306db7f8f1da0e48a","https://github.com/pyca/cryptography/pull/9926","https://github.com/pyca/cryptography/security/advisories/GHSA-jfhm-5ghh-2f97","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QMNTYMUGFJSDBYBU22FUYBHFRZODRKXV/","https://github.com/pyca/cryptography/commit/f09c261ca10a31fe41b1262306db7f8f1da0e48a","https://github.com/pyca/cryptography/pull/9926","https://github.com/pyca/cryptography/security/advisories/GHSA-jfhm-5ghh-2f97","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QMNTYMUGFJSDBYBU22FUYBHFRZODRKXV/"],"description":"cryptography is a package designed to expose cryptographic primitives and recipes to Python developers. Calling `load_pem_pkcs7_certificates` or `load_der_pkcs7_certificates` could lead to a NULL-pointer dereference and segfault. Exploitation of this vulnerability poses a serious risk of Denial of Service (DoS) for any application attempting to deserialize a PKCS7 blob/certificate. The consequences extend to potential disruptions in system availability and stability. This vulnerability has been patched in version 41.0.6.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-49083","epss":0.00457,"percentile":0.63032,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"3.4.8"}},"found":{"versionConstraint":">=3.1,<41.0.6 (python)","vulnerabilityID":"GHSA-jfhm-5ghh-2f97"},"fix":{"suggestedVersion":"41.0.6"}}],"artifact":{"id":"8ab3d91ea77f3b32","name":"cryptography","version":"3.4.8","type":"python","locations":[{"path":"/lib/python3/dist-packages/cryptography-3.4.8.egg-info/PKG-INFO","accessPath":"/lib/python3/dist-packages/cryptography-3.4.8.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/lib/python3/dist-packages/cryptography-3.4.8.egg-info/top_level.txt","accessPath":"/lib/python3/dist-packages/cryptography-3.4.8.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD or Apache License, Version 2.0"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:3.4.8:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:3.4.8:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@3.4.8","upstreams":[]}},{"vulnerability":{"id":"GHSA-jjg7-2v4v-x38h","dataSource":"https://github.com/advisories/GHSA-jjg7-2v4v-x38h","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Internationalized Domain Names in Applications (IDNA) vulnerable to denial of service from specially crafted inputs to idna.encode","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":6.2,"exploitabilityScore":2.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-3651","epss":0.00436,"percentile":0.62113,"date":"2025-06-03"}],"fix":{"versions":["3.7"],"state":"fixed"},"advisories":[],"risk":0.24416000000000004},"relatedVulnerabilities":[{"id":"CVE-2024-3651","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-3651","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/kjd/idna/commit/1d365e17e10d72d0b7876316fc7b9ca0eebdd38d","https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb","https://github.com/kjd/idna/commit/1d365e17e10d72d0b7876316fc7b9ca0eebdd38d","https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb"],"description":"A vulnerability was identified in the kjd/idna library, specifically within the `idna.encode()` function, affecting version 3.6. The issue arises from the function's handling of crafted input strings, which can lead to quadratic complexity and consequently, a denial of service condition. This vulnerability is triggered by a crafted input that causes the `idna.encode()` function to process the input with considerable computational load, significantly increasing the processing time in a quadratic manner relative to the input size.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security@huntr.dev","type":"Secondary","version":"3.0","vector":"CVSS:3.0/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":6.2,"exploitabilityScore":2.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-3651","epss":0.00436,"percentile":0.62113,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"idna","version":"3.3"}},"found":{"versionConstraint":"<3.7 (python)","vulnerabilityID":"GHSA-jjg7-2v4v-x38h"},"fix":{"suggestedVersion":"3.7"}}],"artifact":{"id":"e4d12b70c983dadb","name":"idna","version":"3.3","type":"python","locations":[{"path":"/lib/python3/dist-packages/idna-3.3.egg-info/PKG-INFO","accessPath":"/lib/python3/dist-packages/idna-3.3.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/lib/python3/dist-packages/idna-3.3.egg-info/top_level.txt","accessPath":"/lib/python3/dist-packages/idna-3.3.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:kim_davies_project:python-idna:3.3:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_project:python_idna:3.3:*:*:*:*:*:*:*","cpe:2.3:a:kim_daviesproject:python-idna:3.3:*:*:*:*:*:*:*","cpe:2.3:a:kim_daviesproject:python_idna:3.3:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_project:idna:3.3:*:*:*:*:*:*:*","cpe:2.3:a:kim_project:python-idna:3.3:*:*:*:*:*:*:*","cpe:2.3:a:kim_project:python_idna:3.3:*:*:*:*:*:*:*","cpe:2.3:a:python-idna:python-idna:3.3:*:*:*:*:*:*:*","cpe:2.3:a:python-idna:python_idna:3.3:*:*:*:*:*:*:*","cpe:2.3:a:python_idna:python-idna:3.3:*:*:*:*:*:*:*","cpe:2.3:a:python_idna:python_idna:3.3:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies:python-idna:3.3:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies:python_idna:3.3:*:*:*:*:*:*:*","cpe:2.3:a:kim_daviesproject:idna:3.3:*:*:*:*:*:*:*","cpe:2.3:a:kimproject:python-idna:3.3:*:*:*:*:*:*:*","cpe:2.3:a:kimproject:python_idna:3.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python-idna:3.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python_idna:3.3:*:*:*:*:*:*:*","cpe:2.3:a:idna:python-idna:3.3:*:*:*:*:*:*:*","cpe:2.3:a:idna:python_idna:3.3:*:*:*:*:*:*:*","cpe:2.3:a:kim_project:idna:3.3:*:*:*:*:*:*:*","cpe:2.3:a:python-idna:idna:3.3:*:*:*:*:*:*:*","cpe:2.3:a:python_idna:idna:3.3:*:*:*:*:*:*:*","cpe:2.3:a:kim:python-idna:3.3:*:*:*:*:*:*:*","cpe:2.3:a:kim:python_idna:3.3:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies:idna:3.3:*:*:*:*:*:*:*","cpe:2.3:a:kimproject:idna:3.3:*:*:*:*:*:*:*","cpe:2.3:a:python:idna:3.3:*:*:*:*:*:*:*","cpe:2.3:a:idna:idna:3.3:*:*:*:*:*:*:*","cpe:2.3:a:kim:idna:3.3:*:*:*:*:*:*:*"],"purl":"pkg:pypi/idna@3.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-xg9f-g7g7-2323","dataSource":"https://github.com/advisories/GHSA-xg9f-g7g7-2323","namespace":"github:language:python","severity":"High","urls":[],"description":"High resource usage when parsing multipart form data with many fields","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-25577","epss":0.00306,"percentile":0.53419,"date":"2025-06-03"}],"fix":{"versions":["2.2.3"],"state":"fixed"},"advisories":[],"risk":0.22949999999999998},"relatedVulnerabilities":[{"id":"CVE-2023-25577","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-25577","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pallets/werkzeug/commit/517cac5a804e8c4dc4ed038bb20dacd038e7a9f1","https://github.com/pallets/werkzeug/releases/tag/2.2.3","https://github.com/pallets/werkzeug/security/advisories/GHSA-xg9f-g7g7-2323","https://security.netapp.com/advisory/ntap-20230818-0003/","https://www.debian.org/security/2023/dsa-5470","https://github.com/pallets/werkzeug/commit/517cac5a804e8c4dc4ed038bb20dacd038e7a9f1","https://github.com/pallets/werkzeug/releases/tag/2.2.3","https://github.com/pallets/werkzeug/security/advisories/GHSA-xg9f-g7g7-2323","https://security.netapp.com/advisory/ntap-20230818-0003/","https://www.debian.org/security/2023/dsa-5470"],"description":"Werkzeug is a comprehensive WSGI web application library. Prior to version 2.2.3, Werkzeug's multipart form data parser will parse an unlimited number of parts, including file parts. Parts can be a small amount of bytes, but each requires CPU time to parse and may use more memory as Python data. If a request can be made to an endpoint that accesses `request.data`, `request.form`, `request.files`, or `request.get_data(parse_form_data=False)`, it can cause unexpectedly high resource usage. This allows an attacker to cause a denial of service by sending crafted multipart data to an endpoint that will parse it. The amount of CPU time required can block worker processes from handling legitimate requests. The amount of RAM required can trigger an out of memory kill of the process. Unlimited file parts can use up memory and file handles. If many concurrent requests are sent continuously, this can exhaust or kill all available workers. Version 2.2.3 contains a patch for this issue.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-25577","epss":0.00306,"percentile":0.53419,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"werkzeug","version":"2.2.2"}},"found":{"versionConstraint":"<2.2.3 (python)","vulnerabilityID":"GHSA-xg9f-g7g7-2323"},"fix":{"suggestedVersion":"2.2.3"}}],"artifact":{"id":"a523e09d35353d5e","name":"werkzeug","version":"2.2.2","type":"python","locations":[{"path":"/lib/python3/dist-packages/Werkzeug-2.2.2.egg-info/PKG-INFO","accessPath":"/lib/python3/dist-packages/Werkzeug-2.2.2.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/lib/python3/dist-packages/Werkzeug-2.2.2.egg-info/top_level.txt","accessPath":"/lib/python3/dist-packages/Werkzeug-2.2.2.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:armin_ronacher_project:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher_project:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher_project:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python-werkzeug:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python-werkzeug:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python-werkzeug:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python:werkzeug:2.2.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/werkzeug@2.2.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-hrfv-mqp8-q5rw","dataSource":"https://github.com/advisories/GHSA-hrfv-mqp8-q5rw","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Werkzeug DoS: High resource usage when parsing multipart/form-data containing a large part with CR/LF character at the beginning","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:A/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.7,"exploitabilityScore":2.1,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-46136","epss":0.0041,"percentile":0.60521,"date":"2025-06-03"}],"fix":{"versions":["2.3.8"],"state":"fixed"},"advisories":[],"risk":0.21935000000000002},"relatedVulnerabilities":[{"id":"CVE-2023-46136","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-46136","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pallets/werkzeug/commit/f3c803b3ade485a45f12b6d6617595350c0f03e2","https://github.com/pallets/werkzeug/security/advisories/GHSA-hrfv-mqp8-q5rw","https://security.netapp.com/advisory/ntap-20231124-0008/","https://github.com/pallets/werkzeug/commit/f3c803b3ade485a45f12b6d6617595350c0f03e2","https://github.com/pallets/werkzeug/security/advisories/GHSA-hrfv-mqp8-q5rw","https://security.netapp.com/advisory/ntap-20231124-0008/"],"description":"Werkzeug is a comprehensive WSGI web application library. If an upload of a file that starts with CR or LF and then is followed by megabytes of data without these characters: all of these bytes are appended chunk by chunk into internal bytearray and lookup for boundary is performed on growing buffer. This allows an attacker to cause a denial of service by sending crafted multipart data to an endpoint that will parse it. The amount of CPU time required can block worker processes from handling legitimate requests. This vulnerability has been patched in version 3.0.1.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:A/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":8,"exploitabilityScore":2.1,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-46136","epss":0.0041,"percentile":0.60521,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"werkzeug","version":"2.2.2"}},"found":{"versionConstraint":"<2.3.8 (python)","vulnerabilityID":"GHSA-hrfv-mqp8-q5rw"},"fix":{"suggestedVersion":"2.3.8"}}],"artifact":{"id":"a523e09d35353d5e","name":"werkzeug","version":"2.2.2","type":"python","locations":[{"path":"/lib/python3/dist-packages/Werkzeug-2.2.2.egg-info/PKG-INFO","accessPath":"/lib/python3/dist-packages/Werkzeug-2.2.2.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/lib/python3/dist-packages/Werkzeug-2.2.2.egg-info/top_level.txt","accessPath":"/lib/python3/dist-packages/Werkzeug-2.2.2.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:armin_ronacher_project:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher_project:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher_project:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python-werkzeug:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python-werkzeug:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python-werkzeug:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python:werkzeug:2.2.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/werkzeug@2.2.2","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-7592","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-7592","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/python/cpython/commit/391e5626e3ee5af267b97e37abc7475732e67621","https://github.com/python/cpython/commit/44e458357fca05ca0ae2658d62c8c595b048b5ef","https://github.com/python/cpython/commit/a77ab24427a18bff817025adb03ca920dc3f1a06","https://github.com/python/cpython/commit/b2f11ca7667e4d57c71c1c88b255115f16042d9a","https://github.com/python/cpython/commit/d4ac921a4b081f7f996a5d2b101684b67ba0ed7f","https://github.com/python/cpython/commit/d662e2db2605515a767f88ad48096b8ac623c774","https://github.com/python/cpython/commit/dcc3eaef98cd94d6cb6cb0f44bd1c903d04f33b1","https://github.com/python/cpython/issues/123067","https://github.com/python/cpython/pull/123075","https://mail.python.org/archives/list/security-announce@python.org/thread/HXJAAAALNUNGCQUS2W7WR6GFIZIHFOOK/","https://security.netapp.com/advisory/ntap-20241018-0006/"],"description":"There is a LOW severity vulnerability affecting CPython, specifically the\n'http.cookies' standard library module.\n\n\nWhen parsing cookies that contained backslashes for quoted characters in\nthe cookie value, the parser would use an algorithm with quadratic\ncomplexity, resulting in excess CPU resources being used while parsing the\nvalue.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-7592","epss":0.00255,"percentile":0.49,"date":"2025-06-03"}],"fix":{"versions":["3.8.20","3.9.20","3.10.15","3.11.10","3.12.6","3.13.0rc2"],"state":"fixed"},"advisories":[],"risk":0.19125},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2024-7592","versionConstraint":"< 3.8.20,>= 3.10, < 3.10.15,>= 3.11, < 3.11.10,>= 3.12, < 3.12.6,>= 3.13.0a1, < 3.13.0rc2,>= 3.9, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.10.15"}}],"artifact":{"id":"b83d4cc9d7047529","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","accessPath":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"GHSA-w7pp-m8wf-vj6r","dataSource":"https://github.com/advisories/GHSA-w7pp-m8wf-vj6r","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Cipher.update_into can corrupt memory if passed an immutable python object as the outbuf","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:L","metrics":{"baseScore":6.5,"exploitabilityScore":3.9,"impactScore":2.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-23931","epss":0.00331,"percentile":0.5554,"date":"2025-06-03"}],"fix":{"versions":["39.0.1"],"state":"fixed"},"advisories":[],"risk":0.19032499999999997},"relatedVulnerabilities":[{"id":"CVE-2023-23931","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-23931","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pyca/cryptography/pull/8230/commits/94a50a9731f35405f0357fa5f3b177d46a726ab3","https://github.com/pyca/cryptography/security/advisories/GHSA-w7pp-m8wf-vj6r","https://github.com/pyca/cryptography/pull/8230/commits/94a50a9731f35405f0357fa5f3b177d46a726ab3","https://github.com/pyca/cryptography/security/advisories/GHSA-w7pp-m8wf-vj6r","https://security.netapp.com/advisory/ntap-20230324-0007/"],"description":"cryptography is a package designed to expose cryptographic primitives and recipes to Python developers. In affected versions `Cipher.update_into` would accept Python objects which implement the buffer protocol, but provide only immutable buffers. This would allow immutable objects (such as `bytes`) to be mutated, thus violating fundamental rules of Python and resulting in corrupted output. This now correctly raises an exception. This issue has been present since `update_into` was originally introduced in cryptography 1.8.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:L","metrics":{"baseScore":6.5,"exploitabilityScore":3.9,"impactScore":2.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:L/A:L","metrics":{"baseScore":4.8,"exploitabilityScore":2.3,"impactScore":2.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-23931","epss":0.00331,"percentile":0.5554,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"3.4.8"}},"found":{"versionConstraint":">=1.8,<39.0.1 (python)","vulnerabilityID":"GHSA-w7pp-m8wf-vj6r"},"fix":{"suggestedVersion":"39.0.1"}}],"artifact":{"id":"8ab3d91ea77f3b32","name":"cryptography","version":"3.4.8","type":"python","locations":[{"path":"/lib/python3/dist-packages/cryptography-3.4.8.egg-info/PKG-INFO","accessPath":"/lib/python3/dist-packages/cryptography-3.4.8.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/lib/python3/dist-packages/cryptography-3.4.8.egg-info/top_level.txt","accessPath":"/lib/python3/dist-packages/cryptography-3.4.8.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD or Apache License, Version 2.0"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:3.4.8:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:3.4.8:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@3.4.8","upstreams":[]}},{"vulnerability":{"id":"GHSA-3f84-rpwh-47g6","dataSource":"https://github.com/advisories/GHSA-3f84-rpwh-47g6","namespace":"github:language:python","severity":"High","urls":[],"description":"Waitress vulnerable to DoS leading to high CPU usage/resource exhaustion","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-49769","epss":0.00226,"percentile":0.45608,"date":"2025-06-03"}],"fix":{"versions":["3.0.1"],"state":"fixed"},"advisories":[],"risk":0.16949999999999998},"relatedVulnerabilities":[{"id":"CVE-2024-49769","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-49769","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/Pylons/waitress/commit/1ae4e894c9f76543bee06584001583fc6fa8c95c","https://github.com/Pylons/waitress/issues/418","https://github.com/Pylons/waitress/pull/435","https://github.com/Pylons/waitress/security/advisories/GHSA-3f84-rpwh-47g6","https://lists.debian.org/debian-lts-announce/2024/11/msg00012.html"],"description":"Waitress is a Web Server Gateway Interface server for Python 2 and 3. When a remote client closes the connection before waitress has had the opportunity to call getpeername() waitress won't correctly clean up the connection leading to the main thread attempting to write to a socket that no longer exists, but not removing it from the list of sockets to attempt to process. This leads to a busy-loop calling the write function. A remote attacker could run waitress out of available sockets with very little resources required. Waitress 3.0.1 contains fixes that remove the race condition.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-49769","epss":0.00226,"percentile":0.45608,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"waitress","version":"1.4.4"}},"found":{"versionConstraint":"<3.0.1 (python)","vulnerabilityID":"GHSA-3f84-rpwh-47g6"},"fix":{"suggestedVersion":"3.0.1"}}],"artifact":{"id":"6c6f61ecfc5359da","name":"waitress","version":"1.4.4","type":"python","locations":[{"path":"/lib/python3/dist-packages/waitress-1.4.4.egg-info/PKG-INFO","accessPath":"/lib/python3/dist-packages/waitress-1.4.4.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/lib/python3/dist-packages/waitress-1.4.4.egg-info/top_level.txt","accessPath":"/lib/python3/dist-packages/waitress-1.4.4.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["ZPL 2.1"],"cpes":["cpe:2.3:a:zope_foundation_and_contributors_project:python-waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_foundation_and_contributors_project:python_waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_foundation_and_contributorsproject:python-waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_foundation_and_contributorsproject:python_waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_foundation_and_contributors_project:waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_foundation_and_contributors:python-waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_foundation_and_contributors:python_waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_foundation_and_contributorsproject:waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_foundation_and_contributors:waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_dev_project:python-waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_dev_project:python_waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:python-waitress:python-waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:python-waitress:python_waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:python_waitress:python-waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:python_waitress:python_waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_devproject:python-waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_devproject:python_waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_dev_project:waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:python-waitress:waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:python_waitress:waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:waitress:python-waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:waitress:python_waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope-dev:python-waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope-dev:python_waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_dev:python-waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_dev:python_waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_devproject:waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python-waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python_waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:waitress:waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope-dev:waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_dev:waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:python:waitress:1.4.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/waitress@1.4.4","upstreams":[]}},{"vulnerability":{"id":"GHSA-4f7p-27jc-3c36","dataSource":"https://github.com/advisories/GHSA-4f7p-27jc-3c36","namespace":"github:language:python","severity":"High","urls":[],"description":"HTTP Request Smuggling in waitress","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-24761","epss":0.00197,"percentile":0.42337,"date":"2025-06-03"}],"fix":{"versions":["2.1.1"],"state":"fixed"},"advisories":[],"risk":0.14775000000000002},"relatedVulnerabilities":[{"id":"CVE-2022-24761","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2022-24761","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/Pylons/waitress/commit/9e0b8c801e4d505c2ffc91b891af4ba48af715e0","https://github.com/Pylons/waitress/releases/tag/v2.1.1","https://github.com/Pylons/waitress/security/advisories/GHSA-4f7p-27jc-3c36","https://lists.debian.org/debian-lts-announce/2022/05/msg00011.html","https://www.debian.org/security/2022/dsa-5138","https://github.com/Pylons/waitress/commit/9e0b8c801e4d505c2ffc91b891af4ba48af715e0","https://github.com/Pylons/waitress/releases/tag/v2.1.1","https://github.com/Pylons/waitress/security/advisories/GHSA-4f7p-27jc-3c36","https://lists.debian.org/debian-lts-announce/2022/05/msg00011.html","https://www.debian.org/security/2022/dsa-5138"],"description":"Waitress is a Web Server Gateway Interface server for Python 2 and 3. When using Waitress versions 2.1.0 and prior behind a proxy that does not properly validate the incoming HTTP request matches the RFC7230 standard, Waitress and the frontend proxy may disagree on where one request starts and where it ends. This would allow requests to be smuggled via the front-end proxy to waitress and later behavior. There are two classes of vulnerability that may lead to request smuggling that are addressed by this advisory: The use of Python's `int()` to parse strings into integers, leading to `+10` to be parsed as `10`, or `0x01` to be parsed as `1`, where as the standard specifies that the string should contain only digits or hex digits; and Waitress does not support chunk extensions, however it was discarding them without validating that they did not contain illegal characters. This vulnerability has been patched in Waitress 2.1.1. A workaround is available. When deploying a proxy in front of waitress, turning on any and all functionality to make sure that the request matches the RFC7230 standard. Certain proxy servers may not have this functionality though and users are encouraged to upgrade to the latest version of waitress instead.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:L/Au:N/C:N/I:P/A:N","metrics":{"baseScore":5,"exploitabilityScore":10,"impactScore":2.9},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-24761","epss":0.00197,"percentile":0.42337,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"waitress","version":"1.4.4"}},"found":{"versionConstraint":"<2.1.1 (python)","vulnerabilityID":"GHSA-4f7p-27jc-3c36"},"fix":{"suggestedVersion":"2.1.1"}}],"artifact":{"id":"6c6f61ecfc5359da","name":"waitress","version":"1.4.4","type":"python","locations":[{"path":"/lib/python3/dist-packages/waitress-1.4.4.egg-info/PKG-INFO","accessPath":"/lib/python3/dist-packages/waitress-1.4.4.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/lib/python3/dist-packages/waitress-1.4.4.egg-info/top_level.txt","accessPath":"/lib/python3/dist-packages/waitress-1.4.4.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["ZPL 2.1"],"cpes":["cpe:2.3:a:zope_foundation_and_contributors_project:python-waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_foundation_and_contributors_project:python_waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_foundation_and_contributorsproject:python-waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_foundation_and_contributorsproject:python_waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_foundation_and_contributors_project:waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_foundation_and_contributors:python-waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_foundation_and_contributors:python_waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_foundation_and_contributorsproject:waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_foundation_and_contributors:waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_dev_project:python-waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_dev_project:python_waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:python-waitress:python-waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:python-waitress:python_waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:python_waitress:python-waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:python_waitress:python_waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_devproject:python-waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_devproject:python_waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_dev_project:waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:python-waitress:waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:python_waitress:waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:waitress:python-waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:waitress:python_waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope-dev:python-waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope-dev:python_waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_dev:python-waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_dev:python_waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_devproject:waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python-waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python_waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:waitress:waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope-dev:waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:zope_dev:waitress:1.4.4:*:*:*:*:*:*:*","cpe:2.3:a:python:waitress:1.4.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/waitress@1.4.4","upstreams":[]}},{"vulnerability":{"id":"CVE-2023-40217","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-40217","namespace":"nvd:cpe","severity":"Medium","urls":["https://lists.debian.org/debian-lts-announce/2023/09/msg00022.html","https://lists.debian.org/debian-lts-announce/2023/10/msg00017.html","https://mail.python.org/archives/list/security-announce%40python.org/thread/PEPLII27KYHLF4AK3ZQGKYNCRERG4YXY/","https://security.netapp.com/advisory/ntap-20231006-0014/","https://www.python.org/dev/security/","https://lists.debian.org/debian-lts-announce/2023/09/msg00022.html","https://lists.debian.org/debian-lts-announce/2023/10/msg00017.html","https://mail.python.org/archives/list/security-announce%40python.org/thread/PEPLII27KYHLF4AK3ZQGKYNCRERG4YXY/","https://security.netapp.com/advisory/ntap-20231006-0014/","https://www.python.org/dev/security/"],"description":"An issue was discovered in Python before 3.8.18, 3.9.x before 3.9.18, 3.10.x before 3.10.13, and 3.11.x before 3.11.5. It primarily affects servers (such as HTTP servers) that use TLS client authentication. If a TLS server-side socket is created, receives data into the socket buffer, and then is closed quickly, there is a brief window where the SSLSocket instance will detect the socket as \"not connected\" and won't initiate a handshake, but buffered data will still be readable from the socket buffer. This data will not be authenticated if the server-side TLS peer is expecting client certificate authentication, and is indistinguishable from valid TLS stream data. Data is limited in size to the amount that will fit in the buffer. (The TLS connection cannot directly be used for data exfiltration because the vulnerable code path requires that the connection be closed on initialization of the SSLSocket.)","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N","metrics":{"baseScore":5.3,"exploitabilityScore":3.9,"impactScore":1.5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-40217","epss":0.00284,"percentile":0.51657,"date":"2025-06-03"}],"fix":{"versions":["3.8.18","3.9.18","3.10.13","3.11.5"],"state":"fixed"},"advisories":[],"risk":0.14626},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2023-40217","versionConstraint":"< 3.8.18,>= 3.10.0, < 3.10.13,>= 3.11.0, < 3.11.5,>= 3.9.0, < 3.9.18 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.10.13"}}],"artifact":{"id":"b83d4cc9d7047529","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","accessPath":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-0450","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-0450","namespace":"nvd:cpe","severity":"Medium","urls":["http://www.openwall.com/lists/oss-security/2024/03/20/5","https://github.com/python/cpython/commit/30fe5d853b56138dbec62432d370a1f99409fc85","https://github.com/python/cpython/commit/66363b9a7b9fe7c99eba3a185b74c5fdbf842eba","https://github.com/python/cpython/commit/70497218351ba44bffc8b571201ecb5652d84675","https://github.com/python/cpython/commit/a2c59992e9e8d35baba9695eb186ad6c6ff85c51","https://github.com/python/cpython/commit/a956e510f6336d5ae111ba429a61c3ade30a7549","https://github.com/python/cpython/commit/d05bac0b74153beb541b88b4fca33bf053990183","https://github.com/python/cpython/commit/fa181fcf2156f703347b03a3b1966ce47be8ab3b","https://github.com/python/cpython/issues/109858","https://lists.debian.org/debian-lts-announce/2024/03/msg00024.html","https://lists.debian.org/debian-lts-announce/2024/03/msg00025.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/T3IGRX54M7RNCQOXVQO5KQKTGWCOABIM/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/U5VHWS52HGD743C47UMCSAK2A773M2YE/","https://mail.python.org/archives/list/security-announce@python.org/thread/XELNUX2L3IOHBTFU7RQHCY6OUVEWZ2FG/","https://www.bamsoftware.com/hacks/zipbomb/","http://www.openwall.com/lists/oss-security/2024/03/20/5","https://github.com/python/cpython/commit/30fe5d853b56138dbec62432d370a1f99409fc85","https://github.com/python/cpython/commit/66363b9a7b9fe7c99eba3a185b74c5fdbf842eba","https://github.com/python/cpython/commit/70497218351ba44bffc8b571201ecb5652d84675","https://github.com/python/cpython/commit/a2c59992e9e8d35baba9695eb186ad6c6ff85c51","https://github.com/python/cpython/commit/a956e510f6336d5ae111ba429a61c3ade30a7549","https://github.com/python/cpython/commit/d05bac0b74153beb541b88b4fca33bf053990183","https://github.com/python/cpython/commit/fa181fcf2156f703347b03a3b1966ce47be8ab3b","https://github.com/python/cpython/issues/109858","https://lists.debian.org/debian-lts-announce/2024/03/msg00024.html","https://lists.debian.org/debian-lts-announce/2024/03/msg00025.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/T3IGRX54M7RNCQOXVQO5KQKTGWCOABIM/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/U5VHWS52HGD743C47UMCSAK2A773M2YE/","https://mail.python.org/archives/list/security-announce@python.org/thread/XELNUX2L3IOHBTFU7RQHCY6OUVEWZ2FG/","https://security.netapp.com/advisory/ntap-20250411-0005/","https://www.bamsoftware.com/hacks/zipbomb/"],"description":"An issue was found in the CPython `zipfile` module affecting versions 3.12.1, 3.11.7, 3.10.13, 3.9.18, and 3.8.18 and prior.\n\nThe zipfile module is vulnerable to “quoted-overlap” zip-bombs which exploit the zip format to create a zip-bomb with a high compression ratio. The fixed versions of CPython makes the zipfile module reject zip archives which overlap entries in the archive.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":6.2,"exploitabilityScore":2.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-0450","epss":0.00173,"percentile":0.3959,"date":"2025-06-03"}],"fix":{"versions":["3.8.19","3.9.19","3.10.14","3.11.8","3.12.2","3.13.0a3"],"state":"fixed"},"advisories":[],"risk":0.09688000000000001},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2024-0450","versionConstraint":"< 3.8.19,>= 3.10.0, < 3.10.14,>= 3.11.0, < 3.11.8,>= 3.12.0, < 3.12.2,>= 3.13.0a1, < 3.13.0a3,>= 3.9.0, < 3.9.19 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.10.14"}}],"artifact":{"id":"b83d4cc9d7047529","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","accessPath":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"GHSA-xqr8-7jwr-rhp7","dataSource":"https://github.com/advisories/GHSA-xqr8-7jwr-rhp7","namespace":"github:language:python","severity":"High","urls":[],"description":"Removal of e-Tugra root certificate","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-37920","epss":0.00112,"percentile":0.30835,"date":"2025-06-03"}],"fix":{"versions":["2023.7.22"],"state":"fixed"},"advisories":[],"risk":0.08399999999999999},"relatedVulnerabilities":[{"id":"CVE-2023-37920","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-37920","namespace":"nvd:cpe","severity":"Critical","urls":["https://github.com/certifi/python-certifi/commit/8fb96ed81f71e7097ed11bc4d9b19afd7ea5c909","https://github.com/certifi/python-certifi/security/advisories/GHSA-xqr8-7jwr-rhp7","https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/C-HrP1SEq1A","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5EX6NG7WUFNUKGFHLM35KHHU3GAKXRTG/","https://github.com/certifi/python-certifi/commit/8fb96ed81f71e7097ed11bc4d9b19afd7ea5c909","https://github.com/certifi/python-certifi/security/advisories/GHSA-xqr8-7jwr-rhp7","https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/C-HrP1SEq1A","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5EX6NG7WUFNUKGFHLM35KHHU3GAKXRTG/","https://security.netapp.com/advisory/ntap-20240912-0002/"],"description":"Certifi is a curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts. Certifi prior to version 2023.07.22 recognizes \"e-Tugra\" root certificates. e-Tugra's root certificates were subject to an investigation prompted by reporting of security issues in their systems. Certifi 2023.07.22 removes root certificates from \"e-Tugra\" from the root store.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":9.8,"exploitabilityScore":3.9,"impactScore":5.9},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-37920","epss":0.00112,"percentile":0.30835,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"certifi","version":"2020.6.20"}},"found":{"versionConstraint":">=2015.4.28,<2023.7.22 (python)","vulnerabilityID":"GHSA-xqr8-7jwr-rhp7"},"fix":{"suggestedVersion":"2023.7.22"}}],"artifact":{"id":"82ed802006d3a567","name":"certifi","version":"2020.6.20","type":"python","locations":[{"path":"/lib/python3/dist-packages/certifi-2020.6.20.egg-info/PKG-INFO","accessPath":"/lib/python3/dist-packages/certifi-2020.6.20.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/lib/python3/dist-packages/certifi-2020.6.20.egg-info/top_level.txt","accessPath":"/lib/python3/dist-packages/certifi-2020.6.20.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MPL-2.0"],"cpes":["cpe:2.3:a:certifi:certifi:2020.6.20:*:*:*:*:python:*:*"],"purl":"pkg:pypi/certifi@2020.6.20","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-11168","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-11168","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/python/cpython/commit/29f348e232e82938ba2165843c448c2b291504c5","https://github.com/python/cpython/commit/634ded45545ce8cbd6fd5d49785613dd7fa9b89e","https://github.com/python/cpython/commit/b2171a2fd41416cf68afd67460578631d755a550","https://github.com/python/cpython/commit/ddca2953191c67a12b1f19d6bca41016c6ae7132","https://github.com/python/cpython/issues/103848","https://github.com/python/cpython/pull/103849","https://mail.python.org/archives/list/security-announce@python.org/thread/XPWB6XVZ5G5KGEI63M4AWLIEUF5BPH4T/","https://security.netapp.com/advisory/ntap-20250411-0004/"],"description":"The urllib.parse.urlsplit() and urlparse() functions improperly validated bracketed hosts (`[]`), allowing hosts that weren't IPv6 or IPvFuture. This behavior was not conformant to RFC 3986 and potentially enabled SSRF if a URL is processed by more than one URL parser.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:H/AT:P/PR:N/UI:N/VC:N/VI:L/VA:N/SC:N/SI:L/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:N/R:X/V:X/RE:X/U:X","metrics":{"baseScore":6.3},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:L/A:N","metrics":{"baseScore":3.7,"exploitabilityScore":2.3,"impactScore":1.5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-11168","epss":0.00154,"percentile":0.37324,"date":"2025-06-03"}],"fix":{"versions":["3.9.21","3.10.16","3.11.4","3.12.0b1"],"state":"fixed"},"advisories":[],"risk":0.077},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2024-11168","versionConstraint":"< 3.9.21,>= 3.10.0, < 3.10.16,>= 3.11.0, < 3.11.4,>= 3.12.0a1, < 3.12.0b1 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.10.16"}}],"artifact":{"id":"b83d4cc9d7047529","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","accessPath":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"GHSA-mg3v-6m49-jhp3","dataSource":"https://github.com/advisories/GHSA-mg3v-6m49-jhp3","namespace":"github:language:python","severity":"Medium","urls":[],"description":"WebOb's location header normalization during redirect leads to open redirect","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N","metrics":{"baseScore":6.1,"exploitabilityScore":2.9,"impactScore":2.8},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-42353","epss":0.00127,"percentile":0.33513,"date":"2025-06-03"}],"fix":{"versions":["1.8.8"],"state":"fixed"},"advisories":[],"risk":0.07048499999999999},"relatedVulnerabilities":[{"id":"CVE-2024-42353","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-42353","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/Pylons/webob/commit/f689bcf4f0a1f64f1735b1d5069aef5be6974b5b","https://github.com/Pylons/webob/security/advisories/GHSA-mg3v-6m49-jhp3"],"description":"WebOb provides objects for HTTP requests and responses. When WebOb normalizes the HTTP Location header to include the request hostname, it does so by parsing the URL that the user is to be redirected to with Python's urlparse, and joining it to the base URL. `urlparse` however treats a `//` at the start of a string as a URI without a scheme, and then treats the next part as the hostname. `urljoin` will then use that hostname from the second part as the hostname replacing the original one from the request. This vulnerability is patched in WebOb version 1.8.8.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N","metrics":{"baseScore":6.1,"exploitabilityScore":2.9,"impactScore":2.8},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N","metrics":{"baseScore":6.1,"exploitabilityScore":2.9,"impactScore":2.8},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-42353","epss":0.00127,"percentile":0.33513,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"webob","version":"1.8.6"}},"found":{"versionConstraint":"<=1.8.7 (python)","vulnerabilityID":"GHSA-mg3v-6m49-jhp3"},"fix":{"suggestedVersion":"1.8.8"}}],"artifact":{"id":"7e5b472418282728","name":"webob","version":"1.8.6","type":"python","locations":[{"path":"/lib/python3/dist-packages/WebOb-1.8.6.egg-info/PKG-INFO","accessPath":"/lib/python3/dist-packages/WebOb-1.8.6.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/lib/python3/dist-packages/WebOb-1.8.6.egg-info/top_level.txt","accessPath":"/lib/python3/dist-packages/WebOb-1.8.6.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:ian_bicking_project:python-webob:1.8.6:*:*:*:*:*:*:*","cpe:2.3:a:ian_bicking_project:python_webob:1.8.6:*:*:*:*:*:*:*","cpe:2.3:a:ian_bickingproject:python-webob:1.8.6:*:*:*:*:*:*:*","cpe:2.3:a:ian_bickingproject:python_webob:1.8.6:*:*:*:*:*:*:*","cpe:2.3:a:ian_bicking_project:webob:1.8.6:*:*:*:*:*:*:*","cpe:2.3:a:ianb_project:python-webob:1.8.6:*:*:*:*:*:*:*","cpe:2.3:a:ianb_project:python_webob:1.8.6:*:*:*:*:*:*:*","cpe:2.3:a:python-webob:python-webob:1.8.6:*:*:*:*:*:*:*","cpe:2.3:a:python-webob:python_webob:1.8.6:*:*:*:*:*:*:*","cpe:2.3:a:python_webob:python-webob:1.8.6:*:*:*:*:*:*:*","cpe:2.3:a:python_webob:python_webob:1.8.6:*:*:*:*:*:*:*","cpe:2.3:a:ian_bicking:python-webob:1.8.6:*:*:*:*:*:*:*","cpe:2.3:a:ian_bicking:python_webob:1.8.6:*:*:*:*:*:*:*","cpe:2.3:a:ian_bickingproject:webob:1.8.6:*:*:*:*:*:*:*","cpe:2.3:a:ianbproject:python-webob:1.8.6:*:*:*:*:*:*:*","cpe:2.3:a:ianbproject:python_webob:1.8.6:*:*:*:*:*:*:*","cpe:2.3:a:python:python-webob:1.8.6:*:*:*:*:*:*:*","cpe:2.3:a:python:python_webob:1.8.6:*:*:*:*:*:*:*","cpe:2.3:a:ianb_project:webob:1.8.6:*:*:*:*:*:*:*","cpe:2.3:a:python-webob:webob:1.8.6:*:*:*:*:*:*:*","cpe:2.3:a:python_webob:webob:1.8.6:*:*:*:*:*:*:*","cpe:2.3:a:webob:python-webob:1.8.6:*:*:*:*:*:*:*","cpe:2.3:a:webob:python_webob:1.8.6:*:*:*:*:*:*:*","cpe:2.3:a:ian_bicking:webob:1.8.6:*:*:*:*:*:*:*","cpe:2.3:a:ianb:python-webob:1.8.6:*:*:*:*:*:*:*","cpe:2.3:a:ianb:python_webob:1.8.6:*:*:*:*:*:*:*","cpe:2.3:a:ianbproject:webob:1.8.6:*:*:*:*:*:*:*","cpe:2.3:a:python:webob:1.8.6:*:*:*:*:*:*:*","cpe:2.3:a:webob:webob:1.8.6:*:*:*:*:*:*:*","cpe:2.3:a:ianb:webob:1.8.6:*:*:*:*:*:*:*"],"purl":"pkg:pypi/webob@1.8.6","upstreams":[]}},{"vulnerability":{"id":"GHSA-px8h-6qxv-m22q","dataSource":"https://github.com/advisories/GHSA-px8h-6qxv-m22q","namespace":"github:language:python","severity":"Low","urls":[],"description":"Incorrect parsing of nameless cookies leads to __Host- cookies bypass","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:A/AC:H/PR:N/UI:R/S:U/C:N/I:L/A:N","metrics":{"baseScore":2.6,"exploitabilityScore":1.2,"impactScore":1.5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-23934","epss":0.00222,"percentile":0.4516,"date":"2025-06-03"}],"fix":{"versions":["2.2.3"],"state":"fixed"},"advisories":[],"risk":0.062160000000000014},"relatedVulnerabilities":[{"id":"CVE-2023-23934","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-23934","namespace":"nvd:cpe","severity":"Low","urls":["https://github.com/pallets/werkzeug/commit/cf275f42acad1b5950c50ffe8ef58fe62cdce028","https://github.com/pallets/werkzeug/releases/tag/2.2.3","https://github.com/pallets/werkzeug/security/advisories/GHSA-px8h-6qxv-m22q","https://security.netapp.com/advisory/ntap-20230818-0003/","https://www.debian.org/security/2023/dsa-5470","https://github.com/pallets/werkzeug/commit/cf275f42acad1b5950c50ffe8ef58fe62cdce028","https://github.com/pallets/werkzeug/releases/tag/2.2.3","https://github.com/pallets/werkzeug/security/advisories/GHSA-px8h-6qxv-m22q","https://security.netapp.com/advisory/ntap-20230818-0003/","https://www.debian.org/security/2023/dsa-5470"],"description":"Werkzeug is a comprehensive WSGI web application library. Browsers may allow \"nameless\" cookies that look like `=value` instead of `key=value`. A vulnerable browser may allow a compromised application on an adjacent subdomain to exploit this to set a cookie like `=__Host-test=bad` for another subdomain. Werkzeug prior to 2.2.3 will parse the cookie `=__Host-test=bad` as __Host-test=bad`. If a Werkzeug application is running next to a vulnerable or malicious subdomain which sets such a cookie using a vulnerable browser, the Werkzeug application will see the bad cookie value but the valid cookie key. The issue is fixed in Werkzeug 2.2.3.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:A/AC:L/PR:N/UI:R/S:U/C:N/I:L/A:N","metrics":{"baseScore":3.5,"exploitabilityScore":2.1,"impactScore":1.5},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:A/AC:H/PR:N/UI:R/S:U/C:N/I:L/A:N","metrics":{"baseScore":2.6,"exploitabilityScore":1.2,"impactScore":1.5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-23934","epss":0.00222,"percentile":0.4516,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"werkzeug","version":"2.2.2"}},"found":{"versionConstraint":"<2.2.3 (python)","vulnerabilityID":"GHSA-px8h-6qxv-m22q"},"fix":{"suggestedVersion":"2.2.3"}}],"artifact":{"id":"a523e09d35353d5e","name":"werkzeug","version":"2.2.2","type":"python","locations":[{"path":"/lib/python3/dist-packages/Werkzeug-2.2.2.egg-info/PKG-INFO","accessPath":"/lib/python3/dist-packages/Werkzeug-2.2.2.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/lib/python3/dist-packages/Werkzeug-2.2.2.egg-info/top_level.txt","accessPath":"/lib/python3/dist-packages/Werkzeug-2.2.2.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:armin_ronacher_project:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher_project:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher_project:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python-werkzeug:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python-werkzeug:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python-werkzeug:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python:werkzeug:2.2.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/werkzeug@2.2.2","upstreams":[]}},{"vulnerability":{"id":"CVE-2023-27043","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-27043","namespace":"nvd:cpe","severity":"Medium","urls":["http://python.org","https://github.com/python/cpython/issues/102988","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4ZAEFSFZDNBNJPNOUTLG5COISGQDLMGV/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/75DTHSTNOFFNAWHXKMDXS7EJWC6W2FUC/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ARI7VDSNTQVXRQFM6IK5GSSLEIYV4VZH/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/BQAKLUJMHFGVBRDPEY57BJGNCE5UUPHW/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HXYVPEZUA3465AEFX5JVFVP7KIFZMF3N/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/N6M5I6OQHJABNEYY555HUMMKX3Y4P25Z/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NEUNZSZ3CVSM2QWVYH3N2XGOCDWNYUA3/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ORLXS5YTKN65E2Q2NWKXMFS5FWQHRNZW/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/P2MAICLFDDO3QVNHTZ2OCERZQ34R2PIC/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/P2W2BZQIHMCKRI5FNBJERFYMS5PK6TAH/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PHVGRKQAGANCSGFI3QMYOCIMS4IFOZA5/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PU6Y2S5CBN5BWCBDAJFTGIBZLK3S2G3J/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/QDRDDPDN3VFIYXJIYEABY6USX5EU66AG/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/RDDC2VOX7OQC6OHMYTVD4HLFZIV6PYBC/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SINP4OVYNB2AGDYI2GS37EMW3H3F7XPZ/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SOX7BCN6YL7B3RFPEEXPIU5CMTEHJOKR/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VZXC32CJ7TWDPJO6GY2XIQRO7JZX5FLP/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/XWMBD4LNHWEXRI6YVFWJMTJQUL5WOFTS/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YQVY5C5REXWJIORJIL2FIL3ALOEJEF72/","https://python-security.readthedocs.io/vuln/email-parseaddr-realname.html","https://security.netapp.com/advisory/ntap-20230601-0003/","http://python.org","https://github.com/python/cpython/issues/102988","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4ZAEFSFZDNBNJPNOUTLG5COISGQDLMGV/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/75DTHSTNOFFNAWHXKMDXS7EJWC6W2FUC/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ARI7VDSNTQVXRQFM6IK5GSSLEIYV4VZH/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/BQAKLUJMHFGVBRDPEY57BJGNCE5UUPHW/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HXYVPEZUA3465AEFX5JVFVP7KIFZMF3N/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/N6M5I6OQHJABNEYY555HUMMKX3Y4P25Z/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NEUNZSZ3CVSM2QWVYH3N2XGOCDWNYUA3/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ORLXS5YTKN65E2Q2NWKXMFS5FWQHRNZW/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/P2MAICLFDDO3QVNHTZ2OCERZQ34R2PIC/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/P2W2BZQIHMCKRI5FNBJERFYMS5PK6TAH/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PHVGRKQAGANCSGFI3QMYOCIMS4IFOZA5/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PU6Y2S5CBN5BWCBDAJFTGIBZLK3S2G3J/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/QDRDDPDN3VFIYXJIYEABY6USX5EU66AG/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/RDDC2VOX7OQC6OHMYTVD4HLFZIV6PYBC/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SINP4OVYNB2AGDYI2GS37EMW3H3F7XPZ/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SOX7BCN6YL7B3RFPEEXPIU5CMTEHJOKR/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VZXC32CJ7TWDPJO6GY2XIQRO7JZX5FLP/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/XWMBD4LNHWEXRI6YVFWJMTJQUL5WOFTS/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YQVY5C5REXWJIORJIL2FIL3ALOEJEF72/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4ZAEFSFZDNBNJPNOUTLG5COISGQDLMGV/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/75DTHSTNOFFNAWHXKMDXS7EJWC6W2FUC/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ARI7VDSNTQVXRQFM6IK5GSSLEIYV4VZH/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/BQAKLUJMHFGVBRDPEY57BJGNCE5UUPHW/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HXYVPEZUA3465AEFX5JVFVP7KIFZMF3N/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N6M5I6OQHJABNEYY555HUMMKX3Y4P25Z/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NEUNZSZ3CVSM2QWVYH3N2XGOCDWNYUA3/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ORLXS5YTKN65E2Q2NWKXMFS5FWQHRNZW/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/P2MAICLFDDO3QVNHTZ2OCERZQ34R2PIC/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/P2W2BZQIHMCKRI5FNBJERFYMS5PK6TAH/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PHVGRKQAGANCSGFI3QMYOCIMS4IFOZA5/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PU6Y2S5CBN5BWCBDAJFTGIBZLK3S2G3J/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QDRDDPDN3VFIYXJIYEABY6USX5EU66AG/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/RDDC2VOX7OQC6OHMYTVD4HLFZIV6PYBC/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SINP4OVYNB2AGDYI2GS37EMW3H3F7XPZ/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VZXC32CJ7TWDPJO6GY2XIQRO7JZX5FLP/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XWMBD4LNHWEXRI6YVFWJMTJQUL5WOFTS/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YQVY5C5REXWJIORJIL2FIL3ALOEJEF72/","https://python-security.readthedocs.io/vuln/email-parseaddr-realname.html","https://security.netapp.com/advisory/ntap-20230601-0003/"],"description":"The email module of Python through 3.11.3 incorrectly parses e-mail addresses that contain a special character. The wrong portion of an RFC2822 header is identified as the value of the addr-spec. In some applications, an attacker can bypass a protection mechanism in which application access is granted only after verifying receipt of e-mail to a specific domain (e.g., only @company.example.com addresses may be used for signup). This occurs in email/_parseaddr.py in recent versions of Python.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N","metrics":{"baseScore":5.3,"exploitabilityScore":3.9,"impactScore":1.5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-27043","epss":0.00115,"percentile":0.31355,"date":"2025-06-03"}],"fix":{"versions":["3.8.20","3.9.20","3.10.15","3.11.10","3.12.6","3.13.0a1"],"state":"fixed"},"advisories":[],"risk":0.059225},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2023-27043","versionConstraint":"< 3.8.20,>= 3.10.0a0, < 3.10.15,>= 3.11.0a0, < 3.11.10,>= 3.12.0a0, < 3.12.6,>= 3.13.0a0, < 3.13.0a1,>= 3.9.0a0, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.10.15"}}],"artifact":{"id":"b83d4cc9d7047529","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","accessPath":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-8088","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-8088","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/python/cpython/commit/0aa1ee22ab6e204e9d3d0e9dd63ea648ed691ef1","https://github.com/python/cpython/commit/2231286d78d328c2f575e0b05b16fe447d1656d6","https://github.com/python/cpython/commit/795f2597a4be988e2bb19b69ff9958e981cb894e","https://github.com/python/cpython/commit/7bc367e464ce50b956dd232c1dfa1cad4e7fb814","https://github.com/python/cpython/commit/7e8883a3f04d308302361aeffc73e0e9837f19d4","https://github.com/python/cpython/commit/8c7348939d8a3ecd79d630075f6be1b0c5b41f64","https://github.com/python/cpython/commit/95b073bddefa6243effa08e131e297c0383e7f6a","https://github.com/python/cpython/commit/962055268ed4f2ca1d717bfc8b6385de50a23ab7","https://github.com/python/cpython/commit/dcc5182f27c1500006a1ef78e10613bb45788dea","https://github.com/python/cpython/commit/e0264a61119d551658d9445af38323ba94fc16db","https://github.com/python/cpython/commit/fc0b8259e693caa8400fa8b6ac1e494e47ea7798","https://github.com/python/cpython/issues/122905","https://github.com/python/cpython/issues/123270","https://github.com/python/cpython/pull/122906","https://mail.python.org/archives/list/security-announce@python.org/thread/GNFCKVI4TCATKQLALJ5SN4L4CSPSMILU/","http://www.openwall.com/lists/oss-security/2024/08/22/1","http://www.openwall.com/lists/oss-security/2024/08/22/4","http://www.openwall.com/lists/oss-security/2024/08/23/1","http://www.openwall.com/lists/oss-security/2024/08/23/2","https://security.netapp.com/advisory/ntap-20241011-0010/"],"description":"There is a HIGH severity vulnerability affecting the CPython \"zipfile\"\nmodule affecting \"zipfile.Path\". Note that the more common API \"zipfile.ZipFile\" class is unaffected.\n\n\n\n\n\nWhen iterating over names of entries in a zip archive (for example, methods\nof \"zipfile.Path\" like \"namelist()\", \"iterdir()\", etc)\nthe process can be put into an infinite loop with a maliciously crafted\nzip archive. This defect applies when reading only metadata or extracting\nthe contents of the zip archive. Programs that are not handling\nuser-controlled zip archives are not affected.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:H/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:N/AU:N/R:U/V:X/RE:L/U:X","metrics":{"baseScore":8.7},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-8088","epss":0.00071,"percentile":0.22534,"date":"2025-06-03"}],"fix":{"versions":["3.8.20","3.9.20","3.10.15","3.11.10","3.12.6","3.13.0rc2"],"state":"fixed"},"advisories":[],"risk":0.05750999999999999},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2024-8088","versionConstraint":"< 3.8.20,>= 3.10.0, < 3.10.15,>= 3.11.0, < 3.11.10,>= 3.12.0, < 3.12.6,>= 3.13.0a1, < 3.13.0rc2,>= 3.9.0, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.10.15"}}],"artifact":{"id":"b83d4cc9d7047529","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","accessPath":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"CVE-2023-6597","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-6597","namespace":"nvd:cpe","severity":"High","urls":["http://www.openwall.com/lists/oss-security/2024/03/20/5","https://github.com/python/cpython/commit/02a9259c717738dfe6b463c44d7e17f2b6d2cb3a","https://github.com/python/cpython/commit/5585334d772b253a01a6730e8202ffb1607c3d25","https://github.com/python/cpython/commit/6ceb8aeda504b079fef7a57b8d81472f15cdd9a5","https://github.com/python/cpython/commit/81c16cd94ec38d61aa478b9a452436dc3b1b524d","https://github.com/python/cpython/commit/8eaeefe49d179ca4908d052745e3bb8b6f238f82","https://github.com/python/cpython/commit/d54e22a669ae6e987199bb5d2c69bb5a46b0083b","https://github.com/python/cpython/issues/91133","https://lists.debian.org/debian-lts-announce/2024/03/msg00025.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/T3IGRX54M7RNCQOXVQO5KQKTGWCOABIM/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/U5VHWS52HGD743C47UMCSAK2A773M2YE/","https://mail.python.org/archives/list/security-announce@python.org/thread/Q5C6ATFC67K53XFV4KE45325S7NS62LD/","http://www.openwall.com/lists/oss-security/2024/03/20/5","https://github.com/python/cpython/commit/02a9259c717738dfe6b463c44d7e17f2b6d2cb3a","https://github.com/python/cpython/commit/5585334d772b253a01a6730e8202ffb1607c3d25","https://github.com/python/cpython/commit/6ceb8aeda504b079fef7a57b8d81472f15cdd9a5","https://github.com/python/cpython/commit/81c16cd94ec38d61aa478b9a452436dc3b1b524d","https://github.com/python/cpython/commit/8eaeefe49d179ca4908d052745e3bb8b6f238f82","https://github.com/python/cpython/commit/d54e22a669ae6e987199bb5d2c69bb5a46b0083b","https://github.com/python/cpython/issues/91133","https://lists.debian.org/debian-lts-announce/2024/03/msg00025.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/T3IGRX54M7RNCQOXVQO5KQKTGWCOABIM/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/U5VHWS52HGD743C47UMCSAK2A773M2YE/","https://mail.python.org/archives/list/security-announce@python.org/thread/Q5C6ATFC67K53XFV4KE45325S7NS62LD/"],"description":"An issue was found in the CPython `tempfile.TemporaryDirectory` class affecting versions 3.12.1, 3.11.7, 3.10.13, 3.9.18, and 3.8.18 and prior.\n\nThe tempfile.TemporaryDirectory class would dereference symlinks during cleanup of permissions-related errors. This means users which can run privileged programs are potentially able to modify permissions of files referenced by symlinks in some circumstances.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:H/PR:N/UI:N/S:C/C:H/I:H/A:N","metrics":{"baseScore":7.8,"exploitabilityScore":1.5,"impactScore":5.8},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-6597","epss":0.00073,"percentile":0.23139,"date":"2025-06-03"}],"fix":{"versions":["3.8.19","3.9.19","3.10.14","3.11.8","3.12.1","3.13.0a3"],"state":"fixed"},"advisories":[],"risk":0.05584499999999999},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2023-6597","versionConstraint":"< 3.8.19,>= 3.10.0, < 3.10.14,>= 3.11.0, < 3.11.8,>= 3.12.0, < 3.12.1,>= 3.13.0a1, < 3.13.0a3,>= 3.9.0, < 3.9.19 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.10.14"}}],"artifact":{"id":"b83d4cc9d7047529","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","accessPath":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"GHSA-9v9h-cgj8-h64p","dataSource":"https://github.com/advisories/GHSA-9v9h-cgj8-h64p","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Null pointer dereference in PKCS12 parsing","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-0727","epss":0.00103,"percentile":0.29443,"date":"2025-06-03"}],"fix":{"versions":["42.0.2"],"state":"fixed"},"advisories":[],"risk":0.05407500000000001},"relatedVulnerabilities":[{"id":"CVE-2024-0727","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-0727","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/openssl/openssl/commit/09df4395b5071217b76dc7d3d2e630eb8c5a79c2","https://github.com/openssl/openssl/commit/775acfdbd0c6af9ac855f34969cdab0c0c90844a","https://github.com/openssl/openssl/commit/d135eeab8a5dbf72b3da5240bab9ddb7678dbd2c","https://github.openssl.org/openssl/extended-releases/commit/03b3941d60c4bce58fab69a0c22377ab439bc0e8","https://github.openssl.org/openssl/extended-releases/commit/aebaa5883e31122b404e450732dc833dc9dee539","https://www.openssl.org/news/secadv/20240125.txt","http://www.openwall.com/lists/oss-security/2024/03/11/1","https://github.com/openssl/openssl/commit/09df4395b5071217b76dc7d3d2e630eb8c5a79c2","https://github.com/openssl/openssl/commit/775acfdbd0c6af9ac855f34969cdab0c0c90844a","https://github.com/openssl/openssl/commit/d135eeab8a5dbf72b3da5240bab9ddb7678dbd2c","https://github.openssl.org/openssl/extended-releases/commit/03b3941d60c4bce58fab69a0c22377ab439bc0e8","https://github.openssl.org/openssl/extended-releases/commit/aebaa5883e31122b404e450732dc833dc9dee539","https://security.netapp.com/advisory/ntap-20240208-0006/","https://www.openssl.org/news/secadv/20240125.txt"],"description":"Issue summary: Processing a maliciously formatted PKCS12 file may lead OpenSSL\nto crash leading to a potential Denial of Service attack\n\nImpact summary: Applications loading files in the PKCS12 format from untrusted\nsources might terminate abruptly.\n\nA file in PKCS12 format can contain certificates and keys and may come from an\nuntrusted source. The PKCS12 specification allows certain fields to be NULL, but\nOpenSSL does not correctly check for this case. This can lead to a NULL pointer\ndereference that results in OpenSSL crashing. If an application processes PKCS12\nfiles from an untrusted source using the OpenSSL APIs then that application will\nbe vulnerable to this issue.\n\nOpenSSL APIs that are vulnerable to this are: PKCS12_parse(),\nPKCS12_unpack_p7data(), PKCS12_unpack_p7encdata(), PKCS12_unpack_authsafes()\nand PKCS12_newpass().\n\nWe have also fixed a similar issue in SMIME_write_PKCS7(). However since this\nfunction is related to writing data we do not consider it security significant.\n\nThe FIPS modules in 3.2, 3.1 and 3.0 are not affected by this issue.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-0727","epss":0.00103,"percentile":0.29443,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"3.4.8"}},"found":{"versionConstraint":"<42.0.2 (python)","vulnerabilityID":"GHSA-9v9h-cgj8-h64p"},"fix":{"suggestedVersion":"42.0.2"}}],"artifact":{"id":"8ab3d91ea77f3b32","name":"cryptography","version":"3.4.8","type":"python","locations":[{"path":"/lib/python3/dist-packages/cryptography-3.4.8.egg-info/PKG-INFO","accessPath":"/lib/python3/dist-packages/cryptography-3.4.8.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/lib/python3/dist-packages/cryptography-3.4.8.egg-info/top_level.txt","accessPath":"/lib/python3/dist-packages/cryptography-3.4.8.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD or Apache License, Version 2.0"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:3.4.8:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:3.4.8:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@3.4.8","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-6923","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-6923","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/python/cpython/commit/06f28dc236708f72871c64d4bc4b4ea144c50147","https://github.com/python/cpython/commit/097633981879b3c9de9a1dd120d3aa585ecc2384","https://github.com/python/cpython/commit/4766d1200fdf8b6728137aa2927a297e224d5fa7","https://github.com/python/cpython/commit/4aaa4259b5a6e664b7316a4d60bdec7ee0f124d0","https://github.com/python/cpython/commit/b158a76ce094897c870fb6b3de62887b7ccc33f1","https://github.com/python/cpython/commit/f7be505d137a22528cb0fc004422c0081d5d90e6","https://github.com/python/cpython/commit/f7c0f09e69e950cf3c5ada9dbde93898eb975533","https://github.com/python/cpython/issues/121650","https://github.com/python/cpython/pull/122233","https://mail.python.org/archives/list/security-announce@python.org/thread/QH3BUOE2DYQBWP7NAQ7UNHPPOELKISRW/","http://www.openwall.com/lists/oss-security/2024/08/01/3","http://www.openwall.com/lists/oss-security/2024/08/02/2","https://lists.debian.org/debian-lts-announce/2025/01/msg00005.html","https://security.netapp.com/advisory/ntap-20240926-0003/"],"description":"There is a MEDIUM severity vulnerability affecting CPython.\n\nThe \nemail module didn’t properly quote newlines for email headers when \nserializing an email message allowing for header injection when an email\n is serialized.","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:L/I:L/A:L","metrics":{"baseScore":5.5,"exploitabilityScore":2.1,"impactScore":3.4},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-6923","epss":0.00089,"percentile":0.26706,"date":"2025-06-03"}],"fix":{"versions":["3.8.20","3.9.20","3.10.15","3.11.10","3.12.5","3.13.0rc2"],"state":"fixed"},"advisories":[],"risk":0.046725},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2024-6923","versionConstraint":"< 3.8.20,>= 3.10.0, < 3.10.15,>= 3.11.0, < 3.11.10,>= 3.12.0, < 3.12.5,>= 3.13.0a1, < 3.13.0rc2,>= 3.9.0, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.10.15"}}],"artifact":{"id":"b83d4cc9d7047529","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","accessPath":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"CVE-2025-1795","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-1795","namespace":"nvd:cpe","severity":"Low","urls":["https://github.com/python/cpython/commit/09fab93c3d857496c0bd162797fab816c311ee48","https://github.com/python/cpython/commit/70754d21c288535e86070ca7a6e90dcb670b8593","https://github.com/python/cpython/commit/9148b77e0af91cdacaa7fe3dfac09635c3fe9a74","https://github.com/python/cpython/issues/100884","https://github.com/python/cpython/pull/100885","https://github.com/python/cpython/pull/119099","https://mail.python.org/archives/list/security-announce@python.org/thread/MB62IZMEC3UM6SGHP5LET5JX2Y7H4ZUR/"],"description":"During an address list folding when a separating comma ends up on a folded line and that line is to be unicode-encoded then the separator itself is also unicode-encoded. Expected behavior is that the separating comma remains a plan comma. This can result in the address header being misinterpreted by some mail servers.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:H/AT:P/PR:L/UI:N/VC:L/VI:N/VA:N/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":2.3},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-1795","epss":0.00167,"percentile":0.38927,"date":"2025-06-03"}],"fix":{"versions":["3.11.9","3.12.3","3.13.0a5"],"state":"fixed"},"advisories":[],"risk":0.044255},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2025-1795","versionConstraint":"< 3.11.9,>= 3.12.0, < 3.12.3,>= 3.13.0a1, < 3.13.0a5 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.11.9"}}],"artifact":{"id":"b83d4cc9d7047529","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","accessPath":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"GHSA-2g68-c3qc-8985","dataSource":"https://github.com/advisories/GHSA-2g68-c3qc-8985","namespace":"github:language:python","severity":"High","urls":[],"description":"Werkzeug debugger vulnerable to remote execution when interacting with attacker controlled domain","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":1.7,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-34069","epss":0.0005,"percentile":0.15342,"date":"2025-06-03"}],"fix":{"versions":["3.0.3"],"state":"fixed"},"advisories":[],"risk":0.0375},"relatedVulnerabilities":[{"id":"CVE-2024-34069","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-34069","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pallets/werkzeug/commit/3386395b24c7371db11a5b8eaac0c91da5362692","https://github.com/pallets/werkzeug/security/advisories/GHSA-2g68-c3qc-8985","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/H4SH32AM3CTPMAAEOIDAN7VU565LO4IR/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HFERFN7PINV4MOGMGA3DPIXJPDCYOEJZ/","https://security.netapp.com/advisory/ntap-20240614-0004/","https://github.com/pallets/werkzeug/commit/3386395b24c7371db11a5b8eaac0c91da5362692","https://github.com/pallets/werkzeug/security/advisories/GHSA-2g68-c3qc-8985","https://lists.debian.org/debian-lts-announce/2025/02/msg00026.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/H4SH32AM3CTPMAAEOIDAN7VU565LO4IR/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HFERFN7PINV4MOGMGA3DPIXJPDCYOEJZ/","https://security.netapp.com/advisory/ntap-20240614-0004/"],"description":"Werkzeug is a comprehensive WSGI web application library. The debugger in affected versions of Werkzeug can allow an attacker to execute code on a developer's machine under some circumstances. This requires the attacker to get the developer to interact with a domain and subdomain they control, and enter the debugger PIN, but if they are successful it allows access to the debugger even if it is only running on localhost. This also requires the attacker to guess a URL in the developer's application that will trigger the debugger. This vulnerability is fixed in 3.0.3.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":1.7,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-34069","epss":0.0005,"percentile":0.15342,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"werkzeug","version":"2.2.2"}},"found":{"versionConstraint":"<3.0.3 (python)","vulnerabilityID":"GHSA-2g68-c3qc-8985"},"fix":{"suggestedVersion":"3.0.3"}}],"artifact":{"id":"a523e09d35353d5e","name":"werkzeug","version":"2.2.2","type":"python","locations":[{"path":"/lib/python3/dist-packages/Werkzeug-2.2.2.egg-info/PKG-INFO","accessPath":"/lib/python3/dist-packages/Werkzeug-2.2.2.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/lib/python3/dist-packages/Werkzeug-2.2.2.egg-info/top_level.txt","accessPath":"/lib/python3/dist-packages/Werkzeug-2.2.2.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:armin_ronacher_project:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher_project:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher_project:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python-werkzeug:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python-werkzeug:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python-werkzeug:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python:werkzeug:2.2.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/werkzeug@2.2.2","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-3219","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-3219","namespace":"nvd:cpe","severity":"Medium","urls":["http://www.openwall.com/lists/oss-security/2024/07/29/3","https://github.com/python/cpython/commit/06fa244666ec6335a3b9bf2367e31b42b9a89b20","https://github.com/python/cpython/commit/0b65c8bf5367625673eafb92f85046a1b31259f2","https://github.com/python/cpython/commit/220e31adeaaa8436c9ff234cba1398bc49e2bb6c","https://github.com/python/cpython/commit/2621a8a40ba4b2c68ca564671b7daa5da80a4508","https://github.com/python/cpython/commit/31302f5fc24eecd693f0c8aaba7c2840b09b594d","https://github.com/python/cpython/commit/3f5d9d12c74787fbf3f5891835c85cc15526c86d","https://github.com/python/cpython/commit/5df322e91a40909e6904bbdbc0c3a6b6a9eead39","https://github.com/python/cpython/commit/5f90abaa786f994db3907fc31e2ee00ea2cf0929","https://github.com/python/cpython/commit/78df1043dbdce5c989600616f9f87b4ee72944e5","https://github.com/python/cpython/commit/b252317956b7fc035bb3774ef6a177e227f9fc54","https://github.com/python/cpython/commit/c21a36112a0028d7ac3cf8f480e0dc88dba5922c","https://github.com/python/cpython/commit/c5655aa6ad120d2ed7f255bebd6e8b71a9c07dde","https://github.com/python/cpython/commit/e319f774f9e766a2b92949444a2d46081df3363a","https://github.com/python/cpython/commit/f071f01b7b7e19d7d6b3a4b0ec62f820ecb14660","https://github.com/python/cpython/issues/122133","https://github.com/python/cpython/pull/122134","https://mail.python.org/archives/list/security-announce@python.org/thread/WYKDQWIERRE2ICIYMSVRZJO33GSCWU2B/","http://www.openwall.com/lists/oss-security/2024/07/29/3","https://github.com/python/cpython/commit/06fa244666ec6335a3b9bf2367e31b42b9a89b20","https://github.com/python/cpython/commit/0b65c8bf5367625673eafb92f85046a1b31259f2","https://github.com/python/cpython/commit/220e31adeaaa8436c9ff234cba1398bc49e2bb6c","https://github.com/python/cpython/commit/5f90abaa786f994db3907fc31e2ee00ea2cf0929","https://github.com/python/cpython/commit/b252317956b7fc035bb3774ef6a177e227f9fc54","https://github.com/python/cpython/issues/122133","https://github.com/python/cpython/pull/122134","https://mail.python.org/archives/list/security-announce@python.org/thread/WYKDQWIERRE2ICIYMSVRZJO33GSCWU2B/","https://security.netapp.com/advisory/ntap-20250502-0004/"],"description":"The\n “socket” module provides a pure-Python fallback to the \nsocket.socketpair() function for platforms that don’t support AF_UNIX, \nsuch as Windows. This pure-Python implementation uses AF_INET or \nAF_INET6 to create a local connected pair of sockets. The connection \nbetween the two sockets was not verified before passing the two sockets \nback to the user, which leaves the server socket vulnerable to a \nconnection race from a malicious local peer.\n\nPlatforms that support AF_UNIX such as Linux and macOS are not affected by this vulnerability. Versions prior to CPython 3.5 are not affected due to the vulnerable API not being included.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:L/AC:L/AT:N/PR:N/UI:N/VC:L/VI:N/VA:N/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":5.1},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-3219","epss":0.00059,"percentile":0.18721,"date":"2025-06-03"}],"fix":{"versions":["3.8.20","3.9.20","3.10.15","3.11.10","3.12.5","3.13.0rc1"],"state":"fixed"},"advisories":[],"risk":0.029795000000000002},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2024-3219","versionConstraint":"< 3.8.20,>= 3.10.0, < 3.10.15,>= 3.11.0, < 3.11.10,>= 3.12.0, < 3.12.5,>= 3.13.0a1, < 3.13.0rc1,>= 3.9.0, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.10.15"}}],"artifact":{"id":"b83d4cc9d7047529","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","accessPath":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"GHSA-g4mx-q9vg-27p4","dataSource":"https://github.com/advisories/GHSA-g4mx-q9vg-27p4","namespace":"github:language:python","severity":"Medium","urls":[],"description":"urllib3's request body not stripped after redirect from 303 status changes request method to GET","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.2,"exploitabilityScore":0.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-45803","epss":0.00062,"percentile":0.1968,"date":"2025-06-03"}],"fix":{"versions":["1.26.18"],"state":"fixed"},"advisories":[],"risk":0.02852},"relatedVulnerabilities":[{"id":"CVE-2023-45803","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-45803","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/urllib3/urllib3/commit/4e98d57809dacab1cbe625fddeec1a290c478ea9","https://github.com/urllib3/urllib3/security/advisories/GHSA-g4mx-q9vg-27p4","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4R2Y5XK3WALSR3FNAGN7JBYV2B343ZKB/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PPDPLM6UUMN55ESPQWJFLLIZY4ZKCNRX/","https://www.rfc-editor.org/rfc/rfc9110.html#name-get","https://github.com/urllib3/urllib3/commit/4e98d57809dacab1cbe625fddeec1a290c478ea9","https://github.com/urllib3/urllib3/security/advisories/GHSA-g4mx-q9vg-27p4","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4R2Y5XK3WALSR3FNAGN7JBYV2B343ZKB/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PPDPLM6UUMN55ESPQWJFLLIZY4ZKCNRX/","https://www.rfc-editor.org/rfc/rfc9110.html#name-get"],"description":"urllib3 is a user-friendly HTTP client library for Python. urllib3 previously wouldn't remove the HTTP request body when an HTTP redirect response using status 301, 302, or 303 after the request had its method changed from one that could accept a request body (like `POST`) to `GET` as is required by HTTP RFCs. Although this behavior is not specified in the section for redirects, it can be inferred by piecing together information from different sections and we have observed the behavior in other major HTTP client implementations like curl and web browsers. Because the vulnerability requires a previously trusted service to become compromised in order to have an impact on confidentiality we believe the exploitability of this vulnerability is low. Additionally, many users aren't putting sensitive data in HTTP request bodies, if this is the case then this vulnerability isn't exploitable. Both of the following conditions must be true to be affected by this vulnerability: 1. Using urllib3 and submitting sensitive information in the HTTP request body (such as form data or JSON) and 2. The origin service is compromised and starts redirecting using 301, 302, or 303 to a malicious peer or the redirected-to service becomes compromised. This issue has been addressed in versions 1.26.18 and 2.0.7 and users are advised to update to resolve this issue. Users unable to update should disable redirects for services that aren't expecting to respond with redirects with `redirects=False` and disable automatic redirects with `redirects=False` and handle 301, 302, and 303 redirects manually by stripping the HTTP request body.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.2,"exploitabilityScore":0.6,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.2,"exploitabilityScore":0.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-45803","epss":0.00062,"percentile":0.1968,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"urllib3","version":"1.26.5"}},"found":{"versionConstraint":">=0,<1.26.18 (python)","vulnerabilityID":"GHSA-g4mx-q9vg-27p4"},"fix":{"suggestedVersion":"1.26.18"}}],"artifact":{"id":"ec3d240d7279ae9b","name":"urllib3","version":"1.26.5","type":"python","locations":[{"path":"/lib/python3/dist-packages/urllib3-1.26.5.egg-info/PKG-INFO","accessPath":"/lib/python3/dist-packages/urllib3-1.26.5.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/lib/python3/dist-packages/urllib3-1.26.5.egg-info/top_level.txt","accessPath":"/lib/python3/dist-packages/urllib3-1.26.5.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:urllib3:1.26.5:*:*:*:*:*:*:*"],"purl":"pkg:pypi/urllib3@1.26.5","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-9287","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-9287","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/python/cpython/commit/633555735a023d3e4d92ba31da35b1205f9ecbd7","https://github.com/python/cpython/commit/8450b2482586857d689b6658f08de9c8179af7db","https://github.com/python/cpython/commit/9286ab3a107ea41bd3f3c3682ce2512692bdded8","https://github.com/python/cpython/commit/ae961ae94bf19c8f8c7fbea3d1c25cc55ce8ae97","https://github.com/python/cpython/commit/d48cc82ed25e26b02eb97c6263d95dcaa1e9111b","https://github.com/python/cpython/commit/e52095a0c1005a87eed2276af7a1f2f66e2b6483","https://github.com/python/cpython/issues/124651","https://github.com/python/cpython/pull/124712","https://mail.python.org/archives/list/security-announce@python.org/thread/RSPJ2B5JL22FG3TKUJ7D7DQ4N5JRRBZL/","https://security.netapp.com/advisory/ntap-20250425-0006/"],"description":"A vulnerability has been found in the CPython `venv` module and CLI where path names provided when creating a virtual environment were not quoted properly, allowing the creator to inject commands into virtual environment \"activation\" scripts (ie \"source venv/bin/activate\"). This means that attacker-controlled virtual environments are able to run commands when the virtual environment is activated. Virtual environments which are not created by an attacker or which aren't activated before being used (ie \"./venv/bin/python\") are not affected.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":7.8,"exploitabilityScore":1.9,"impactScore":5.9},"vendorMetadata":{}},{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:L/AC:L/AT:P/PR:H/UI:A/VC:H/VI:H/VA:N/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:Green","metrics":{"baseScore":5.3},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-9287","epss":0.00038,"percentile":0.1055,"date":"2025-06-03"}],"fix":{"versions":["3.9.21","3.10.16","3.11.11","3.12.8","3.13.1","3.14.0a2"],"state":"fixed"},"advisories":[],"risk":0.026695},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2024-9287","versionConstraint":"< 3.9.21,>= 3.10.0, < 3.10.16,>= 3.11.0, < 3.11.11,>= 3.12.0, < 3.12.8,>= 3.13.0, < 3.13.1,>= 3.14.0a1, < 3.14.0a2 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.10.16"}}],"artifact":{"id":"b83d4cc9d7047529","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","accessPath":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-3220","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-3220","namespace":"nvd:cpe","severity":"Low","urls":["https://mail.python.org/archives/list/security-announce@python.org/thread/CDXW34ND2LSAOYAR5N6UNONP4ZBX4D6R/","http://www.openwall.com/lists/oss-security/2025/02/14/8","https://security.netapp.com/advisory/ntap-20250314-0001/"],"description":"There is a defect in the CPython standard library module “mimetypes” where on Windows the default list of known file locations are writable meaning other users can create invalid files to cause MemoryError to be raised on Python runtime startup or have file extensions be interpreted as the incorrect file type.\n\nThis defect is caused by the default locations of Linux and macOS platforms (such as “/etc/mime.types”) also being used on Windows, where they are user-writable locations (“C:\\etc\\mime.types”).\n\nTo work-around this issue a user can call mimetypes.init() with an empty list (“[]”) on Windows platforms to avoid using the default list of known file locations.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:L/AT:P/PR:L/UI:N/VC:N/VI:L/VA:L/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":2.3},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-3220","epss":0.00088,"percentile":0.26554,"date":"2025-06-03"}],"fix":{"versions":["3.14.0"],"state":"fixed"},"advisories":[],"risk":0.023320000000000004},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2024-3220","versionConstraint":"< 3.14.0 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.14.0"}}],"artifact":{"id":"b83d4cc9d7047529","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","accessPath":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"CVE-2023-36632","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-36632","namespace":"nvd:cpe","severity":"High","urls":["https://docs.python.org/3/library/email.html","https://docs.python.org/3/library/email.utils.html","https://github.com/Daybreak2019/PoC_python3.9_Vul/blob/main/RecursionError-email.utils.parseaddr.py","https://github.com/python/cpython/issues/103800","https://docs.python.org/3/library/email.html","https://docs.python.org/3/library/email.utils.html","https://github.com/Daybreak2019/PoC_python3.9_Vul/blob/main/RecursionError-email.utils.parseaddr.py","https://github.com/python/cpython/issues/103800"],"description":"The legacy email.utils.parseaddr function in Python through 3.11.4 allows attackers to trigger \"RecursionError: maximum recursion depth exceeded while calling a Python object\" via a crafted argument. This argument is plausibly an untrusted value from an application's input data that was supposed to contain a name and an e-mail address. NOTE: email.utils.parseaddr is categorized as a Legacy API in the documentation of the Python email package. Applications should instead use the email.parser.BytesParser or email.parser.Parser class. NOTE: the vendor's perspective is that this is neither a vulnerability nor a bug. The email package is intended to have size limits and to throw an exception when limits are exceeded; they were exceeded by the example demonstration code.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-36632","epss":0.0003,"percentile":0.0708,"date":"2025-06-03"}],"fix":{"versions":[],"state":""},"advisories":[],"risk":0.0225},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2023-36632","versionConstraint":"<= 3.11.4 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]}}],"artifact":{"id":"b83d4cc9d7047529","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","accessPath":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"GHSA-43fp-rhv2-5gv8","dataSource":"https://github.com/advisories/GHSA-43fp-rhv2-5gv8","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Certifi removing TrustCor root certificate","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:C/C:N/I:H/A:N","metrics":{"baseScore":6.8,"exploitabilityScore":2.3,"impactScore":4},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-23491","epss":0.00038,"percentile":0.10381,"date":"2025-06-03"}],"fix":{"versions":["2022.12.07"],"state":"fixed"},"advisories":[],"risk":0.02242},"relatedVulnerabilities":[{"id":"CVE-2022-23491","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2022-23491","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/certifi/python-certifi/security/advisories/GHSA-43fp-rhv2-5gv8","https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/oxX69KFvsm4/m/yLohoVqtCgAJ","https://github.com/certifi/python-certifi/security/advisories/GHSA-43fp-rhv2-5gv8","https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/oxX69KFvsm4/m/yLohoVqtCgAJ","https://security.netapp.com/advisory/ntap-20230223-0010/"],"description":"Certifi is a curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts. Certifi 2022.12.07 removes root certificates from \"TrustCor\" from the root store. These are in the process of being removed from Mozilla's trust store. TrustCor's root certificates are being removed pursuant to an investigation prompted by media reporting that TrustCor's ownership also operated a business that produced spyware. Conclusions of Mozilla's investigation can be found in the linked google group discussion.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:C/C:N/I:H/A:N","metrics":{"baseScore":6.8,"exploitabilityScore":2.3,"impactScore":4},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-23491","epss":0.00038,"percentile":0.10381,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"certifi","version":"2020.6.20"}},"found":{"versionConstraint":">=2017.11.05,<2022.12.07 (python)","vulnerabilityID":"GHSA-43fp-rhv2-5gv8"},"fix":{"suggestedVersion":"2022.12.07"}}],"artifact":{"id":"82ed802006d3a567","name":"certifi","version":"2020.6.20","type":"python","locations":[{"path":"/lib/python3/dist-packages/certifi-2020.6.20.egg-info/PKG-INFO","accessPath":"/lib/python3/dist-packages/certifi-2020.6.20.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/lib/python3/dist-packages/certifi-2020.6.20.egg-info/top_level.txt","accessPath":"/lib/python3/dist-packages/certifi-2020.6.20.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MPL-2.0"],"cpes":["cpe:2.3:a:certifi:certifi:2020.6.20:*:*:*:*:python:*:*"],"purl":"pkg:pypi/certifi@2020.6.20","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-50602","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-50602","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/libexpat/libexpat/pull/915","https://lists.debian.org/debian-lts-announce/2025/04/msg00040.html","https://security.netapp.com/advisory/ntap-20250404-0008/"],"description":"An issue was discovered in libexpat before 2.6.4. There is a crash within the XML_ResumeParser function because XML_StopParser can stop/suspend an unstarted parser.","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-50602","epss":0.00037,"percentile":0.10022,"date":"2025-06-03"}],"fix":{"versions":["3.9.21","3.10.16","3.11.11","3.12.8","3.13.1"],"state":"fixed"},"advisories":[],"risk":0.020165000000000002},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2024-50602","versionConstraint":"< 3.9.21,>= 3.10, < 3.10.16,>= 3.11, < 3.11.11,>= 3.12, < 3.12.8,>= 3.13, < 3.13.1 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.10.16"}}],"artifact":{"id":"b83d4cc9d7047529","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","accessPath":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"GHSA-f9vj-2wh5-fj8j","dataSource":"https://github.com/advisories/GHSA-f9vj-2wh5-fj8j","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Werkzeug safe_join not safe on Windows","cvss":[],"epss":[{"cve":"CVE-2024-49766","epss":0.00036,"percentile":0.09079,"date":"2025-06-03"}],"fix":{"versions":["3.0.6"],"state":"fixed"},"advisories":[],"risk":0.018000000000000002},"relatedVulnerabilities":[{"id":"CVE-2024-49766","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-49766","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pallets/werkzeug/commit/2767bcb10a7dd1c297d812cc5e6d11a474c1f092","https://github.com/pallets/werkzeug/releases/tag/3.0.6","https://github.com/pallets/werkzeug/security/advisories/GHSA-f9vj-2wh5-fj8j","https://security.netapp.com/advisory/ntap-20250131-0005/"],"description":"Werkzeug is a Web Server Gateway Interface web application library. On Python < 3.11 on Windows, os.path.isabs() does not catch UNC paths like //server/share. Werkzeug's safe_join() relies on this check, and so can produce a path that is not safe, potentially allowing unintended access to data. Applications using Python >= 3.11, or not using Windows, are not vulnerable. Werkzeug version 3.0.6 contains a patch.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:H/AT:N/PR:N/UI:N/VC:L/VI:N/VA:N/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":6.3},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-49766","epss":0.00036,"percentile":0.09079,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"werkzeug","version":"2.2.2"}},"found":{"versionConstraint":"<=3.0.5 (python)","vulnerabilityID":"GHSA-f9vj-2wh5-fj8j"},"fix":{"suggestedVersion":"3.0.6"}}],"artifact":{"id":"a523e09d35353d5e","name":"werkzeug","version":"2.2.2","type":"python","locations":[{"path":"/lib/python3/dist-packages/Werkzeug-2.2.2.egg-info/PKG-INFO","accessPath":"/lib/python3/dist-packages/Werkzeug-2.2.2.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/lib/python3/dist-packages/Werkzeug-2.2.2.egg-info/top_level.txt","accessPath":"/lib/python3/dist-packages/Werkzeug-2.2.2.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:armin_ronacher_project:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher_project:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher_project:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python-werkzeug:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python-werkzeug:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacherproject:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python-werkzeug:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python_werkzeug:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin-ronacher:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:armin_ronacher:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python-werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python:python_werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:werkzeug:werkzeug:2.2.2:*:*:*:*:*:*:*","cpe:2.3:a:python:werkzeug:2.2.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/werkzeug@2.2.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-34jh-p97f-mpxf","dataSource":"https://github.com/advisories/GHSA-34jh-p97f-mpxf","namespace":"github:language:python","severity":"Medium","urls":[],"description":"urllib3's Proxy-Authorization request header isn't stripped during cross-origin redirects","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.4,"exploitabilityScore":0.8,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-37891","epss":0.00033,"percentile":0.08049,"date":"2025-06-03"}],"fix":{"versions":["1.26.19"],"state":"fixed"},"advisories":[],"risk":0.01551},"relatedVulnerabilities":[{"id":"CVE-2024-37891","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-37891","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/urllib3/urllib3/commit/accff72ecc2f6cf5a76d9570198a93ac7c90270e","https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf","https://github.com/urllib3/urllib3/commit/accff72ecc2f6cf5a76d9570198a93ac7c90270e","https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf","https://security.netapp.com/advisory/ntap-20240822-0003/","https://www.vicarius.io/vsociety/posts/proxy-authorization-header-handling-vulnerability-in-urllib3-cve-2024-37891"],"description":"urllib3 is a user-friendly HTTP client library for Python. When using urllib3's proxy support with `ProxyManager`, the `Proxy-Authorization` header is only sent to the configured proxy, as expected. However, when sending HTTP requests *without* using urllib3's proxy support, it's possible to accidentally configure the `Proxy-Authorization` header even though it won't have any effect as the request is not using a forwarding proxy or a tunneling proxy. In those cases, urllib3 doesn't treat the `Proxy-Authorization` HTTP header as one carrying authentication material and thus doesn't strip the header on cross-origin redirects. Because this is a highly unlikely scenario, we believe the severity of this vulnerability is low for almost all users. Out of an abundance of caution urllib3 will automatically strip the `Proxy-Authorization` header during cross-origin redirects to avoid the small chance that users are doing this on accident. Users should use urllib3's proxy support or disable automatic redirects to achieve safe processing of the `Proxy-Authorization` header, but we still decided to strip the header by default in order to further protect users who aren't using the correct approach. We believe the number of usages affected by this advisory is low. It requires all of the following to be true to be exploited: 1. Setting the `Proxy-Authorization` header without using urllib3's built-in proxy support. 2. Not disabling HTTP redirects. 3. Either not using an HTTPS origin server or for the proxy or target origin to redirect to a malicious origin. Users are advised to update to either version 1.26.19 or version 2.2.2. Users unable to upgrade may use the `Proxy-Authorization` header with urllib3's `ProxyManager`, disable HTTP redirects using `redirects=False` when sending requests, or not user the `Proxy-Authorization` header as mitigations.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.4,"exploitabilityScore":0.8,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-37891","epss":0.00033,"percentile":0.08049,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"urllib3","version":"1.26.5"}},"found":{"versionConstraint":"<1.26.19 (python)","vulnerabilityID":"GHSA-34jh-p97f-mpxf"},"fix":{"suggestedVersion":"1.26.19"}}],"artifact":{"id":"ec3d240d7279ae9b","name":"urllib3","version":"1.26.5","type":"python","locations":[{"path":"/lib/python3/dist-packages/urllib3-1.26.5.egg-info/PKG-INFO","accessPath":"/lib/python3/dist-packages/urllib3-1.26.5.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/lib/python3/dist-packages/urllib3-1.26.5.egg-info/top_level.txt","accessPath":"/lib/python3/dist-packages/urllib3-1.26.5.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:urllib3:1.26.5:*:*:*:*:*:*:*"],"purl":"pkg:pypi/urllib3@1.26.5","upstreams":[]}},{"vulnerability":{"id":"CVE-2024-4030","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-4030","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/python/cpython/commit/35c799d79177b962ddace2fa068101465570a29a","https://github.com/python/cpython/commit/5130731c9e779b97d00a24f54cdce73ce9975dfd","https://github.com/python/cpython/commit/66f8bb76a15e64a1bb7688b177ed29e26230fdee","https://github.com/python/cpython/commit/6d0850c4c8188035643586ab4d8ec2468abd699e","https://github.com/python/cpython/commit/81939dad77001556c527485d31a2d0f4a759033e","https://github.com/python/cpython/commit/8ed546679524140d8282175411fd141fe7df070d","https://github.com/python/cpython/commit/91e3669e01245185569d09e9e6e11641282971ee","https://github.com/python/cpython/commit/94591dca510c796c7d40e9b4167ea56f2fdf28ca","https://github.com/python/cpython/commit/c8f868dc52f98011d0f9b459b6487920bfb0ac4d","https://github.com/python/cpython/commit/d86b49411753bf2c83291e3a14ae43fefded2f84","https://github.com/python/cpython/commit/e1dfa978b1ad210d551385ad8073ec6154f53763","https://github.com/python/cpython/commit/eb29e2f5905da93333d1ce78bc98b151e763ff46","https://github.com/python/cpython/issues/118486","https://mail.python.org/archives/list/security-announce@python.org/thread/PRGS5OR3N3PNPT4BMV2VAGN5GMUI5636/","https://security.netapp.com/advisory/ntap-20240705-0005/","https://github.com/python/cpython/commit/35c799d79177b962ddace2fa068101465570a29a","https://github.com/python/cpython/commit/5130731c9e779b97d00a24f54cdce73ce9975dfd","https://github.com/python/cpython/commit/66f8bb76a15e64a1bb7688b177ed29e26230fdee","https://github.com/python/cpython/commit/6d0850c4c8188035643586ab4d8ec2468abd699e","https://github.com/python/cpython/commit/81939dad77001556c527485d31a2d0f4a759033e","https://github.com/python/cpython/commit/8ed546679524140d8282175411fd141fe7df070d","https://github.com/python/cpython/commit/91e3669e01245185569d09e9e6e11641282971ee","https://github.com/python/cpython/commit/94591dca510c796c7d40e9b4167ea56f2fdf28ca","https://github.com/python/cpython/commit/c8f868dc52f98011d0f9b459b6487920bfb0ac4d","https://github.com/python/cpython/commit/d86b49411753bf2c83291e3a14ae43fefded2f84","https://github.com/python/cpython/commit/e1dfa978b1ad210d551385ad8073ec6154f53763","https://github.com/python/cpython/commit/eb29e2f5905da93333d1ce78bc98b151e763ff46","https://github.com/python/cpython/issues/118486","https://mail.python.org/archives/list/security-announce@python.org/thread/PRGS5OR3N3PNPT4BMV2VAGN5GMUI5636/","https://security.netapp.com/advisory/ntap-20240705-0005/"],"description":"On Windows a directory returned by tempfile.mkdtemp() would not always have permissions set to restrict reading and writing to the temporary directory by other users, instead usually inheriting the correct permissions from the default location. Alternate configurations or users without a profile directory may not have the intended permissions.\n\nIf you’re not using Windows or haven’t changed the temporary directory location then you aren’t affected by this vulnerability. On other platforms the returned directory is consistently readable and writable only by the current user.\n\nThis issue was caused by Python not supporting Unix permissions on Windows. The fix adds support for Unix “700” for the mkdir function on Windows which is used by mkdtemp() to ensure the newly created directory has the proper permissions.","cvss":[{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N","metrics":{"baseScore":7.1,"exploitabilityScore":1.9,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-4030","epss":0.00014,"percentile":0.01528,"date":"2025-06-03"}],"fix":{"versions":["3.8.20","3.9.20","3.10.15","3.11.10","3.12.4","3.13.0b1"],"state":"fixed"},"advisories":[],"risk":0.01022},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2024-4030","versionConstraint":"< 3.8.20,>= 3.10.0, < 3.10.15,>= 3.11.0, < 3.11.10,>= 3.12.0, < 3.12.4,>= 3.13.0a1, < 3.13.0b1,>= 3.9.0, < 3.9.20 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.10.15"}}],"artifact":{"id":"b83d4cc9d7047529","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","accessPath":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"CVE-2025-4516","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-4516","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/python/cpython/commit/4398b788ffc1f954a2c552da285477d42a571292","https://github.com/python/cpython/commit/6279eb8c076d89d3739a6edb393e43c7929b429d","https://github.com/python/cpython/commit/69b4387f78f413e8c47572a85b3478c47eba8142","https://github.com/python/cpython/commit/73b3040f592436385007918887b7e2132aa8431f","https://github.com/python/cpython/commit/8d35fd1b34935221aff23a1ab69a429dd156be77","https://github.com/python/cpython/commit/9f69a58623bd01349a18ba0c7a9cb1dad6a51e8e","https://github.com/python/cpython/commit/ab9893c40609935e0d40a6d2a7307ea51aec598b","https://github.com/python/cpython/issues/133767","https://github.com/python/cpython/pull/129648","https://mail.python.org/archives/list/security-announce@python.org/thread/L75IPBBTSCYEF56I2M4KIW353BB3AY74/","http://www.openwall.com/lists/oss-security/2025/05/16/4","http://www.openwall.com/lists/oss-security/2025/05/19/1"],"description":"There is an issue in CPython when using `bytes.decode(\"unicode_escape\", error=\"ignore|replace\")`. If you are not using the \"unicode_escape\" encoding or an error handler your usage is not affected. To work-around this issue you may stop using the error= handler and instead wrap the bytes.decode() call in a try-except catching the DecodeError.","cvss":[{"source":"cna@python.org","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:L/AC:H/AT:P/PR:N/UI:N/VC:N/VI:N/VA:H/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-4516","epss":0.00018,"percentile":0.0322,"date":"2025-06-03"}],"fix":{"versions":["3.14.0b1"],"state":"fixed"},"advisories":[],"risk":0.009810000000000001},"relatedVulnerabilities":[],"matchDetails":[{"type":"cpe-match","matcher":"stock-matcher","searchedBy":{"namespace":"nvd:cpe","cpes":["cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"package":{"name":"python","version":"3.10.12"}},"found":{"vulnerabilityID":"CVE-2025-4516","versionConstraint":"< 3.14.0b1 (unknown)","cpes":["cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"]},"fix":{"suggestedVersion":"3.14.0b1"}}],"artifact":{"id":"b83d4cc9d7047529","name":"python","version":"3.10.12","type":"binary","locations":[{"path":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","accessPath":"/lib/x86_64-linux-gnu/libpython3.10.so.1.0","annotations":{"evidence":"primary"}}],"language":"","licenses":[],"cpes":["cpe:2.3:a:python_software_foundation:python:3.10.12:*:*:*:*:*:*:*","cpe:2.3:a:python:python:3.10.12:*:*:*:*:*:*:*"],"purl":"pkg:generic/python@3.10.12","upstreams":[]}},{"vulnerability":{"id":"GHSA-9wx4-h78v-vm56","dataSource":"https://github.com/advisories/GHSA-9wx4-h78v-vm56","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Requests `Session` object does not verify requests after making first request with verify=False","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N","metrics":{"baseScore":5.6,"exploitabilityScore":0.4,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-35195","epss":0.00009,"percentile":0.00549,"date":"2025-06-03"}],"fix":{"versions":["2.32.0"],"state":"fixed"},"advisories":[],"risk":0.004770000000000001},"relatedVulnerabilities":[{"id":"CVE-2024-35195","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-35195","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac","https://github.com/psf/requests/pull/6655","https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ/","https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac","https://github.com/psf/requests/pull/6655","https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ/"],"description":"Requests is a HTTP library. Prior to 2.32.0, when making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same host will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool. This vulnerability is fixed in 2.32.0.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N","metrics":{"baseScore":5.6,"exploitabilityScore":0.4,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-35195","epss":0.00009,"percentile":0.00549,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"requests","version":"2.25.1"}},"found":{"versionConstraint":"<2.32.0 (python)","vulnerabilityID":"GHSA-9wx4-h78v-vm56"},"fix":{"suggestedVersion":"2.32.0"}}],"artifact":{"id":"d14a5be27a949d95","name":"requests","version":"2.25.1","type":"python","locations":[{"path":"/lib/python3/dist-packages/requests-2.25.1.egg-info/PKG-INFO","accessPath":"/lib/python3/dist-packages/requests-2.25.1.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/lib/python3/dist-packages/requests-2.25.1.egg-info/top_level.txt","accessPath":"/lib/python3/dist-packages/requests-2.25.1.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache 2.0"],"cpes":["cpe:2.3:a:python:requests:2.25.1:*:*:*:*:*:*:*"],"purl":"pkg:pypi/requests@2.25.1","upstreams":[]}},{"vulnerability":{"id":"GHSA-5cpq-8wj7-hf2v","dataSource":"https://github.com/advisories/GHSA-5cpq-8wj7-hf2v","namespace":"github:language:python","severity":"Low","urls":[],"description":"Vulnerable OpenSSL included in cryptography wheels","cvss":[],"fix":{"versions":["41.0.0"],"state":"fixed"},"advisories":[],"risk":0},"relatedVulnerabilities":[],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"3.4.8"}},"found":{"versionConstraint":">=0.5,<=40.0.2 (python)","vulnerabilityID":"GHSA-5cpq-8wj7-hf2v"},"fix":{"suggestedVersion":"41.0.0"}}],"artifact":{"id":"8ab3d91ea77f3b32","name":"cryptography","version":"3.4.8","type":"python","locations":[{"path":"/lib/python3/dist-packages/cryptography-3.4.8.egg-info/PKG-INFO","accessPath":"/lib/python3/dist-packages/cryptography-3.4.8.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/lib/python3/dist-packages/cryptography-3.4.8.egg-info/top_level.txt","accessPath":"/lib/python3/dist-packages/cryptography-3.4.8.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD or Apache License, Version 2.0"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:3.4.8:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:3.4.8:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@3.4.8","upstreams":[]}},{"vulnerability":{"id":"GHSA-jm77-qphf-c4w8","dataSource":"https://github.com/advisories/GHSA-jm77-qphf-c4w8","namespace":"github:language:python","severity":"Low","urls":[],"description":"pyca/cryptography's wheels include vulnerable OpenSSL","cvss":[],"fix":{"versions":["41.0.3"],"state":"fixed"},"advisories":[],"risk":0},"relatedVulnerabilities":[],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"3.4.8"}},"found":{"versionConstraint":">=0.8,<41.0.3 (python)","vulnerabilityID":"GHSA-jm77-qphf-c4w8"},"fix":{"suggestedVersion":"41.0.3"}}],"artifact":{"id":"8ab3d91ea77f3b32","name":"cryptography","version":"3.4.8","type":"python","locations":[{"path":"/lib/python3/dist-packages/cryptography-3.4.8.egg-info/PKG-INFO","accessPath":"/lib/python3/dist-packages/cryptography-3.4.8.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/lib/python3/dist-packages/cryptography-3.4.8.egg-info/top_level.txt","accessPath":"/lib/python3/dist-packages/cryptography-3.4.8.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD or Apache License, Version 2.0"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:3.4.8:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:3.4.8:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@3.4.8","upstreams":[]}},{"vulnerability":{"id":"GHSA-v8gr-m533-ghj9","dataSource":"https://github.com/advisories/GHSA-v8gr-m533-ghj9","namespace":"github:language:python","severity":"Low","urls":[],"description":"Vulnerable OpenSSL included in cryptography wheels","cvss":[],"fix":{"versions":["41.0.4"],"state":"fixed"},"advisories":[],"risk":0},"relatedVulnerabilities":[],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"3.4.8"}},"found":{"versionConstraint":">=2.5,<41.0.4 (python)","vulnerabilityID":"GHSA-v8gr-m533-ghj9"},"fix":{"suggestedVersion":"41.0.4"}}],"artifact":{"id":"8ab3d91ea77f3b32","name":"cryptography","version":"3.4.8","type":"python","locations":[{"path":"/lib/python3/dist-packages/cryptography-3.4.8.egg-info/PKG-INFO","accessPath":"/lib/python3/dist-packages/cryptography-3.4.8.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/lib/python3/dist-packages/cryptography-3.4.8.egg-info/top_level.txt","accessPath":"/lib/python3/dist-packages/cryptography-3.4.8.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD or Apache License, Version 2.0"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:3.4.8:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:3.4.8:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@3.4.8","upstreams":[]}}],"source":{"type":"sbom-file","target":"microceph-syft.json"},"distro":{"name":"","version":"","idLike":null},"descriptor":{"name":"grype","version":"0.92.2","configuration":{"output":["json=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-06-04/microceph-grype.json","template=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-06-04/microceph-grype.html"],"file":"","pretty":false,"distro":"","add-cpes-if-none":false,"output-template-file":"../html.tmpl","check-for-app-update":true,"only-fixed":false,"only-notfixed":false,"ignore-wontfix":"","platform":"","search":{"scope":"squashed","unindexed-archives":false,"indexed-archives":true},"ignore":[{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"kernel-headers","version":"","language":"","type":"rpm","location":"","upstream-name":"kernel"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux(-.*)?-headers-.*","version":"","language":"","type":"deb","location":"","upstream-name":"linux.*"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux-libc-dev","version":"","language":"","type":"deb","location":"","upstream-name":"linux"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"}],"exclude":[],"externalSources":{"enable":false,"maven":{"searchUpstreamBySha1":true,"baseUrl":"https://search.maven.org/solrsearch/select","rateLimit":300000000}},"match":{"java":{"using-cpes":false},"jvm":{"using-cpes":true},"dotnet":{"using-cpes":false},"golang":{"using-cpes":false,"always-use-cpe-for-stdlib":true,"allow-main-module-pseudo-version-comparison":false},"javascript":{"using-cpes":false},"python":{"using-cpes":false},"ruby":{"using-cpes":false},"rust":{"using-cpes":false},"stock":{"using-cpes":true}},"fail-on-severity":"","registry":{"insecure-skip-tls-verify":false,"insecure-use-http":false,"auth":null,"ca-cert":""},"show-suppressed":false,"by-cve":false,"SortBy":{"sort-by":"risk"},"name":"","default-image-pull-source":"","vex-documents":[],"vex-add":[],"match-upstream-kernel-headers":false,"db":{"cache-dir":"/Users/alan/Library/Caches/grype/db","update-url":"https://grype.anchore.io/databases","ca-cert":"","auto-update":true,"validate-by-hash-on-start":true,"validate-age":true,"max-allowed-built-age":432000000000000,"require-update-check":false,"update-available-timeout":30000000000,"update-download-timeout":300000000000,"max-update-check-frequency":7200000000000},"exp":{},"dev":{"db":{"debug":false}}},"db":{"status":{"schemaVersion":"v6.0.2","from":"https://grype.anchore.io/databases/v6/vulnerability-db_v6.0.2_2025-06-04T01:32:23Z_1749035557.tar.zst?checksum=sha256%3A77238f4ffbc7cf72bf4dedabbb21a3d0dd3ade90fb5d9df7c4da2870f8d1a9b7","built":"2025-06-04T11:12:37Z","path":"/Users/alan/Library/Caches/grype/db/6/vulnerability.db","valid":true},"providers":{"alpine":{"captured":"2025-06-04T01:32:23Z","input":"xxh64:a6a065ece392f6d1"},"amazon":{"captured":"2025-06-04T01:32:32Z","input":"xxh64:b65d458d6858d72a"},"chainguard":{"captured":"2025-06-04T01:32:33Z","input":"xxh64:03c9c4d182d77791"},"debian":{"captured":"2025-06-04T01:32:49Z","input":"xxh64:169ceb8fbcb8d6f1"},"epss":{"captured":"2025-06-04T01:32:42Z","input":"xxh64:bf87c4c234d02346"},"github":{"captured":"2025-06-04T01:32:30Z","input":"xxh64:3dab0be50635e057"},"kev":{"captured":"2025-06-04T01:32:45Z","input":"xxh64:a934e75f468f4e09"},"mariner":{"captured":"2025-06-04T01:32:43Z","input":"xxh64:ac698752085c186f"},"nvd":{"captured":"2025-06-04T01:33:28Z","input":"xxh64:389887843a59d29c"},"oracle":{"captured":"2025-06-04T01:32:35Z","input":"xxh64:0b8aabcfb6505b62"},"rhel":{"captured":"2025-06-04T04:49:10Z","input":"xxh64:947d0caeb19e9ccc"},"sles":{"captured":"2025-06-04T01:32:34Z","input":"xxh64:1c50b1219296628a"},"ubuntu":{"captured":"2025-06-04T01:33:14Z","input":"xxh64:71e22d5c5bbe7d14"},"wolfi":{"captured":"2025-06-04T01:32:42Z","input":"xxh64:e68fca5a870c6769"}}},"timestamp":"2025-06-04T19:31:47.663641+01:00"}}
