{"matches":[{"vulnerability":{"id":"GHSA-x4qr-2fvf-3mr5","dataSource":"https://github.com/advisories/GHSA-x4qr-2fvf-3mr5","namespace":"github:language:python","severity":"High","urls":[],"description":"Vulnerable OpenSSL included in cryptography wheels","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:H","metrics":{"baseScore":7.4,"exploitabilityScore":2.3,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-0286","epss":0.8576,"percentile":0.99335,"date":"2025-06-03"}],"fix":{"versions":["39.0.1"],"state":"fixed"},"advisories":[],"risk":63.891200000000005},"relatedVulnerabilities":[{"id":"CVE-2023-0286","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-0286","namespace":"nvd:cpe","severity":"High","urls":["https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.6.2-relnotes.txt","https://ftp.openbsd.org/pub/OpenBSD/patches/7.2/common/018_x509.patch.sig","https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=2c6c9d439b484e1ba9830d8454a34fa4f80fdfe9","https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=2f7530077e0ef79d98718138716bc51ca0cad658","https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=fd2af07dc083a350c959147097003a14a5e8ac4d","https://security.gentoo.org/glsa/202402-08","https://www.openssl.org/news/secadv/20230207.txt","https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.6.2-relnotes.txt","https://ftp.openbsd.org/pub/OpenBSD/patches/7.2/common/018_x509.patch.sig","https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=2c6c9d439b484e1ba9830d8454a34fa4f80fdfe9","https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=2f7530077e0ef79d98718138716bc51ca0cad658","https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=fd2af07dc083a350c959147097003a14a5e8ac4d","https://security.gentoo.org/glsa/202402-08","https://www.openssl.org/news/secadv/20230207.txt"],"description":"There is a type confusion vulnerability relating to X.400 address processing\ninside an X.509 GeneralName. X.400 addresses were parsed as an ASN1_STRING but\nthe public structure definition for GENERAL_NAME incorrectly specified the type\nof the x400Address field as ASN1_TYPE. This field is subsequently interpreted by\nthe OpenSSL function GENERAL_NAME_cmp as an ASN1_TYPE rather than an\nASN1_STRING.\n\nWhen CRL checking is enabled (i.e. the application sets the\nX509_V_FLAG_CRL_CHECK flag), this vulnerability may allow an attacker to pass\narbitrary pointers to a memcmp call, enabling them to read memory contents or\nenact a denial of service. In most cases, the attack requires the attacker to\nprovide both the certificate chain and CRL, neither of which need to have a\nvalid signature. If the attacker only controls one of these inputs, the other\ninput must already contain an X.400 address as a CRL distribution point, which\nis uncommon. As such, this vulnerability is most likely to only affect\napplications which have implemented their own functionality for retrieving CRLs\nover a network.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:H","metrics":{"baseScore":7.4,"exploitabilityScore":2.3,"impactScore":5.2},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:H","metrics":{"baseScore":7.4,"exploitabilityScore":2.3,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-0286","epss":0.8576,"percentile":0.99335,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"2.8"}},"found":{"versionConstraint":">=0.8.1,<39.0.1 (python)","vulnerabilityID":"GHSA-x4qr-2fvf-3mr5"},"fix":{"suggestedVersion":"39.0.1"}}],"artifact":{"id":"5db92af054d69cbe","name":"cryptography","version":"2.8","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/cryptography-2.8.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/cryptography-2.8.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/cryptography-2.8.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/cryptography-2.8.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD or Apache License, Version 2.0"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:2.8:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:2.8:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@2.8","upstreams":[]}},{"vulnerability":{"id":"GHSA-q2q7-5pp4-w6pg","dataSource":"https://github.com/advisories/GHSA-q2q7-5pp4-w6pg","namespace":"github:language:python","severity":"High","urls":[],"description":"Catastrophic backtracking in URL authority parser when passed URL containing many @ characters","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-33503","epss":0.00863,"percentile":0.74071,"date":"2025-06-03"}],"fix":{"versions":["1.26.5"],"state":"fixed"},"advisories":[],"risk":0.6472500000000001},"relatedVulnerabilities":[{"id":"CVE-2021-33503","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2021-33503","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/advisories/GHSA-q2q7-5pp4-w6pg","https://github.com/urllib3/urllib3/commit/2d4a3fee6de2fa45eb82169361918f759269b4ec","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/6SCV7ZNAHS3E6PBFLJGENCDRDRWRZZ6W/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/FMUGWEAUYGGHTPPXT6YBD53WYXQGVV73/","https://security.gentoo.org/glsa/202107-36","https://www.oracle.com/security-alerts/cpuoct2021.html","https://github.com/advisories/GHSA-q2q7-5pp4-w6pg","https://github.com/urllib3/urllib3/commit/2d4a3fee6de2fa45eb82169361918f759269b4ec","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/6SCV7ZNAHS3E6PBFLJGENCDRDRWRZZ6W/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/FMUGWEAUYGGHTPPXT6YBD53WYXQGVV73/","https://security.gentoo.org/glsa/202107-36","https://www.oracle.com/security-alerts/cpuoct2021.html"],"description":"An issue was discovered in urllib3 before 1.26.5. When provided with a URL containing many @ characters in the authority component, the authority regular expression exhibits catastrophic backtracking, causing a denial of service if a URL were passed as a parameter or redirected to via an HTTP redirect.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:L/Au:N/C:N/I:N/A:P","metrics":{"baseScore":5,"exploitabilityScore":10,"impactScore":2.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-33503","epss":0.00863,"percentile":0.74071,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"urllib3","version":"1.25.8"}},"found":{"versionConstraint":">=1.25.4,<1.26.5 (python)","vulnerabilityID":"GHSA-q2q7-5pp4-w6pg"},"fix":{"suggestedVersion":"1.26.5"}}],"artifact":{"id":"26bbe87e6e558d9d","name":"urllib3","version":"1.25.8","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/urllib3-1.25.8.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/urllib3-1.25.8.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/urllib3-1.25.8.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/urllib3-1.25.8.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:urllib3:1.25.8:*:*:*:*:*:*:*"],"purl":"pkg:pypi/urllib3@1.25.8","upstreams":[]}},{"vulnerability":{"id":"GHSA-3ww4-gg4f-jr7f","dataSource":"https://github.com/advisories/GHSA-3ww4-gg4f-jr7f","namespace":"github:language:python","severity":"High","urls":[],"description":"Python Cryptography package vulnerable to Bleichenbacher timing oracle attack","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-50782","epss":0.00521,"percentile":0.6593,"date":"2025-06-03"}],"fix":{"versions":["42.0.0"],"state":"fixed"},"advisories":[],"risk":0.39075000000000004},"relatedVulnerabilities":[{"id":"CVE-2023-50782","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-50782","namespace":"nvd:cpe","severity":"High","urls":["https://access.redhat.com/security/cve/CVE-2023-50782","https://bugzilla.redhat.com/show_bug.cgi?id=2254432","https://access.redhat.com/security/cve/CVE-2023-50782","https://bugzilla.redhat.com/show_bug.cgi?id=2254432","https://www.couchbase.com/alerts/"],"description":"A flaw was found in the python-cryptography package. This issue may allow a remote attacker to decrypt captured messages in TLS servers that use RSA key exchanges, which may lead to exposure of confidential or sensitive data.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"secalert@redhat.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-50782","epss":0.00521,"percentile":0.6593,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"2.8"}},"found":{"versionConstraint":"<42.0.0 (python)","vulnerabilityID":"GHSA-3ww4-gg4f-jr7f"},"fix":{"suggestedVersion":"42.0.0"}}],"artifact":{"id":"5db92af054d69cbe","name":"cryptography","version":"2.8","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/cryptography-2.8.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/cryptography-2.8.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/cryptography-2.8.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/cryptography-2.8.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD or Apache License, Version 2.0"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:2.8:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:2.8:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@2.8","upstreams":[]}},{"vulnerability":{"id":"GHSA-v845-jxx5-vc9f","dataSource":"https://github.com/advisories/GHSA-v845-jxx5-vc9f","namespace":"github:language:python","severity":"High","urls":[],"description":"`Cookie` HTTP header isn't stripped on cross-origin redirects","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:H/A:N","metrics":{"baseScore":5.9,"exploitabilityScore":0.8,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-43804","epss":0.00554,"percentile":0.67072,"date":"2025-06-03"}],"fix":{"versions":["1.26.17"],"state":"fixed"},"advisories":[],"risk":0.37118},"relatedVulnerabilities":[{"id":"CVE-2023-43804","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-43804","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/urllib3/urllib3/commit/01220354d389cd05474713f8c982d05c9b17aafb","https://github.com/urllib3/urllib3/commit/644124ecd0b6e417c527191f866daa05a5a2056d","https://github.com/urllib3/urllib3/security/advisories/GHSA-v845-jxx5-vc9f","https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/I3PR7C6RJ6JUBQKIJ644DMIJSUP36VDY/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NDAGZXYJ7H2G3SB47M453VQVNAWKAEJJ/","https://github.com/urllib3/urllib3/commit/01220354d389cd05474713f8c982d05c9b17aafb","https://github.com/urllib3/urllib3/commit/644124ecd0b6e417c527191f866daa05a5a2056d","https://github.com/urllib3/urllib3/security/advisories/GHSA-v845-jxx5-vc9f","https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/I3PR7C6RJ6JUBQKIJ644DMIJSUP36VDY/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NDAGZXYJ7H2G3SB47M453VQVNAWKAEJJ/","https://security.netapp.com/advisory/ntap-20241213-0007/","https://www.vicarius.io/vsociety/posts/cve-2023-43804-urllib3-vulnerability-3"],"description":"urllib3 is a user-friendly HTTP client library for Python. urllib3 doesn't treat the `Cookie` HTTP header special or provide any helpers for managing cookies over HTTP, that is the responsibility of the user. However, it is possible for a user to specify a `Cookie` header and unknowingly leak information via HTTP redirects to a different origin if that user doesn't disable redirects explicitly. This issue has been patched in urllib3 version 1.26.17 or 2.0.5.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N","metrics":{"baseScore":8.1,"exploitabilityScore":2.9,"impactScore":5.2},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:H/A:N","metrics":{"baseScore":5.9,"exploitabilityScore":0.8,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-43804","epss":0.00554,"percentile":0.67072,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"urllib3","version":"1.25.8"}},"found":{"versionConstraint":"<1.26.17 (python)","vulnerabilityID":"GHSA-v845-jxx5-vc9f"},"fix":{"suggestedVersion":"1.26.17"}}],"artifact":{"id":"26bbe87e6e558d9d","name":"urllib3","version":"1.25.8","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/urllib3-1.25.8.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/urllib3-1.25.8.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/urllib3-1.25.8.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/urllib3-1.25.8.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:urllib3:1.25.8:*:*:*:*:*:*:*"],"purl":"pkg:pypi/urllib3@1.25.8","upstreams":[]}},{"vulnerability":{"id":"GHSA-hggm-jpg3-v476","dataSource":"https://github.com/advisories/GHSA-hggm-jpg3-v476","namespace":"github:language:python","severity":"High","urls":[],"description":"RSA decryption vulnerable to Bleichenbacher timing vulnerability","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2020-25659","epss":0.00343,"percentile":0.56361,"date":"2025-06-03"}],"fix":{"versions":["3.2"],"state":"fixed"},"advisories":[],"risk":0.22981},"relatedVulnerabilities":[{"id":"CVE-2020-25659","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2020-25659","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pyca/cryptography/pull/5507/commits/ce1bef6f1ee06ac497ca0c837fbd1c7ef6c2472b","https://www.oracle.com/security-alerts/cpuapr2022.html","https://www.oracle.com/security-alerts/cpujul2022.html","https://github.com/pyca/cryptography/pull/5507/commits/ce1bef6f1ee06ac497ca0c837fbd1c7ef6c2472b","https://www.oracle.com/security-alerts/cpuapr2022.html","https://www.oracle.com/security-alerts/cpujul2022.html"],"description":"python-cryptography 3.2 is vulnerable to Bleichenbacher timing attacks in the RSA decryption API, via timed processing of valid PKCS#1 v1.5 ciphertext.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:M/Au:N/C:P/I:N/A:N","metrics":{"baseScore":4.3,"exploitabilityScore":8.6,"impactScore":2.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2020-25659","epss":0.00343,"percentile":0.56361,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"2.8"}},"found":{"versionConstraint":"<3.2 (python)","vulnerabilityID":"GHSA-hggm-jpg3-v476"},"fix":{"suggestedVersion":"3.2"}}],"artifact":{"id":"5db92af054d69cbe","name":"cryptography","version":"2.8","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/cryptography-2.8.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/cryptography-2.8.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/cryptography-2.8.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/cryptography-2.8.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD or Apache License, Version 2.0"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:2.8:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:2.8:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@2.8","upstreams":[]}},{"vulnerability":{"id":"GHSA-w7pp-m8wf-vj6r","dataSource":"https://github.com/advisories/GHSA-w7pp-m8wf-vj6r","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Cipher.update_into can corrupt memory if passed an immutable python object as the outbuf","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:L","metrics":{"baseScore":6.5,"exploitabilityScore":3.9,"impactScore":2.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-23931","epss":0.00331,"percentile":0.5554,"date":"2025-06-03"}],"fix":{"versions":["39.0.1"],"state":"fixed"},"advisories":[],"risk":0.19032499999999997},"relatedVulnerabilities":[{"id":"CVE-2023-23931","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-23931","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pyca/cryptography/pull/8230/commits/94a50a9731f35405f0357fa5f3b177d46a726ab3","https://github.com/pyca/cryptography/security/advisories/GHSA-w7pp-m8wf-vj6r","https://github.com/pyca/cryptography/pull/8230/commits/94a50a9731f35405f0357fa5f3b177d46a726ab3","https://github.com/pyca/cryptography/security/advisories/GHSA-w7pp-m8wf-vj6r","https://security.netapp.com/advisory/ntap-20230324-0007/"],"description":"cryptography is a package designed to expose cryptographic primitives and recipes to Python developers. In affected versions `Cipher.update_into` would accept Python objects which implement the buffer protocol, but provide only immutable buffers. This would allow immutable objects (such as `bytes`) to be mutated, thus violating fundamental rules of Python and resulting in corrupted output. This now correctly raises an exception. This issue has been present since `update_into` was originally introduced in cryptography 1.8.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:L","metrics":{"baseScore":6.5,"exploitabilityScore":3.9,"impactScore":2.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:L/A:L","metrics":{"baseScore":4.8,"exploitabilityScore":2.3,"impactScore":2.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-23931","epss":0.00331,"percentile":0.5554,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"2.8"}},"found":{"versionConstraint":">=1.8,<39.0.1 (python)","vulnerabilityID":"GHSA-w7pp-m8wf-vj6r"},"fix":{"suggestedVersion":"39.0.1"}}],"artifact":{"id":"5db92af054d69cbe","name":"cryptography","version":"2.8","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/cryptography-2.8.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/cryptography-2.8.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/cryptography-2.8.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/cryptography-2.8.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD or Apache License, Version 2.0"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:2.8:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:2.8:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@2.8","upstreams":[]}},{"vulnerability":{"id":"GHSA-wqvq-5m8c-6g24","dataSource":"https://github.com/advisories/GHSA-wqvq-5m8c-6g24","namespace":"github:language:python","severity":"Medium","urls":[],"description":"CRLF injection in urllib3","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N","metrics":{"baseScore":6.5,"exploitabilityScore":3.9,"impactScore":2.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2020-26137","epss":0.00215,"percentile":0.44389,"date":"2025-06-03"}],"fix":{"versions":["1.25.9"],"state":"fixed"},"advisories":[],"risk":0.123625},"relatedVulnerabilities":[{"id":"CVE-2020-26137","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2020-26137","namespace":"nvd:cpe","severity":"Medium","urls":["https://bugs.python.org/issue39603","https://github.com/urllib3/urllib3/commit/1dd69c5c5982fae7c87a620d487c2ebf7a6b436b","https://github.com/urllib3/urllib3/pull/1800","https://lists.debian.org/debian-lts-announce/2021/06/msg00015.html","https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html","https://usn.ubuntu.com/4570-1/","https://www.oracle.com/security-alerts/cpujul2022.html","https://www.oracle.com/security-alerts/cpuoct2021.html","https://bugs.python.org/issue39603","https://github.com/urllib3/urllib3/commit/1dd69c5c5982fae7c87a620d487c2ebf7a6b436b","https://github.com/urllib3/urllib3/pull/1800","https://lists.debian.org/debian-lts-announce/2021/06/msg00015.html","https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html","https://usn.ubuntu.com/4570-1/","https://www.oracle.com/security-alerts/cpujul2022.html","https://www.oracle.com/security-alerts/cpuoct2021.html"],"description":"urllib3 before 1.25.9 allows CRLF injection if the attacker controls the HTTP request method, as demonstrated by inserting CR and LF control characters in the first argument of putrequest(). NOTE: this is similar to CVE-2020-26116.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N","metrics":{"baseScore":6.5,"exploitabilityScore":3.9,"impactScore":2.6},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:L/Au:N/C:P/I:P/A:N","metrics":{"baseScore":6.4,"exploitabilityScore":10,"impactScore":5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2020-26137","epss":0.00215,"percentile":0.44389,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"urllib3","version":"1.25.8"}},"found":{"versionConstraint":"<1.25.9 (python)","vulnerabilityID":"GHSA-wqvq-5m8c-6g24"},"fix":{"suggestedVersion":"1.25.9"}}],"artifact":{"id":"26bbe87e6e558d9d","name":"urllib3","version":"1.25.8","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/urllib3-1.25.8.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/urllib3-1.25.8.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/urllib3-1.25.8.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/urllib3-1.25.8.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:urllib3:1.25.8:*:*:*:*:*:*:*"],"purl":"pkg:pypi/urllib3@1.25.8","upstreams":[]}},{"vulnerability":{"id":"GHSA-5545-2q6w-2gh6","dataSource":"https://github.com/advisories/GHSA-5545-2q6w-2gh6","namespace":"github:language:python","severity":"High","urls":[],"description":"NumPy NULL Pointer Dereference","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-41495","epss":0.00102,"percentile":0.29251,"date":"2025-06-03"}],"fix":{"versions":["1.19"],"state":"fixed"},"advisories":[],"risk":0.07650000000000001},"relatedVulnerabilities":[{"id":"CVE-2021-41495","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2021-41495","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/numpy/numpy/issues/19038","https://www.oracle.com/security-alerts/cpujul2022.html","https://github.com/numpy/numpy/issues/19038","https://www.oracle.com/security-alerts/cpujul2022.html"],"description":"Null Pointer Dereference vulnerability exists in numpy.sort in NumPy &lt and 1.19 in the PyArray_DescrNew function due to missing return-value validation, which allows attackers to conduct DoS attacks by repetitively creating sort arrays. NOTE: While correct that validation is missing, an error can only occur due to an exhaustion of memory. If the user can exhaust memory, they are already privileged. Further, it should be practically impossible to construct an attack which can target the memory exhaustion to occur at exactly this place","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.3,"exploitabilityScore":1.7,"impactScore":3.6},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:M/Au:S/C:N/I:N/A:P","metrics":{"baseScore":3.5,"exploitabilityScore":6.9,"impactScore":2.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-41495","epss":0.00102,"percentile":0.29251,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"numpy","version":"1.17.4"}},"found":{"versionConstraint":"<=1.18.5 (python)","vulnerabilityID":"GHSA-5545-2q6w-2gh6"},"fix":{"suggestedVersion":"1.19"}}],"artifact":{"id":"bd1fdd8e53a74bf6","name":"numpy","version":"1.17.4","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/numpy-1.17.4.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/numpy-1.17.4.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/numpy-1.17.4.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/numpy-1.17.4.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD"],"cpes":["cpe:2.3:a:travis_e__oliphant_et_al__project:python-numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:travis_e__oliphant_et_al__project:python_numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:travis_e__oliphant_et_al_project:python-numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:travis_e__oliphant_et_al_project:python_numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:travis_e__oliphant_et_al__project:numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:travis_e__oliphant_et_al_:python-numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:travis_e__oliphant_et_al_:python_numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:travis_e__oliphant_et_al_project:numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:travis_e__oliphant_et_al_:numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python-numpy:python-numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python-numpy:python_numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python_numpy:python-numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python_numpy:python_numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python-numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python_numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:numpy:python-numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:numpy:python_numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python-numpy:numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python_numpy:numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python:numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:numpy:numpy:1.17.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/numpy@1.17.4","upstreams":[]}},{"vulnerability":{"id":"GHSA-6p56-wp2h-9hxr","dataSource":"https://github.com/advisories/GHSA-6p56-wp2h-9hxr","namespace":"github:language:python","severity":"Medium","urls":[],"description":"NumPy Buffer Overflow (Disputed)","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.3,"exploitabilityScore":1.7,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-33430","epss":0.00124,"percentile":0.32963,"date":"2025-06-03"}],"fix":{"versions":["1.21"],"state":"fixed"},"advisories":[],"risk":0.06386},"relatedVulnerabilities":[{"id":"CVE-2021-33430","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2021-33430","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/numpy/numpy/issues/18939","https://github.com/numpy/numpy/issues/18939"],"description":"A Buffer Overflow vulnerability exists in NumPy 1.9.x in the PyArray_NewFromDescr_int function of ctors.c when specifying arrays of large dimensions (over 32) from Python code, which could let a malicious user cause a Denial of Service. NOTE: The vendor does not agree this is a vulneraility; In (very limited) circumstances a user may be able provoke the buffer overflow, the user is most likely already privileged to at least provoke denial of service by exhausting memory. Triggering this further requires the use of uncommon API (complicated structured dtypes), which is very unlikely to be available to an unprivileged user","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.3,"exploitabilityScore":1.7,"impactScore":3.6},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:M/Au:S/C:N/I:N/A:P","metrics":{"baseScore":3.5,"exploitabilityScore":6.9,"impactScore":2.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-33430","epss":0.00124,"percentile":0.32963,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"numpy","version":"1.17.4"}},"found":{"versionConstraint":">=1.9.0,<1.21 (python)","vulnerabilityID":"GHSA-6p56-wp2h-9hxr"},"fix":{"suggestedVersion":"1.21"}}],"artifact":{"id":"bd1fdd8e53a74bf6","name":"numpy","version":"1.17.4","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/numpy-1.17.4.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/numpy-1.17.4.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/numpy-1.17.4.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/numpy-1.17.4.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD"],"cpes":["cpe:2.3:a:travis_e__oliphant_et_al__project:python-numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:travis_e__oliphant_et_al__project:python_numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:travis_e__oliphant_et_al_project:python-numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:travis_e__oliphant_et_al_project:python_numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:travis_e__oliphant_et_al__project:numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:travis_e__oliphant_et_al_:python-numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:travis_e__oliphant_et_al_:python_numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:travis_e__oliphant_et_al_project:numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:travis_e__oliphant_et_al_:numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python-numpy:python-numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python-numpy:python_numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python_numpy:python-numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python_numpy:python_numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python-numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python_numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:numpy:python-numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:numpy:python_numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python-numpy:numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python_numpy:numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python:numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:numpy:numpy:1.17.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/numpy@1.17.4","upstreams":[]}},{"vulnerability":{"id":"GHSA-9v9h-cgj8-h64p","dataSource":"https://github.com/advisories/GHSA-9v9h-cgj8-h64p","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Null pointer dereference in PKCS12 parsing","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-0727","epss":0.00103,"percentile":0.29443,"date":"2025-06-03"}],"fix":{"versions":["42.0.2"],"state":"fixed"},"advisories":[],"risk":0.05407500000000001},"relatedVulnerabilities":[{"id":"CVE-2024-0727","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-0727","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/openssl/openssl/commit/09df4395b5071217b76dc7d3d2e630eb8c5a79c2","https://github.com/openssl/openssl/commit/775acfdbd0c6af9ac855f34969cdab0c0c90844a","https://github.com/openssl/openssl/commit/d135eeab8a5dbf72b3da5240bab9ddb7678dbd2c","https://github.openssl.org/openssl/extended-releases/commit/03b3941d60c4bce58fab69a0c22377ab439bc0e8","https://github.openssl.org/openssl/extended-releases/commit/aebaa5883e31122b404e450732dc833dc9dee539","https://www.openssl.org/news/secadv/20240125.txt","http://www.openwall.com/lists/oss-security/2024/03/11/1","https://github.com/openssl/openssl/commit/09df4395b5071217b76dc7d3d2e630eb8c5a79c2","https://github.com/openssl/openssl/commit/775acfdbd0c6af9ac855f34969cdab0c0c90844a","https://github.com/openssl/openssl/commit/d135eeab8a5dbf72b3da5240bab9ddb7678dbd2c","https://github.openssl.org/openssl/extended-releases/commit/03b3941d60c4bce58fab69a0c22377ab439bc0e8","https://github.openssl.org/openssl/extended-releases/commit/aebaa5883e31122b404e450732dc833dc9dee539","https://security.netapp.com/advisory/ntap-20240208-0006/","https://www.openssl.org/news/secadv/20240125.txt"],"description":"Issue summary: Processing a maliciously formatted PKCS12 file may lead OpenSSL\nto crash leading to a potential Denial of Service attack\n\nImpact summary: Applications loading files in the PKCS12 format from untrusted\nsources might terminate abruptly.\n\nA file in PKCS12 format can contain certificates and keys and may come from an\nuntrusted source. The PKCS12 specification allows certain fields to be NULL, but\nOpenSSL does not correctly check for this case. This can lead to a NULL pointer\ndereference that results in OpenSSL crashing. If an application processes PKCS12\nfiles from an untrusted source using the OpenSSL APIs then that application will\nbe vulnerable to this issue.\n\nOpenSSL APIs that are vulnerable to this are: PKCS12_parse(),\nPKCS12_unpack_p7data(), PKCS12_unpack_p7encdata(), PKCS12_unpack_authsafes()\nand PKCS12_newpass().\n\nWe have also fixed a similar issue in SMIME_write_PKCS7(). However since this\nfunction is related to writing data we do not consider it security significant.\n\nThe FIPS modules in 3.2, 3.1 and 3.0 are not affected by this issue.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-0727","epss":0.00103,"percentile":0.29443,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"2.8"}},"found":{"versionConstraint":"<42.0.2 (python)","vulnerabilityID":"GHSA-9v9h-cgj8-h64p"},"fix":{"suggestedVersion":"42.0.2"}}],"artifact":{"id":"5db92af054d69cbe","name":"cryptography","version":"2.8","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/cryptography-2.8.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/cryptography-2.8.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/cryptography-2.8.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/cryptography-2.8.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD or Apache License, Version 2.0"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:2.8:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:2.8:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@2.8","upstreams":[]}},{"vulnerability":{"id":"GHSA-fpfv-jqm9-f5jm","dataSource":"https://github.com/advisories/GHSA-fpfv-jqm9-f5jm","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Incorrect Comparison in NumPy","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L","metrics":{"baseScore":5.3,"exploitabilityScore":3.9,"impactScore":1.5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-34141","epss":0.00061,"percentile":0.19494,"date":"2025-06-03"}],"fix":{"versions":["1.22"],"state":"fixed"},"advisories":[],"risk":0.031415},"relatedVulnerabilities":[{"id":"CVE-2021-34141","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2021-34141","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/numpy/numpy/issues/18993","https://www.oracle.com/security-alerts/cpujul2022.html","https://github.com/numpy/numpy/issues/18993","https://www.oracle.com/security-alerts/cpujul2022.html"],"description":"An incomplete string comparison in the numpy.core component in NumPy before 1.22.0 allows attackers to trigger slightly incorrect copying by constructing specific string objects. NOTE: the vendor states that this reported code behavior is \"completely harmless.\"","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L","metrics":{"baseScore":5.3,"exploitabilityScore":3.9,"impactScore":1.5},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:L/Au:N/C:N/I:N/A:P","metrics":{"baseScore":5,"exploitabilityScore":10,"impactScore":2.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-34141","epss":0.00061,"percentile":0.19494,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"numpy","version":"1.17.4"}},"found":{"versionConstraint":"<1.22 (python)","vulnerabilityID":"GHSA-fpfv-jqm9-f5jm"},"fix":{"suggestedVersion":"1.22"}}],"artifact":{"id":"bd1fdd8e53a74bf6","name":"numpy","version":"1.17.4","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/numpy-1.17.4.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/numpy-1.17.4.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/numpy-1.17.4.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/numpy-1.17.4.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD"],"cpes":["cpe:2.3:a:travis_e__oliphant_et_al__project:python-numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:travis_e__oliphant_et_al__project:python_numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:travis_e__oliphant_et_al_project:python-numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:travis_e__oliphant_et_al_project:python_numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:travis_e__oliphant_et_al__project:numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:travis_e__oliphant_et_al_:python-numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:travis_e__oliphant_et_al_:python_numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:travis_e__oliphant_et_al_project:numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:travis_e__oliphant_et_al_:numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python-numpy:python-numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python-numpy:python_numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python_numpy:python-numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python_numpy:python_numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python-numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python_numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:numpy:python-numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:numpy:python_numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python-numpy:numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python_numpy:numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python:numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:numpy:numpy:1.17.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/numpy@1.17.4","upstreams":[]}},{"vulnerability":{"id":"GHSA-g4mx-q9vg-27p4","dataSource":"https://github.com/advisories/GHSA-g4mx-q9vg-27p4","namespace":"github:language:python","severity":"Medium","urls":[],"description":"urllib3's request body not stripped after redirect from 303 status changes request method to GET","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.2,"exploitabilityScore":0.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-45803","epss":0.00062,"percentile":0.1968,"date":"2025-06-03"}],"fix":{"versions":["1.26.18"],"state":"fixed"},"advisories":[],"risk":0.02852},"relatedVulnerabilities":[{"id":"CVE-2023-45803","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-45803","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/urllib3/urllib3/commit/4e98d57809dacab1cbe625fddeec1a290c478ea9","https://github.com/urllib3/urllib3/security/advisories/GHSA-g4mx-q9vg-27p4","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4R2Y5XK3WALSR3FNAGN7JBYV2B343ZKB/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PPDPLM6UUMN55ESPQWJFLLIZY4ZKCNRX/","https://www.rfc-editor.org/rfc/rfc9110.html#name-get","https://github.com/urllib3/urllib3/commit/4e98d57809dacab1cbe625fddeec1a290c478ea9","https://github.com/urllib3/urllib3/security/advisories/GHSA-g4mx-q9vg-27p4","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4R2Y5XK3WALSR3FNAGN7JBYV2B343ZKB/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PPDPLM6UUMN55ESPQWJFLLIZY4ZKCNRX/","https://www.rfc-editor.org/rfc/rfc9110.html#name-get"],"description":"urllib3 is a user-friendly HTTP client library for Python. urllib3 previously wouldn't remove the HTTP request body when an HTTP redirect response using status 301, 302, or 303 after the request had its method changed from one that could accept a request body (like `POST`) to `GET` as is required by HTTP RFCs. Although this behavior is not specified in the section for redirects, it can be inferred by piecing together information from different sections and we have observed the behavior in other major HTTP client implementations like curl and web browsers. Because the vulnerability requires a previously trusted service to become compromised in order to have an impact on confidentiality we believe the exploitability of this vulnerability is low. Additionally, many users aren't putting sensitive data in HTTP request bodies, if this is the case then this vulnerability isn't exploitable. Both of the following conditions must be true to be affected by this vulnerability: 1. Using urllib3 and submitting sensitive information in the HTTP request body (such as form data or JSON) and 2. The origin service is compromised and starts redirecting using 301, 302, or 303 to a malicious peer or the redirected-to service becomes compromised. This issue has been addressed in versions 1.26.18 and 2.0.7 and users are advised to update to resolve this issue. Users unable to update should disable redirects for services that aren't expecting to respond with redirects with `redirects=False` and disable automatic redirects with `redirects=False` and handle 301, 302, and 303 redirects manually by stripping the HTTP request body.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.2,"exploitabilityScore":0.6,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.2,"exploitabilityScore":0.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-45803","epss":0.00062,"percentile":0.1968,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"urllib3","version":"1.25.8"}},"found":{"versionConstraint":">=0,<1.26.18 (python)","vulnerabilityID":"GHSA-g4mx-q9vg-27p4"},"fix":{"suggestedVersion":"1.26.18"}}],"artifact":{"id":"26bbe87e6e558d9d","name":"urllib3","version":"1.25.8","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/urllib3-1.25.8.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/urllib3-1.25.8.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/urllib3-1.25.8.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/urllib3-1.25.8.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:urllib3:1.25.8:*:*:*:*:*:*:*"],"purl":"pkg:pypi/urllib3@1.25.8","upstreams":[]}},{"vulnerability":{"id":"GHSA-f7c7-j99h-c22f","dataSource":"https://github.com/advisories/GHSA-f7c7-j99h-c22f","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Buffer Copy without Checking Size of Input in NumPy","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-41496","epss":0.00031,"percentile":0.07384,"date":"2025-06-03"}],"fix":{"versions":["1.19"],"state":"fixed"},"advisories":[],"risk":0.016275},"relatedVulnerabilities":[{"id":"CVE-2021-41496","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2021-41496","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/numpy/numpy/issues/19000","https://www.oracle.com/security-alerts/cpujul2022.html","https://github.com/numpy/numpy/issues/19000","https://www.oracle.com/security-alerts/cpujul2022.html"],"description":"Buffer overflow in the array_from_pyobj function of fortranobject.c in NumPy < 1.19, which allows attackers to conduct a Denial of Service attacks by carefully constructing an array with negative values. NOTE: The vendor does not agree this is a vulnerability; the negative dimensions can only be created by an already privileged user (or internally)","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:L/AC:L/Au:N/C:N/I:N/A:P","metrics":{"baseScore":2.1,"exploitabilityScore":4,"impactScore":2.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-41496","epss":0.00031,"percentile":0.07384,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"numpy","version":"1.17.4"}},"found":{"versionConstraint":"<=1.18.5 (python)","vulnerabilityID":"GHSA-f7c7-j99h-c22f"},"fix":{"suggestedVersion":"1.19"}}],"artifact":{"id":"bd1fdd8e53a74bf6","name":"numpy","version":"1.17.4","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/numpy-1.17.4.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/numpy-1.17.4.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/numpy-1.17.4.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/numpy-1.17.4.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD"],"cpes":["cpe:2.3:a:travis_e__oliphant_et_al__project:python-numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:travis_e__oliphant_et_al__project:python_numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:travis_e__oliphant_et_al_project:python-numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:travis_e__oliphant_et_al_project:python_numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:travis_e__oliphant_et_al__project:numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:travis_e__oliphant_et_al_:python-numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:travis_e__oliphant_et_al_:python_numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:travis_e__oliphant_et_al_project:numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:travis_e__oliphant_et_al_:numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python-numpy:python-numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python-numpy:python_numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python_numpy:python-numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python_numpy:python_numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python-numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python:python_numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:numpy:python-numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:numpy:python_numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python-numpy:numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python_numpy:numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:python:numpy:1.17.4:*:*:*:*:*:*:*","cpe:2.3:a:numpy:numpy:1.17.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/numpy@1.17.4","upstreams":[]}},{"vulnerability":{"id":"GHSA-34jh-p97f-mpxf","dataSource":"https://github.com/advisories/GHSA-34jh-p97f-mpxf","namespace":"github:language:python","severity":"Medium","urls":[],"description":"urllib3's Proxy-Authorization request header isn't stripped during cross-origin redirects","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.4,"exploitabilityScore":0.8,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-37891","epss":0.00033,"percentile":0.08049,"date":"2025-06-03"}],"fix":{"versions":["1.26.19"],"state":"fixed"},"advisories":[],"risk":0.01551},"relatedVulnerabilities":[{"id":"CVE-2024-37891","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-37891","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/urllib3/urllib3/commit/accff72ecc2f6cf5a76d9570198a93ac7c90270e","https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf","https://github.com/urllib3/urllib3/commit/accff72ecc2f6cf5a76d9570198a93ac7c90270e","https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf","https://security.netapp.com/advisory/ntap-20240822-0003/","https://www.vicarius.io/vsociety/posts/proxy-authorization-header-handling-vulnerability-in-urllib3-cve-2024-37891"],"description":"urllib3 is a user-friendly HTTP client library for Python. When using urllib3's proxy support with `ProxyManager`, the `Proxy-Authorization` header is only sent to the configured proxy, as expected. However, when sending HTTP requests *without* using urllib3's proxy support, it's possible to accidentally configure the `Proxy-Authorization` header even though it won't have any effect as the request is not using a forwarding proxy or a tunneling proxy. In those cases, urllib3 doesn't treat the `Proxy-Authorization` HTTP header as one carrying authentication material and thus doesn't strip the header on cross-origin redirects. Because this is a highly unlikely scenario, we believe the severity of this vulnerability is low for almost all users. Out of an abundance of caution urllib3 will automatically strip the `Proxy-Authorization` header during cross-origin redirects to avoid the small chance that users are doing this on accident. Users should use urllib3's proxy support or disable automatic redirects to achieve safe processing of the `Proxy-Authorization` header, but we still decided to strip the header by default in order to further protect users who aren't using the correct approach. We believe the number of usages affected by this advisory is low. It requires all of the following to be true to be exploited: 1. Setting the `Proxy-Authorization` header without using urllib3's built-in proxy support. 2. Not disabling HTTP redirects. 3. Either not using an HTTPS origin server or for the proxy or target origin to redirect to a malicious origin. Users are advised to update to either version 1.26.19 or version 2.2.2. Users unable to upgrade may use the `Proxy-Authorization` header with urllib3's `ProxyManager`, disable HTTP redirects using `redirects=False` when sending requests, or not user the `Proxy-Authorization` header as mitigations.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.4,"exploitabilityScore":0.8,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-37891","epss":0.00033,"percentile":0.08049,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"urllib3","version":"1.25.8"}},"found":{"versionConstraint":"<1.26.19 (python)","vulnerabilityID":"GHSA-34jh-p97f-mpxf"},"fix":{"suggestedVersion":"1.26.19"}}],"artifact":{"id":"26bbe87e6e558d9d","name":"urllib3","version":"1.25.8","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/urllib3-1.25.8.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/urllib3-1.25.8.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/urllib3-1.25.8.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/urllib3-1.25.8.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:urllib3:1.25.8:*:*:*:*:*:*:*"],"purl":"pkg:pypi/urllib3@1.25.8","upstreams":[]}},{"vulnerability":{"id":"GHSA-5cpq-8wj7-hf2v","dataSource":"https://github.com/advisories/GHSA-5cpq-8wj7-hf2v","namespace":"github:language:python","severity":"Low","urls":[],"description":"Vulnerable OpenSSL included in cryptography wheels","cvss":[],"fix":{"versions":["41.0.0"],"state":"fixed"},"advisories":[],"risk":0},"relatedVulnerabilities":[],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"2.8"}},"found":{"versionConstraint":">=0.5,<=40.0.2 (python)","vulnerabilityID":"GHSA-5cpq-8wj7-hf2v"},"fix":{"suggestedVersion":"41.0.0"}}],"artifact":{"id":"5db92af054d69cbe","name":"cryptography","version":"2.8","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/cryptography-2.8.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/cryptography-2.8.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/cryptography-2.8.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/cryptography-2.8.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD or Apache License, Version 2.0"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:2.8:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:2.8:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@2.8","upstreams":[]}},{"vulnerability":{"id":"GHSA-jm77-qphf-c4w8","dataSource":"https://github.com/advisories/GHSA-jm77-qphf-c4w8","namespace":"github:language:python","severity":"Low","urls":[],"description":"pyca/cryptography's wheels include vulnerable OpenSSL","cvss":[],"fix":{"versions":["41.0.3"],"state":"fixed"},"advisories":[],"risk":0},"relatedVulnerabilities":[],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"2.8"}},"found":{"versionConstraint":">=0.8,<41.0.3 (python)","vulnerabilityID":"GHSA-jm77-qphf-c4w8"},"fix":{"suggestedVersion":"41.0.3"}}],"artifact":{"id":"5db92af054d69cbe","name":"cryptography","version":"2.8","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/cryptography-2.8.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/cryptography-2.8.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/cryptography-2.8.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/cryptography-2.8.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD or Apache License, Version 2.0"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:2.8:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:2.8:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@2.8","upstreams":[]}},{"vulnerability":{"id":"GHSA-v8gr-m533-ghj9","dataSource":"https://github.com/advisories/GHSA-v8gr-m533-ghj9","namespace":"github:language:python","severity":"Low","urls":[],"description":"Vulnerable OpenSSL included in cryptography wheels","cvss":[],"fix":{"versions":["41.0.4"],"state":"fixed"},"advisories":[],"risk":0},"relatedVulnerabilities":[],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"2.8"}},"found":{"versionConstraint":">=2.5,<41.0.4 (python)","vulnerabilityID":"GHSA-v8gr-m533-ghj9"},"fix":{"suggestedVersion":"41.0.4"}}],"artifact":{"id":"5db92af054d69cbe","name":"cryptography","version":"2.8","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/cryptography-2.8.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/cryptography-2.8.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/cryptography-2.8.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/cryptography-2.8.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD or Apache License, Version 2.0"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:2.8:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:2.8:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@2.8","upstreams":[]}}],"source":{"type":"sbom-file","target":"pymol-oss-syft.json"},"distro":{"name":"","version":"","idLike":null},"descriptor":{"name":"grype","version":"0.92.2","configuration":{"output":["json=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-06-04/pymol-oss-grype.json","template=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-06-04/pymol-oss-grype.html"],"file":"","pretty":false,"distro":"","add-cpes-if-none":false,"output-template-file":"../html.tmpl","check-for-app-update":true,"only-fixed":false,"only-notfixed":false,"ignore-wontfix":"","platform":"","search":{"scope":"squashed","unindexed-archives":false,"indexed-archives":true},"ignore":[{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"kernel-headers","version":"","language":"","type":"rpm","location":"","upstream-name":"kernel"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux(-.*)?-headers-.*","version":"","language":"","type":"deb","location":"","upstream-name":"linux.*"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux-libc-dev","version":"","language":"","type":"deb","location":"","upstream-name":"linux"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"}],"exclude":[],"externalSources":{"enable":false,"maven":{"searchUpstreamBySha1":true,"baseUrl":"https://search.maven.org/solrsearch/select","rateLimit":300000000}},"match":{"java":{"using-cpes":false},"jvm":{"using-cpes":true},"dotnet":{"using-cpes":false},"golang":{"using-cpes":false,"always-use-cpe-for-stdlib":true,"allow-main-module-pseudo-version-comparison":false},"javascript":{"using-cpes":false},"python":{"using-cpes":false},"ruby":{"using-cpes":false},"rust":{"using-cpes":false},"stock":{"using-cpes":true}},"fail-on-severity":"","registry":{"insecure-skip-tls-verify":false,"insecure-use-http":false,"auth":null,"ca-cert":""},"show-suppressed":false,"by-cve":false,"SortBy":{"sort-by":"risk"},"name":"","default-image-pull-source":"","vex-documents":[],"vex-add":[],"match-upstream-kernel-headers":false,"db":{"cache-dir":"/Users/alan/Library/Caches/grype/db","update-url":"https://grype.anchore.io/databases","ca-cert":"","auto-update":true,"validate-by-hash-on-start":true,"validate-age":true,"max-allowed-built-age":432000000000000,"require-update-check":false,"update-available-timeout":30000000000,"update-download-timeout":300000000000,"max-update-check-frequency":7200000000000},"exp":{},"dev":{"db":{"debug":false}}},"db":{"status":{"schemaVersion":"v6.0.2","from":"https://grype.anchore.io/databases/v6/vulnerability-db_v6.0.2_2025-06-04T01:32:23Z_1749035557.tar.zst?checksum=sha256%3A77238f4ffbc7cf72bf4dedabbb21a3d0dd3ade90fb5d9df7c4da2870f8d1a9b7","built":"2025-06-04T11:12:37Z","path":"/Users/alan/Library/Caches/grype/db/6/vulnerability.db","valid":true},"providers":{"alpine":{"captured":"2025-06-04T01:32:23Z","input":"xxh64:a6a065ece392f6d1"},"amazon":{"captured":"2025-06-04T01:32:32Z","input":"xxh64:b65d458d6858d72a"},"chainguard":{"captured":"2025-06-04T01:32:33Z","input":"xxh64:03c9c4d182d77791"},"debian":{"captured":"2025-06-04T01:32:49Z","input":"xxh64:169ceb8fbcb8d6f1"},"epss":{"captured":"2025-06-04T01:32:42Z","input":"xxh64:bf87c4c234d02346"},"github":{"captured":"2025-06-04T01:32:30Z","input":"xxh64:3dab0be50635e057"},"kev":{"captured":"2025-06-04T01:32:45Z","input":"xxh64:a934e75f468f4e09"},"mariner":{"captured":"2025-06-04T01:32:43Z","input":"xxh64:ac698752085c186f"},"nvd":{"captured":"2025-06-04T01:33:28Z","input":"xxh64:389887843a59d29c"},"oracle":{"captured":"2025-06-04T01:32:35Z","input":"xxh64:0b8aabcfb6505b62"},"rhel":{"captured":"2025-06-04T04:49:10Z","input":"xxh64:947d0caeb19e9ccc"},"sles":{"captured":"2025-06-04T01:32:34Z","input":"xxh64:1c50b1219296628a"},"ubuntu":{"captured":"2025-06-04T01:33:14Z","input":"xxh64:71e22d5c5bbe7d14"},"wolfi":{"captured":"2025-06-04T01:32:42Z","input":"xxh64:e68fca5a870c6769"}}},"timestamp":"2025-06-04T19:38:59.011337+01:00"}}
