{"matches":[{"vulnerability":{"id":"GHSA-9fq2-x9r6-wfmf","dataSource":"https://github.com/advisories/GHSA-9fq2-x9r6-wfmf","namespace":"github:language:python","severity":"Critical","urls":[],"description":"Numpy Deserialization of Untrusted Data","cvss":[{"type":"Secondary","version":"3.0","vector":"CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":9.8,"exploitabilityScore":3.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2019-6446","epss":0.57542,"percentile":0.98023,"date":"2025-06-03"}],"fix":{"versions":[],"state":"not-fixed"},"advisories":[],"risk":54.08948000000001},"relatedVulnerabilities":[{"id":"CVE-2019-6446","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2019-6446","namespace":"nvd:cpe","severity":"Critical","urls":["http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00091.html","http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00092.html","http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00015.html","http://www.securityfocus.com/bid/106670","https://access.redhat.com/errata/RHSA-2019:3335","https://access.redhat.com/errata/RHSA-2019:3704","https://bugzilla.suse.com/show_bug.cgi?id=1122208","https://github.com/numpy/numpy/issues/12759","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/7ZZAYIQNUUYXGMKHSPEEXS4TRYFOUYE4/","http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00091.html","http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00092.html","http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00015.html","http://www.securityfocus.com/bid/106670","https://access.redhat.com/errata/RHSA-2019:3335","https://access.redhat.com/errata/RHSA-2019:3704","https://bugzilla.suse.com/show_bug.cgi?id=1122208","https://github.com/numpy/numpy/issues/12759","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/7ZZAYIQNUUYXGMKHSPEEXS4TRYFOUYE4/"],"description":"An issue was discovered in NumPy 1.16.0 and earlier. It uses the pickle Python module unsafely, which allows remote attackers to execute arbitrary code via a crafted serialized object, as demonstrated by a numpy.load call. NOTE: third parties dispute this issue because it is  a behavior that might have legitimate applications in (for example)  loading serialized Python object arrays from trusted and authenticated  sources","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.0","vector":"CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":9.8,"exploitabilityScore":3.9,"impactScore":5.9},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:L/Au:N/C:P/I:P/A:P","metrics":{"baseScore":7.5,"exploitabilityScore":10,"impactScore":6.5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2019-6446","epss":0.57542,"percentile":0.98023,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"numpy","version":"1.13.3"}},"found":{"versionConstraint":"<=1.16.0 (python)","vulnerabilityID":"GHSA-9fq2-x9r6-wfmf"}}],"artifact":{"id":"e1c9582bd743a37c","name":"numpy","version":"1.13.3","type":"python","locations":[{"path":"/usr/lib/python2.7/dist-packages/numpy-1.13.3.egg-info/PKG-INFO","accessPath":"/usr/lib/python2.7/dist-packages/numpy-1.13.3.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python2.7/dist-packages/numpy-1.13.3.egg-info/top_level.txt","accessPath":"/usr/lib/python2.7/dist-packages/numpy-1.13.3.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD"],"cpes":["cpe:2.3:a:numpy_developers_project:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developers_project:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussion_project:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussion_project:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developersproject:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developersproject:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussionproject:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussionproject:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developers_project:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussion_project:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy-discussion:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy-discussion:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developers:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developers:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developersproject:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussion:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussion:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussionproject:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python-numpy:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python-numpy:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python_numpy:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python_numpy:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy-discussion:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developers:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussion:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python-numpy:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python_numpy:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy:numpy:1.13.3:*:*:*:*:*:*:*"],"purl":"pkg:pypi/numpy@1.13.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-5rjg-fvgr-3xxf","dataSource":"https://github.com/advisories/GHSA-5rjg-fvgr-3xxf","namespace":"github:language:python","severity":"High","urls":[],"description":"setuptools has a path traversal vulnerability in PackageIndex.download that leads to Arbitrary File Write","cvss":[],"epss":[{"cve":"CVE-2025-47273","epss":0.00435,"percentile":0.62062,"date":"2025-06-03"}],"fix":{"versions":["78.1.1"],"state":"fixed"},"advisories":[],"risk":0.32625},"relatedVulnerabilities":[{"id":"CVE-2025-47273","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-47273","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pypa/setuptools/blob/6ead555c5fb29bc57fe6105b1bffc163f56fd558/setuptools/package_index.py#L810C1-L825C88","https://github.com/pypa/setuptools/commit/250a6d17978f9f6ac3ac887091f2d32886fbbb0b","https://github.com/pypa/setuptools/issues/4946","https://github.com/pypa/setuptools/security/advisories/GHSA-5rjg-fvgr-3xxf","https://lists.debian.org/debian-lts-announce/2025/05/msg00035.html","https://github.com/pypa/setuptools/issues/4946"],"description":"setuptools is a package that allows users to download, build, install, upgrade, and uninstall Python packages. A path traversal vulnerability in `PackageIndex` is present in setuptools prior to version 78.1.1. An attacker would be allowed to write files to arbitrary locations on the filesystem with the permissions of the process running the Python code, which could escalate to remote code execution depending on the context. Version 78.1.1 fixes the issue.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:H/VA:N/SC:N/SI:N/SA:N/E:P/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":7.7},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-47273","epss":0.00435,"percentile":0.62062,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"setuptools","version":"41.4.0"}},"found":{"versionConstraint":"<78.1.1 (python)","vulnerabilityID":"GHSA-5rjg-fvgr-3xxf"},"fix":{"suggestedVersion":"78.1.1"}}],"artifact":{"id":"2ef9c3b3d4328bf0","name":"setuptools","version":"41.4.0","type":"python","locations":[{"path":"/lib/python2.7/site-packages/setuptools-41.4.0.dist-info/METADATA","accessPath":"/lib/python2.7/site-packages/setuptools-41.4.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python2.7/site-packages/setuptools-41.4.0.dist-info/top_level.txt","accessPath":"/lib/python2.7/site-packages/setuptools-41.4.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["UNKNOWN"],"cpes":["cpe:2.3:a:python:setuptools:41.4.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/setuptools@41.4.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-r9hx-vwmv-q579","dataSource":"https://github.com/advisories/GHSA-r9hx-vwmv-q579","namespace":"github:language:python","severity":"High","urls":[],"description":"pypa/setuptools vulnerable to Regular Expression Denial of Service (ReDoS)","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-40897","epss":0.00318,"percentile":0.54328,"date":"2025-06-03"}],"fix":{"versions":["65.5.1"],"state":"fixed"},"advisories":[],"risk":0.2385},"relatedVulnerabilities":[{"id":"CVE-2022-40897","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2022-40897","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pypa/setuptools/blob/fe8a98e696241487ba6ac9f91faa38ade939ec5d/setuptools/package_index.py#L200","https://github.com/pypa/setuptools/commit/43a9c9bfa6aa626ec2a22540bea28d2ca77964be","https://github.com/pypa/setuptools/compare/v65.5.0...v65.5.1","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H/","https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/","https://pyup.io/vulnerabilities/CVE-2022-40897/52495/","https://security.netapp.com/advisory/ntap-20230214-0001/","https://security.netapp.com/advisory/ntap-20240621-0006/","https://github.com/pypa/setuptools/blob/fe8a98e696241487ba6ac9f91faa38ade939ec5d/setuptools/package_index.py#L200","https://github.com/pypa/setuptools/commit/43a9c9bfa6aa626ec2a22540bea28d2ca77964be","https://github.com/pypa/setuptools/compare/v65.5.0...v65.5.1","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H/","https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/","https://pyup.io/vulnerabilities/CVE-2022-40897/52495/","https://security.netapp.com/advisory/ntap-20230214-0001/","https://security.netapp.com/advisory/ntap-20240621-0006/"],"description":"Python Packaging Authority (PyPA) setuptools before 65.5.1 allows remote attackers to cause a denial of service via HTML in a crafted package or custom PackageIndex page. There is a Regular Expression Denial of Service (ReDoS) in package_index.py.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-40897","epss":0.00318,"percentile":0.54328,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"setuptools","version":"41.4.0"}},"found":{"versionConstraint":"<65.5.1 (python)","vulnerabilityID":"GHSA-r9hx-vwmv-q579"},"fix":{"suggestedVersion":"65.5.1"}}],"artifact":{"id":"2ef9c3b3d4328bf0","name":"setuptools","version":"41.4.0","type":"python","locations":[{"path":"/lib/python2.7/site-packages/setuptools-41.4.0.dist-info/METADATA","accessPath":"/lib/python2.7/site-packages/setuptools-41.4.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python2.7/site-packages/setuptools-41.4.0.dist-info/top_level.txt","accessPath":"/lib/python2.7/site-packages/setuptools-41.4.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["UNKNOWN"],"cpes":["cpe:2.3:a:python:setuptools:41.4.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/setuptools@41.4.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-cx63-2mw6-8hw5","dataSource":"https://github.com/advisories/GHSA-cx63-2mw6-8hw5","namespace":"github:language:python","severity":"High","urls":[],"description":"setuptools vulnerable to Command Injection via package URL","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.8,"exploitabilityScore":2.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-6345","epss":0.00227,"percentile":0.45699,"date":"2025-06-03"}],"fix":{"versions":["70.0.0"],"state":"fixed"},"advisories":[],"risk":0.185005},"relatedVulnerabilities":[{"id":"CVE-2024-6345","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-6345","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pypa/setuptools/commit/88807c7062788254f654ea8c03427adc859321f0","https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5","https://github.com/pypa/setuptools/commit/88807c7062788254f654ea8c03427adc859321f0","https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5"],"description":"A vulnerability in the package_index module of pypa/setuptools versions up to 69.1.1 allows for remote code execution via its download functions. These functions, which are used to download packages from URLs provided by users or retrieved from package index servers, are susceptible to code injection. If these functions are exposed to user-controlled inputs, such as package URLs, they can execute arbitrary commands on the system. The issue is fixed in version 70.0.","cvss":[{"source":"security@huntr.dev","type":"Secondary","version":"3.0","vector":"CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.8,"exploitabilityScore":2.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-6345","epss":0.00227,"percentile":0.45699,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"setuptools","version":"41.4.0"}},"found":{"versionConstraint":"<70.0.0 (python)","vulnerabilityID":"GHSA-cx63-2mw6-8hw5"},"fix":{"suggestedVersion":"70.0.0"}}],"artifact":{"id":"2ef9c3b3d4328bf0","name":"setuptools","version":"41.4.0","type":"python","locations":[{"path":"/lib/python2.7/site-packages/setuptools-41.4.0.dist-info/METADATA","accessPath":"/lib/python2.7/site-packages/setuptools-41.4.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python2.7/site-packages/setuptools-41.4.0.dist-info/top_level.txt","accessPath":"/lib/python2.7/site-packages/setuptools-41.4.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["UNKNOWN"],"cpes":["cpe:2.3:a:python:setuptools:41.4.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/setuptools@41.4.0","upstreams":[]}},{"vulnerability":{"id":"GHSA-5xp3-jfq3-5q8x","dataSource":"https://github.com/advisories/GHSA-5xp3-jfq3-5q8x","namespace":"github:language:python","severity":"High","urls":[],"description":"Improper Input Validation in pip","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:N/I:H/A:N","metrics":{"baseScore":5.7,"exploitabilityScore":2.1,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-3572","epss":0.0024,"percentile":0.4753,"date":"2025-06-03"}],"fix":{"versions":["21.1"],"state":"fixed"},"advisories":[],"risk":0.15839999999999999},"relatedVulnerabilities":[{"id":"CVE-2021-3572","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2021-3572","namespace":"nvd:cpe","severity":"Medium","urls":["https://bugzilla.redhat.com/show_bug.cgi?id=1962856","https://security.netapp.com/advisory/ntap-20240621-0006/","https://www.oracle.com/security-alerts/cpuapr2022.html","https://www.oracle.com/security-alerts/cpujul2022.html","https://bugzilla.redhat.com/show_bug.cgi?id=1962856","https://security.netapp.com/advisory/ntap-20240621-0006/","https://www.oracle.com/security-alerts/cpuapr2022.html","https://www.oracle.com/security-alerts/cpujul2022.html"],"description":"A flaw was found in python-pip in the way it handled Unicode separators in git references. A remote attacker could possibly use this issue to install a different revision on a repository. The highest threat from this vulnerability is to data integrity. This is fixed in python-pip version 21.1.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:N/I:H/A:N","metrics":{"baseScore":5.7,"exploitabilityScore":2.1,"impactScore":3.6},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:M/Au:S/C:N/I:P/A:N","metrics":{"baseScore":3.5,"exploitabilityScore":6.9,"impactScore":2.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-3572","epss":0.0024,"percentile":0.4753,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"pip","version":"19.3.1"}},"found":{"versionConstraint":"<21.1 (python)","vulnerabilityID":"GHSA-5xp3-jfq3-5q8x"},"fix":{"suggestedVersion":"21.1"}}],"artifact":{"id":"19ed55bc4b57352f","name":"pip","version":"19.3.1","type":"python","locations":[{"path":"/lib/python2.7/site-packages/pip-19.3.1.dist-info/METADATA","accessPath":"/lib/python2.7/site-packages/pip-19.3.1.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python2.7/site-packages/pip-19.3.1.dist-info/top_level.txt","accessPath":"/lib/python2.7/site-packages/pip-19.3.1.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:pip_developers_project:python-pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers_project:python_pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:python-pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:python_pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev_project:python-pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev_project:python_pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers_project:pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pypa_devproject:python-pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pypa_devproject:python_pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:python-pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:python_pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:python-pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:python_pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:python-pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:python_pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev_project:pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pypa-dev:python-pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pypa-dev:python_pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev:python-pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev:python_pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pypa_devproject:pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:python:python-pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:python:python_pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pypa:python-pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pypa:python_pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pip:python-pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pip:python_pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pypa-dev:pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev:pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:python:pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pypa:pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pip:pip:19.3.1:*:*:*:*:*:*:*"],"purl":"pkg:pypi/pip@19.3.1","upstreams":[]}},{"vulnerability":{"id":"GHSA-qwmp-2cf2-g9g6","dataSource":"https://github.com/advisories/GHSA-qwmp-2cf2-g9g6","namespace":"github:language:python","severity":"High","urls":[],"description":"pypa/wheel vulnerable to Regular Expression denial of service (ReDoS)","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-40898","epss":0.00108,"percentile":0.30278,"date":"2025-06-03"}],"fix":{"versions":["0.38.1"],"state":"fixed"},"advisories":[],"risk":0.08099999999999999},"relatedVulnerabilities":[{"id":"CVE-2022-40898","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2022-40898","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pypa/wheel/blob/main/src/wheel/wheelfile.py#L18","https://pypi.org/project/wheel/","https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/","https://github.com/pypa/wheel/blob/main/src/wheel/wheelfile.py#L18","https://pypi.org/project/wheel/","https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/"],"description":"An issue discovered in Python Packaging Authority (PyPA) Wheel 0.37.1 and earlier allows remote attackers to cause a denial of service via attacker controlled input to wheel cli.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-40898","epss":0.00108,"percentile":0.30278,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"wheel","version":"0.33.6"}},"found":{"versionConstraint":"<0.38.1 (python)","vulnerabilityID":"GHSA-qwmp-2cf2-g9g6"},"fix":{"suggestedVersion":"0.38.1"}}],"artifact":{"id":"9d27518b84e70da2","name":"wheel","version":"0.33.6","type":"python","locations":[{"path":"/lib/python2.7/site-packages/wheel-0.33.6.dist-info/METADATA","accessPath":"/lib/python2.7/site-packages/wheel-0.33.6.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python2.7/site-packages/wheel-0.33.6.dist-info/top_level.txt","accessPath":"/lib/python2.7/site-packages/wheel-0.33.6.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:daniel_holth_project:python-wheel:0.33.6:*:*:*:*:*:*:*","cpe:2.3:a:daniel_holth_project:python_wheel:0.33.6:*:*:*:*:*:*:*","cpe:2.3:a:daniel_holthproject:python-wheel:0.33.6:*:*:*:*:*:*:*","cpe:2.3:a:daniel_holthproject:python_wheel:0.33.6:*:*:*:*:*:*:*","cpe:2.3:a:dholth_project:python-wheel:0.33.6:*:*:*:*:*:*:*","cpe:2.3:a:dholth_project:python_wheel:0.33.6:*:*:*:*:*:*:*","cpe:2.3:a:daniel_holth_project:wheel:0.33.6:*:*:*:*:*:*:*","cpe:2.3:a:dholthproject:python-wheel:0.33.6:*:*:*:*:*:*:*","cpe:2.3:a:dholthproject:python_wheel:0.33.6:*:*:*:*:*:*:*","cpe:2.3:a:daniel_holth:python-wheel:0.33.6:*:*:*:*:*:*:*","cpe:2.3:a:daniel_holth:python_wheel:0.33.6:*:*:*:*:*:*:*","cpe:2.3:a:daniel_holthproject:wheel:0.33.6:*:*:*:*:*:*:*","cpe:2.3:a:python-wheel:python-wheel:0.33.6:*:*:*:*:*:*:*","cpe:2.3:a:python-wheel:python_wheel:0.33.6:*:*:*:*:*:*:*","cpe:2.3:a:python_wheel:python-wheel:0.33.6:*:*:*:*:*:*:*","cpe:2.3:a:python_wheel:python_wheel:0.33.6:*:*:*:*:*:*:*","cpe:2.3:a:dholth_project:wheel:0.33.6:*:*:*:*:*:*:*","cpe:2.3:a:dholth:python-wheel:0.33.6:*:*:*:*:*:*:*","cpe:2.3:a:dholth:python_wheel:0.33.6:*:*:*:*:*:*:*","cpe:2.3:a:dholthproject:wheel:0.33.6:*:*:*:*:*:*:*","cpe:2.3:a:python:python-wheel:0.33.6:*:*:*:*:*:*:*","cpe:2.3:a:python:python_wheel:0.33.6:*:*:*:*:*:*:*","cpe:2.3:a:daniel_holth:wheel:0.33.6:*:*:*:*:*:*:*","cpe:2.3:a:python-wheel:wheel:0.33.6:*:*:*:*:*:*:*","cpe:2.3:a:python_wheel:wheel:0.33.6:*:*:*:*:*:*:*","cpe:2.3:a:wheel:python-wheel:0.33.6:*:*:*:*:*:*:*","cpe:2.3:a:wheel:python_wheel:0.33.6:*:*:*:*:*:*:*","cpe:2.3:a:dholth:wheel:0.33.6:*:*:*:*:*:*:*","cpe:2.3:a:python:wheel:0.33.6:*:*:*:*:*:*:*","cpe:2.3:a:wheel:wheel:0.33.6:*:*:*:*:*:*:*"],"purl":"pkg:pypi/wheel@0.33.6","upstreams":[]}},{"vulnerability":{"id":"GHSA-5545-2q6w-2gh6","dataSource":"https://github.com/advisories/GHSA-5545-2q6w-2gh6","namespace":"github:language:python","severity":"High","urls":[],"description":"NumPy NULL Pointer Dereference","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-41495","epss":0.00102,"percentile":0.29251,"date":"2025-06-03"}],"fix":{"versions":["1.19"],"state":"fixed"},"advisories":[],"risk":0.07650000000000001},"relatedVulnerabilities":[{"id":"CVE-2021-41495","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2021-41495","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/numpy/numpy/issues/19038","https://www.oracle.com/security-alerts/cpujul2022.html","https://github.com/numpy/numpy/issues/19038","https://www.oracle.com/security-alerts/cpujul2022.html"],"description":"Null Pointer Dereference vulnerability exists in numpy.sort in NumPy &lt and 1.19 in the PyArray_DescrNew function due to missing return-value validation, which allows attackers to conduct DoS attacks by repetitively creating sort arrays. NOTE: While correct that validation is missing, an error can only occur due to an exhaustion of memory. If the user can exhaust memory, they are already privileged. Further, it should be practically impossible to construct an attack which can target the memory exhaustion to occur at exactly this place","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.3,"exploitabilityScore":1.7,"impactScore":3.6},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:M/Au:S/C:N/I:N/A:P","metrics":{"baseScore":3.5,"exploitabilityScore":6.9,"impactScore":2.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-41495","epss":0.00102,"percentile":0.29251,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"numpy","version":"1.13.3"}},"found":{"versionConstraint":"<=1.18.5 (python)","vulnerabilityID":"GHSA-5545-2q6w-2gh6"},"fix":{"suggestedVersion":"1.19"}}],"artifact":{"id":"e1c9582bd743a37c","name":"numpy","version":"1.13.3","type":"python","locations":[{"path":"/usr/lib/python2.7/dist-packages/numpy-1.13.3.egg-info/PKG-INFO","accessPath":"/usr/lib/python2.7/dist-packages/numpy-1.13.3.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python2.7/dist-packages/numpy-1.13.3.egg-info/top_level.txt","accessPath":"/usr/lib/python2.7/dist-packages/numpy-1.13.3.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD"],"cpes":["cpe:2.3:a:numpy_developers_project:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developers_project:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussion_project:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussion_project:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developersproject:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developersproject:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussionproject:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussionproject:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developers_project:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussion_project:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy-discussion:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy-discussion:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developers:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developers:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developersproject:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussion:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussion:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussionproject:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python-numpy:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python-numpy:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python_numpy:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python_numpy:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy-discussion:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developers:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussion:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python-numpy:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python_numpy:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy:numpy:1.13.3:*:*:*:*:*:*:*"],"purl":"pkg:pypi/numpy@1.13.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-6p56-wp2h-9hxr","dataSource":"https://github.com/advisories/GHSA-6p56-wp2h-9hxr","namespace":"github:language:python","severity":"Medium","urls":[],"description":"NumPy Buffer Overflow (Disputed)","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.3,"exploitabilityScore":1.7,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-33430","epss":0.00124,"percentile":0.32963,"date":"2025-06-03"}],"fix":{"versions":["1.21"],"state":"fixed"},"advisories":[],"risk":0.06386},"relatedVulnerabilities":[{"id":"CVE-2021-33430","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2021-33430","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/numpy/numpy/issues/18939","https://github.com/numpy/numpy/issues/18939"],"description":"A Buffer Overflow vulnerability exists in NumPy 1.9.x in the PyArray_NewFromDescr_int function of ctors.c when specifying arrays of large dimensions (over 32) from Python code, which could let a malicious user cause a Denial of Service. NOTE: The vendor does not agree this is a vulneraility; In (very limited) circumstances a user may be able provoke the buffer overflow, the user is most likely already privileged to at least provoke denial of service by exhausting memory. Triggering this further requires the use of uncommon API (complicated structured dtypes), which is very unlikely to be available to an unprivileged user","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.3,"exploitabilityScore":1.7,"impactScore":3.6},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:M/Au:S/C:N/I:N/A:P","metrics":{"baseScore":3.5,"exploitabilityScore":6.9,"impactScore":2.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-33430","epss":0.00124,"percentile":0.32963,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"numpy","version":"1.13.3"}},"found":{"versionConstraint":">=1.9.0,<1.21 (python)","vulnerabilityID":"GHSA-6p56-wp2h-9hxr"},"fix":{"suggestedVersion":"1.21"}}],"artifact":{"id":"e1c9582bd743a37c","name":"numpy","version":"1.13.3","type":"python","locations":[{"path":"/usr/lib/python2.7/dist-packages/numpy-1.13.3.egg-info/PKG-INFO","accessPath":"/usr/lib/python2.7/dist-packages/numpy-1.13.3.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python2.7/dist-packages/numpy-1.13.3.egg-info/top_level.txt","accessPath":"/usr/lib/python2.7/dist-packages/numpy-1.13.3.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD"],"cpes":["cpe:2.3:a:numpy_developers_project:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developers_project:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussion_project:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussion_project:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developersproject:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developersproject:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussionproject:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussionproject:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developers_project:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussion_project:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy-discussion:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy-discussion:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developers:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developers:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developersproject:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussion:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussion:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussionproject:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python-numpy:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python-numpy:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python_numpy:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python_numpy:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy-discussion:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developers:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussion:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python-numpy:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python_numpy:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy:numpy:1.13.3:*:*:*:*:*:*:*"],"purl":"pkg:pypi/numpy@1.13.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-fpfv-jqm9-f5jm","dataSource":"https://github.com/advisories/GHSA-fpfv-jqm9-f5jm","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Incorrect Comparison in NumPy","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L","metrics":{"baseScore":5.3,"exploitabilityScore":3.9,"impactScore":1.5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-34141","epss":0.00061,"percentile":0.19494,"date":"2025-06-03"}],"fix":{"versions":["1.22"],"state":"fixed"},"advisories":[],"risk":0.031415},"relatedVulnerabilities":[{"id":"CVE-2021-34141","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2021-34141","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/numpy/numpy/issues/18993","https://www.oracle.com/security-alerts/cpujul2022.html","https://github.com/numpy/numpy/issues/18993","https://www.oracle.com/security-alerts/cpujul2022.html"],"description":"An incomplete string comparison in the numpy.core component in NumPy before 1.22.0 allows attackers to trigger slightly incorrect copying by constructing specific string objects. NOTE: the vendor states that this reported code behavior is \"completely harmless.\"","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L","metrics":{"baseScore":5.3,"exploitabilityScore":3.9,"impactScore":1.5},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:L/Au:N/C:N/I:N/A:P","metrics":{"baseScore":5,"exploitabilityScore":10,"impactScore":2.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-34141","epss":0.00061,"percentile":0.19494,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"numpy","version":"1.13.3"}},"found":{"versionConstraint":"<1.22 (python)","vulnerabilityID":"GHSA-fpfv-jqm9-f5jm"},"fix":{"suggestedVersion":"1.22"}}],"artifact":{"id":"e1c9582bd743a37c","name":"numpy","version":"1.13.3","type":"python","locations":[{"path":"/usr/lib/python2.7/dist-packages/numpy-1.13.3.egg-info/PKG-INFO","accessPath":"/usr/lib/python2.7/dist-packages/numpy-1.13.3.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python2.7/dist-packages/numpy-1.13.3.egg-info/top_level.txt","accessPath":"/usr/lib/python2.7/dist-packages/numpy-1.13.3.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD"],"cpes":["cpe:2.3:a:numpy_developers_project:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developers_project:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussion_project:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussion_project:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developersproject:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developersproject:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussionproject:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussionproject:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developers_project:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussion_project:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy-discussion:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy-discussion:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developers:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developers:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developersproject:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussion:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussion:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussionproject:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python-numpy:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python-numpy:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python_numpy:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python_numpy:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy-discussion:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developers:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussion:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python-numpy:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python_numpy:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy:numpy:1.13.3:*:*:*:*:*:*:*"],"purl":"pkg:pypi/numpy@1.13.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-mq26-g339-26xf","dataSource":"https://github.com/advisories/GHSA-mq26-g339-26xf","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Command Injection in pip when used with Mercurial","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-5752","epss":0.0004,"percentile":0.11691,"date":"2025-06-03"}],"fix":{"versions":["23.3"],"state":"fixed"},"advisories":[],"risk":0.021},"relatedVulnerabilities":[{"id":"CVE-2023-5752","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-5752","namespace":"nvd:cpe","severity":"Low","urls":["https://github.com/pypa/pip/pull/12306","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/622OZXWG72ISQPLM5Y57YCVIMWHD4C3U/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/65UKKF5LBHEFDCUSPBHUN4IHYX7SRMHH/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FXUVMJM25PUAZRQZBF54OFVKTY3MINPW/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KFC2SPFG5FLCZBYY2K3T5MFW2D22NG6E/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YBSB3SUPQ3VIFYUMHPO3MEQI4BJAXKCZ/","https://mail.python.org/archives/list/security-announce@python.org/thread/F4PL35U6X4VVHZ5ILJU3PWUWN7H7LZXL/","https://github.com/pypa/pip/pull/12306","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/622OZXWG72ISQPLM5Y57YCVIMWHD4C3U/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/65UKKF5LBHEFDCUSPBHUN4IHYX7SRMHH/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FXUVMJM25PUAZRQZBF54OFVKTY3MINPW/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KFC2SPFG5FLCZBYY2K3T5MFW2D22NG6E/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YBSB3SUPQ3VIFYUMHPO3MEQI4BJAXKCZ/","https://mail.python.org/archives/list/security-announce@python.org/thread/F4PL35U6X4VVHZ5ILJU3PWUWN7H7LZXL/"],"description":"When installing a package from a Mercurial VCS URL  (ie \"pip install \nhg+...\") with pip prior to v23.3, the specified Mercurial revision could\n be used to inject arbitrary configuration options to the \"hg clone\" \ncall (ie \"--config\"). Controlling the Mercurial configuration can modify\n how and which repository is installed. This vulnerability does not \naffect users who aren't installing from Mercurial.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:N","metrics":{"baseScore":3.3,"exploitabilityScore":1.9,"impactScore":1.5},"vendorMetadata":{}},{"source":"cna@python.org","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-5752","epss":0.0004,"percentile":0.11691,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"pip","version":"19.3.1"}},"found":{"versionConstraint":"<23.3 (python)","vulnerabilityID":"GHSA-mq26-g339-26xf"},"fix":{"suggestedVersion":"23.3"}}],"artifact":{"id":"19ed55bc4b57352f","name":"pip","version":"19.3.1","type":"python","locations":[{"path":"/lib/python2.7/site-packages/pip-19.3.1.dist-info/METADATA","accessPath":"/lib/python2.7/site-packages/pip-19.3.1.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python2.7/site-packages/pip-19.3.1.dist-info/top_level.txt","accessPath":"/lib/python2.7/site-packages/pip-19.3.1.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:pip_developers_project:python-pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers_project:python_pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:python-pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:python_pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev_project:python-pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev_project:python_pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers_project:pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pypa_devproject:python-pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pypa_devproject:python_pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:python-pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:python_pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pip_developersproject:pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:python-pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:python_pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:python-pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:python_pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev_project:pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pypa-dev:python-pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pypa-dev:python_pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev:python-pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev:python_pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pypa_devproject:pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pip_developers:pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:python:python-pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:python:python_pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pypa:python-pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pypa:python_pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pip:python-pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pip:python_pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:python-pip:pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:python_pip:pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pypa-dev:pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pypa_dev:pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:python:pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pypa:pip:19.3.1:*:*:*:*:*:*:*","cpe:2.3:a:pip:pip:19.3.1:*:*:*:*:*:*:*"],"purl":"pkg:pypi/pip@19.3.1","upstreams":[]}},{"vulnerability":{"id":"GHSA-f7c7-j99h-c22f","dataSource":"https://github.com/advisories/GHSA-f7c7-j99h-c22f","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Buffer Copy without Checking Size of Input in NumPy","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-41496","epss":0.00031,"percentile":0.07384,"date":"2025-06-03"}],"fix":{"versions":["1.19"],"state":"fixed"},"advisories":[],"risk":0.016275},"relatedVulnerabilities":[{"id":"CVE-2021-41496","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2021-41496","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/numpy/numpy/issues/19000","https://www.oracle.com/security-alerts/cpujul2022.html","https://github.com/numpy/numpy/issues/19000","https://www.oracle.com/security-alerts/cpujul2022.html"],"description":"Buffer overflow in the array_from_pyobj function of fortranobject.c in NumPy < 1.19, which allows attackers to conduct a Denial of Service attacks by carefully constructing an array with negative values. NOTE: The vendor does not agree this is a vulnerability; the negative dimensions can only be created by an already privileged user (or internally)","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:L/AC:L/Au:N/C:N/I:N/A:P","metrics":{"baseScore":2.1,"exploitabilityScore":4,"impactScore":2.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-41496","epss":0.00031,"percentile":0.07384,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"numpy","version":"1.13.3"}},"found":{"versionConstraint":"<=1.18.5 (python)","vulnerabilityID":"GHSA-f7c7-j99h-c22f"},"fix":{"suggestedVersion":"1.19"}}],"artifact":{"id":"e1c9582bd743a37c","name":"numpy","version":"1.13.3","type":"python","locations":[{"path":"/usr/lib/python2.7/dist-packages/numpy-1.13.3.egg-info/PKG-INFO","accessPath":"/usr/lib/python2.7/dist-packages/numpy-1.13.3.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python2.7/dist-packages/numpy-1.13.3.egg-info/top_level.txt","accessPath":"/usr/lib/python2.7/dist-packages/numpy-1.13.3.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD"],"cpes":["cpe:2.3:a:numpy_developers_project:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developers_project:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussion_project:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussion_project:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developersproject:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developersproject:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussionproject:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussionproject:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developers_project:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussion_project:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy-discussion:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy-discussion:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developers:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developers:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developersproject:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussion:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussion:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussionproject:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python-numpy:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python-numpy:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python_numpy:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python_numpy:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy-discussion:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_developers:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy_discussion:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy:python-numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy:python_numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python-numpy:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python_numpy:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:python:numpy:1.13.3:*:*:*:*:*:*:*","cpe:2.3:a:numpy:numpy:1.13.3:*:*:*:*:*:*:*"],"purl":"pkg:pypi/numpy@1.13.3","upstreams":[]}}],"source":{"type":"sbom-file","target":"suspended-sentence-syft.json"},"distro":{"name":"","version":"","idLike":null},"descriptor":{"name":"grype","version":"0.92.2","configuration":{"output":["json=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-06-04/suspended-sentence-grype.json","template=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-06-04/suspended-sentence-grype.html"],"file":"","pretty":false,"distro":"","add-cpes-if-none":false,"output-template-file":"../html.tmpl","check-for-app-update":true,"only-fixed":false,"only-notfixed":false,"ignore-wontfix":"","platform":"","search":{"scope":"squashed","unindexed-archives":false,"indexed-archives":true},"ignore":[{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"kernel-headers","version":"","language":"","type":"rpm","location":"","upstream-name":"kernel"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux(-.*)?-headers-.*","version":"","language":"","type":"deb","location":"","upstream-name":"linux.*"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux-libc-dev","version":"","language":"","type":"deb","location":"","upstream-name":"linux"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"}],"exclude":[],"externalSources":{"enable":false,"maven":{"searchUpstreamBySha1":true,"baseUrl":"https://search.maven.org/solrsearch/select","rateLimit":300000000}},"match":{"java":{"using-cpes":false},"jvm":{"using-cpes":true},"dotnet":{"using-cpes":false},"golang":{"using-cpes":false,"always-use-cpe-for-stdlib":true,"allow-main-module-pseudo-version-comparison":false},"javascript":{"using-cpes":false},"python":{"using-cpes":false},"ruby":{"using-cpes":false},"rust":{"using-cpes":false},"stock":{"using-cpes":true}},"fail-on-severity":"","registry":{"insecure-skip-tls-verify":false,"insecure-use-http":false,"auth":null,"ca-cert":""},"show-suppressed":false,"by-cve":false,"SortBy":{"sort-by":"risk"},"name":"","default-image-pull-source":"","vex-documents":[],"vex-add":[],"match-upstream-kernel-headers":false,"db":{"cache-dir":"/Users/alan/Library/Caches/grype/db","update-url":"https://grype.anchore.io/databases","ca-cert":"","auto-update":true,"validate-by-hash-on-start":true,"validate-age":true,"max-allowed-built-age":432000000000000,"require-update-check":false,"update-available-timeout":30000000000,"update-download-timeout":300000000000,"max-update-check-frequency":7200000000000},"exp":{},"dev":{"db":{"debug":false}}},"db":{"status":{"schemaVersion":"v6.0.2","from":"https://grype.anchore.io/databases/v6/vulnerability-db_v6.0.2_2025-06-04T01:32:23Z_1749035557.tar.zst?checksum=sha256%3A77238f4ffbc7cf72bf4dedabbb21a3d0dd3ade90fb5d9df7c4da2870f8d1a9b7","built":"2025-06-04T11:12:37Z","path":"/Users/alan/Library/Caches/grype/db/6/vulnerability.db","valid":true},"providers":{"alpine":{"captured":"2025-06-04T01:32:23Z","input":"xxh64:a6a065ece392f6d1"},"amazon":{"captured":"2025-06-04T01:32:32Z","input":"xxh64:b65d458d6858d72a"},"chainguard":{"captured":"2025-06-04T01:32:33Z","input":"xxh64:03c9c4d182d77791"},"debian":{"captured":"2025-06-04T01:32:49Z","input":"xxh64:169ceb8fbcb8d6f1"},"epss":{"captured":"2025-06-04T01:32:42Z","input":"xxh64:bf87c4c234d02346"},"github":{"captured":"2025-06-04T01:32:30Z","input":"xxh64:3dab0be50635e057"},"kev":{"captured":"2025-06-04T01:32:45Z","input":"xxh64:a934e75f468f4e09"},"mariner":{"captured":"2025-06-04T01:32:43Z","input":"xxh64:ac698752085c186f"},"nvd":{"captured":"2025-06-04T01:33:28Z","input":"xxh64:389887843a59d29c"},"oracle":{"captured":"2025-06-04T01:32:35Z","input":"xxh64:0b8aabcfb6505b62"},"rhel":{"captured":"2025-06-04T04:49:10Z","input":"xxh64:947d0caeb19e9ccc"},"sles":{"captured":"2025-06-04T01:32:34Z","input":"xxh64:1c50b1219296628a"},"ubuntu":{"captured":"2025-06-04T01:33:14Z","input":"xxh64:71e22d5c5bbe7d14"},"wolfi":{"captured":"2025-06-04T01:32:42Z","input":"xxh64:e68fca5a870c6769"}}},"timestamp":"2025-06-04T19:45:23.268049+01:00"}}
