{"matches":[{"vulnerability":{"id":"GHSA-5rjg-fvgr-3xxf","dataSource":"https://github.com/advisories/GHSA-5rjg-fvgr-3xxf","namespace":"github:language:python","severity":"High","urls":[],"description":"setuptools has a path traversal vulnerability in PackageIndex.download that leads to Arbitrary File Write","cvss":[],"epss":[{"cve":"CVE-2025-47273","epss":0.00435,"percentile":0.62062,"date":"2025-06-03"}],"fix":{"versions":["78.1.1"],"state":"fixed"},"advisories":[],"risk":0.32625},"relatedVulnerabilities":[{"id":"CVE-2025-47273","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2025-47273","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pypa/setuptools/blob/6ead555c5fb29bc57fe6105b1bffc163f56fd558/setuptools/package_index.py#L810C1-L825C88","https://github.com/pypa/setuptools/commit/250a6d17978f9f6ac3ac887091f2d32886fbbb0b","https://github.com/pypa/setuptools/issues/4946","https://github.com/pypa/setuptools/security/advisories/GHSA-5rjg-fvgr-3xxf","https://lists.debian.org/debian-lts-announce/2025/05/msg00035.html","https://github.com/pypa/setuptools/issues/4946"],"description":"setuptools is a package that allows users to download, build, install, upgrade, and uninstall Python packages. A path traversal vulnerability in `PackageIndex` is present in setuptools prior to version 78.1.1. An attacker would be allowed to write files to arbitrary locations on the filesystem with the permissions of the process running the Python code, which could escalate to remote code execution depending on the context. Version 78.1.1 fixes the issue.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:H/VA:N/SC:N/SI:N/SA:N/E:P/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":7.7},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2025-47273","epss":0.00435,"percentile":0.62062,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"setuptools","version":"69.0.3"}},"found":{"versionConstraint":"<78.1.1 (python)","vulnerabilityID":"GHSA-5rjg-fvgr-3xxf"},"fix":{"suggestedVersion":"78.1.1"}}],"artifact":{"id":"635b4d7029f8ed83","name":"setuptools","version":"69.0.3","type":"python","locations":[{"path":"/lib/python3.10/site-packages/setuptools-69.0.3.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/setuptools-69.0.3.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/setuptools-69.0.3.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/setuptools-69.0.3.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/setuptools-69.0.3.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/setuptools-69.0.3.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:setuptools:69.0.3:*:*:*:*:*:*:*"],"purl":"pkg:pypi/setuptools@69.0.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-jjg7-2v4v-x38h","dataSource":"https://github.com/advisories/GHSA-jjg7-2v4v-x38h","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Internationalized Domain Names in Applications (IDNA) vulnerable to denial of service from specially crafted inputs to idna.encode","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":6.2,"exploitabilityScore":2.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-3651","epss":0.00436,"percentile":0.62113,"date":"2025-06-03"}],"fix":{"versions":["3.7"],"state":"fixed"},"advisories":[],"risk":0.24416000000000004},"relatedVulnerabilities":[{"id":"CVE-2024-3651","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-3651","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/kjd/idna/commit/1d365e17e10d72d0b7876316fc7b9ca0eebdd38d","https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb","https://github.com/kjd/idna/commit/1d365e17e10d72d0b7876316fc7b9ca0eebdd38d","https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb"],"description":"A vulnerability was identified in the kjd/idna library, specifically within the `idna.encode()` function, affecting version 3.6. The issue arises from the function's handling of crafted input strings, which can lead to quadratic complexity and consequently, a denial of service condition. This vulnerability is triggered by a crafted input that causes the `idna.encode()` function to process the input with considerable computational load, significantly increasing the processing time in a quadratic manner relative to the input size.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security@huntr.dev","type":"Secondary","version":"3.0","vector":"CVSS:3.0/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":6.2,"exploitabilityScore":2.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-3651","epss":0.00436,"percentile":0.62113,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"idna","version":"3.6"}},"found":{"versionConstraint":"<3.7 (python)","vulnerabilityID":"GHSA-jjg7-2v4v-x38h"},"fix":{"suggestedVersion":"3.7"}}],"artifact":{"id":"a3cf6af32f8c4a0b","name":"idna","version":"3.6","type":"python","locations":[{"path":"/lib/python3.10/site-packages/idna-3.6.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/idna-3.6.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/idna-3.6.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/idna-3.6.dist-info/RECORD","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-3-Clause"],"cpes":["cpe:2.3:a:kim_davies_<kim+pypi_project:python-idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kim+pypi_project:python_idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kim+pypiproject:python-idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kim+pypiproject:python_idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kim+pypi_project:idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:kim-davies-<kim+pypi:python-idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:kim-davies-<kim+pypi:python_idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kim+pypi:python-idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kim+pypi:python_idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kim+pypiproject:idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:kim-davies-<kim+pypi:idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_<kim+pypi:idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:python-idna:python-idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:python-idna:python_idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:python_idna:python-idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:python_idna:python_idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:python:python-idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:python:python_idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:idna:python-idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:idna:python_idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:python-idna:idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:python_idna:idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:python:idna:3.6:*:*:*:*:*:*:*","cpe:2.3:a:idna:idna:3.6:*:*:*:*:*:*:*"],"purl":"pkg:pypi/idna@3.6","upstreams":[]}},{"vulnerability":{"id":"GHSA-5m98-qgg9-wh84","dataSource":"https://github.com/advisories/GHSA-5m98-qgg9-wh84","namespace":"github:language:python","severity":"High","urls":[],"description":"aiohttp vulnerable to Denial of Service when trying to parse malformed POST requests","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-30251","epss":0.00288,"percentile":0.52063,"date":"2025-06-03"}],"fix":{"versions":["3.9.4"],"state":"fixed"},"advisories":[],"risk":0.216},"relatedVulnerabilities":[{"id":"CVE-2024-30251","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-30251","namespace":"nvd:cpe","severity":"High","urls":["http://www.openwall.com/lists/oss-security/2024/05/02/4","https://github.com/aio-libs/aiohttp/commit/7eecdff163ccf029fbb1ddc9de4169d4aaeb6597","https://github.com/aio-libs/aiohttp/commit/cebe526b9c34dc3a3da9140409db63014bc4cf19","https://github.com/aio-libs/aiohttp/commit/f21c6f2ca512a026ce7f0f6c6311f62d6a638866","https://github.com/aio-libs/aiohttp/security/advisories/GHSA-5m98-qgg9-wh84","http://www.openwall.com/lists/oss-security/2024/05/02/4","https://github.com/aio-libs/aiohttp/commit/7eecdff163ccf029fbb1ddc9de4169d4aaeb6597","https://github.com/aio-libs/aiohttp/commit/cebe526b9c34dc3a3da9140409db63014bc4cf19","https://github.com/aio-libs/aiohttp/commit/f21c6f2ca512a026ce7f0f6c6311f62d6a638866","https://github.com/aio-libs/aiohttp/security/advisories/GHSA-5m98-qgg9-wh84"],"description":"aiohttp is an asynchronous HTTP client/server framework for asyncio and Python. In affected versions an attacker can send a specially crafted POST (multipart/form-data) request. When the aiohttp server processes it, the server will enter an infinite loop and be unable to process any further requests. An attacker can stop the application from serving requests after sending a single request. This issue has been addressed in version 3.9.4. Users are advised to upgrade. Users unable to upgrade may manually apply a patch to their systems. Please see the linked GHSA for instructions.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-30251","epss":0.00288,"percentile":0.52063,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"aiohttp","version":"3.9.3"}},"found":{"versionConstraint":"<3.9.4 (python)","vulnerabilityID":"GHSA-5m98-qgg9-wh84"},"fix":{"suggestedVersion":"3.9.4"}}],"artifact":{"id":"08d9dd729e10d23a","name":"aiohttp","version":"3.9.3","type":"python","locations":[{"path":"/lib/python3.10/site-packages/aiohttp-3.9.3.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/aiohttp-3.9.3.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/aiohttp-3.9.3.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/aiohttp-3.9.3.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/aiohttp-3.9.3.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/aiohttp-3.9.3.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache 2"],"cpes":["cpe:2.3:a:python-aiohttp:python-aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:python-aiohttp:python_aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:python-aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:python_aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:python-aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:python_aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:python-aiohttp:aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python-aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python_aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:python:aiohttp:3.9.3:*:*:*:*:*:*:*"],"purl":"pkg:pypi/aiohttp@3.9.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-cx63-2mw6-8hw5","dataSource":"https://github.com/advisories/GHSA-cx63-2mw6-8hw5","namespace":"github:language:python","severity":"High","urls":[],"description":"setuptools vulnerable to Command Injection via package URL","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.8,"exploitabilityScore":2.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-6345","epss":0.00227,"percentile":0.45699,"date":"2025-06-03"}],"fix":{"versions":["70.0.0"],"state":"fixed"},"advisories":[],"risk":0.185005},"relatedVulnerabilities":[{"id":"CVE-2024-6345","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-6345","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/pypa/setuptools/commit/88807c7062788254f654ea8c03427adc859321f0","https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5","https://github.com/pypa/setuptools/commit/88807c7062788254f654ea8c03427adc859321f0","https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5"],"description":"A vulnerability in the package_index module of pypa/setuptools versions up to 69.1.1 allows for remote code execution via its download functions. These functions, which are used to download packages from URLs provided by users or retrieved from package index servers, are susceptible to code injection. If these functions are exposed to user-controlled inputs, such as package URLs, they can execute arbitrary commands on the system. The issue is fixed in version 70.0.","cvss":[{"source":"security@huntr.dev","type":"Secondary","version":"3.0","vector":"CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H","metrics":{"baseScore":8.8,"exploitabilityScore":2.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-6345","epss":0.00227,"percentile":0.45699,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"setuptools","version":"69.0.3"}},"found":{"versionConstraint":"<70.0.0 (python)","vulnerabilityID":"GHSA-cx63-2mw6-8hw5"},"fix":{"suggestedVersion":"70.0.0"}}],"artifact":{"id":"635b4d7029f8ed83","name":"setuptools","version":"69.0.3","type":"python","locations":[{"path":"/lib/python3.10/site-packages/setuptools-69.0.3.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/setuptools-69.0.3.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/setuptools-69.0.3.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/setuptools-69.0.3.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/setuptools-69.0.3.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/setuptools-69.0.3.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:setuptools:69.0.3:*:*:*:*:*:*:*"],"purl":"pkg:pypi/setuptools@69.0.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-jwhx-xcg6-8xhj","dataSource":"https://github.com/advisories/GHSA-jwhx-xcg6-8xhj","namespace":"github:language:python","severity":"Medium","urls":[],"description":"In aiohttp, compressed files as symlinks are not protected from path traversal","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N","metrics":{"baseScore":4.8,"exploitabilityScore":2.3,"impactScore":2.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-42367","epss":0.00203,"percentile":0.4306,"date":"2025-06-03"}],"fix":{"versions":["3.10.2"],"state":"fixed"},"advisories":[],"risk":0.09947},"relatedVulnerabilities":[{"id":"CVE-2024-42367","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-42367","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/aio-libs/aiohttp/blob/e0ff5246e1d29b7710ab1a2bbc972b48169f1c05/aiohttp/web_fileresponse.py#L177","https://github.com/aio-libs/aiohttp/blob/e0ff5246e1d29b7710ab1a2bbc972b48169f1c05/aiohttp/web_urldispatcher.py#L674","https://github.com/aio-libs/aiohttp/commit/ce2e9758814527589b10759a20783fb03b98339f","https://github.com/aio-libs/aiohttp/pull/8653","https://github.com/aio-libs/aiohttp/security/advisories/GHSA-jwhx-xcg6-8xhj"],"description":"aiohttp is an asynchronous HTTP client/server framework for asyncio and Python. Prior to version 3.10.2, static routes which contain files with compressed variants (`.gz` or `.br` extension) are vulnerable to path traversal outside the root directory if those variants are symbolic links. The server protects static routes from path traversal outside the root directory when `follow_symlinks=False` (default).  It does this by resolving the requested URL to an absolute path and then checking that path relative to the root. However, these checks are not performed when looking for compressed variants in the `FileResponse` class, and symbolic links are then automatically followed when performing the `Path.stat()` and `Path.open()` to send the file. Version 3.10.2 contains a patch for the issue.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:N","metrics":{"baseScore":4.8,"exploitabilityScore":2.3,"impactScore":2.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-42367","epss":0.00203,"percentile":0.4306,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"aiohttp","version":"3.9.3"}},"found":{"versionConstraint":"<3.10.2 (python)","vulnerabilityID":"GHSA-jwhx-xcg6-8xhj"},"fix":{"suggestedVersion":"3.10.2"}}],"artifact":{"id":"08d9dd729e10d23a","name":"aiohttp","version":"3.9.3","type":"python","locations":[{"path":"/lib/python3.10/site-packages/aiohttp-3.9.3.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/aiohttp-3.9.3.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/aiohttp-3.9.3.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/aiohttp-3.9.3.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/aiohttp-3.9.3.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/aiohttp-3.9.3.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache 2"],"cpes":["cpe:2.3:a:python-aiohttp:python-aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:python-aiohttp:python_aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:python-aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:python_aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:python-aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:python_aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:python-aiohttp:aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python-aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python_aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:python:aiohttp:3.9.3:*:*:*:*:*:*:*"],"purl":"pkg:pypi/aiohttp@3.9.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-8495-4g3g-x7pr","dataSource":"https://github.com/advisories/GHSA-8495-4g3g-x7pr","namespace":"github:language:python","severity":"Medium","urls":[],"description":"aiohttp allows request smuggling due to incorrect parsing of chunk extensions","cvss":[],"epss":[{"cve":"CVE-2024-52304","epss":0.00153,"percentile":0.3721,"date":"2025-06-03"}],"fix":{"versions":["3.10.11"],"state":"fixed"},"advisories":[],"risk":0.0765},"relatedVulnerabilities":[{"id":"CVE-2024-52304","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-52304","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/aio-libs/aiohttp/commit/259edc369075de63e6f3a4eaade058c62af0df71","https://github.com/aio-libs/aiohttp/security/advisories/GHSA-8495-4g3g-x7pr"],"description":"aiohttp is an asynchronous HTTP client/server framework for asyncio and Python. Prior to version 3.10.11, the Python parser parses newlines in chunk extensions incorrectly which can lead to request smuggling vulnerabilities under certain conditions. If a pure Python version of aiohttp is installed (i.e. without the usual C extensions) or `AIOHTTP_NO_EXTENSIONS` is enabled, then an attacker may be able to execute a request smuggling attack to bypass certain firewalls or proxy protections. Version 3.10.11 fixes the issue.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"4.0","vector":"CVSS:4.0/AV:N/AC:L/AT:P/PR:N/UI:N/VC:N/VI:L/VA:N/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X","metrics":{"baseScore":6.3},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-52304","epss":0.00153,"percentile":0.3721,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"aiohttp","version":"3.9.3"}},"found":{"versionConstraint":"<=3.10.10 (python)","vulnerabilityID":"GHSA-8495-4g3g-x7pr"},"fix":{"suggestedVersion":"3.10.11"}}],"artifact":{"id":"08d9dd729e10d23a","name":"aiohttp","version":"3.9.3","type":"python","locations":[{"path":"/lib/python3.10/site-packages/aiohttp-3.9.3.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/aiohttp-3.9.3.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/aiohttp-3.9.3.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/aiohttp-3.9.3.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/aiohttp-3.9.3.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/aiohttp-3.9.3.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache 2"],"cpes":["cpe:2.3:a:python-aiohttp:python-aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:python-aiohttp:python_aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:python-aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:python_aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:python-aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:python_aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:python-aiohttp:aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python-aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python_aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:python:aiohttp:3.9.3:*:*:*:*:*:*:*"],"purl":"pkg:pypi/aiohttp@3.9.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-7gpw-8wmc-pm8g","dataSource":"https://github.com/advisories/GHSA-7gpw-8wmc-pm8g","namespace":"github:language:python","severity":"Medium","urls":[],"description":"aiohttp Cross-site Scripting vulnerability on index pages for static file handling","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N","metrics":{"baseScore":6.1,"exploitabilityScore":2.9,"impactScore":2.8},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-27306","epss":0.00132,"percentile":0.34199,"date":"2025-06-03"}],"fix":{"versions":["3.9.4"],"state":"fixed"},"advisories":[],"risk":0.07325999999999999},"relatedVulnerabilities":[{"id":"CVE-2024-27306","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-27306","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/aio-libs/aiohttp/commit/28335525d1eac015a7e7584137678cbb6ff19397","https://github.com/aio-libs/aiohttp/pull/8319","https://github.com/aio-libs/aiohttp/security/advisories/GHSA-7gpw-8wmc-pm8g","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/2EXRGTN2WG7VZLUZ7WOXU5GQJKCPPHKP/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NWEI6NIHZ3G7DURDZVMRK7ZEFC2BTD3U/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZIVBMPEY7WWOFMC3CWXFBRQPFECV4SW3/","https://github.com/aio-libs/aiohttp/commit/28335525d1eac015a7e7584137678cbb6ff19397","https://github.com/aio-libs/aiohttp/pull/8319","https://github.com/aio-libs/aiohttp/security/advisories/GHSA-7gpw-8wmc-pm8g","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/2EXRGTN2WG7VZLUZ7WOXU5GQJKCPPHKP/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NWEI6NIHZ3G7DURDZVMRK7ZEFC2BTD3U/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZIVBMPEY7WWOFMC3CWXFBRQPFECV4SW3/"],"description":"aiohttp is an asynchronous HTTP client/server framework for asyncio and Python. A XSS vulnerability exists on index pages for static file handling. This vulnerability is fixed in 3.9.4. We have always recommended using a reverse proxy server (e.g. nginx) for serving static files. Users following the recommendation are unaffected. Other users can disable `show_index` if unable to upgrade.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N","metrics":{"baseScore":6.1,"exploitabilityScore":2.9,"impactScore":2.8},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-27306","epss":0.00132,"percentile":0.34199,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"aiohttp","version":"3.9.3"}},"found":{"versionConstraint":"<3.9.4 (python)","vulnerabilityID":"GHSA-7gpw-8wmc-pm8g"},"fix":{"suggestedVersion":"3.9.4"}}],"artifact":{"id":"08d9dd729e10d23a","name":"aiohttp","version":"3.9.3","type":"python","locations":[{"path":"/lib/python3.10/site-packages/aiohttp-3.9.3.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/aiohttp-3.9.3.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/aiohttp-3.9.3.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/aiohttp-3.9.3.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/aiohttp-3.9.3.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/aiohttp-3.9.3.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache 2"],"cpes":["cpe:2.3:a:python-aiohttp:python-aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:python-aiohttp:python_aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:python-aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:python_aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:python-aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:python_aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:python-aiohttp:aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:python_aiohttp:aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python-aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:python:python_aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:aiohttp:aiohttp:3.9.3:*:*:*:*:*:*:*","cpe:2.3:a:python:aiohttp:3.9.3:*:*:*:*:*:*:*"],"purl":"pkg:pypi/aiohttp@3.9.3","upstreams":[]}},{"vulnerability":{"id":"GHSA-jfmj-5v4g-7637","dataSource":"https://github.com/advisories/GHSA-jfmj-5v4g-7637","namespace":"github:language:python","severity":"Medium","urls":[],"description":"zipp Denial of Service vulnerability","cvss":[{"type":"Secondary","version":"3.0","vector":"CVSS:3.0/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":6.2,"exploitabilityScore":2.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-5569","epss":0.00042,"percentile":0.12193,"date":"2025-06-03"}],"fix":{"versions":["3.19.1"],"state":"fixed"},"advisories":[],"risk":0.023520000000000003},"relatedVulnerabilities":[{"id":"CVE-2024-5569","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-5569","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/jaraco/zipp/commit/fd604bd34f0343472521a36da1fbd22e793e14fd","https://huntr.com/bounties/be898306-11f9-46b4-b28c-f4c4aa4ffbae","https://github.com/jaraco/zipp/commit/fd604bd34f0343472521a36da1fbd22e793e14fd","https://huntr.com/bounties/be898306-11f9-46b4-b28c-f4c4aa4ffbae"],"description":"A Denial of Service (DoS) vulnerability exists in the jaraco/zipp library, affecting all versions prior to 3.19.1. The vulnerability is triggered when processing a specially crafted zip file that leads to an infinite loop. This issue also impacts the zipfile module of CPython, as features from the third-party zipp library are later merged into CPython, and the affected code is identical in both projects. The infinite loop can be initiated through the use of functions affecting the `Path` module in both zipp and zipfile, such as `joinpath`, the overloaded division operator, and `iterdir`. Although the infinite loop is not resource exhaustive, it prevents the application from responding. The vulnerability was addressed in version 3.19.1 of jaraco/zipp.","cvss":[{"source":"security@huntr.dev","type":"Secondary","version":"3.0","vector":"CVSS:3.0/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":6.2,"exploitabilityScore":2.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-5569","epss":0.00042,"percentile":0.12193,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"zipp","version":"3.17.0"}},"found":{"versionConstraint":"<3.19.1 (python)","vulnerabilityID":"GHSA-jfmj-5v4g-7637"},"fix":{"suggestedVersion":"3.19.1"}}],"artifact":{"id":"3659620f55569583","name":"zipp","version":"3.17.0","type":"python","locations":[{"path":"/lib/python3.10/site-packages/zipp-3.17.0.dist-info/METADATA","accessPath":"/lib/python3.10/site-packages/zipp-3.17.0.dist-info/METADATA","annotations":{"evidence":"primary"}},{"path":"/lib/python3.10/site-packages/zipp-3.17.0.dist-info/RECORD","accessPath":"/lib/python3.10/site-packages/zipp-3.17.0.dist-info/RECORD","annotations":{"evidence":"supporting"}},{"path":"/lib/python3.10/site-packages/zipp-3.17.0.dist-info/top_level.txt","accessPath":"/lib/python3.10/site-packages/zipp-3.17.0.dist-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:jason_r__coombs_project:python-zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jason_r__coombs_project:python_zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jason_r__coombsproject:python-zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jason_r__coombsproject:python_zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jason_r__coombs_project:zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jason_r__coombs:python-zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jason_r__coombs:python_zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jason_r__coombsproject:zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jaraco_project:python-zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jaraco_project:python_zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jaracoproject:python-zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jaracoproject:python_zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:python-zipp:python-zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:python-zipp:python_zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:python_zipp:python-zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:python_zipp:python_zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jason_r__coombs:zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jaraco_project:zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jaraco:python-zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jaraco:python_zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jaracoproject:zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python-zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:python:python_zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:python-zipp:zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:python_zipp:zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:zipp:python-zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:zipp:python_zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:jaraco:zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:python:zipp:3.17.0:*:*:*:*:*:*:*","cpe:2.3:a:zipp:zipp:3.17.0:*:*:*:*:*:*:*"],"purl":"pkg:pypi/zipp@3.17.0","upstreams":[]}}],"source":{"type":"sbom-file","target":"theengs-gateway-syft.json"},"distro":{"name":"","version":"","idLike":null},"descriptor":{"name":"grype","version":"0.92.2","configuration":{"output":["json=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-06-04/theengs-gateway-grype.json","template=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-06-04/theengs-gateway-grype.html"],"file":"","pretty":false,"distro":"","add-cpes-if-none":false,"output-template-file":"../html.tmpl","check-for-app-update":true,"only-fixed":false,"only-notfixed":false,"ignore-wontfix":"","platform":"","search":{"scope":"squashed","unindexed-archives":false,"indexed-archives":true},"ignore":[{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"kernel-headers","version":"","language":"","type":"rpm","location":"","upstream-name":"kernel"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux(-.*)?-headers-.*","version":"","language":"","type":"deb","location":"","upstream-name":"linux.*"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux-libc-dev","version":"","language":"","type":"deb","location":"","upstream-name":"linux"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"}],"exclude":[],"externalSources":{"enable":false,"maven":{"searchUpstreamBySha1":true,"baseUrl":"https://search.maven.org/solrsearch/select","rateLimit":300000000}},"match":{"java":{"using-cpes":false},"jvm":{"using-cpes":true},"dotnet":{"using-cpes":false},"golang":{"using-cpes":false,"always-use-cpe-for-stdlib":true,"allow-main-module-pseudo-version-comparison":false},"javascript":{"using-cpes":false},"python":{"using-cpes":false},"ruby":{"using-cpes":false},"rust":{"using-cpes":false},"stock":{"using-cpes":true}},"fail-on-severity":"","registry":{"insecure-skip-tls-verify":false,"insecure-use-http":false,"auth":null,"ca-cert":""},"show-suppressed":false,"by-cve":false,"SortBy":{"sort-by":"risk"},"name":"","default-image-pull-source":"","vex-documents":[],"vex-add":[],"match-upstream-kernel-headers":false,"db":{"cache-dir":"/Users/alan/Library/Caches/grype/db","update-url":"https://grype.anchore.io/databases","ca-cert":"","auto-update":true,"validate-by-hash-on-start":true,"validate-age":true,"max-allowed-built-age":432000000000000,"require-update-check":false,"update-available-timeout":30000000000,"update-download-timeout":300000000000,"max-update-check-frequency":7200000000000},"exp":{},"dev":{"db":{"debug":false}}},"db":{"status":{"schemaVersion":"v6.0.2","from":"https://grype.anchore.io/databases/v6/vulnerability-db_v6.0.2_2025-06-04T01:32:23Z_1749035557.tar.zst?checksum=sha256%3A77238f4ffbc7cf72bf4dedabbb21a3d0dd3ade90fb5d9df7c4da2870f8d1a9b7","built":"2025-06-04T11:12:37Z","path":"/Users/alan/Library/Caches/grype/db/6/vulnerability.db","valid":true},"providers":{"alpine":{"captured":"2025-06-04T01:32:23Z","input":"xxh64:a6a065ece392f6d1"},"amazon":{"captured":"2025-06-04T01:32:32Z","input":"xxh64:b65d458d6858d72a"},"chainguard":{"captured":"2025-06-04T01:32:33Z","input":"xxh64:03c9c4d182d77791"},"debian":{"captured":"2025-06-04T01:32:49Z","input":"xxh64:169ceb8fbcb8d6f1"},"epss":{"captured":"2025-06-04T01:32:42Z","input":"xxh64:bf87c4c234d02346"},"github":{"captured":"2025-06-04T01:32:30Z","input":"xxh64:3dab0be50635e057"},"kev":{"captured":"2025-06-04T01:32:45Z","input":"xxh64:a934e75f468f4e09"},"mariner":{"captured":"2025-06-04T01:32:43Z","input":"xxh64:ac698752085c186f"},"nvd":{"captured":"2025-06-04T01:33:28Z","input":"xxh64:389887843a59d29c"},"oracle":{"captured":"2025-06-04T01:32:35Z","input":"xxh64:0b8aabcfb6505b62"},"rhel":{"captured":"2025-06-04T04:49:10Z","input":"xxh64:947d0caeb19e9ccc"},"sles":{"captured":"2025-06-04T01:32:34Z","input":"xxh64:1c50b1219296628a"},"ubuntu":{"captured":"2025-06-04T01:33:14Z","input":"xxh64:71e22d5c5bbe7d14"},"wolfi":{"captured":"2025-06-04T01:32:42Z","input":"xxh64:e68fca5a870c6769"}}},"timestamp":"2025-06-04T19:47:34.686866+01:00"}}
