{"matches":[{"vulnerability":{"id":"GHSA-x4qr-2fvf-3mr5","dataSource":"https://github.com/advisories/GHSA-x4qr-2fvf-3mr5","namespace":"github:language:python","severity":"High","urls":[],"description":"Vulnerable OpenSSL included in cryptography wheels","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:H","metrics":{"baseScore":7.4,"exploitabilityScore":2.3,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-0286","epss":0.8576,"percentile":0.99335,"date":"2025-06-03"}],"fix":{"versions":["39.0.1"],"state":"fixed"},"advisories":[],"risk":63.891200000000005},"relatedVulnerabilities":[{"id":"CVE-2023-0286","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-0286","namespace":"nvd:cpe","severity":"High","urls":["https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.6.2-relnotes.txt","https://ftp.openbsd.org/pub/OpenBSD/patches/7.2/common/018_x509.patch.sig","https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=2c6c9d439b484e1ba9830d8454a34fa4f80fdfe9","https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=2f7530077e0ef79d98718138716bc51ca0cad658","https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=fd2af07dc083a350c959147097003a14a5e8ac4d","https://security.gentoo.org/glsa/202402-08","https://www.openssl.org/news/secadv/20230207.txt","https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.6.2-relnotes.txt","https://ftp.openbsd.org/pub/OpenBSD/patches/7.2/common/018_x509.patch.sig","https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=2c6c9d439b484e1ba9830d8454a34fa4f80fdfe9","https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=2f7530077e0ef79d98718138716bc51ca0cad658","https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=fd2af07dc083a350c959147097003a14a5e8ac4d","https://security.gentoo.org/glsa/202402-08","https://www.openssl.org/news/secadv/20230207.txt"],"description":"There is a type confusion vulnerability relating to X.400 address processing\ninside an X.509 GeneralName. X.400 addresses were parsed as an ASN1_STRING but\nthe public structure definition for GENERAL_NAME incorrectly specified the type\nof the x400Address field as ASN1_TYPE. This field is subsequently interpreted by\nthe OpenSSL function GENERAL_NAME_cmp as an ASN1_TYPE rather than an\nASN1_STRING.\n\nWhen CRL checking is enabled (i.e. the application sets the\nX509_V_FLAG_CRL_CHECK flag), this vulnerability may allow an attacker to pass\narbitrary pointers to a memcmp call, enabling them to read memory contents or\nenact a denial of service. In most cases, the attack requires the attacker to\nprovide both the certificate chain and CRL, neither of which need to have a\nvalid signature. If the attacker only controls one of these inputs, the other\ninput must already contain an X.400 address as a CRL distribution point, which\nis uncommon. As such, this vulnerability is most likely to only affect\napplications which have implemented their own functionality for retrieving CRLs\nover a network.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:H","metrics":{"baseScore":7.4,"exploitabilityScore":2.3,"impactScore":5.2},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:H","metrics":{"baseScore":7.4,"exploitabilityScore":2.3,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-0286","epss":0.8576,"percentile":0.99335,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"2.1.4"}},"found":{"versionConstraint":">=0.8.1,<39.0.1 (python)","vulnerabilityID":"GHSA-x4qr-2fvf-3mr5"},"fix":{"suggestedVersion":"39.0.1"}}],"artifact":{"id":"b914b2bfe04438ce","name":"cryptography","version":"2.1.4","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/cryptography-2.1.4.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/cryptography-2.1.4.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/cryptography-2.1.4.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/cryptography-2.1.4.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD or Apache License, Version 2.0"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:2.1.4:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:2.1.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@2.1.4","upstreams":[]}},{"vulnerability":{"id":"GHSA-j8r2-6x86-q33q","dataSource":"https://github.com/advisories/GHSA-j8r2-6x86-q33q","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Unintended leak of Proxy-Authorization header in requests","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N","metrics":{"baseScore":6.1,"exploitabilityScore":1.7,"impactScore":4},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-32681","epss":0.04731,"percentile":0.88915,"date":"2025-06-03"}],"fix":{"versions":["2.31.0"],"state":"fixed"},"advisories":[],"risk":2.6257049999999995},"relatedVulnerabilities":[{"id":"CVE-2023-32681","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-32681","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/psf/requests/commit/74ea7cf7a6a27a4eeb2ae24e162bcc942a6706d5","https://github.com/psf/requests/releases/tag/v2.31.0","https://github.com/psf/requests/security/advisories/GHSA-j8r2-6x86-q33q","https://lists.debian.org/debian-lts-announce/2023/06/msg00018.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AW7HNFGYP44RT3DUDQXG2QT3OEV2PJ7Y/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KOYASTZDGQG2BWLSNBPL3TQRL2G7QYNZ/","https://security.gentoo.org/glsa/202309-08","https://github.com/psf/requests/commit/74ea7cf7a6a27a4eeb2ae24e162bcc942a6706d5","https://github.com/psf/requests/releases/tag/v2.31.0","https://github.com/psf/requests/security/advisories/GHSA-j8r2-6x86-q33q","https://lists.debian.org/debian-lts-announce/2023/06/msg00018.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AW7HNFGYP44RT3DUDQXG2QT3OEV2PJ7Y/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KOYASTZDGQG2BWLSNBPL3TQRL2G7QYNZ/","https://security.gentoo.org/glsa/202309-08"],"description":"Requests is a HTTP library. Since Requests 2.3.0, Requests has been leaking Proxy-Authorization headers to destination servers when redirected to an HTTPS endpoint. This is a product of how we use `rebuild_proxies` to reattach the `Proxy-Authorization` header to requests. For HTTP connections sent through the tunnel, the proxy will identify the header in the request itself and remove it prior to forwarding to the destination server. However when sent over HTTPS, the `Proxy-Authorization` header must be sent in the CONNECT request as the proxy has no visibility into the tunneled request. This results in Requests forwarding proxy credentials to the destination server unintentionally, allowing a malicious actor to potentially exfiltrate sensitive information. This issue has been patched in version 2.31.0.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N","metrics":{"baseScore":6.1,"exploitabilityScore":1.7,"impactScore":4},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N","metrics":{"baseScore":6.1,"exploitabilityScore":1.7,"impactScore":4},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-32681","epss":0.04731,"percentile":0.88915,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"requests","version":"2.18.4"}},"found":{"versionConstraint":">=2.3.0,<2.31.0 (python)","vulnerabilityID":"GHSA-j8r2-6x86-q33q"},"fix":{"suggestedVersion":"2.31.0"}}],"artifact":{"id":"88c53a79c1f81c0c","name":"requests","version":"2.18.4","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/requests-2.18.4.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/requests-2.18.4.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/requests-2.18.4.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/requests-2.18.4.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache 2.0"],"cpes":["cpe:2.3:a:python:requests:2.18.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/requests@2.18.4","upstreams":[]}},{"vulnerability":{"id":"GHSA-gg84-qgv9-w4pq","dataSource":"https://github.com/advisories/GHSA-gg84-qgv9-w4pq","namespace":"github:language:python","severity":"Medium","urls":[],"description":"CRLF injection in httplib2","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:N/I:H/A:N","metrics":{"baseScore":6.8,"exploitabilityScore":2.3,"impactScore":4},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2020-11078","epss":0.03194,"percentile":0.86427,"date":"2025-06-03"}],"fix":{"versions":["0.18.0"],"state":"fixed"},"advisories":[],"risk":1.88446},"relatedVulnerabilities":[{"id":"CVE-2020-11078","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2020-11078","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/httplib2/httplib2/commit/a1457cc31f3206cf691d11d2bf34e98865873e9e","https://github.com/httplib2/httplib2/security/advisories/GHSA-gg84-qgv9-w4pq","https://lists.apache.org/thread.html/r23711190c2e98152cb6f216b95090d5eeb978543bb7e0bad22ce47fc%40%3Cissues.beam.apache.org%3E","https://lists.apache.org/thread.html/r4d35dac106fab979f0db75a07fc4e320ad848b722103e79667ff99e1%40%3Cissues.beam.apache.org%3E","https://lists.apache.org/thread.html/r69a462e690b5f2c3d418a288a2c98ae764d58587bd0b5d6ab141f25f%40%3Cissues.beam.apache.org%3E","https://lists.apache.org/thread.html/r7f364000066748299b331b615ba51c62f55ab5b201ddce9a22d98202%40%3Cissues.beam.apache.org%3E","https://lists.apache.org/thread.html/rad8872fc99f670958c2774e2bf84ee32a3a0562a0c787465cf3dfa23%40%3Cissues.beam.apache.org%3E","https://lists.apache.org/thread.html/rc9eff9572946142b657c900fe63ea4bbd3535911e8d4ce4d08fe4b89%40%3Ccommits.allura.apache.org%3E","https://lists.debian.org/debian-lts-announce/2020/06/msg00000.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/IXCX2AWROGWGY5GXR7VN3BKF34A2FO6J/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PZJ3D6JSM7CFZESZZKGUW2VX55BOSOXI/","https://github.com/httplib2/httplib2/commit/a1457cc31f3206cf691d11d2bf34e98865873e9e","https://github.com/httplib2/httplib2/security/advisories/GHSA-gg84-qgv9-w4pq","https://lists.apache.org/thread.html/r23711190c2e98152cb6f216b95090d5eeb978543bb7e0bad22ce47fc%40%3Cissues.beam.apache.org%3E","https://lists.apache.org/thread.html/r4d35dac106fab979f0db75a07fc4e320ad848b722103e79667ff99e1%40%3Cissues.beam.apache.org%3E","https://lists.apache.org/thread.html/r69a462e690b5f2c3d418a288a2c98ae764d58587bd0b5d6ab141f25f%40%3Cissues.beam.apache.org%3E","https://lists.apache.org/thread.html/r7f364000066748299b331b615ba51c62f55ab5b201ddce9a22d98202%40%3Cissues.beam.apache.org%3E","https://lists.apache.org/thread.html/rad8872fc99f670958c2774e2bf84ee32a3a0562a0c787465cf3dfa23%40%3Cissues.beam.apache.org%3E","https://lists.apache.org/thread.html/rc9eff9572946142b657c900fe63ea4bbd3535911e8d4ce4d08fe4b89%40%3Ccommits.allura.apache.org%3E","https://lists.debian.org/debian-lts-announce/2020/06/msg00000.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/IXCX2AWROGWGY5GXR7VN3BKF34A2FO6J/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PZJ3D6JSM7CFZESZZKGUW2VX55BOSOXI/"],"description":"In httplib2 before version 0.18.0, an attacker controlling unescaped part of uri for `httplib2.Http.request()` could change request headers and body, send additional hidden requests to same server. This vulnerability impacts software that uses httplib2 with uri constructed by string concatenation, as opposed to proper urllib building with escaping. This has been fixed in 0.18.0.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:N/I:H/A:N","metrics":{"baseScore":6.8,"exploitabilityScore":2.3,"impactScore":4},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:M/Au:N/C:N/I:P/A:N","metrics":{"baseScore":4.3,"exploitabilityScore":8.6,"impactScore":2.9},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:N/I:H/A:N","metrics":{"baseScore":6.8,"exploitabilityScore":2.3,"impactScore":4},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2020-11078","epss":0.03194,"percentile":0.86427,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"httplib2","version":"0.9.2"}},"found":{"versionConstraint":"<0.18.0 (python)","vulnerabilityID":"GHSA-gg84-qgv9-w4pq"},"fix":{"suggestedVersion":"0.18.0"}}],"artifact":{"id":"fdc5582e911c4a35","name":"httplib2","version":"0.9.2","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/httplib2-0.9.2.egg-info","accessPath":"/usr/lib/python3/dist-packages/httplib2-0.9.2.egg-info","annotations":{"evidence":"primary"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:httplib2_project:httplib2:0.9.2:*:*:*:*:python:*:*","cpe:2.3:a:httplib2_project:httplib2:0.9.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/httplib2@0.9.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-mh33-7rrq-662w","dataSource":"https://github.com/advisories/GHSA-mh33-7rrq-662w","namespace":"github:language:python","severity":"High","urls":[],"description":"Improper Certificate Validation in urllib3","cvss":[{"type":"Secondary","version":"3.0","vector":"CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2019-11324","epss":0.01379,"percentile":0.79393,"date":"2025-06-03"}],"fix":{"versions":["1.24.2"],"state":"fixed"},"advisories":[],"risk":1.0342500000000001},"relatedVulnerabilities":[{"id":"CVE-2019-11324","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2019-11324","namespace":"nvd:cpe","severity":"High","urls":["http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00039.html","http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00041.html","http://www.openwall.com/lists/oss-security/2019/04/19/1","https://access.redhat.com/errata/RHSA-2019:3335","https://access.redhat.com/errata/RHSA-2019:3590","https://github.com/urllib3/urllib3/compare/a6ec68a...1efadf4","https://lists.debian.org/debian-lts-announce/2021/06/msg00015.html","https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NKGPJLVLVYCL4L4B4G5TIOTVK4BKPG72/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/XOSA2NT4DUQDBEIWE6O7KKD24XND7TE2/","https://usn.ubuntu.com/3990-1/","http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00039.html","http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00041.html","http://www.openwall.com/lists/oss-security/2019/04/19/1","https://access.redhat.com/errata/RHSA-2019:3335","https://access.redhat.com/errata/RHSA-2019:3590","https://github.com/urllib3/urllib3/compare/a6ec68a...1efadf4","https://lists.debian.org/debian-lts-announce/2021/06/msg00015.html","https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NKGPJLVLVYCL4L4B4G5TIOTVK4BKPG72/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/XOSA2NT4DUQDBEIWE6O7KKD24XND7TE2/","https://usn.ubuntu.com/3990-1/"],"description":"The urllib3 library before 1.24.2 for Python mishandles certain cases where the desired set of CA certificates is different from the OS store of CA certificates, which results in SSL connections succeeding in situations where a verification failure is the correct outcome. This is related to use of the ssl_context, ca_certs, or ca_certs_dir argument.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.0","vector":"CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:L/Au:N/C:N/I:P/A:N","metrics":{"baseScore":5,"exploitabilityScore":10,"impactScore":2.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2019-11324","epss":0.01379,"percentile":0.79393,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"urllib3","version":"1.22"}},"found":{"versionConstraint":"<1.24.2 (python)","vulnerabilityID":"GHSA-mh33-7rrq-662w"},"fix":{"suggestedVersion":"1.24.2"}}],"artifact":{"id":"9e592efbeaf63d3d","name":"urllib3","version":"1.22","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/urllib3-1.22.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/urllib3-1.22.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/urllib3-1.22.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/urllib3-1.22.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:urllib3:1.22:*:*:*:*:*:*:*"],"purl":"pkg:pypi/urllib3@1.22","upstreams":[]}},{"vulnerability":{"id":"GHSA-93xj-8mrv-444m","dataSource":"https://github.com/advisories/GHSA-93xj-8mrv-444m","namespace":"github:language:python","severity":"High","urls":[],"description":"Regular Expression Denial of Service (REDoS) in httplib2","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-21240","epss":0.01371,"percentile":0.79345,"date":"2025-06-03"}],"fix":{"versions":["0.19.0"],"state":"fixed"},"advisories":[],"risk":1.0282499999999999},"relatedVulnerabilities":[{"id":"CVE-2021-21240","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2021-21240","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/httplib2/httplib2/commit/bd9ee252c8f099608019709e22c0d705e98d26bc","https://github.com/httplib2/httplib2/pull/182","https://github.com/httplib2/httplib2/security/advisories/GHSA-93xj-8mrv-444m","https://pypi.org/project/httplib2","https://github.com/httplib2/httplib2/commit/bd9ee252c8f099608019709e22c0d705e98d26bc","https://github.com/httplib2/httplib2/pull/182","https://github.com/httplib2/httplib2/security/advisories/GHSA-93xj-8mrv-444m","https://pypi.org/project/httplib2"],"description":"httplib2 is a comprehensive HTTP client library for Python. In httplib2 before version 0.19.0, a malicious server which responds with long series of \"\\xa0\" characters in the \"www-authenticate\" header may cause Denial of Service (CPU burn while parsing header) of the httplib2 client accessing said server. This is fixed in version 0.19.0 which contains a new implementation of auth headers parsing using the pyparsing library.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:L/Au:N/C:N/I:N/A:P","metrics":{"baseScore":5,"exploitabilityScore":10,"impactScore":2.9},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2021-21240","epss":0.01371,"percentile":0.79345,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"httplib2","version":"0.9.2"}},"found":{"versionConstraint":"<0.19.0 (python)","vulnerabilityID":"GHSA-93xj-8mrv-444m"},"fix":{"suggestedVersion":"0.19.0"}}],"artifact":{"id":"fdc5582e911c4a35","name":"httplib2","version":"0.9.2","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/httplib2-0.9.2.egg-info","accessPath":"/usr/lib/python3/dist-packages/httplib2-0.9.2.egg-info","annotations":{"evidence":"primary"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:httplib2_project:httplib2:0.9.2:*:*:*:*:python:*:*","cpe:2.3:a:httplib2_project:httplib2:0.9.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/httplib2@0.9.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-www2-v7xj-xrc6","dataSource":"https://github.com/advisories/GHSA-www2-v7xj-xrc6","namespace":"github:language:python","severity":"Critical","urls":[],"description":"Exposure of Sensitive Information to an Unauthorized Actor in urllib3","cvss":[{"type":"Secondary","version":"3.0","vector":"CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":9.8,"exploitabilityScore":3.9,"impactScore":5.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2018-20060","epss":0.00949,"percentile":0.75315,"date":"2025-06-03"}],"fix":{"versions":["1.23"],"state":"fixed"},"advisories":[],"risk":0.8920600000000001},"relatedVulnerabilities":[{"id":"CVE-2018-20060","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2018-20060","namespace":"nvd:cpe","severity":"Critical","urls":["http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00039.html","https://access.redhat.com/errata/RHSA-2019:2272","https://bugzilla.redhat.com/show_bug.cgi?id=1649153","https://github.com/urllib3/urllib3/blob/master/CHANGES.rst","https://github.com/urllib3/urllib3/issues/1316","https://github.com/urllib3/urllib3/pull/1346","https://lists.debian.org/debian-lts-announce/2021/06/msg00015.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/5SJERZEJDSUYQP7BNBXMBHRHGY26HRZD/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/BXLAXHM3Z6DUCXZ7ZXZ2EAYJXWDCZFCT/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/XWP36YW3KSVLXDBY3QJKDYEPCIMN3VQZ/","https://usn.ubuntu.com/3990-1/","http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00039.html","https://access.redhat.com/errata/RHSA-2019:2272","https://bugzilla.redhat.com/show_bug.cgi?id=1649153","https://github.com/urllib3/urllib3/blob/master/CHANGES.rst","https://github.com/urllib3/urllib3/issues/1316","https://github.com/urllib3/urllib3/pull/1346","https://lists.debian.org/debian-lts-announce/2021/06/msg00015.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/5SJERZEJDSUYQP7BNBXMBHRHGY26HRZD/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/BXLAXHM3Z6DUCXZ7ZXZ2EAYJXWDCZFCT/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/XWP36YW3KSVLXDBY3QJKDYEPCIMN3VQZ/","https://security.netapp.com/advisory/ntap-20241227-0010/","https://usn.ubuntu.com/3990-1/"],"description":"urllib3 before version 1.23 does not remove the Authorization HTTP header when following a cross-origin redirect (i.e., a redirect that differs in host, port, or scheme). This can allow for credentials in the Authorization header to be exposed to unintended hosts or transmitted in cleartext.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.0","vector":"CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":9.8,"exploitabilityScore":3.9,"impactScore":5.9},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:L/Au:N/C:P/I:N/A:N","metrics":{"baseScore":5,"exploitabilityScore":10,"impactScore":2.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2018-20060","epss":0.00949,"percentile":0.75315,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"urllib3","version":"1.22"}},"found":{"versionConstraint":"<1.23 (python)","vulnerabilityID":"GHSA-www2-v7xj-xrc6"},"fix":{"suggestedVersion":"1.23"}}],"artifact":{"id":"9e592efbeaf63d3d","name":"urllib3","version":"1.22","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/urllib3-1.22.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/urllib3-1.22.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/urllib3-1.22.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/urllib3-1.22.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:urllib3:1.22:*:*:*:*:*:*:*"],"purl":"pkg:pypi/urllib3@1.22","upstreams":[]}},{"vulnerability":{"id":"GHSA-3ww4-gg4f-jr7f","dataSource":"https://github.com/advisories/GHSA-3ww4-gg4f-jr7f","namespace":"github:language:python","severity":"High","urls":[],"description":"Python Cryptography package vulnerable to Bleichenbacher timing oracle attack","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-50782","epss":0.00521,"percentile":0.6593,"date":"2025-06-03"}],"fix":{"versions":["42.0.0"],"state":"fixed"},"advisories":[],"risk":0.39075000000000004},"relatedVulnerabilities":[{"id":"CVE-2023-50782","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-50782","namespace":"nvd:cpe","severity":"High","urls":["https://access.redhat.com/security/cve/CVE-2023-50782","https://bugzilla.redhat.com/show_bug.cgi?id=2254432","https://access.redhat.com/security/cve/CVE-2023-50782","https://bugzilla.redhat.com/show_bug.cgi?id=2254432","https://www.couchbase.com/alerts/"],"description":"A flaw was found in the python-cryptography package. This issue may allow a remote attacker to decrypt captured messages in TLS servers that use RSA key exchanges, which may lead to exposure of confidential or sensitive data.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"secalert@redhat.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-50782","epss":0.00521,"percentile":0.6593,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"2.1.4"}},"found":{"versionConstraint":"<42.0.0 (python)","vulnerabilityID":"GHSA-3ww4-gg4f-jr7f"},"fix":{"suggestedVersion":"42.0.0"}}],"artifact":{"id":"b914b2bfe04438ce","name":"cryptography","version":"2.1.4","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/cryptography-2.1.4.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/cryptography-2.1.4.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/cryptography-2.1.4.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/cryptography-2.1.4.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD or Apache License, Version 2.0"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:2.1.4:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:2.1.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@2.1.4","upstreams":[]}},{"vulnerability":{"id":"GHSA-v845-jxx5-vc9f","dataSource":"https://github.com/advisories/GHSA-v845-jxx5-vc9f","namespace":"github:language:python","severity":"High","urls":[],"description":"`Cookie` HTTP header isn't stripped on cross-origin redirects","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:H/A:N","metrics":{"baseScore":5.9,"exploitabilityScore":0.8,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-43804","epss":0.00554,"percentile":0.67072,"date":"2025-06-03"}],"fix":{"versions":["1.26.17"],"state":"fixed"},"advisories":[],"risk":0.37118},"relatedVulnerabilities":[{"id":"CVE-2023-43804","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-43804","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/urllib3/urllib3/commit/01220354d389cd05474713f8c982d05c9b17aafb","https://github.com/urllib3/urllib3/commit/644124ecd0b6e417c527191f866daa05a5a2056d","https://github.com/urllib3/urllib3/security/advisories/GHSA-v845-jxx5-vc9f","https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/I3PR7C6RJ6JUBQKIJ644DMIJSUP36VDY/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NDAGZXYJ7H2G3SB47M453VQVNAWKAEJJ/","https://github.com/urllib3/urllib3/commit/01220354d389cd05474713f8c982d05c9b17aafb","https://github.com/urllib3/urllib3/commit/644124ecd0b6e417c527191f866daa05a5a2056d","https://github.com/urllib3/urllib3/security/advisories/GHSA-v845-jxx5-vc9f","https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/I3PR7C6RJ6JUBQKIJ644DMIJSUP36VDY/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NDAGZXYJ7H2G3SB47M453VQVNAWKAEJJ/","https://security.netapp.com/advisory/ntap-20241213-0007/","https://www.vicarius.io/vsociety/posts/cve-2023-43804-urllib3-vulnerability-3"],"description":"urllib3 is a user-friendly HTTP client library for Python. urllib3 doesn't treat the `Cookie` HTTP header special or provide any helpers for managing cookies over HTTP, that is the responsibility of the user. However, it is possible for a user to specify a `Cookie` header and unknowingly leak information via HTTP redirects to a different origin if that user doesn't disable redirects explicitly. This issue has been patched in urllib3 version 1.26.17 or 2.0.5.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N","metrics":{"baseScore":8.1,"exploitabilityScore":2.9,"impactScore":5.2},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:H/A:N","metrics":{"baseScore":5.9,"exploitabilityScore":0.8,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-43804","epss":0.00554,"percentile":0.67072,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"urllib3","version":"1.22"}},"found":{"versionConstraint":"<1.26.17 (python)","vulnerabilityID":"GHSA-v845-jxx5-vc9f"},"fix":{"suggestedVersion":"1.26.17"}}],"artifact":{"id":"9e592efbeaf63d3d","name":"urllib3","version":"1.22","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/urllib3-1.22.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/urllib3-1.22.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/urllib3-1.22.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/urllib3-1.22.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:urllib3:1.22:*:*:*:*:*:*:*"],"purl":"pkg:pypi/urllib3@1.22","upstreams":[]}},{"vulnerability":{"id":"GHSA-r64q-w8jr-g9qp","dataSource":"https://github.com/advisories/GHSA-r64q-w8jr-g9qp","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Improper Neutralization of CRLF Sequences in urllib3 library for Python","cvss":[{"type":"Secondary","version":"3.0","vector":"CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N","metrics":{"baseScore":6.1,"exploitabilityScore":2.9,"impactScore":2.8},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2019-11236","epss":0.00636,"percentile":0.69467,"date":"2025-06-03"}],"fix":{"versions":["1.24.3"],"state":"fixed"},"advisories":[],"risk":0.35297999999999996},"relatedVulnerabilities":[{"id":"CVE-2019-11236","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2019-11236","namespace":"nvd:cpe","severity":"Medium","urls":["http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00039.html","http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00041.html","https://access.redhat.com/errata/RHSA-2019:2272","https://access.redhat.com/errata/RHSA-2019:3335","https://access.redhat.com/errata/RHSA-2019:3590","https://github.com/urllib3/urllib3/issues/1553","https://lists.debian.org/debian-lts-announce/2019/06/msg00016.html","https://lists.debian.org/debian-lts-announce/2021/06/msg00015.html","https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NKGPJLVLVYCL4L4B4G5TIOTVK4BKPG72/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/R62XGEYPUTXMRHGX5I37EBCGQ5COHGKR/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/TBI45HO533KYHNB5YRO43TBYKA3E3VRL/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/XOSA2NT4DUQDBEIWE6O7KKD24XND7TE2/","https://usn.ubuntu.com/3990-1/","https://usn.ubuntu.com/3990-2/","http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00039.html","http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00041.html","https://access.redhat.com/errata/RHSA-2019:2272","https://access.redhat.com/errata/RHSA-2019:3335","https://access.redhat.com/errata/RHSA-2019:3590","https://github.com/urllib3/urllib3/issues/1553","https://lists.debian.org/debian-lts-announce/2019/06/msg00016.html","https://lists.debian.org/debian-lts-announce/2021/06/msg00015.html","https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NKGPJLVLVYCL4L4B4G5TIOTVK4BKPG72/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/R62XGEYPUTXMRHGX5I37EBCGQ5COHGKR/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/TBI45HO533KYHNB5YRO43TBYKA3E3VRL/","https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/XOSA2NT4DUQDBEIWE6O7KKD24XND7TE2/","https://usn.ubuntu.com/3990-1/","https://usn.ubuntu.com/3990-2/"],"description":"In the urllib3 library through 1.24.1 for Python, CRLF injection is possible if the attacker controls the request parameter.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.0","vector":"CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N","metrics":{"baseScore":6.1,"exploitabilityScore":2.9,"impactScore":2.8},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:M/Au:N/C:N/I:P/A:N","metrics":{"baseScore":4.3,"exploitabilityScore":8.6,"impactScore":2.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2019-11236","epss":0.00636,"percentile":0.69467,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"urllib3","version":"1.22"}},"found":{"versionConstraint":"<=1.24.2 (python)","vulnerabilityID":"GHSA-r64q-w8jr-g9qp"},"fix":{"suggestedVersion":"1.24.3"}}],"artifact":{"id":"9e592efbeaf63d3d","name":"urllib3","version":"1.22","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/urllib3-1.22.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/urllib3-1.22.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/urllib3-1.22.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/urllib3-1.22.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:urllib3:1.22:*:*:*:*:*:*:*"],"purl":"pkg:pypi/urllib3@1.22","upstreams":[]}},{"vulnerability":{"id":"GHSA-q48q-77qv-cf9p","dataSource":"https://github.com/advisories/GHSA-q48q-77qv-cf9p","namespace":"github:language:python","severity":"Medium","urls":[],"description":"httplib2 incorrectly checks SSL certificate","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2013-2037","epss":0.00492,"percentile":0.64665,"date":"2025-06-03"}],"fix":{"versions":["0.10.1"],"state":"fixed"},"advisories":[],"risk":0.3075},"relatedVulnerabilities":[{"id":"CVE-2013-2037","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2013-2037","namespace":"nvd:cpe","severity":"Low","urls":["http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=706602","http://code.google.com/p/httplib2/issues/detail?id=282","http://seclists.org/oss-sec/2013/q2/257","http://www.securityfocus.com/bid/52179","http://www.ubuntu.com/usn/USN-1948-1","https://bugs.launchpad.net/httplib2/+bug/1175272","http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=706602","http://code.google.com/p/httplib2/issues/detail?id=282","http://seclists.org/oss-sec/2013/q2/257","http://www.securityfocus.com/bid/52179","http://www.ubuntu.com/usn/USN-1948-1","https://bugs.launchpad.net/httplib2/+bug/1175272"],"description":"httplib2 0.7.2, 0.8, and earlier, after an initial connection is made, does not verify that the server hostname matches a domain name in the subject's Common Name (CN) or subjectAltName field of the X.509 certificate, which allows man-in-the-middle attackers to spoof SSL servers via an arbitrary valid certificate.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:H/Au:N/C:N/I:P/A:N","metrics":{"baseScore":2.6,"exploitabilityScore":5,"impactScore":2.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2013-2037","epss":0.00492,"percentile":0.64665,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"httplib2","version":"0.9.2"}},"found":{"versionConstraint":"<0.10.1 (python)","vulnerabilityID":"GHSA-q48q-77qv-cf9p"},"fix":{"suggestedVersion":"0.10.1"}}],"artifact":{"id":"fdc5582e911c4a35","name":"httplib2","version":"0.9.2","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/httplib2-0.9.2.egg-info","accessPath":"/usr/lib/python3/dist-packages/httplib2-0.9.2.egg-info","annotations":{"evidence":"primary"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:httplib2_project:httplib2:0.9.2:*:*:*:*:python:*:*","cpe:2.3:a:httplib2_project:httplib2:0.9.2:*:*:*:*:*:*:*"],"purl":"pkg:pypi/httplib2@0.9.2","upstreams":[]}},{"vulnerability":{"id":"GHSA-fcf9-3qw3-gxmj","dataSource":"https://github.com/advisories/GHSA-fcf9-3qw3-gxmj","namespace":"github:language:python","severity":"High","urls":[],"description":"PyCA Cryptography vulnerable to GCM tag forgery","cvss":[{"type":"Secondary","version":"3.0","vector":"CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2018-10903","epss":0.00327,"percentile":0.55062,"date":"2025-06-03"}],"fix":{"versions":["2.3"],"state":"fixed"},"advisories":[],"risk":0.24524999999999997},"relatedVulnerabilities":[{"id":"CVE-2018-10903","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2018-10903","namespace":"nvd:cpe","severity":"High","urls":["https://access.redhat.com/errata/RHSA-2018:3600","https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10903","https://github.com/pyca/cryptography/pull/4342/commits/688e0f673bfbf43fa898994326c6877f00ab19ef","https://usn.ubuntu.com/3720-1/","https://access.redhat.com/errata/RHSA-2018:3600","https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10903","https://github.com/pyca/cryptography/pull/4342/commits/688e0f673bfbf43fa898994326c6877f00ab19ef","https://usn.ubuntu.com/3720-1/"],"description":"A flaw was found in python-cryptography versions between >=1.9.0 and <2.3. The finalize_with_tag API did not enforce a minimum tag length. If a user did not validate the input length prior to passing it to finalize_with_tag an attacker could craft an invalid payload with a shortened tag (e.g. 1 byte) such that they would have a 1 in 256 chance of passing the MAC check. GCM tag forgeries can cause key leakage.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.0","vector":"CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:L/Au:N/C:P/I:N/A:N","metrics":{"baseScore":5,"exploitabilityScore":10,"impactScore":2.9},"vendorMetadata":{}},{"source":"secalert@redhat.com","type":"Secondary","version":"3.0","vector":"CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2018-10903","epss":0.00327,"percentile":0.55062,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"2.1.4"}},"found":{"versionConstraint":">=1.9.0,<2.3 (python)","vulnerabilityID":"GHSA-fcf9-3qw3-gxmj"},"fix":{"suggestedVersion":"2.3"}}],"artifact":{"id":"b914b2bfe04438ce","name":"cryptography","version":"2.1.4","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/cryptography-2.1.4.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/cryptography-2.1.4.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/cryptography-2.1.4.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/cryptography-2.1.4.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD or Apache License, Version 2.0"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:2.1.4:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:2.1.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@2.1.4","upstreams":[]}},{"vulnerability":{"id":"GHSA-jjg7-2v4v-x38h","dataSource":"https://github.com/advisories/GHSA-jjg7-2v4v-x38h","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Internationalized Domain Names in Applications (IDNA) vulnerable to denial of service from specially crafted inputs to idna.encode","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":6.2,"exploitabilityScore":2.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-3651","epss":0.00436,"percentile":0.62113,"date":"2025-06-03"}],"fix":{"versions":["3.7"],"state":"fixed"},"advisories":[],"risk":0.24416000000000004},"relatedVulnerabilities":[{"id":"CVE-2024-3651","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-3651","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/kjd/idna/commit/1d365e17e10d72d0b7876316fc7b9ca0eebdd38d","https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb","https://github.com/kjd/idna/commit/1d365e17e10d72d0b7876316fc7b9ca0eebdd38d","https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb"],"description":"A vulnerability was identified in the kjd/idna library, specifically within the `idna.encode()` function, affecting version 3.6. The issue arises from the function's handling of crafted input strings, which can lead to quadratic complexity and consequently, a denial of service condition. This vulnerability is triggered by a crafted input that causes the `idna.encode()` function to process the input with considerable computational load, significantly increasing the processing time in a quadratic manner relative to the input size.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security@huntr.dev","type":"Secondary","version":"3.0","vector":"CVSS:3.0/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H","metrics":{"baseScore":6.2,"exploitabilityScore":2.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-3651","epss":0.00436,"percentile":0.62113,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"idna","version":"2.6"}},"found":{"versionConstraint":"<3.7 (python)","vulnerabilityID":"GHSA-jjg7-2v4v-x38h"},"fix":{"suggestedVersion":"3.7"}}],"artifact":{"id":"dcb686ce06ed2350","name":"idna","version":"2.6","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/idna-2.6.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/idna-2.6.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/idna-2.6.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/idna-2.6.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD-like"],"cpes":["cpe:2.3:a:kim_davies_project:python-idna:2.6:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_project:python_idna:2.6:*:*:*:*:*:*:*","cpe:2.3:a:kim_daviesproject:python-idna:2.6:*:*:*:*:*:*:*","cpe:2.3:a:kim_daviesproject:python_idna:2.6:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies_project:idna:2.6:*:*:*:*:*:*:*","cpe:2.3:a:kim_project:python-idna:2.6:*:*:*:*:*:*:*","cpe:2.3:a:kim_project:python_idna:2.6:*:*:*:*:*:*:*","cpe:2.3:a:python-idna:python-idna:2.6:*:*:*:*:*:*:*","cpe:2.3:a:python-idna:python_idna:2.6:*:*:*:*:*:*:*","cpe:2.3:a:python_idna:python-idna:2.6:*:*:*:*:*:*:*","cpe:2.3:a:python_idna:python_idna:2.6:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies:python-idna:2.6:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies:python_idna:2.6:*:*:*:*:*:*:*","cpe:2.3:a:kim_daviesproject:idna:2.6:*:*:*:*:*:*:*","cpe:2.3:a:kimproject:python-idna:2.6:*:*:*:*:*:*:*","cpe:2.3:a:kimproject:python_idna:2.6:*:*:*:*:*:*:*","cpe:2.3:a:python:python-idna:2.6:*:*:*:*:*:*:*","cpe:2.3:a:python:python_idna:2.6:*:*:*:*:*:*:*","cpe:2.3:a:idna:python-idna:2.6:*:*:*:*:*:*:*","cpe:2.3:a:idna:python_idna:2.6:*:*:*:*:*:*:*","cpe:2.3:a:kim_project:idna:2.6:*:*:*:*:*:*:*","cpe:2.3:a:python-idna:idna:2.6:*:*:*:*:*:*:*","cpe:2.3:a:python_idna:idna:2.6:*:*:*:*:*:*:*","cpe:2.3:a:kim:python-idna:2.6:*:*:*:*:*:*:*","cpe:2.3:a:kim:python_idna:2.6:*:*:*:*:*:*:*","cpe:2.3:a:kim_davies:idna:2.6:*:*:*:*:*:*:*","cpe:2.3:a:kimproject:idna:2.6:*:*:*:*:*:*:*","cpe:2.3:a:python:idna:2.6:*:*:*:*:*:*:*","cpe:2.3:a:idna:idna:2.6:*:*:*:*:*:*:*","cpe:2.3:a:kim:idna:2.6:*:*:*:*:*:*:*"],"purl":"pkg:pypi/idna@2.6","upstreams":[]}},{"vulnerability":{"id":"GHSA-hggm-jpg3-v476","dataSource":"https://github.com/advisories/GHSA-hggm-jpg3-v476","namespace":"github:language:python","severity":"High","urls":[],"description":"RSA decryption vulnerable to Bleichenbacher timing vulnerability","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2020-25659","epss":0.00343,"percentile":0.56361,"date":"2025-06-03"}],"fix":{"versions":["3.2"],"state":"fixed"},"advisories":[],"risk":0.22981},"relatedVulnerabilities":[{"id":"CVE-2020-25659","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2020-25659","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pyca/cryptography/pull/5507/commits/ce1bef6f1ee06ac497ca0c837fbd1c7ef6c2472b","https://www.oracle.com/security-alerts/cpuapr2022.html","https://www.oracle.com/security-alerts/cpujul2022.html","https://github.com/pyca/cryptography/pull/5507/commits/ce1bef6f1ee06ac497ca0c837fbd1c7ef6c2472b","https://www.oracle.com/security-alerts/cpuapr2022.html","https://www.oracle.com/security-alerts/cpujul2022.html"],"description":"python-cryptography 3.2 is vulnerable to Bleichenbacher timing attacks in the RSA decryption API, via timed processing of valid PKCS#1 v1.5 ciphertext.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":5.9,"exploitabilityScore":2.3,"impactScore":3.6},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:M/Au:N/C:P/I:N/A:N","metrics":{"baseScore":4.3,"exploitabilityScore":8.6,"impactScore":2.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2020-25659","epss":0.00343,"percentile":0.56361,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"2.1.4"}},"found":{"versionConstraint":"<3.2 (python)","vulnerabilityID":"GHSA-hggm-jpg3-v476"},"fix":{"suggestedVersion":"3.2"}}],"artifact":{"id":"b914b2bfe04438ce","name":"cryptography","version":"2.1.4","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/cryptography-2.1.4.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/cryptography-2.1.4.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/cryptography-2.1.4.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/cryptography-2.1.4.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD or Apache License, Version 2.0"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:2.1.4:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:2.1.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@2.1.4","upstreams":[]}},{"vulnerability":{"id":"GHSA-w7pp-m8wf-vj6r","dataSource":"https://github.com/advisories/GHSA-w7pp-m8wf-vj6r","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Cipher.update_into can corrupt memory if passed an immutable python object as the outbuf","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:L","metrics":{"baseScore":6.5,"exploitabilityScore":3.9,"impactScore":2.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-23931","epss":0.00331,"percentile":0.5554,"date":"2025-06-03"}],"fix":{"versions":["39.0.1"],"state":"fixed"},"advisories":[],"risk":0.19032499999999997},"relatedVulnerabilities":[{"id":"CVE-2023-23931","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-23931","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/pyca/cryptography/pull/8230/commits/94a50a9731f35405f0357fa5f3b177d46a726ab3","https://github.com/pyca/cryptography/security/advisories/GHSA-w7pp-m8wf-vj6r","https://github.com/pyca/cryptography/pull/8230/commits/94a50a9731f35405f0357fa5f3b177d46a726ab3","https://github.com/pyca/cryptography/security/advisories/GHSA-w7pp-m8wf-vj6r","https://security.netapp.com/advisory/ntap-20230324-0007/"],"description":"cryptography is a package designed to expose cryptographic primitives and recipes to Python developers. In affected versions `Cipher.update_into` would accept Python objects which implement the buffer protocol, but provide only immutable buffers. This would allow immutable objects (such as `bytes`) to be mutated, thus violating fundamental rules of Python and resulting in corrupted output. This now correctly raises an exception. This issue has been present since `update_into` was originally introduced in cryptography 1.8.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:L","metrics":{"baseScore":6.5,"exploitabilityScore":3.9,"impactScore":2.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:L/A:L","metrics":{"baseScore":4.8,"exploitabilityScore":2.3,"impactScore":2.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-23931","epss":0.00331,"percentile":0.5554,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"2.1.4"}},"found":{"versionConstraint":">=1.8,<39.0.1 (python)","vulnerabilityID":"GHSA-w7pp-m8wf-vj6r"},"fix":{"suggestedVersion":"39.0.1"}}],"artifact":{"id":"b914b2bfe04438ce","name":"cryptography","version":"2.1.4","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/cryptography-2.1.4.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/cryptography-2.1.4.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/cryptography-2.1.4.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/cryptography-2.1.4.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD or Apache License, Version 2.0"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:2.1.4:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:2.1.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@2.1.4","upstreams":[]}},{"vulnerability":{"id":"GHSA-gwvm-45gx-3cf8","dataSource":"https://github.com/advisories/GHSA-gwvm-45gx-3cf8","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Authorization Header forwarded on redirect","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N","metrics":{"baseScore":6.1,"exploitabilityScore":2.9,"impactScore":2.8},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2018-25091","epss":0.0025,"percentile":0.48548,"date":"2025-06-03"}],"fix":{"versions":["1.24.2"],"state":"fixed"},"advisories":[],"risk":0.13874999999999998},"relatedVulnerabilities":[{"id":"CVE-2018-25091","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2018-25091","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/urllib3/urllib3/commit/adb358f8e06865406d1f05e581a16cbea2136fbc","https://github.com/urllib3/urllib3/compare/1.24.1...1.24.2","https://github.com/urllib3/urllib3/issues/1510","https://github.com/urllib3/urllib3/commit/adb358f8e06865406d1f05e581a16cbea2136fbc","https://github.com/urllib3/urllib3/compare/1.24.1...1.24.2","https://github.com/urllib3/urllib3/issues/1510"],"description":"urllib3 before 1.24.2 does not remove the authorization HTTP header when following a cross-origin redirect (i.e., a redirect that differs in host, port, or scheme). This can allow for credentials in the authorization header to be exposed to unintended hosts or transmitted in cleartext. NOTE: this issue exists because of an incomplete fix for CVE-2018-20060 (which was case-sensitive).","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N","metrics":{"baseScore":6.1,"exploitabilityScore":2.9,"impactScore":2.8},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2018-25091","epss":0.0025,"percentile":0.48548,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"urllib3","version":"1.22"}},"found":{"versionConstraint":"<1.24.2 (python)","vulnerabilityID":"GHSA-gwvm-45gx-3cf8"},"fix":{"suggestedVersion":"1.24.2"}}],"artifact":{"id":"9e592efbeaf63d3d","name":"urllib3","version":"1.22","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/urllib3-1.22.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/urllib3-1.22.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/urllib3-1.22.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/urllib3-1.22.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:urllib3:1.22:*:*:*:*:*:*:*"],"purl":"pkg:pypi/urllib3@1.22","upstreams":[]}},{"vulnerability":{"id":"GHSA-wqvq-5m8c-6g24","dataSource":"https://github.com/advisories/GHSA-wqvq-5m8c-6g24","namespace":"github:language:python","severity":"Medium","urls":[],"description":"CRLF injection in urllib3","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N","metrics":{"baseScore":6.5,"exploitabilityScore":3.9,"impactScore":2.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2020-26137","epss":0.00215,"percentile":0.44389,"date":"2025-06-03"}],"fix":{"versions":["1.25.9"],"state":"fixed"},"advisories":[],"risk":0.123625},"relatedVulnerabilities":[{"id":"CVE-2020-26137","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2020-26137","namespace":"nvd:cpe","severity":"Medium","urls":["https://bugs.python.org/issue39603","https://github.com/urllib3/urllib3/commit/1dd69c5c5982fae7c87a620d487c2ebf7a6b436b","https://github.com/urllib3/urllib3/pull/1800","https://lists.debian.org/debian-lts-announce/2021/06/msg00015.html","https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html","https://usn.ubuntu.com/4570-1/","https://www.oracle.com/security-alerts/cpujul2022.html","https://www.oracle.com/security-alerts/cpuoct2021.html","https://bugs.python.org/issue39603","https://github.com/urllib3/urllib3/commit/1dd69c5c5982fae7c87a620d487c2ebf7a6b436b","https://github.com/urllib3/urllib3/pull/1800","https://lists.debian.org/debian-lts-announce/2021/06/msg00015.html","https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html","https://usn.ubuntu.com/4570-1/","https://www.oracle.com/security-alerts/cpujul2022.html","https://www.oracle.com/security-alerts/cpuoct2021.html"],"description":"urllib3 before 1.25.9 allows CRLF injection if the attacker controls the HTTP request method, as demonstrated by inserting CR and LF control characters in the first argument of putrequest(). NOTE: this is similar to CVE-2020-26116.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N","metrics":{"baseScore":6.5,"exploitabilityScore":3.9,"impactScore":2.6},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:L/Au:N/C:P/I:P/A:N","metrics":{"baseScore":6.4,"exploitabilityScore":10,"impactScore":5},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2020-26137","epss":0.00215,"percentile":0.44389,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"urllib3","version":"1.22"}},"found":{"versionConstraint":"<1.25.9 (python)","vulnerabilityID":"GHSA-wqvq-5m8c-6g24"},"fix":{"suggestedVersion":"1.25.9"}}],"artifact":{"id":"9e592efbeaf63d3d","name":"urllib3","version":"1.22","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/urllib3-1.22.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/urllib3-1.22.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/urllib3-1.22.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/urllib3-1.22.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:urllib3:1.22:*:*:*:*:*:*:*"],"purl":"pkg:pypi/urllib3@1.22","upstreams":[]}},{"vulnerability":{"id":"GHSA-x84v-xcm2-53pg","dataSource":"https://github.com/advisories/GHSA-x84v-xcm2-53pg","namespace":"github:language:python","severity":"High","urls":[],"description":"Insufficiently Protected Credentials in Requests","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2018-18074","epss":0.00155,"percentile":0.37385,"date":"2025-06-03"}],"fix":{"versions":["2.20.0"],"state":"fixed"},"advisories":[],"risk":0.11624999999999999},"relatedVulnerabilities":[{"id":"CVE-2018-18074","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2018-18074","namespace":"nvd:cpe","severity":"High","urls":["http://docs.python-requests.org/en/master/community/updates/#release-and-version-history","http://lists.opensuse.org/opensuse-security-announce/2019-07/msg00024.html","https://access.redhat.com/errata/RHSA-2019:2035","https://bugs.debian.org/910766","https://github.com/requests/requests/commit/c45d7c49ea75133e52ab22a8e9e13173938e36ff","https://github.com/requests/requests/issues/4716","https://github.com/requests/requests/pull/4718","https://usn.ubuntu.com/3790-1/","https://usn.ubuntu.com/3790-2/","https://www.oracle.com/security-alerts/cpujul2022.html","http://docs.python-requests.org/en/master/community/updates/#release-and-version-history","http://lists.opensuse.org/opensuse-security-announce/2019-07/msg00024.html","https://access.redhat.com/errata/RHSA-2019:2035","https://bugs.debian.org/910766","https://github.com/requests/requests/commit/c45d7c49ea75133e52ab22a8e9e13173938e36ff","https://github.com/requests/requests/issues/4716","https://github.com/requests/requests/pull/4718","https://usn.ubuntu.com/3790-1/","https://usn.ubuntu.com/3790-2/","https://www.oracle.com/security-alerts/cpujul2022.html"],"description":"The Requests package before 2.20.0 for Python sends an HTTP Authorization header to an http URI upon receiving a same-hostname https-to-http redirect, which makes it easier for remote attackers to discover credentials by sniffing the network.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"nvd@nist.gov","type":"Primary","version":"2.0","vector":"AV:N/AC:L/Au:N/C:P/I:N/A:N","metrics":{"baseScore":5,"exploitabilityScore":10,"impactScore":2.9},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2018-18074","epss":0.00155,"percentile":0.37385,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"requests","version":"2.18.4"}},"found":{"versionConstraint":"<=2.19.1 (python)","vulnerabilityID":"GHSA-x84v-xcm2-53pg"},"fix":{"suggestedVersion":"2.20.0"}}],"artifact":{"id":"88c53a79c1f81c0c","name":"requests","version":"2.18.4","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/requests-2.18.4.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/requests-2.18.4.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/requests-2.18.4.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/requests-2.18.4.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache 2.0"],"cpes":["cpe:2.3:a:python:requests:2.18.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/requests@2.18.4","upstreams":[]}},{"vulnerability":{"id":"GHSA-xqr8-7jwr-rhp7","dataSource":"https://github.com/advisories/GHSA-xqr8-7jwr-rhp7","namespace":"github:language:python","severity":"High","urls":[],"description":"Removal of e-Tugra root certificate","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-37920","epss":0.00112,"percentile":0.30835,"date":"2025-06-03"}],"fix":{"versions":["2023.7.22"],"state":"fixed"},"advisories":[],"risk":0.08399999999999999},"relatedVulnerabilities":[{"id":"CVE-2023-37920","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-37920","namespace":"nvd:cpe","severity":"Critical","urls":["https://github.com/certifi/python-certifi/commit/8fb96ed81f71e7097ed11bc4d9b19afd7ea5c909","https://github.com/certifi/python-certifi/security/advisories/GHSA-xqr8-7jwr-rhp7","https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/C-HrP1SEq1A","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5EX6NG7WUFNUKGFHLM35KHHU3GAKXRTG/","https://github.com/certifi/python-certifi/commit/8fb96ed81f71e7097ed11bc4d9b19afd7ea5c909","https://github.com/certifi/python-certifi/security/advisories/GHSA-xqr8-7jwr-rhp7","https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/C-HrP1SEq1A","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5EX6NG7WUFNUKGFHLM35KHHU3GAKXRTG/","https://security.netapp.com/advisory/ntap-20240912-0002/"],"description":"Certifi is a curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts. Certifi prior to version 2023.07.22 recognizes \"e-Tugra\" root certificates. e-Tugra's root certificates were subject to an investigation prompted by reporting of security issues in their systems. Certifi 2023.07.22 removes root certificates from \"e-Tugra\" from the root store.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H","metrics":{"baseScore":9.8,"exploitabilityScore":3.9,"impactScore":5.9},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-37920","epss":0.00112,"percentile":0.30835,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"certifi","version":"2018.1.18"}},"found":{"versionConstraint":">=2015.4.28,<2023.7.22 (python)","vulnerabilityID":"GHSA-xqr8-7jwr-rhp7"},"fix":{"suggestedVersion":"2023.7.22"}}],"artifact":{"id":"feef86bbbf018235","name":"certifi","version":"2018.1.18","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/certifi-2018.1.18.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/certifi-2018.1.18.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/certifi-2018.1.18.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/certifi-2018.1.18.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MPL-2.0"],"cpes":["cpe:2.3:a:certifi:certifi:2018.1.18:*:*:*:*:python:*:*"],"purl":"pkg:pypi/certifi@2018.1.18","upstreams":[]}},{"vulnerability":{"id":"GHSA-9v9h-cgj8-h64p","dataSource":"https://github.com/advisories/GHSA-9v9h-cgj8-h64p","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Null pointer dereference in PKCS12 parsing","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-0727","epss":0.00103,"percentile":0.29443,"date":"2025-06-03"}],"fix":{"versions":["42.0.2"],"state":"fixed"},"advisories":[],"risk":0.05407500000000001},"relatedVulnerabilities":[{"id":"CVE-2024-0727","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-0727","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/openssl/openssl/commit/09df4395b5071217b76dc7d3d2e630eb8c5a79c2","https://github.com/openssl/openssl/commit/775acfdbd0c6af9ac855f34969cdab0c0c90844a","https://github.com/openssl/openssl/commit/d135eeab8a5dbf72b3da5240bab9ddb7678dbd2c","https://github.openssl.org/openssl/extended-releases/commit/03b3941d60c4bce58fab69a0c22377ab439bc0e8","https://github.openssl.org/openssl/extended-releases/commit/aebaa5883e31122b404e450732dc833dc9dee539","https://www.openssl.org/news/secadv/20240125.txt","http://www.openwall.com/lists/oss-security/2024/03/11/1","https://github.com/openssl/openssl/commit/09df4395b5071217b76dc7d3d2e630eb8c5a79c2","https://github.com/openssl/openssl/commit/775acfdbd0c6af9ac855f34969cdab0c0c90844a","https://github.com/openssl/openssl/commit/d135eeab8a5dbf72b3da5240bab9ddb7678dbd2c","https://github.openssl.org/openssl/extended-releases/commit/03b3941d60c4bce58fab69a0c22377ab439bc0e8","https://github.openssl.org/openssl/extended-releases/commit/aebaa5883e31122b404e450732dc833dc9dee539","https://security.netapp.com/advisory/ntap-20240208-0006/","https://www.openssl.org/news/secadv/20240125.txt"],"description":"Issue summary: Processing a maliciously formatted PKCS12 file may lead OpenSSL\nto crash leading to a potential Denial of Service attack\n\nImpact summary: Applications loading files in the PKCS12 format from untrusted\nsources might terminate abruptly.\n\nA file in PKCS12 format can contain certificates and keys and may come from an\nuntrusted source. The PKCS12 specification allows certain fields to be NULL, but\nOpenSSL does not correctly check for this case. This can lead to a NULL pointer\ndereference that results in OpenSSL crashing. If an application processes PKCS12\nfiles from an untrusted source using the OpenSSL APIs then that application will\nbe vulnerable to this issue.\n\nOpenSSL APIs that are vulnerable to this are: PKCS12_parse(),\nPKCS12_unpack_p7data(), PKCS12_unpack_p7encdata(), PKCS12_unpack_authsafes()\nand PKCS12_newpass().\n\nWe have also fixed a similar issue in SMIME_write_PKCS7(). However since this\nfunction is related to writing data we do not consider it security significant.\n\nThe FIPS modules in 3.2, 3.1 and 3.0 are not affected by this issue.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"134c704f-9b21-4f2e-91b3-4a467353bcc0","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H","metrics":{"baseScore":5.5,"exploitabilityScore":1.9,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-0727","epss":0.00103,"percentile":0.29443,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"2.1.4"}},"found":{"versionConstraint":"<42.0.2 (python)","vulnerabilityID":"GHSA-9v9h-cgj8-h64p"},"fix":{"suggestedVersion":"42.0.2"}}],"artifact":{"id":"b914b2bfe04438ce","name":"cryptography","version":"2.1.4","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/cryptography-2.1.4.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/cryptography-2.1.4.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/cryptography-2.1.4.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/cryptography-2.1.4.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD or Apache License, Version 2.0"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:2.1.4:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:2.1.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@2.1.4","upstreams":[]}},{"vulnerability":{"id":"GHSA-g4mx-q9vg-27p4","dataSource":"https://github.com/advisories/GHSA-g4mx-q9vg-27p4","namespace":"github:language:python","severity":"Medium","urls":[],"description":"urllib3's request body not stripped after redirect from 303 status changes request method to GET","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.2,"exploitabilityScore":0.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-45803","epss":0.00062,"percentile":0.1968,"date":"2025-06-03"}],"fix":{"versions":["1.26.18"],"state":"fixed"},"advisories":[],"risk":0.02852},"relatedVulnerabilities":[{"id":"CVE-2023-45803","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2023-45803","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/urllib3/urllib3/commit/4e98d57809dacab1cbe625fddeec1a290c478ea9","https://github.com/urllib3/urllib3/security/advisories/GHSA-g4mx-q9vg-27p4","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4R2Y5XK3WALSR3FNAGN7JBYV2B343ZKB/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PPDPLM6UUMN55ESPQWJFLLIZY4ZKCNRX/","https://www.rfc-editor.org/rfc/rfc9110.html#name-get","https://github.com/urllib3/urllib3/commit/4e98d57809dacab1cbe625fddeec1a290c478ea9","https://github.com/urllib3/urllib3/security/advisories/GHSA-g4mx-q9vg-27p4","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4R2Y5XK3WALSR3FNAGN7JBYV2B343ZKB/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PPDPLM6UUMN55ESPQWJFLLIZY4ZKCNRX/","https://www.rfc-editor.org/rfc/rfc9110.html#name-get"],"description":"urllib3 is a user-friendly HTTP client library for Python. urllib3 previously wouldn't remove the HTTP request body when an HTTP redirect response using status 301, 302, or 303 after the request had its method changed from one that could accept a request body (like `POST`) to `GET` as is required by HTTP RFCs. Although this behavior is not specified in the section for redirects, it can be inferred by piecing together information from different sections and we have observed the behavior in other major HTTP client implementations like curl and web browsers. Because the vulnerability requires a previously trusted service to become compromised in order to have an impact on confidentiality we believe the exploitability of this vulnerability is low. Additionally, many users aren't putting sensitive data in HTTP request bodies, if this is the case then this vulnerability isn't exploitable. Both of the following conditions must be true to be affected by this vulnerability: 1. Using urllib3 and submitting sensitive information in the HTTP request body (such as form data or JSON) and 2. The origin service is compromised and starts redirecting using 301, 302, or 303 to a malicious peer or the redirected-to service becomes compromised. This issue has been addressed in versions 1.26.18 and 2.0.7 and users are advised to update to resolve this issue. Users unable to update should disable redirects for services that aren't expecting to respond with redirects with `redirects=False` and disable automatic redirects with `redirects=False` and handle 301, 302, and 303 redirects manually by stripping the HTTP request body.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.2,"exploitabilityScore":0.6,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.2,"exploitabilityScore":0.6,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2023-45803","epss":0.00062,"percentile":0.1968,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"urllib3","version":"1.22"}},"found":{"versionConstraint":">=0,<1.26.18 (python)","vulnerabilityID":"GHSA-g4mx-q9vg-27p4"},"fix":{"suggestedVersion":"1.26.18"}}],"artifact":{"id":"9e592efbeaf63d3d","name":"urllib3","version":"1.22","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/urllib3-1.22.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/urllib3-1.22.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/urllib3-1.22.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/urllib3-1.22.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:urllib3:1.22:*:*:*:*:*:*:*"],"purl":"pkg:pypi/urllib3@1.22","upstreams":[]}},{"vulnerability":{"id":"GHSA-43fp-rhv2-5gv8","dataSource":"https://github.com/advisories/GHSA-43fp-rhv2-5gv8","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Certifi removing TrustCor root certificate","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:C/C:N/I:H/A:N","metrics":{"baseScore":6.8,"exploitabilityScore":2.3,"impactScore":4},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-23491","epss":0.00038,"percentile":0.10381,"date":"2025-06-03"}],"fix":{"versions":["2022.12.07"],"state":"fixed"},"advisories":[],"risk":0.02242},"relatedVulnerabilities":[{"id":"CVE-2022-23491","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2022-23491","namespace":"nvd:cpe","severity":"High","urls":["https://github.com/certifi/python-certifi/security/advisories/GHSA-43fp-rhv2-5gv8","https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/oxX69KFvsm4/m/yLohoVqtCgAJ","https://github.com/certifi/python-certifi/security/advisories/GHSA-43fp-rhv2-5gv8","https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/oxX69KFvsm4/m/yLohoVqtCgAJ","https://security.netapp.com/advisory/ntap-20230223-0010/"],"description":"Certifi is a curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts. Certifi 2022.12.07 removes root certificates from \"TrustCor\" from the root store. These are in the process of being removed from Mozilla's trust store. TrustCor's root certificates are being removed pursuant to an investigation prompted by media reporting that TrustCor's ownership also operated a business that produced spyware. Conclusions of Mozilla's investigation can be found in the linked google group discussion.","cvss":[{"source":"nvd@nist.gov","type":"Primary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N","metrics":{"baseScore":7.5,"exploitabilityScore":3.9,"impactScore":3.6},"vendorMetadata":{}},{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:C/C:N/I:H/A:N","metrics":{"baseScore":6.8,"exploitabilityScore":2.3,"impactScore":4},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2022-23491","epss":0.00038,"percentile":0.10381,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"certifi","version":"2018.1.18"}},"found":{"versionConstraint":">=2017.11.05,<2022.12.07 (python)","vulnerabilityID":"GHSA-43fp-rhv2-5gv8"},"fix":{"suggestedVersion":"2022.12.07"}}],"artifact":{"id":"feef86bbbf018235","name":"certifi","version":"2018.1.18","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/certifi-2018.1.18.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/certifi-2018.1.18.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/certifi-2018.1.18.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/certifi-2018.1.18.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MPL-2.0"],"cpes":["cpe:2.3:a:certifi:certifi:2018.1.18:*:*:*:*:python:*:*"],"purl":"pkg:pypi/certifi@2018.1.18","upstreams":[]}},{"vulnerability":{"id":"GHSA-34jh-p97f-mpxf","dataSource":"https://github.com/advisories/GHSA-34jh-p97f-mpxf","namespace":"github:language:python","severity":"Medium","urls":[],"description":"urllib3's Proxy-Authorization request header isn't stripped during cross-origin redirects","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.4,"exploitabilityScore":0.8,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-37891","epss":0.00033,"percentile":0.08049,"date":"2025-06-03"}],"fix":{"versions":["1.26.19"],"state":"fixed"},"advisories":[],"risk":0.01551},"relatedVulnerabilities":[{"id":"CVE-2024-37891","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-37891","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/urllib3/urllib3/commit/accff72ecc2f6cf5a76d9570198a93ac7c90270e","https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf","https://github.com/urllib3/urllib3/commit/accff72ecc2f6cf5a76d9570198a93ac7c90270e","https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf","https://security.netapp.com/advisory/ntap-20240822-0003/","https://www.vicarius.io/vsociety/posts/proxy-authorization-header-handling-vulnerability-in-urllib3-cve-2024-37891"],"description":"urllib3 is a user-friendly HTTP client library for Python. When using urllib3's proxy support with `ProxyManager`, the `Proxy-Authorization` header is only sent to the configured proxy, as expected. However, when sending HTTP requests *without* using urllib3's proxy support, it's possible to accidentally configure the `Proxy-Authorization` header even though it won't have any effect as the request is not using a forwarding proxy or a tunneling proxy. In those cases, urllib3 doesn't treat the `Proxy-Authorization` HTTP header as one carrying authentication material and thus doesn't strip the header on cross-origin redirects. Because this is a highly unlikely scenario, we believe the severity of this vulnerability is low for almost all users. Out of an abundance of caution urllib3 will automatically strip the `Proxy-Authorization` header during cross-origin redirects to avoid the small chance that users are doing this on accident. Users should use urllib3's proxy support or disable automatic redirects to achieve safe processing of the `Proxy-Authorization` header, but we still decided to strip the header by default in order to further protect users who aren't using the correct approach. We believe the number of usages affected by this advisory is low. It requires all of the following to be true to be exploited: 1. Setting the `Proxy-Authorization` header without using urllib3's built-in proxy support. 2. Not disabling HTTP redirects. 3. Either not using an HTTPS origin server or for the proxy or target origin to redirect to a malicious origin. Users are advised to update to either version 1.26.19 or version 2.2.2. Users unable to upgrade may use the `Proxy-Authorization` header with urllib3's `ProxyManager`, disable HTTP redirects using `redirects=False` when sending requests, or not user the `Proxy-Authorization` header as mitigations.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N","metrics":{"baseScore":4.4,"exploitabilityScore":0.8,"impactScore":3.6},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-37891","epss":0.00033,"percentile":0.08049,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"urllib3","version":"1.22"}},"found":{"versionConstraint":"<1.26.19 (python)","vulnerabilityID":"GHSA-34jh-p97f-mpxf"},"fix":{"suggestedVersion":"1.26.19"}}],"artifact":{"id":"9e592efbeaf63d3d","name":"urllib3","version":"1.22","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/urllib3-1.22.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/urllib3-1.22.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/urllib3-1.22.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/urllib3-1.22.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["MIT"],"cpes":["cpe:2.3:a:python:urllib3:1.22:*:*:*:*:*:*:*"],"purl":"pkg:pypi/urllib3@1.22","upstreams":[]}},{"vulnerability":{"id":"GHSA-9wx4-h78v-vm56","dataSource":"https://github.com/advisories/GHSA-9wx4-h78v-vm56","namespace":"github:language:python","severity":"Medium","urls":[],"description":"Requests `Session` object does not verify requests after making first request with verify=False","cvss":[{"type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N","metrics":{"baseScore":5.6,"exploitabilityScore":0.4,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-35195","epss":0.00009,"percentile":0.00549,"date":"2025-06-03"}],"fix":{"versions":["2.32.0"],"state":"fixed"},"advisories":[],"risk":0.004770000000000001},"relatedVulnerabilities":[{"id":"CVE-2024-35195","dataSource":"https://nvd.nist.gov/vuln/detail/CVE-2024-35195","namespace":"nvd:cpe","severity":"Medium","urls":["https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac","https://github.com/psf/requests/pull/6655","https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ/","https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac","https://github.com/psf/requests/pull/6655","https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q/","https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ/"],"description":"Requests is a HTTP library. Prior to 2.32.0, when making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same host will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool. This vulnerability is fixed in 2.32.0.","cvss":[{"source":"security-advisories@github.com","type":"Secondary","version":"3.1","vector":"CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N","metrics":{"baseScore":5.6,"exploitabilityScore":0.4,"impactScore":5.2},"vendorMetadata":{}}],"epss":[{"cve":"CVE-2024-35195","epss":0.00009,"percentile":0.00549,"date":"2025-06-03"}]}],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"requests","version":"2.18.4"}},"found":{"versionConstraint":"<2.32.0 (python)","vulnerabilityID":"GHSA-9wx4-h78v-vm56"},"fix":{"suggestedVersion":"2.32.0"}}],"artifact":{"id":"88c53a79c1f81c0c","name":"requests","version":"2.18.4","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/requests-2.18.4.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/requests-2.18.4.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/requests-2.18.4.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/requests-2.18.4.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["Apache 2.0"],"cpes":["cpe:2.3:a:python:requests:2.18.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/requests@2.18.4","upstreams":[]}},{"vulnerability":{"id":"GHSA-5cpq-8wj7-hf2v","dataSource":"https://github.com/advisories/GHSA-5cpq-8wj7-hf2v","namespace":"github:language:python","severity":"Low","urls":[],"description":"Vulnerable OpenSSL included in cryptography wheels","cvss":[],"fix":{"versions":["41.0.0"],"state":"fixed"},"advisories":[],"risk":0},"relatedVulnerabilities":[],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"2.1.4"}},"found":{"versionConstraint":">=0.5,<=40.0.2 (python)","vulnerabilityID":"GHSA-5cpq-8wj7-hf2v"},"fix":{"suggestedVersion":"41.0.0"}}],"artifact":{"id":"b914b2bfe04438ce","name":"cryptography","version":"2.1.4","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/cryptography-2.1.4.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/cryptography-2.1.4.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/cryptography-2.1.4.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/cryptography-2.1.4.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD or Apache License, Version 2.0"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:2.1.4:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:2.1.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@2.1.4","upstreams":[]}},{"vulnerability":{"id":"GHSA-jm77-qphf-c4w8","dataSource":"https://github.com/advisories/GHSA-jm77-qphf-c4w8","namespace":"github:language:python","severity":"Low","urls":[],"description":"pyca/cryptography's wheels include vulnerable OpenSSL","cvss":[],"fix":{"versions":["41.0.3"],"state":"fixed"},"advisories":[],"risk":0},"relatedVulnerabilities":[],"matchDetails":[{"type":"exact-direct-match","matcher":"python-matcher","searchedBy":{"language":"python","namespace":"github:language:python","package":{"name":"cryptography","version":"2.1.4"}},"found":{"versionConstraint":">=0.8,<41.0.3 (python)","vulnerabilityID":"GHSA-jm77-qphf-c4w8"},"fix":{"suggestedVersion":"41.0.3"}}],"artifact":{"id":"b914b2bfe04438ce","name":"cryptography","version":"2.1.4","type":"python","locations":[{"path":"/usr/lib/python3/dist-packages/cryptography-2.1.4.egg-info/PKG-INFO","accessPath":"/usr/lib/python3/dist-packages/cryptography-2.1.4.egg-info/PKG-INFO","annotations":{"evidence":"primary"}},{"path":"/usr/lib/python3/dist-packages/cryptography-2.1.4.egg-info/top_level.txt","accessPath":"/usr/lib/python3/dist-packages/cryptography-2.1.4.egg-info/top_level.txt","annotations":{"evidence":"supporting"}}],"language":"python","licenses":["BSD or Apache License, Version 2.0"],"cpes":["cpe:2.3:a:cryptography.io:cryptography:2.1.4:*:*:*:*:python:*:*","cpe:2.3:a:cryptography.io:cryptography:2.1.4:*:*:*:*:*:*:*"],"purl":"pkg:pypi/cryptography@2.1.4","upstreams":[]}}],"source":{"type":"sbom-file","target":"ubuntu-accomplishments-syft.json"},"distro":{"name":"","version":"","idLike":null},"descriptor":{"name":"grype","version":"0.92.2","configuration":{"output":["json=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-06-04/ubuntu-accomplishments-grype.json","template=/Users/alan/Personal/popey/syft-snap-source-test/grype/v1.26.0/2025-06-04/ubuntu-accomplishments-grype.html"],"file":"","pretty":false,"distro":"","add-cpes-if-none":false,"output-template-file":"../html.tmpl","check-for-app-update":true,"only-fixed":false,"only-notfixed":false,"ignore-wontfix":"","platform":"","search":{"scope":"squashed","unindexed-archives":false,"indexed-archives":true},"ignore":[{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"kernel-headers","version":"","language":"","type":"rpm","location":"","upstream-name":"kernel"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux(-.*)?-headers-.*","version":"","language":"","type":"deb","location":"","upstream-name":"linux.*"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"},{"vulnerability":"","reason":"","namespace":"","fix-state":"","package":{"name":"linux-libc-dev","version":"","language":"","type":"deb","location":"","upstream-name":"linux"},"vex-status":"","vex-justification":"","match-type":"exact-indirect-match"}],"exclude":[],"externalSources":{"enable":false,"maven":{"searchUpstreamBySha1":true,"baseUrl":"https://search.maven.org/solrsearch/select","rateLimit":300000000}},"match":{"java":{"using-cpes":false},"jvm":{"using-cpes":true},"dotnet":{"using-cpes":false},"golang":{"using-cpes":false,"always-use-cpe-for-stdlib":true,"allow-main-module-pseudo-version-comparison":false},"javascript":{"using-cpes":false},"python":{"using-cpes":false},"ruby":{"using-cpes":false},"rust":{"using-cpes":false},"stock":{"using-cpes":true}},"fail-on-severity":"","registry":{"insecure-skip-tls-verify":false,"insecure-use-http":false,"auth":null,"ca-cert":""},"show-suppressed":false,"by-cve":false,"SortBy":{"sort-by":"risk"},"name":"","default-image-pull-source":"","vex-documents":[],"vex-add":[],"match-upstream-kernel-headers":false,"db":{"cache-dir":"/Users/alan/Library/Caches/grype/db","update-url":"https://grype.anchore.io/databases","ca-cert":"","auto-update":true,"validate-by-hash-on-start":true,"validate-age":true,"max-allowed-built-age":432000000000000,"require-update-check":false,"update-available-timeout":30000000000,"update-download-timeout":300000000000,"max-update-check-frequency":7200000000000},"exp":{},"dev":{"db":{"debug":false}}},"db":{"status":{"schemaVersion":"v6.0.2","from":"https://grype.anchore.io/databases/v6/vulnerability-db_v6.0.2_2025-06-04T01:32:23Z_1749035557.tar.zst?checksum=sha256%3A77238f4ffbc7cf72bf4dedabbb21a3d0dd3ade90fb5d9df7c4da2870f8d1a9b7","built":"2025-06-04T11:12:37Z","path":"/Users/alan/Library/Caches/grype/db/6/vulnerability.db","valid":true},"providers":{"alpine":{"captured":"2025-06-04T01:32:23Z","input":"xxh64:a6a065ece392f6d1"},"amazon":{"captured":"2025-06-04T01:32:32Z","input":"xxh64:b65d458d6858d72a"},"chainguard":{"captured":"2025-06-04T01:32:33Z","input":"xxh64:03c9c4d182d77791"},"debian":{"captured":"2025-06-04T01:32:49Z","input":"xxh64:169ceb8fbcb8d6f1"},"epss":{"captured":"2025-06-04T01:32:42Z","input":"xxh64:bf87c4c234d02346"},"github":{"captured":"2025-06-04T01:32:30Z","input":"xxh64:3dab0be50635e057"},"kev":{"captured":"2025-06-04T01:32:45Z","input":"xxh64:a934e75f468f4e09"},"mariner":{"captured":"2025-06-04T01:32:43Z","input":"xxh64:ac698752085c186f"},"nvd":{"captured":"2025-06-04T01:33:28Z","input":"xxh64:389887843a59d29c"},"oracle":{"captured":"2025-06-04T01:32:35Z","input":"xxh64:0b8aabcfb6505b62"},"rhel":{"captured":"2025-06-04T04:49:10Z","input":"xxh64:947d0caeb19e9ccc"},"sles":{"captured":"2025-06-04T01:32:34Z","input":"xxh64:1c50b1219296628a"},"ubuntu":{"captured":"2025-06-04T01:33:14Z","input":"xxh64:71e22d5c5bbe7d14"},"wolfi":{"captured":"2025-06-04T01:32:42Z","input":"xxh64:e68fca5a870c6769"}}},"timestamp":"2025-06-04T19:49:01.991283+01:00"}}
